import { ConditionalsType } from "./conditionals";
import { FutureContinuousType } from "./tenses/future_contnuous";
import { FuturePerfectType } from "./tenses/future_perfect";
import { FuturePerfectContinuousType } from "./tenses/future_perfect_continuous";
import { PluralOnlyNounsType } from "./noun_special/plural_only_nouns";
import { NounsType } from "./nouns";
import { PastContinuousType } from "./tenses/past_continuous";
import { PastPerfectContinuousType } from "./tenses/past_perfect-continuous";
import { PastPerfectType } from "./tenses/past_perfeect";
import { PresentContinuousType } from "./tenses/present_continuous";
import { PresentPerfectType } from "./tenses/present_perfect";
import { PresentPerfectContinuousType } from "./tenses/present_perfect_continuous";
import { PronounsType } from "./pronouns";
import { RelativeClausesType } from "./relative_clauses";
import { ReportedSpeechType } from "./reported_speech";
import { SimpleFutureType } from "./tenses/simple_future";
import { SimplePastType } from "./tenses/simple_past";
import { SimplePresentType } from "./tenses/simple_present";
import { VerbsType } from "./verbs";
import { AdjectiveType } from "./Adjective";
import { AdjectiveOrderType } from "./AdjectiveOrder";
import { AdverbType } from "./Adverb";
import { ArticlesType } from "./Articles";
import { CausativeFormType } from "./CausativeForm";
import { ComparativeType } from "./Comparative";
import { ComparisonsType } from "./Comparisons";
import { ConjunctionsType } from "./Conjunctions";
import { DeterminersType } from "./Determiners";
import { DirectAndIndirectSpeechType } from "./DirectAndIndirectSpeech";
import { DiscourseMarkersType } from "./DiscourseMarkers";
import { DoubleComparativeType } from "./DoubleComparative";
import { EllipsisAndSubstitutionType } from "./EllipsisAndSubstitution";
import { EmphasisType } from "./Emphasis";
import { EqualityComparisonType } from "./EqualityComparison";
import { FocusStructuresType } from "./FocusStructures";
import { FutureInThePastType } from "./FutureInThePast";
import { GerundsAndInfinitivesType } from "./GerundsAndInfinitives";
import { HedgingType } from "./Hedging";
import { IdiomaticLanguageType } from "./IdiomaticLanguage";
import { ImperativesType } from "./Imperatives";
import { InfinitivesType } from "./Infinitives";
import { InterjectionsType } from "./Interjections";
import { InversionType } from "./Inversion";
import { ModalVerbsType } from "./ModalVerbs";
import { NegationType } from "./Negation";
import { NominalisationType } from "./Nominalisation";
import { PassiveVoiceType } from "./PassiveVoice";
import { PhrasalVerbsType } from "./PhrasalVerbs";
import { PossessivesType } from "./Possessives";
import { PrepositionType } from "./Preposition";
import { QuantifiersType } from "./Quantifiers";
import { QuestionFormsType } from "./QuestionForms";
import { ReflexivePronounsType } from "./ReflexivePronouns";
import { RepeatedComparativeType } from "./RepeatedComparative";
import { ReportedQuestionsType } from "./ReportedQuestions";
import { SentenceTypesType } from "./SentenceTypes";
import { SubjectVerbAgreementType } from "./SubjectVerbAgreement";
import { SubjunctiveMoodType } from "./SubjunctiveMood";
import { SuperlativeType } from "./Superlative";
import { TagQuestionsType } from "./TagQuestions";
import { TenseConsistencyType } from "./TenseConsistency";
import { TenseShiftInReportedSpeechType } from "./TenseShiftInReportedSpeech";
import { TimeExpressionsType } from "./TimeExpressions";
import { WordFormationSentencesType } from "./WordFormationSentences";
import { WordOrderType } from "./WordOrder";
import { adjectivesNoComparisonType } from "./adjective_special/adjectivesNoComparison";
import { adjectivesUsedAsNounsType } from "./adjective_special/adjectivesUsedAsNouns";
import { adjectivesWithPluralNounsType } from "./adjective_special/adjectivesWithPluralNouns";
import { compoundAdjectivesType } from "./adjective_special/compound_adjectives";
import { emotionAdjectivesType } from "./adjective_special/emotionAdjectives";
import { possessiveAndEmphaticAdjectivesType } from "./adjective_special/possessiveAndEmphaticAdjectives";
import { postpositiveAdjectivesType } from "./adjective_special/postpositiveAdjectives";
import { quantitativeAdjectivesType } from "./adjective_special/quantitativeAdjectives";
import { specialPositionAdjectivesType } from "./adjective_special/specialPositionAdjectives";
import { adverbFrontingInversionType } from "./adverbs_special/adverbFrontingInversion";
import { adverbPositionMeaningChangeType } from "./adverbs_special/adverbPositionMeaningChange";
import { adverbsEndingLyVsIdenticalAdjectivesType } from "./adverbs_special/adverbsEndingLyVsIdenticalAdjectives";
import { adverbsInversionAndEmphasisType } from "./adverbs_special/adverbsInversionAndEmphasis";
import { adverbsNotEndingLyType } from "./adverbs_special/adverbsNotEndingLy";
import { adverbsOfCertaintyType } from "./adverbs_special/adverbsOfCertainty";
import { adverbsOfFrequencyType } from "./adverbs_special/adverbsOfFrequency";
import { degreeAdverbsType } from "./adverbs_special/degreeAdverbs";
import { emphasizingAdverbsType } from "./adverbs_special/emphasizingAdverbs";
import { linkingAdverbsType } from "./adverbs_special/linkingAdverbs";
import { expressingAgreementDisagreementSuggestionsRequestsResponsesType } from "./communication_advance/expressingAgreementDisagreementSuggestionsRequestsResponses";
import { politeVsDirectLanguageType } from "@/types/grammars/grammar/communication_advance/politeVsDirectLanguage";
import { transitionPhrasesAcademicWritingType } from "./communication_advance/transitionPhrasesAcademicWriting";
import { advancedConditionalsType } from "./grammar_advance/advancedConditionalsData";
import { adverbialClauseAdvancedType } from "./grammar_advance/adverbialClauseAdvanced";
import { binomialsType } from "./grammar_advance/binomials";
import { cleftSentencesType } from "./grammar_advance/cleftSentences";
import { collocationsType } from "./grammar_advance/collocations";
import { emphaticCleftSentencesType } from "./grammar_advance/emphatic_cleft_sentences";
import { fixedExpressionsType } from "./grammar_advance/fixedExpressions";
import { nounClauseGrammarType } from "./grammar_advance/nounClauseGrammar";
import { parallelStructuresDataType } from "./grammar_advance/parallelStructures";
import { purposeResultConditionClausesType } from "./grammar_advance/purposeResultConditionClauses";
import { reducedRelativeClausesType } from "./grammar_advance/reducedRelativeClauses";
import { verbToVOrVingAdvancedType } from "./grammar_advance/verbToVOrVingAdvanced";
import { abstractNounsType } from "./noun_special/abstract_nouns";
import { CollectiveNounsType } from "./noun_special/collective_nouns";
import { CountableVsUncountableNounsType } from "./noun_special/countable_vs_uncountable_nouns";
import { DualUsageNounsType } from "./noun_special/dual_usage_nouns";
import { irregularPluralsType } from "./noun_special/irregular_plurals";
import { pluraliaTantumType } from "./noun_special/pluralia_tantum";
import { singularOnlyNounsType } from "./noun_special/singular_only_nouns";
import { singulariaTantumType } from "./noun_special/singularia_tantum";
import { uncountableNounsType } from "./noun_special/uncountable_nouns";
import { CausativeVerbsType } from "./verb_special/causative_verbs";
import { infinitivePatternsType } from "./verb_special/infinitive_patterns";
import { IrregularVerbsType } from "./verb_special/irregular_verbs";
import { LinkingVerbsType } from "./verb_special/linking_verbs";
import { PerceptionVerbsType } from "./verb_special/perception_verbs";
import { phrasalVerbsType } from "./verb_special/phrasal_verbs";
import { ReflexiveVerbsType } from "./verb_special/reflexive_verbs";
import { ReportingVerbsType } from "./verb_special/reporting_verbs";
import { StatisticVerbsType } from "./verb_special/statistic_verbs";
import { transitiveIntransitiveVerbsType } from "./verb_special/transitiveIntransitive_verbs";
import { VerbsOfPerceptionType } from "./verb_special/verbs_of_perception";

// New interface for citations
export interface Citation {
  title: string;
  url: string;
  description: string;
  source: string; // e.g., "Cambridge Dictionary", "Tensesly", "BBC Learning English"
  type: "reference" | "practice" | "examples" | "explanation" | string;
}

// Main interface containing all tenses with their specific separate types
export interface TensesStructure {
  Simple_Present?: SimplePresentType;
  Present_Continuous?: PresentContinuousType;
  Simple_Past?: SimplePastType;
  Past_Continuous?: PastContinuousType;
  Present_Perfect?: PresentPerfectType;
  Present_Perfect_Continuous?: PresentPerfectContinuousType;
  Past_Perfect?: PastPerfectType;
  Past_Perfect_Continuous?: PastPerfectContinuousType;
  Simple_Future?: SimpleFutureType;
  Future_Continuous?: FutureContinuousType;
  Future_Perfect?: FuturePerfectType;
  Future_Perfect_Continuous?: FuturePerfectContinuousType;
  Conditionals?: ConditionalsType;
  Reported_Speech?: ReportedSpeechType;
  Relative_Clauses?: RelativeClausesType;
  Nouns?: NounsType;
  Pronouns?: PronounsType;
  Verbs?: VerbsType;
  Adjective?: AdjectiveType;
  AdjectiveOrder?: AdjectiveOrderType;
  Adverb?: AdverbType;
  Articles?: ArticlesType;
  CausativeForm?: CausativeFormType;
  Comparative?: ComparativeType;
  Comparisons?: ComparisonsType;
  Conjunctions?: ConjunctionsType;
  Determiners?: DeterminersType;
  DirectAndIndirectSpeech?: DirectAndIndirectSpeechType;
  DiscourseMarkers?: DiscourseMarkersType;
  DoubleComparative?: DoubleComparativeType;
  EllipsisAndSubstitution?: EllipsisAndSubstitutionType;
  Emphasis?: EmphasisType;
  EqualityComparison?: EqualityComparisonType;
  FocusStructures?: FocusStructuresType;
  FutureInThePast?: FutureInThePastType;
  GerundsAndInfinitives?: GerundsAndInfinitivesType;
  Hedging?: HedgingType;
  IdiomaticLanguage?: IdiomaticLanguageType;
  Imperatives?: ImperativesType;
  Infinitives?: InfinitivesType;
  Interjections?: InterjectionsType;
  Inversion?: InversionType;
  ModalVerbs?: ModalVerbsType;
  Negation?: NegationType;
  Nominalisation?: NominalisationType;
  PassiveVoice?: PassiveVoiceType;
  PhrasalVerbs?: PhrasalVerbsType;
  Possessives?: PossessivesType;
  Preposition?: PrepositionType;
  Quantifiers?: QuantifiersType;
  QuestionForms?: QuestionFormsType;
  ReflexivePronouns?: ReflexivePronounsType;
  RepeatedComparative?: RepeatedComparativeType;
  ReportedQuestions?: ReportedQuestionsType;
  SentenceTypes?: SentenceTypesType;
  SubjectVerbAgreement?: SubjectVerbAgreementType;
  SubjunctiveMood?: SubjunctiveMoodType;
  Superlative?: SuperlativeType;
  TagQuestions?: TagQuestionsType;
  TenseConsistency?: TenseConsistencyType;
  TenseShiftInReportedSpeech?: TenseShiftInReportedSpeechType;
  TimeExpressions?: TimeExpressionsType;
  WordFormationSentences?: WordFormationSentencesType;
  WordOrder?: WordOrderType;
  adjectivesNoComparison?: adjectivesNoComparisonType;
  adjectivesUsedAsNouns?: adjectivesUsedAsNounsType;
  adjectivesWithPluralNouns?: adjectivesWithPluralNounsType;
  compoundAdjectives?: compoundAdjectivesType;
  emotionAdjectives?: emotionAdjectivesType;
  possessiveAndEmphaticAdjectives?: possessiveAndEmphaticAdjectivesType;
  postpositiveAdjectives?: postpositiveAdjectivesType;
  quantitativeAdjectives?: quantitativeAdjectivesType;
  specialPositionAdjectives?: specialPositionAdjectivesType;
  adverbFrontingInversion?: adverbFrontingInversionType;
  adverbPositionMeaningChange?: adverbPositionMeaningChangeType;
  adverbsEndingLyVsIdenticalAdjectives?: adverbsEndingLyVsIdenticalAdjectivesType;
  adverbsInversionAndEmphasis?: adverbsInversionAndEmphasisType;
  adverbsNotEndingLy?: adverbsNotEndingLyType;
  adverbsOfCertainty?: adverbsOfCertaintyType;
  adverbsOfFrequency?: adverbsOfFrequencyType;
  degreeAdverbs?: degreeAdverbsType;
  emphasizingAdverbs?: emphasizingAdverbsType;
  linkingAdverbs?: linkingAdverbsType;

  expressingAgreementDisagreementSuggestionsRequestsResponses?: expressingAgreementDisagreementSuggestionsRequestsResponsesType;
  politeVsDirectLanguage?: politeVsDirectLanguageType;
  transitionPhrasesAcademicWriting?: transitionPhrasesAcademicWritingType;
  advancedConditionals?: advancedConditionalsType;
  adverbialClauseAdvanced?: adverbialClauseAdvancedType;
  binomials?: binomialsType;
  cleftSentences?: cleftSentencesType;
  collocations?: collocationsType;
  emphaticCleftSentences?: emphaticCleftSentencesType;
  fixedExpressions?: fixedExpressionsType;
  nounClauseGrammar?: nounClauseGrammarType;
  parallelStructuresData?: parallelStructuresDataType;
  purposeResultConditionClauses?: purposeResultConditionClausesType;
  reducedRelativeClauses?: reducedRelativeClausesType;
  verbToVOrVingAdvanced?: verbToVOrVingAdvancedType;
  abstractNouns?: abstractNounsType;
  CollectiveNouns?: CollectiveNounsType;
  CountableVsUncountableNouns?: CountableVsUncountableNounsType;
  DualUsageNouns?: DualUsageNounsType;
  irregularPlurals?: irregularPluralsType;
  PluralOnlyNouns?: PluralOnlyNounsType;
  pluraliaTantum?: pluraliaTantumType;
  singularOnlyNouns?: singularOnlyNounsType;
  singulariaTantum?: singulariaTantumType;
  uncountableNouns?: uncountableNounsType;
  CausativeVerbs?: CausativeVerbsType;
  infinitivePatterns?: infinitivePatternsType;
  IrregularVerbs?: IrregularVerbsType;
  LinkingVerbs?: LinkingVerbsType;
  PerceptionVerbs?: PerceptionVerbsType;
  phrasalVerbs?: phrasalVerbsType;
  ReflexiveVerbs?: ReflexiveVerbsType;
  ReportingVerbs?: ReportingVerbsType;
  StatisticVerbs?: StatisticVerbsType;
  transitiveIntransitiveVerbs?: transitiveIntransitiveVerbsType;
  VerbsOfPerception?: VerbsOfPerceptionType;
}