import { ConditionalsType } from "./conditionals";
import { FutureContinuousType } from "./tenses/future_contnuous";
import { FuturePerfectType } from "./tenses/future_perfect";
import { FuturePerfectContinuousType } from "./tenses/future_perfect_continuous";
import { PluralOnlyNounsType } from "./noun_special/plural_only_nouns";
import { NounsType } from "./nouns";
import { PastContinuousType } from "./tenses/past_continuous";
import { PastPerfectContinuousType } from "./tenses/past_perfect-continuous";
import { PastPerfectType } from "./tenses/past_perfeect";
import { PresentContinuousType } from "./tenses/present_continuous";
import { PresentPerfectType } from "./tenses/present_perfect";
import { PresentPerfectContinuousType } from "./tenses/present_perfect_continuous";
import { PronounsType } from "./pronouns";
import { RelativeClausesType } from "./relative_clauses";
import { ReportedSpeechType } from "./reported_speech";
import { SimpleFutureType } from "./tenses/simple_future";
import { SimplePastType } from "./tenses/simple_past";
import { SimplePresentType } from "./tenses/simple_present";
import { VerbsType } from "./verbs";
import { AdjectiveType } from "./Adjective";
import { AdjectiveOrderType } from "./AdjectiveOrder";
import { AdverbType } from "./Adverb";
import { ArticlesType } from "./Articles";
import { CausativeFormType } from "./CausativeForm";
import { ComparativeType } from "./Comparative";
import { ComparisonsType } from "./Comparisons";
import { ConjunctionsType } from "./Conjunctions";
import { DeterminersType } from "./Determiners";
import { DirectAndIndirectSpeechType } from "./DirectAndIndirectSpeech";
import { DiscourseMarkersType } from "./DiscourseMarkers";
import { DoubleComparativeType } from "./DoubleComparative";
import { EllipsisAndSubstitutionType } from "./EllipsisAndSubstitution";
import { EmphasisType } from "./Emphasis";
import { EqualityComparisonType } from "./EqualityComparison";
import { FocusStructuresType } from "./FocusStructures";
import { FutureInThePastType } from "./FutureInThePast";
import { GerundsAndInfinitivesType } from "./GerundsAndInfinitives";
import { HedgingType } from "./Hedging";
import { IdiomaticLanguageType } from "./IdiomaticLanguage";
import { ImperativesType } from "./Imperatives";
import { InfinitivesType } from "./Infinitives";
import { InterjectionsType } from "./Interjections";
import { InversionType } from "./Inversion";
import { ModalVerbsType } from "./ModalVerbs";
import { NegationType } from "./Negation";
import { NominalisationType } from "./Nominalisation";
import { PassiveVoiceType } from "./PassiveVoice";
import { PhrasalVerbsType } from "./PhrasalVerbs";
import { PossessivesType } from "./Possessives";
import { PrepositionType } from "./Preposition";
import { QuantifiersType } from "./Quantifiers";
import { QuestionFormsType } from "./QuestionForms";
import { ReflexivePronounsType } from "./ReflexivePronouns";
import { RepeatedComparativeType } from "./RepeatedComparative";
import { ReportedQuestionsType } from "./ReportedQuestions";
import { SentenceTypesType } from "./SentenceTypes";
import { SubjectVerbAgreementType } from "./SubjectVerbAgreement";
import { SubjunctiveMoodType } from "./SubjunctiveMood";
import { SuperlativeType } from "./Superlative";
import { TagQuestionsType } from "./TagQuestions";
import { TenseConsistencyType } from "./TenseConsistency";
import { TenseShiftInReportedSpeechType } from "./TenseShiftInReportedSpeech";
import { TimeExpressionsType } from "./TimeExpressions";
import { WordFormationSentencesType } from "./WordFormationSentences";
import { WordOrderType } from "./WordOrder";
import { adjectivesNoComparisonType } from "./adjective_special/adjectivesNoComparison";
import { adjectivesUsedAsNounsType } from "./adjective_special/adjectivesUsedAsNouns";
import { adjectivesWithPluralNounsType } from "./adjective_special/adjectivesWithPluralNouns";
import { compoundAdjectivesType } from "./adjective_special/compound_adjectives";
import { emotionAdjectivesType } from "./adjective_special/emotionAdjectives";
import { possessiveAndEmphaticAdjectivesType } from "./adjective_special/possessiveAndEmphaticAdjectives";
import { postpositiveAdjectivesType } from "./adjective_special/postpositiveAdjectives";
import { quantitativeAdjectivesType } from "./adjective_special/quantitativeAdjectives";
import { specialPositionAdjectivesType } from "./adjective_special/specialPositionAdjectives";
import { adverbFrontingInversionType } from "./adverbs_special/adverbFrontingInversion";
import { adverbPositionMeaningChangeType } from "./adverbs_special/adverbPositionMeaningChange";
import { adverbsEndingLyVsIdenticalAdjectivesType } from "./adverbs_special/adverbsEndingLyVsIdenticalAdjectives";
import { adverbsInversionAndEmphasisType } from "./adverbs_special/adverbsInversionAndEmphasis";
import { adverbsNotEndingLyType } from "./adverbs_special/adverbsNotEndingLy";
import { adverbsOfCertaintyType } from "./adverbs_special/adverbsOfCertainty";
import { adverbsOfFrequencyType } from "./adverbs_special/adverbsOfFrequency";
import { degreeAdverbsType } from "./adverbs_special/degreeAdverbs";
import { emphasizingAdverbsType } from "./adverbs_special/emphasizingAdverbs";
import { linkingAdverbsType } from "./adverbs_special/linkingAdverbs";
import { expressingAgreementDisagreementSuggestionsRequestsResponsesType } from "./communication_advance/expressingAgreementDisagreementSuggestionsRequestsResponses";
import { politeVsDirectLanguageType } from "@/types/grammars/grammar/communication_advance/politeVsDirectLanguage";
import { transitionPhrasesAcademicWritingType } from "./communication_advance/transitionPhrasesAcademicWriting";
import { advancedConditionalsType } from "./grammar_advance/advancedConditionalsData";
import { adverbialClauseAdvancedType } from "./grammar_advance/adverbialClauseAdvanced";
import { binomialsType } from "./grammar_advance/binomials";
import { cleftSentencesType } from "./grammar_advance/cleftSentences";
import { collocationsType } from "./grammar_advance/collocations";
import { emphaticCleftSentencesType } from "./grammar_advance/emphatic_cleft_sentences";
import { fixedExpressionsType } from "./grammar_advance/fixedExpressions";
import { nounClauseGrammarType } from "./grammar_advance/nounClauseGrammar";
import { parallelStructuresDataType } from "./grammar_advance/parallelStructures";
import { purposeResultConditionClausesType } from "./grammar_advance/purposeResultConditionClauses";
import { reducedRelativeClausesType } from "./grammar_advance/reducedRelativeClauses";
import { verbToVOrVingAdvancedType } from "./grammar_advance/verbToVOrVingAdvanced";
import { abstractNounsType } from "./noun_special/abstract_nouns";
import { CollectiveNounsType } from "./noun_special/collective_nouns";
import { CountableVsUncountableNounsType } from "./noun_special/countable_vs_uncountable_nouns";
import { DualUsageNounsType } from "./noun_special/dual_usage_nouns";
import { irregularPluralsType } from "./noun_special/irregular_plurals";
import { pluraliaTantumType } from "./noun_special/pluralia_tantum";
import { singularOnlyNounsType } from "./noun_special/singular_only_nouns";
import { singulariaTantumType } from "./noun_special/singularia_tantum";
import { uncountableNounsType } from "./noun_special/uncountable_nouns";
import { CausativeVerbsType } from "./verb_special/causative_verbs";
import { infinitivePatternsType } from "./verb_special/infinitive_patterns";
import { IrregularVerbsType } from "./verb_special/irregular_verbs";
import { LinkingVerbsType } from "./verb_special/linking_verbs";
import { PerceptionVerbsType } from "./verb_special/perception_verbs";
import { phrasalVerbsType } from "./verb_special/phrasal_verbs";
import { ReflexiveVerbsType } from "./verb_special/reflexive_verbs";
import { ReportingVerbsType } from "./verb_special/reporting_verbs";
import { StatisticVerbsType } from "./verb_special/statistic_verbs";
import { transitiveIntransitiveVerbsType } from "./verb_special/transitiveIntransitive_verbs";
import { VerbsOfPerceptionType } from "./verb_special/verbs_of_perception";

// New interface for citations
export interface Citation {
  title: string;
  url: string;
  description: string;
  source: string; // e.g., "Cambridge Dictionary", "Tensesly", "BBC Learning English"
  type: "reference" | "practice" | "examples" | "explanation" | string;
}

export interface DateCreatedUpdated {
  created: string;
  updated: string;
}

// Main interface containing all tenses with their specific separate types
export interface TensesStructure {
  createdAt: string;
  updatedAt: string;
  Simple_Present?: SimplePresentType & DateCreatedUpdated;
  Present_Continuous?: PresentContinuousType & DateCreatedUpdated;
  Simple_Past?: SimplePastType & DateCreatedUpdated;
  Past_Continuous?: PastContinuousType & DateCreatedUpdated;
  Present_Perfect?: PresentPerfectType & DateCreatedUpdated;
  Present_Perfect_Continuous?: PresentPerfectContinuousType &
    DateCreatedUpdated;
  Past_Perfect?: PastPerfectType & DateCreatedUpdated;
  Past_Perfect_Continuous?: PastPerfectContinuousType & DateCreatedUpdated;
  Simple_Future?: SimpleFutureType & DateCreatedUpdated;
  Future_Continuous?: FutureContinuousType & DateCreatedUpdated;
  Future_Perfect?: FuturePerfectType & DateCreatedUpdated;
  Future_Perfect_Continuous?: FuturePerfectContinuousType & DateCreatedUpdated;
  Conditionals?: ConditionalsType & DateCreatedUpdated;
  Reported_Speech?: ReportedSpeechType & DateCreatedUpdated;
  Relative_Clauses?: RelativeClausesType & DateCreatedUpdated;
  Nouns?: NounsType & DateCreatedUpdated;
  Pronouns?: PronounsType & DateCreatedUpdated;
  Verbs?: VerbsType & DateCreatedUpdated;
  Adjective?: AdjectiveType & DateCreatedUpdated;
  AdjectiveOrder?: AdjectiveOrderType & DateCreatedUpdated;
  Adverb?: AdverbType & DateCreatedUpdated;
  Articles?: ArticlesType & DateCreatedUpdated;
  CausativeForm?: CausativeFormType & DateCreatedUpdated;
  Comparative?: ComparativeType & DateCreatedUpdated;
  Comparisons?: ComparisonsType & DateCreatedUpdated;
  Conjunctions?: ConjunctionsType & DateCreatedUpdated;
  Determiners?: DeterminersType & DateCreatedUpdated;
  DirectAndIndirectSpeech?: DirectAndIndirectSpeechType & DateCreatedUpdated;
  DiscourseMarkers?: DiscourseMarkersType & DateCreatedUpdated;
  DoubleComparative?: DoubleComparativeType & DateCreatedUpdated;
  EllipsisAndSubstitution?: EllipsisAndSubstitutionType & DateCreatedUpdated;
  Emphasis?: EmphasisType & DateCreatedUpdated;
  EqualityComparison?: EqualityComparisonType & DateCreatedUpdated;
  FocusStructures?: FocusStructuresType & DateCreatedUpdated;
  FutureInThePast?: FutureInThePastType & DateCreatedUpdated;
  GerundsAndInfinitives?: GerundsAndInfinitivesType & DateCreatedUpdated;
  Hedging?: HedgingType & DateCreatedUpdated;
  IdiomaticLanguage?: IdiomaticLanguageType & DateCreatedUpdated;
  Imperatives?: ImperativesType & DateCreatedUpdated;
  Infinitives?: InfinitivesType & DateCreatedUpdated;
  Interjections?: InterjectionsType & DateCreatedUpdated;
  Inversion?: InversionType & DateCreatedUpdated;
  ModalVerbs?: ModalVerbsType & DateCreatedUpdated;
  Negation?: NegationType & DateCreatedUpdated;
  Nominalisation?: NominalisationType & DateCreatedUpdated;
  PassiveVoice?: PassiveVoiceType & DateCreatedUpdated;
  PhrasalVerbs?: PhrasalVerbsType & DateCreatedUpdated;
  Possessives?: PossessivesType & DateCreatedUpdated;
  Preposition?: PrepositionType & DateCreatedUpdated;
  Quantifiers?: QuantifiersType & DateCreatedUpdated;
  QuestionForms?: QuestionFormsType & DateCreatedUpdated;
  ReflexivePronouns?: ReflexivePronounsType & DateCreatedUpdated;
  RepeatedComparative?: RepeatedComparativeType & DateCreatedUpdated;
  ReportedQuestions?: ReportedQuestionsType & DateCreatedUpdated;
  SentenceTypes?: SentenceTypesType & DateCreatedUpdated;
  SubjectVerbAgreement?: SubjectVerbAgreementType & DateCreatedUpdated;
  SubjunctiveMood?: SubjunctiveMoodType & DateCreatedUpdated;
  Superlative?: SuperlativeType & DateCreatedUpdated;
  TagQuestions?: TagQuestionsType & DateCreatedUpdated;
  TenseConsistency?: TenseConsistencyType & DateCreatedUpdated;
  TenseShiftInReportedSpeech?: TenseShiftInReportedSpeechType &
    DateCreatedUpdated;
  TimeExpressions?: TimeExpressionsType & DateCreatedUpdated;
  WordFormationSentences?: WordFormationSentencesType & DateCreatedUpdated;
  WordOrder?: WordOrderType & DateCreatedUpdated;
  adjectivesNoComparison?: adjectivesNoComparisonType & DateCreatedUpdated;
  adjectivesUsedAsNouns?: adjectivesUsedAsNounsType & DateCreatedUpdated;
  adjectivesWithPluralNouns?: adjectivesWithPluralNounsType &
    DateCreatedUpdated;
  compoundAdjectives?: compoundAdjectivesType & DateCreatedUpdated;
  emotionAdjectives?: emotionAdjectivesType & DateCreatedUpdated;
  possessiveAndEmphaticAdjectives?: possessiveAndEmphaticAdjectivesType &
    DateCreatedUpdated;
  postpositiveAdjectives?: postpositiveAdjectivesType & DateCreatedUpdated;
  quantitativeAdjectives?: quantitativeAdjectivesType & DateCreatedUpdated;
  specialPositionAdjectives?: specialPositionAdjectivesType &
    DateCreatedUpdated;
  adverbFrontingInversion?: adverbFrontingInversionType & DateCreatedUpdated;
  adverbPositionMeaningChange?: adverbPositionMeaningChangeType &
    DateCreatedUpdated;
  adverbsEndingLyVsIdenticalAdjectives?: adverbsEndingLyVsIdenticalAdjectivesType &
    DateCreatedUpdated;
  adverbsInversionAndEmphasis?: adverbsInversionAndEmphasisType &
    DateCreatedUpdated;
  adverbsNotEndingLy?: adverbsNotEndingLyType & DateCreatedUpdated;
  adverbsOfCertainty?: adverbsOfCertaintyType & DateCreatedUpdated;
  adverbsOfFrequency?: adverbsOfFrequencyType & DateCreatedUpdated;
  degreeAdverbs?: degreeAdverbsType & DateCreatedUpdated;
  emphasizingAdverbs?: emphasizingAdverbsType & DateCreatedUpdated;
  linkingAdverbs?: linkingAdverbsType & DateCreatedUpdated;

  expressingAgreementDisagreementSuggestionsRequestsResponses?: expressingAgreementDisagreementSuggestionsRequestsResponsesType &
    DateCreatedUpdated;
  politeVsDirectLanguage?: politeVsDirectLanguageType & DateCreatedUpdated;
  transitionPhrasesAcademicWriting?: transitionPhrasesAcademicWritingType &
    DateCreatedUpdated;
  advancedConditionals?: advancedConditionalsType & DateCreatedUpdated;
  adverbialClauseAdvanced?: adverbialClauseAdvancedType & DateCreatedUpdated;
  binomials?: binomialsType & DateCreatedUpdated;
  cleftSentences?: cleftSentencesType & DateCreatedUpdated;
  collocations?: collocationsType & DateCreatedUpdated;
  emphaticCleftSentences?: emphaticCleftSentencesType & DateCreatedUpdated;
  fixedExpressions?: fixedExpressionsType & DateCreatedUpdated;
  nounClauseGrammar?: nounClauseGrammarType & DateCreatedUpdated;
  parallelStructuresData?: parallelStructuresDataType & DateCreatedUpdated;
  purposeResultConditionClauses?: purposeResultConditionClausesType &
    DateCreatedUpdated;
  reducedRelativeClauses?: reducedRelativeClausesType & DateCreatedUpdated;
  verbToVOrVingAdvanced?: verbToVOrVingAdvancedType & DateCreatedUpdated;
  abstractNouns?: abstractNounsType & DateCreatedUpdated;
  CollectiveNouns?: CollectiveNounsType & DateCreatedUpdated;
  CountableVsUncountableNouns?: CountableVsUncountableNounsType &
    DateCreatedUpdated;
  DualUsageNouns?: DualUsageNounsType & DateCreatedUpdated;
  irregularPlurals?: irregularPluralsType & DateCreatedUpdated;
  PluralOnlyNouns?: PluralOnlyNounsType & DateCreatedUpdated;
  pluraliaTantum?: pluraliaTantumType & DateCreatedUpdated;
  singularOnlyNouns?: singularOnlyNounsType & DateCreatedUpdated;
  singulariaTantum?: singulariaTantumType & DateCreatedUpdated;
  uncountableNouns?: uncountableNounsType & DateCreatedUpdated;
  CausativeVerbs?: CausativeVerbsType & DateCreatedUpdated;
  infinitivePatterns?: infinitivePatternsType & DateCreatedUpdated;
  IrregularVerbs?: IrregularVerbsType & DateCreatedUpdated;
  LinkingVerbs?: LinkingVerbsType & DateCreatedUpdated;
  PerceptionVerbs?: PerceptionVerbsType & DateCreatedUpdated;
  phrasalVerbs?: phrasalVerbsType & DateCreatedUpdated;
  ReflexiveVerbs?: ReflexiveVerbsType & DateCreatedUpdated;
  ReportingVerbs?: ReportingVerbsType & DateCreatedUpdated;
  StatisticVerbs?: StatisticVerbsType & DateCreatedUpdated;
  transitiveIntransitiveVerbs?: transitiveIntransitiveVerbsType &
    DateCreatedUpdated;
  VerbsOfPerception?: VerbsOfPerceptionType & DateCreatedUpdated;
}
