// Comprehensive Collective Nouns Data (A1-C2)
const collective_nouns = {
  definition: {
    core_concept:
      "Collective nouns refer to a group of people, animals, or things considered as a single unit.",
    grammatical_status:
      "Collective nouns can take either singular or plural verb agreement depending on whether the group is seen as a unit or as individuals.",
    linguistic_significance:
      "They allow speakers to refer to multiple entities as a single entity, and their verb agreement can vary by dialect and context.",
    examples: [
      "team",
      "family",
      "group",
      "class",
      "committee",
      "audience",
      "staff",
      "crew",
      "jury",
      "government",
      "public",
      "army",
      "band",
      "choir",
      "crowd",
      "flock",
      "herd",
      "pack",
      "swarm",
      "bunch",
      "bouquet",
      "fleet",
      "panel",
      "board",
      "company",
      "gang",
      "cast",
      "choir",
      "orchestra",
      "pair",
      "couple",
      "set",
      "collection",
      "series",
      "range",
      "series",
      "series",
      "series",
    ],
  },
  cefrLevels: {
    A1: "Recognize and use basic collective nouns for people and animals (e.g., family, team, class, group, crowd, herd, flock)",
    A2: "Use collective nouns in simple descriptions and daily contexts (e.g., staff, crew, audience, band, pack, bunch)",
    B1: "Use collective nouns in explanations, opinions, and more abstract contexts (e.g., committee, government, public, company, army, choir)",
    B2: "Use collective nouns in academic, professional, and technical contexts (e.g., jury, panel, board, fleet, orchestra, cast, collection)",
    C1: "Nuanced use in formal, academic, and idiomatic expressions (e.g., range, series, set, pair, couple, series)",
    C2: "Mastery of rare, idiomatic, and highly abstract collective nouns (e.g., consortium, congregation, faculty, legislature, populace, syndicate, array, multitude, throng, ensemble)",
  },
  forms: {
    basic:
      "S + collective noun + singular/plural verb • e.g., The team is winning. / The team are arguing.",
    with_of:
      "S + collective noun + of + plural noun • e.g., A flock of birds, a bunch of grapes, a group of students.",
    with_quantifier:
      "S + quantifier + collective noun • e.g., Several teams, many groups, a few committees.",
    with_article:
      "S + a/the + collective noun • e.g., The family, a crowd, the staff.",
  },
  usage: [
    {
      type: "People groups",
      description: "Collective nouns for groups of people.",
      examples: [
        "family",
        "team",
        "class",
        "committee",
        "audience",
        "staff",
        "crew",
        "jury",
        "government",
        "public",
        "company",
        "panel",
        "board",
        "choir",
        "cast",
        "orchestra",
        "faculty",
        "legislature",
        "congregation",
        "ensemble",
      ],
      level: "A1-B2",
    },
    {
      type: "Animal groups",
      description: "Collective nouns for groups of animals.",
      examples: [
        "herd",
        "flock",
        "pack",
        "swarm",
        "school",
        "pride",
        "gaggle",
        "colony",
        "pod",
        "murder",
        "parliament",
        "troop",
        "litter",
        "shoal",
        "army (of ants)",
        "band (of gorillas)",
        "leap (of leopards)",
        "crash (of rhinos)",
        "bale (of turtles)",
        "business (of ferrets)",
        "exaltation (of larks)",
        "murmuration (of starlings)",
        "parade (of elephants)",
        "raft (of ducks)",
        "skulk (of foxes)",
        "sounder (of pigs)",
        "wake (of vultures)",
        "zeal (of zebras)",
      ],
      level: "A1-C2",
    },
    {
      type: "Things/objects",
      description: "Collective nouns for groups of things or objects.",
      examples: [
        "bunch",
        "bouquet",
        "fleet",
        "set",
        "collection",
        "series",
        "range",
        "array",
        "stack",
        "pile",
        "heap",
        "cluster",
        "bundle",
        "batch",
        "group",
        "pack",
        "pair",
        "couple",
      ],
      level: "A1-C2",
    },
    {
      type: "Abstract/technical",
      description:
        "Collective nouns used in academic, technical, or abstract contexts.",
      examples: [
        "consortium",
        "syndicate",
        "faculty",
        "legislature",
        "populace",
        "multitude",
        "throng",
        "ensemble",
        "array",
        "series",
        "range",
      ],
      level: "B2-C2",
    },
  ],
  examples: {
    basic: {
      singular: "The team is winning the match.",
      plural: "The team are arguing among themselves.",
      context: "Sports, daily conversation (A1)",
    },
    with_of: {
      singular: "A flock of birds is flying south.",
      plural: "A flock of birds are making a lot of noise.",
      context: "Nature, animal groups (A2)",
    },
    with_quantifier: {
      singular: "Several committees have been formed.",
      plural: "Many groups are participating.",
      context: "Academic, professional (B1-B2)",
    },
    idiomatic: {
      singular: "The crowd was buzzing with excitement.",
      plural: "The crowd were all wearing red.",
      context: "Events, idiomatic (B2-C1)",
    },
    technical: {
      singular: "The faculty is meeting today.",
      plural: "The faculty are publishing their research.",
      context: "Academic, technical (C1-C2)",
    },
  },
  practiceTypes: {
    A1: [
      "Identify collective nouns in simple sentences",
      "Choose correct verb agreement with collective nouns",
      "Match collective nouns to pictures (e.g., team, family, herd)",
      "Fill in the blank with a collective noun",
    ],
    A2: [
      "Use 'of' phrases with collective nouns (a group of, a bunch of, a flock of)",
      "Distinguish between collective and non-collective nouns",
      "Correct sentences with verb agreement errors",
      "Simple gap-filling with collective nouns",
    ],
    B1: [
      "Use collective nouns in short paragraphs",
      "Rewrite sentences to use collective nouns idiomatically",
      "Identify collective nouns for animals and things",
      "Explain the meaning of collective nouns in context",
    ],
    B2: [
      "Use collective nouns in academic and professional writing",
      "Paraphrase sentences to use collective nouns idiomatically",
      "Correct advanced errors with collective nouns",
      "Explain the difference between singular and plural agreement",
    ],
    C1: [
      "Use collective nouns in formal and academic registers",
      "Analyze idiomatic and metaphorical uses of collective nouns",
      "Identify subtle errors in advanced writing",
      "Produce essays using a range of collective nouns",
    ],
    C2: [
      "Master rare and highly abstract collective nouns",
      "Critique and edit advanced texts for collective noun accuracy",
      "Use collective nouns in creative and literary writing",
      "Demonstrate register flexibility with collective nouns",
    ],
  },
  commonMistakes: {
    beginners: [
      "Using plural verbs with collective nouns when the group is seen as a unit: ❌ The team are winning ✅ The team is winning (AmE)",
      "Using singular verbs when referring to individuals: ❌ The staff is all late ✅ The staff are all late",
      "Adding -s to collective nouns: ❌ teams of people ✅ team of people",
      "Using 'a/an' with plural nouns: ❌ a teams ✅ a team",
    ],
    intermediate: [
      "Confusing collective and plural nouns: ❌ The families is big ✅ The family is big",
      "Incorrect quantifiers: ❌ many team ✅ many teams",
      "Wrong article: ❌ a committee ✅ the committee",
      "Using 'these/those' with singular collective nouns: ❌ these team ✅ this team",
    ],
    advanced: [
      "Overusing singular agreement in British English: ❌ The government is divided ✅ The government are divided (BrE)",
      "Incorrect idiomatic use: ❌ a group of people is happy ✅ a group of people are happy (when focusing on individuals)",
      "Mixing countable and collective forms: ❌ herds of cattle ✅ a herd of cattle",
      "Using plural forms in technical writing: ❌ panels of experts are ✅ a panel of experts is",
    ],
  },
  recognition: [
    "Collective nouns refer to groups as single units or as individuals depending on context.",
    "Verb agreement can be singular or plural (especially in British English).",
    "Often used with 'of' phrases (a group of, a bunch of, a flock of).",
    "Cannot be used with 'a/an' if the noun is already plural.",
    "Some collective nouns are always singular (e.g., furniture, equipment), but most can be singular or plural.",
    "Context and dialect (AmE vs BrE) affect verb agreement.",
  ],
  timeMarkers: [
    "now",
    "today",
    "yesterday",
    "tomorrow",
    "this week",
    "last year",
    "at the moment",
    "recently",
    "soon",
  ],
  pronounChanges: {
    basic: {
      it: "It is a team.",
      they: "They are a team.",
      this: "This is a group.",
      those: "Those are groups.",
    },
    advanced: {
      who: "Who are the staff?",
      which: "Which team is winning?",
      all: "All of the committee are present.",
    },
  },
  reportingVerbs: [
    "have",
    "include",
    "consist of",
    "comprise",
    "contain",
    "represent",
    "form",
    "make up",
    "lead",
    "join",
    "belong to",
    "organize",
    "assemble",
    "gather",
    "meet",
    "divide",
    "unite",
  ],
  exercises: {
    recognition: {
      description: "Identify collective nouns in context",
      difficulty: "A1-B1",
      examples: [
        "Find the collective noun: The class is noisy.",
        "Choose the correct verb: The team (is/are) winning.",
      ],
    },
    correction: {
      description: "Correct common mistakes with collective nouns",
      difficulty: "A2-B2",
      examples: [
        "❌ The staff is all late. ✅ The staff are all late.",
        "❌ These team are good. ✅ This team is good.",
      ],
    },
    production: {
      description: "Use collective nouns in your own sentences",
      difficulty: "B1-C2",
      examples: [
        "Write a paragraph about your family using collective nouns.",
        "Describe a group activity and use 'team', 'group', and 'audience' correctly.",
      ],
    },
  },
  notes: [
    "Collective nouns can take singular or plural verbs depending on meaning and dialect.",
    "In American English, collective nouns usually take singular verbs; in British English, plural verbs are common when focusing on individuals.",
    "Some collective nouns are used only for animals (e.g., a pride of lions, a murder of crows).",
    "Use 'of' phrases to specify the members of the group (a group of students, a bunch of grapes).",
    "Be careful with quantifiers and articles; 'a team', 'the staff', 'many teams', 'several groups'.",
    "Some collective nouns are also used metaphorically (e.g., a bouquet of lies, a fleet of ideas).",
    "Collective nouns are common in both spoken and written English, especially in news, sports, and academic contexts.",
  ],
  culturalContexts: {
    daily_life: {
      description: "Common in daily conversation, family, and school contexts",
      examples: [
        "My family is big.",
        "The class is noisy.",
        "The team is practicing.",
      ],
    },
    academic: {
      description: "Essential in academic and professional writing",
      examples: [
        "The committee has decided...",
        "The jury are still deliberating.",
      ],
    },
    idiomatic: {
      description: "Used in idiomatic expressions and news/media",
      examples: [
        "A crowd of people gathered.",
        "A flock of birds flew overhead.",
      ],
    },
  },
  specialCases: {
    animal_groups: {
      description: "Unique collective nouns for animal groups",
      examples: [
        "a murder of crows",
        "a parliament of owls",
        "a pride of lions",
        "a leap of leopards",
        "a crash of rhinos",
        "a troop of monkeys",
        "a pod of dolphins",
        "a school of fish",
        "a gaggle of geese",
        "a skulk of foxes",
        "a wake of vultures",
        "a zeal of zebras",
      ],
    },
    dialectal: {
      description:
        "Differences in verb agreement between American and British English",
      examples: [
        {
          context: "AmE",
          singular: "The team is winning.",
          plural: "The team are arguing (rare).",
        },
        {
          context: "BrE",
          singular: "The team is winning.",
          plural: "The team are arguing.",
        },
      ],
    },
    metaphorical: {
      description: "Metaphorical and creative uses of collective nouns",
      examples: [
        "a bouquet of lies",
        "a fleet of ideas",
        "a cluster of thoughts",
        "a range of emotions",
      ],
    },
    dual_use: {
      description:
        "Nouns that can be both collective and countable/uncountable with different meanings",
      examples: [
        {
          word: "staff",
          collective: "The staff are friendly.",
          countable: "a staff (a stick)",
        },
        {
          word: "family",
          collective: "My family is large.",
          countable: "families (different groups)",
        },
        {
          word: "fleet",
          collective: "A fleet of ships.",
          countable: "fleets (multiple groups)",
        },
      ],
    },
  },
  etymology: {
    origin:
      "Many collective nouns derive from Old English, Latin, or French, often reflecting social or natural groupings.",
    development:
      "The use of collective nouns has evolved to include both traditional and creative groupings in modern English.",
    modernUsage:
      "Collective nouns are now common in both spoken and written English, especially in news, sports, and academic contexts.",
  },
  crossLinguistic: {
    similarities:
      "Many languages have collective nouns, but the specific list and verb agreement rules vary.",
    differences:
      "Some collective nouns in English are not used the same way in other languages, and verb agreement may differ.",
    learnerChallenges:
      "Learners often struggle with verb agreement and the use of 'of' phrases with collective nouns.",
  },
  vocabulary: {
    A1: [
      "family",
      "team",
      "class",
      "group",
      "crowd",
      "herd",
      "flock",
      "pack",
      "bunch",
      "pair",
      "set",
    ],
    A2: [
      "staff",
      "crew",
      "audience",
      "band",
      "committee",
      "company",
      "choir",
      "panel",
      "board",
      "fleet",
      "collection",
      "range",
      "series",
      "batch",
      "bundle",
      "cluster",
    ],
    B1: [
      "jury",
      "government",
      "public",
      "army",
      "cast",
      "orchestra",
      "faculty",
      "legislature",
      "congregation",
      "ensemble",
      "gang",
      "choir",
      "company",
      "panel",
    ],
    B2: [
      "consortium",
      "syndicate",
      "populace",
      "multitude",
      "throng",
      "array",
      "stack",
      "pile",
      "heap",
      "bouquet",
      "raft",
      "shoal",
      "school",
      "colony",
      "pod",
      "pride",
      "gaggle",
      "troop",
      "litter",
    ],
    C1: [
      "parliament",
      "murder",
      "exaltation",
      "murmuration",
      "parade",
      "crash",
      "bale",
      "business",
      "leap",
      "wake",
      "zeal",
      "skulk",
      "sounder",
      "faculty",
      "legislature",
      "congregation",
      "ensemble",
    ],
    C2: [
      "consortium",
      "syndicate",
      "populace",
      "multitude",
      "throng",
      "array",
      "ensemble",
      "faculty",
      "legislature",
      "congregation",
      "parliament",
      "murder",
      "exaltation",
      "murmuration",
      "parade",
      "crash",
      "bale",
      "business",
      "leap",
      "wake",
      "zeal",
      "skulk",
      "sounder",
    ],
  },
  grammaticalPatterns: {
    article_usage: {
      correct: [
        "a team",
        "the staff",
        "many teams",
        "several groups",
        "a bunch of grapes",
      ],
      incorrect: ["a teams", "the staffs", "many team", "these team"],
    },
    verb_agreement: {
      correct: [
        "The team is winning.",
        "The staff are all late.",
        "The committee has decided.",
        "The jury are still deliberating.",
      ],
      incorrect: [
        "The team are winning (AmE, unless focusing on individuals)",
        "The staff is all late (when referring to individuals)",
        "The committee have decided (AmE, unless focusing on individuals)",
        "The jury is still deliberating (BrE, when focusing on individuals)",
      ],
    },
    quantifiers: {
      correct: [
        "many teams",
        "several groups",
        "a few committees",
        "a bunch of flowers",
      ],
      incorrect: [
        "many team",
        "several group",
        "a few committee",
        "a bunch of flower",
      ],
    },
    of_phrases: {
      correct: ["a group of students", "a flock of birds", "a bunch of grapes"],
      incorrect: ["a group students", "a flock birds", "a bunch grapes"],
    },
  },
  usageContexts: {
    A1: ["family life", "school", "sports", "animals", "shopping"],
    A2: ["workplace", "entertainment", "events", "nature", "travel"],
    B1: ["news", "media", "government", "public life", "academic settings"],
    B2: [
      "professional writing",
      "technical descriptions",
      "formal communication",
    ],
    C1: [
      "research papers",
      "literary analysis",
      "advanced presentations",
      "creative writing",
    ],
    C2: [
      "critical reviews",
      "specialized academic discourse",
      "creative and metaphorical writing",
    ],
  },
  errorPatterns: {
    A1: [
      "❌ teams of people ✅ team of people",
      "❌ a teams ✅ a team",
      "❌ a family are ✅ a family is",
    ],
    A2: [
      "❌ many team ✅ many teams",
      "❌ these team ✅ this team",
      "❌ a bunch grapes ✅ a bunch of grapes",
    ],
    B1: [
      "❌ the families is big ✅ the family is big",
      "❌ the staff is all late ✅ the staff are all late",
    ],
    B2: [
      "❌ panels of experts are ✅ a panel of experts is",
      "❌ herds of cattle ✅ a herd of cattle",
    ],
    C1: [
      "❌ the government is divided (BrE) ✅ the government are divided",
      "❌ a group of people is happy ✅ a group of people are happy (when focusing on individuals)",
    ],
    C2: [
      "❌ a murder of crows is ✅ a murder of crows are (when focusing on individuals)",
      "❌ a parliament of owls is ✅ a parliament of owls are (when focusing on individuals)",
    ],
  },
  learningStrategies: {
    A1: [
      "Memorize common collective nouns with pictures and examples.",
      "Practice using correct verb agreement.",
      "Listen for collective nouns in simple conversations.",
    ],
    A2: [
      "Use 'of' phrases (a group of, a bunch of) in speaking and writing.",
      "Compare collective and plural nouns in context.",
      "Correct common mistakes in exercises.",
    ],
    B1: [
      "Practice using quantifiers (many, several, a few) with collective nouns.",
      "Write short texts using a variety of collective nouns.",
      "Edit sentences for correct collective noun usage.",
    ],
    B2: [
      "Use collective nouns in academic and technical writing.",
      "Paraphrase sentences to use collective nouns idiomatically.",
      "Analyze authentic texts for advanced usage.",
    ],
    C1: [
      "Produce essays and presentations using advanced collective nouns.",
      "Identify and correct subtle errors in peer writing.",
      "Experiment with idiomatic and metaphorical uses.",
    ],
    C2: [
      "Master rare and highly abstract collective nouns.",
      "Critique and edit advanced texts for accuracy.",
      "Use collective nouns creatively in literary and academic contexts.",
    ],
  },
};

const tense = {
  collective_nouns,
};

export default tense;
