// Comprehensive Countable vs. Uncountable Nouns Data (A1-C2)
const countable_vs_uncountable_nouns = {
  definition: {
    core_concept:
      "Countable nouns refer to things that can be counted as individual units (e.g., apple/apples), while uncountable nouns refer to substances, concepts, or masses that cannot be counted individually (e.g., water, information).",
    grammatical_status:
      "Countable nouns can be singular or plural and use 'a/an', numbers, and quantifiers like 'many' and 'few'. Uncountable nouns are always singular, do not use 'a/an', and use quantifiers like 'much' and 'little'.",
    linguistic_significance:
      "Understanding the difference is essential for correct article, quantifier, and verb agreement usage in English.",
    examples_countable: [
      "book/books",
      "car/cars",
      "child/children",
      "idea/ideas",
      "apple/apples",
      "dog/dogs",
      "table/tables",
      "city/cities",
      "question/questions",
      "friend/friends",
    ],
    examples_uncountable: [
      "water",
      "rice",
      "advice",
      "information",
      "music",
      "furniture",
      "bread",
      "happiness",
      "news",
      "progress",
      "equipment",
      "homework",
      "knowledge",
      "research",
      "traffic",
      "weather",
      "work",
      "money",
      "sand",
      "air",
      "sugar",
      "salt",
      "love",
      "anger",
    ],
  },
  cefrLevels: {
    A1: "Recognize and use basic countable and uncountable nouns in daily life (e.g., apple/apples, water, bread, book/books, money)",
    A2: "Use countable and uncountable nouns in simple requests, descriptions, and needs (e.g., advice, information, knowledge, bottle of water, two apples)",
    B1: "Use countable and uncountable nouns in explanations, opinions, and more abstract contexts (e.g., experience, progress, education, respect, responsibility, opportunity, challenge, advantage, disadvantage)",
    B2: "Use countable and uncountable nouns in academic, professional, and technical contexts (e.g., evidence, research, analysis, summary, criticism, influence, impact, effect, result, consequence, outcome, strategy, policy, principle, value, tradition, culture, heritage, legacy, philosophy, science, literature, art, music, design, method, system, structure, pattern, model, trend, fashion, custom, law, regulation, standard, norm)",
    C1: "Nuanced use in formal, academic, and idiomatic expressions (e.g., democracy, liberty, equality, charity, compassion, inspiration, motivation, leadership, innovation, creativity, imagination, vision, insight, perspective, synthesis, review, comment, statement, argument, assumption, presumption, expectation, anticipation, surprise, shock, disappointment, frustration, boredom, interest, curiosity, wonder, amazement, awe, fear, terror, panic, anxiety, worry, concern, care, sympathy, empathy, compassion, pity, mercy, forgiveness, tolerance, acceptance, approval, disapproval, rejection, denial, refusal, agreement, consent, permission, authorization, license, certificate, qualification, degree, diploma, award, prize, reward, punishment, penalty, fine, sentence, verdict, judgment, decision, order, command, instruction, direction, guidance, advice, recommendation, suggestion, proposal, offer, invitation, request, demand, requirement, obligation, duty, responsibility, task, job, work, assignment, mission, project, plan, scheme, strategy, tactic, method, approach, technique, procedure, process, operation, activity, event, incident, accident, disaster, catastrophe, crisis, emergency, situation, circumstance, condition, state, position, location, place, area, region, zone, territory, country, nation, state, province, district, city, town, village, community, society, population, people, citizen, resident, inhabitant, foreigner, immigrant, refugee, visitor, guest, host, owner, tenant, landlord, neighbor, friend, enemy, rival, competitor, partner, colleague, associate, companion, ally, supporter, follower, leader, boss, manager, director, supervisor, employee, worker, staff, team, group, organization, institution, company, business, enterprise, firm, corporation, agency, office, department, division, section, unit, branch, committee, board, council, assembly, parliament, government, authority, administration, regime, system, structure, network, chain, series, sequence, cycle, circle, loop, spiral, helix, pattern, design, model, prototype, sample, example, case, instance, illustration, demonstration, experiment, test, trial, attempt, effort, endeavor, struggle, fight, battle, war, conflict, competition, contest, race, match, game, play, performance, show, exhibition, display, presentation, demonstration, parade, festival, celebration, party, meeting, conference, seminar, workshop, lecture, lesson, class, course, program, curriculum, syllabus, schedule, timetable, calendar, agenda",
  },
  forms: {
    countable:
      "a/an + singular countable noun (a book), number + plural countable noun (two books), many/few/several + plural countable noun (many books)",
    uncountable:
      "(no article) + uncountable noun (water), some/much/little + uncountable noun (some water), partitive + of + uncountable noun (a piece of advice, a bottle of water)",
    mixed:
      "Some nouns can be both countable and uncountable with different meanings (e.g., chicken: a chicken (animal), chicken (meat); paper: a paper (article), paper (material))",
  },
  usage: [
    {
      type: "Everyday objects and food",
      description:
        "Countable: apple, egg, chair, car, pen, cup, sandwich. Uncountable: water, bread, rice, milk, cheese, coffee, tea, sugar, salt, butter, meat, fruit (in general)",
      level: "A1-A2",
    },
    {
      type: "Abstract and academic nouns",
      description:
        "Countable: idea, fact, result, problem, solution, suggestion, decision, question, answer. Uncountable: information, advice, knowledge, research, evidence, progress, news, homework, equipment, furniture, luggage, traffic, weather, work, money, music, literature, art, science, education, health, beauty, happiness, love, peace, freedom, justice, courage, patience, experience, respect, responsibility, opportunity, challenge, advantage, disadvantage, influence, impact, effect, result, consequence, outcome, strategy, policy, principle, value, tradition, culture, heritage, legacy, philosophy, design, method, system, structure, pattern, model, trend, fashion, custom, law, regulation, standard, norm",
      level: "B1-C2",
    },
    {
      type: "Dual-use nouns",
      description:
        "Some nouns can be both countable and uncountable with different meanings: chicken (animal vs. meat), paper (article vs. material), glass (cup vs. material), experience (event vs. knowledge), time (occasion vs. duration), light (lamp vs. brightness), hair (strand vs. all hair)",
      level: "A2-C2",
    },
  ],
  examples: {
    countable: {
      singular: "I have a book.",
      plural: "There are three apples on the table.",
      with_many: "Many students are in the classroom.",
      with_few: "Few people know the answer.",
    },
    uncountable: {
      no_article: "Water is important for life.",
      with_some: "I need some information.",
      with_much: "There isn't much sugar left.",
      with_little: "There is little hope of success.",
    },
    dual_use: {
      countable: "I bought a paper (newspaper).",
      uncountable: "Paper is made from wood.",
      countable2: "She had a chicken for dinner (animal).",
      uncountable2: "We ate chicken for lunch (meat).",
    },
  },
  practiceTypes: {
    A1: [
      "Identify countable and uncountable nouns in simple sentences",
      "Choose correct article or quantifier",
      "Match nouns to pictures (e.g., apple, water, bread)",
      "Fill in the blank with a countable or uncountable noun",
    ],
    A2: [
      "Use some/many/much/few/little with nouns",
      "Distinguish between countable and uncountable nouns in context",
      "Correct sentences with article or quantifier errors",
      "Simple gap-filling with countable and uncountable nouns",
    ],
    B1: [
      "Use dual-use nouns in context",
      "Rewrite sentences to use correct noun type",
      "Use countable and uncountable nouns in short paragraphs",
      "Explain the meaning of dual-use nouns in context",
    ],
    B2: [
      "Use countable and uncountable nouns in academic and professional writing",
      "Paraphrase sentences to use correct noun type idiomatically",
      "Correct advanced errors with noun types",
      "Explain the difference between countable and uncountable usage",
    ],
    C1: [
      "Use countable and uncountable nouns in formal and academic registers",
      "Analyze idiomatic and metaphorical uses of noun types",
      "Identify subtle errors in advanced writing",
      "Produce essays using a range of noun types",
    ],
    C2: [
      "Master rare and highly abstract noun types",
      "Critique and edit advanced texts for noun type accuracy",
      "Use countable and uncountable nouns in creative and literary writing",
      "Demonstrate register flexibility with noun types",
    ],
  },
  commonMistakes: {
    beginners: [
      "Adding -s to uncountable nouns: ❌ informations ✅ information",
      "Using 'a/an' with uncountable nouns: ❌ an advice ✅ a piece of advice",
      "Plural verb agreement: ❌ The news are good ✅ The news is good",
      "Using 'many' with uncountable nouns: ❌ many furniture ✅ much furniture",
      "Using 'much' with countable nouns: ❌ much apples ✅ many apples",
    ],
    intermediate: [
      "Confusing dual-use nouns: ❌ a chicken (meat) ✅ chicken (meat); a chicken (animal)",
      "Incorrect quantifiers: ❌ few information ✅ little information",
      "Wrong article: ❌ a research ✅ research",
      "Using 'these/those' with uncountable nouns: ❌ these information ✅ this information",
    ],
    advanced: [
      "Overusing singular agreement with plural countable nouns: ❌ The apples is ✅ The apples are",
      "Incorrect idiomatic use: ❌ a good news ✅ good news",
      "Mixing countable and uncountable forms: ❌ advices ✅ advice",
      "Using plural forms in academic writing: ❌ researches show ✅ research shows",
    ],
  },
  recognition: [
    "Countable nouns can be counted, have singular/plural forms, and use 'a/an', numbers, and quantifiers like 'many', 'few', 'several'.",
    "Uncountable nouns cannot be counted individually, do not use 'a/an', and use quantifiers like 'much', 'little', 'some'.",
    "Some nouns can be both countable and uncountable with different meanings.",
    "Correct article and quantifier usage depends on noun type.",
    "Dual-use nouns are common in English and can cause confusion for learners.",
  ],
  timeMarkers: [
    "now",
    "today",
    "yesterday",
    "tomorrow",
    "this week",
    "last year",
    "at the moment",
    "recently",
    "soon",
  ],
  pronounChanges: {
    countable: {
      singular: "it (the apple)",
      plural: "they (the apples)",
    },
    uncountable: {
      singular: "it (the water)",
    },
    dual_use: {
      countable: "it (the paper = article)",
      uncountable: "it (paper = material)",
    },
  },
  reportingVerbs: [
    "have",
    "need",
    "give",
    "receive",
    "show",
    "find",
    "provide",
    "offer",
    "bring",
    "contain",
    "include",
    "require",
    "lack",
    "represent",
    "express",
    "count",
    "measure",
    "pour",
    "add",
    "buy",
    "sell",
    "eat",
    "drink",
  ],
  exercises: {
    recognition: {
      description: "Identify countable and uncountable nouns in context",
      difficulty: "A1-B1",
      examples: [
        "Find the countable noun: There are three apples.",
        "Find the uncountable noun: I need some information.",
      ],
    },
    correction: {
      description:
        "Correct common mistakes with countable and uncountable nouns",
      difficulty: "A2-B2",
      examples: [
        "❌ I have many luggages. ✅ I have a lot of luggage.",
        "❌ These are good advices. ✅ This is good advice.",
        "❌ Much apples are on the table. ✅ Many apples are on the table.",
      ],
    },
    production: {
      description: "Use countable and uncountable nouns in your own sentences",
      difficulty: "B1-C2",
      examples: [
        "Write a paragraph about your favorite food using both noun types.",
        "Describe a shopping trip and use 'apple', 'water', 'bread', 'information', and 'advice' correctly.",
      ],
    },
  },
  notes: [
    "Countable and uncountable nouns are a key part of English grammar and affect article, quantifier, and verb usage.",
    "Some nouns can be both countable and uncountable with different meanings (dual-use nouns).",
    "Use partitive structures (a piece of, a bottle of, a loaf of) to measure uncountable nouns.",
    "In academic writing, avoid using plural forms for research, evidence, advice, etc.",
    "Be careful with false friends in other languages that may be countable or uncountable in English.",
    "Practice with real-life examples and contexts to master the difference.",
  ],
  culturalContexts: {
    daily_life: {
      description: "Common in daily requests, shopping, and conversation",
      examples: [
        "Can I have some bread?",
        "I need information.",
        "There are three apples on the table.",
      ],
    },
    academic: {
      description: "Essential in academic and professional writing",
      examples: ["Research shows...", "There is evidence that..."],
    },
    idiomatic: {
      description: "Used in idiomatic expressions and news/media",
      examples: ["That's good news!", "Bad weather delayed the flight."],
    },
  },
  specialCases: {
    dual_use: {
      description:
        "Nouns that can be both countable and uncountable with different meanings",
      examples: [
        {
          word: "paper",
          countable: "a paper (an article)",
          uncountable: "paper (material)",
        },
        {
          word: "chicken",
          countable: "a chicken (an animal)",
          uncountable: "chicken (meat)",
        },
        {
          word: "glass",
          countable: "a glass (a cup)",
          uncountable: "glass (material)",
        },
        {
          word: "experience",
          countable: "an experience (an event)",
          uncountable: "experience (knowledge)",
        },
        {
          word: "time",
          countable: "a time (an occasion)",
          uncountable: "time (duration)",
        },
        {
          word: "light",
          countable: "a light (a lamp)",
          uncountable: "light (brightness)",
        },
        {
          word: "hair",
          countable: "a hair (a strand)",
          uncountable: "hair (all hair)",
        },
      ],
    },
  },
  etymology: {
    origin:
      "Many countable and uncountable nouns derive from Old English, Latin, or French, often reflecting concrete or mass concepts.",
    development:
      "The distinction between countable and uncountable nouns developed over centuries as English absorbed vocabulary from other languages.",
    modernUsage:
      "Countable and uncountable nouns are now common in both spoken and written English, especially in academic and professional contexts.",
  },
  crossLinguistic: {
    similarities:
      "Many languages have countable and uncountable nouns, but the specific list and usage rules vary.",
    differences:
      "Some nouns that are countable in English are uncountable in other languages and vice versa.",
    learnerChallenges:
      "Learners often overgeneralize plural forms or use incorrect articles/quantifiers due to interference from their native language.",
  },
  vocabulary: {
    countable: [
      "apple",
      "book",
      "car",
      "dog",
      "table",
      "chair",
      "pen",
      "student",
      "question",
      "idea",
      "friend",
      "city",
      "egg",
      "sandwich",
      "cup",
      "bottle",
      "child",
      "person",
      "house",
      "tree",
      "flower",
      "computer",
      "phone",
      "bag",
      "shoe",
      "coin",
      "ticket",
      "letter",
      "photo",
      "room",
      "window",
      "door",
      "bus",
      "train",
      "plane",
      "cat",
      "bird",
      "fish",
      "star",
      "mountain",
      "river",
      "island",
      "country",
      "language",
      "subject",
      "lesson",
      "game",
      "match",
      "team",
      "group",
      "family",
      "party",
      "meeting",
      "class",
      "course",
      "program",
      "project",
      "plan",
      "goal",
      "aim",
      "result",
      "problem",
      "solution",
      "suggestion",
      "decision",
      "choice",
      "opinion",
      "answer",
      "response",
      "reaction",
      "comment",
      "remark",
      "statement",
      "question",
      "event",
      "incident",
      "accident",
      "disaster",
      "catastrophe",
      "crisis",
      "emergency",
      "situation",
      "circumstance",
      "condition",
      "state",
      "position",
      "location",
      "place",
      "area",
      "region",
      "zone",
      "territory",
      "country",
      "nation",
      "province",
      "district",
      "city",
      "town",
      "village",
      "community",
      "society",
      "population",
      "person",
      "citizen",
      "resident",
      "inhabitant",
      "foreigner",
      "immigrant",
      "refugee",
      "visitor",
      "guest",
      "host",
      "owner",
      "tenant",
      "landlord",
      "neighbor",
      "enemy",
      "rival",
      "competitor",
      "partner",
      "colleague",
      "associate",
      "companion",
      "ally",
      "supporter",
      "follower",
      "leader",
      "boss",
      "manager",
      "director",
      "supervisor",
      "employee",
      "worker",
      "staff",
      "team",
      "group",
      "organization",
      "institution",
      "company",
      "business",
      "enterprise",
      "firm",
      "corporation",
      "agency",
      "office",
      "department",
      "division",
      "section",
      "unit",
      "branch",
      "committee",
      "board",
      "council",
      "assembly",
      "parliament",
      "government",
      "authority",
      "administration",
      "regime",
      "system",
      "structure",
      "network",
      "chain",
      "series",
      "sequence",
      "cycle",
      "circle",
      "loop",
      "spiral",
      "helix",
      "pattern",
      "design",
      "model",
      "prototype",
      "sample",
      "example",
      "case",
      "instance",
      "illustration",
      "demonstration",
      "experiment",
      "test",
      "trial",
      "attempt",
      "effort",
      "endeavor",
      "struggle",
      "fight",
      "battle",
      "competition",
      "contest",
      "race",
      "match",
      "game",
      "play",
      "performance",
      "show",
      "exhibition",
      "display",
      "presentation",
      "parade",
      "festival",
      "celebration",
      "party",
      "meeting",
      "conference",
      "seminar",
      "workshop",
      "lecture",
      "lesson",
      "class",
      "course",
      "program",
      "curriculum",
      "syllabus",
      "schedule",
      "timetable",
      "calendar",
      "agenda",
    ],
    uncountable: [
      "water",
      "rice",
      "advice",
      "information",
      "music",
      "furniture",
      "bread",
      "happiness",
      "news",
      "progress",
      "equipment",
      "homework",
      "knowledge",
      "research",
      "traffic",
      "weather",
      "work",
      "money",
      "sand",
      "air",
      "sugar",
      "salt",
      "love",
      "anger",
      "beauty",
      "health",
      "education",
      "science",
      "literature",
      "art",
      "philosophy",
      "history",
      "culture",
      "tradition",
      "custom",
      "law",
      "order",
      "chaos",
      "silence",
      "noise",
      "violence",
      "war",
      "peace",
      "conflict",
      "agreement",
      "disagreement",
      "decision",
      "choice",
      "opinion",
      "evidence",
      "experience",
      "practice",
      "habit",
      "method",
      "system",
      "pattern",
      "style",
      "trend",
      "fashion",
      "design",
      "plan",
      "project",
      "goal",
      "aim",
      "purpose",
      "result",
      "effect",
      "cause",
      "reason",
      "solution",
      "problem",
      "issue",
      "topic",
      "subject",
      "theme",
      "idea",
      "concept",
      "notion",
      "view",
      "perspective",
      "vision",
      "insight",
      "analysis",
      "summary",
      "review",
      "criticism",
      "comment",
      "statement",
      "question",
      "answer",
      "response",
      "reaction",
      "feedback",
      "support",
      "opposition",
      "help",
      "assistance",
      "service",
      "care",
      "treatment",
      "protection",
      "security",
      "safety",
      "danger",
      "risk",
      "threat",
      "challenge",
      "opportunity",
      "advantage",
      "benefit",
      "loss",
      "damage",
      "harm",
      "injury",
      "pain",
      "pleasure",
      "joy",
      "sorrow",
      "sadness",
      "grief",
      "regret",
      "remorse",
      "guilt",
      "shame",
      "pride",
      "glory",
      "honor",
      "dignity",
      "admiration",
      "envy",
      "jealousy",
      "hatred",
      "hostility",
      "rage",
      "fury",
      "aggression",
      "confusion",
      "doubt",
      "uncertainty",
      "certainty",
      "confidence",
      "conviction",
      "assumption",
      "expectation",
      "anticipation",
      "surprise",
      "shock",
      "disappointment",
      "frustration",
      "boredom",
      "interest",
      "wonder",
      "amazement",
      "awe",
      "terror",
      "panic",
      "anxiety",
      "worry",
      "concern",
      "sympathy",
      "empathy",
      "pity",
      "mercy",
      "forgiveness",
      "tolerance",
      "acceptance",
      "approval",
      "disapproval",
      "rejection",
      "denial",
      "refusal",
      "consent",
      "permission",
      "authorization",
      "qualification",
      "degree",
      "award",
      "prize",
      "reward",
      "punishment",
      "penalty",
      "fine",
      "sentence",
      "verdict",
      "judgment",
      "order",
      "command",
      "instruction",
      "direction",
      "guidance",
      "recommendation",
      "suggestion",
      "proposal",
      "offer",
      "invitation",
      "request",
      "demand",
      "requirement",
      "obligation",
      "duty",
      "task",
      "job",
      "work",
      "assignment",
      "mission",
      "scheme",
      "strategy",
      "tactic",
      "approach",
      "technique",
      "procedure",
      "operation",
      "activity",
      "event",
      "incident",
      "accident",
      "disaster",
      "catastrophe",
      "crisis",
      "emergency",
      "situation",
      "circumstance",
      "condition",
      "state",
      "position",
      "location",
      "place",
      "area",
      "region",
      "zone",
      "territory",
      "country",
      "nation",
      "province",
      "district",
      "city",
      "town",
      "village",
      "community",
      "society",
      "population",
    ],
  },
  grammaticalPatterns: {
    article_usage: {
      countable: [
        "a book",
        "an apple",
        "the car",
        "some apples",
        "many books",
        "few students",
      ],
      uncountable: [
        "some water",
        "much information",
        "little sugar",
        "the furniture",
        "a piece of advice",
        "a bottle of water",
      ],
    },
    verb_agreement: {
      countable: ["The apples are red.", "A book is on the table."],
      uncountable: [
        "The information is useful.",
        "Water is important for life.",
      ],
    },
    quantifiers: {
      countable: ["many", "few", "several", "a number of", "a few"],
      uncountable: [
        "much",
        "little",
        "a bit of",
        "a great deal of",
        "a little",
      ],
    },
    partitives: {
      uncountable: [
        "a piece of advice",
        "a loaf of bread",
        "a bottle of water",
        "a bar of chocolate",
        "a cup of tea",
        "a slice of cheese",
      ],
    },
  },
  usageContexts: {
    A1: ["shopping", "food and drink", "school", "family", "basic needs"],
    A2: [
      "giving/receiving advice",
      "home and furniture",
      "travel",
      "weather",
      "simple descriptions",
    ],
    B1: [
      "news and media",
      "progress updates",
      "information requests",
      "academic settings",
      "workplace",
    ],
    B2: [
      "academic writing",
      "technical descriptions",
      "professional communication",
      "formal essays",
    ],
    C1: [
      "research papers",
      "literary analysis",
      "advanced presentations",
      "creative writing",
    ],
    C2: [
      "critical reviews",
      "specialized academic discourse",
      "creative and metaphorical writing",
    ],
  },
  errorPatterns: {
    A1: [
      "❌ a waters ✅ water",
      "❌ an informations ✅ information",
      "❌ a breads ✅ bread",
      "❌ much apples ✅ many apples",
    ],
    A2: [
      "❌ a advices ✅ advice",
      "❌ few information ✅ little information",
      "❌ many furniture ✅ much furniture",
    ],
    B1: [
      "❌ the apples is ✅ the apples are",
      "❌ the information are ✅ the information is",
    ],
    B2: [
      "❌ researches ✅ research",
      "❌ furnitures ✅ furniture",
      "❌ luggages ✅ luggage",
    ],
    C1: ["❌ evidences ✅ evidence", "❌ informations ✅ information"],
    C2: ["❌ advices ✅ advice", "❌ datas ✅ data"],
  },
  learningStrategies: {
    A1: [
      "Memorize common countable and uncountable nouns with pictures and examples.",
      "Practice using correct article and quantifier.",
      "Listen for noun types in simple conversations.",
    ],
    A2: [
      "Use partitive structures (a piece of, a bottle of) in speaking and writing.",
      "Compare countable and uncountable nouns in context.",
      "Correct common mistakes in exercises.",
    ],
    B1: [
      "Practice using quantifiers (many, much, few, little) with noun types.",
      "Write short texts using a variety of noun types.",
      "Edit sentences for correct noun type usage.",
    ],
    B2: [
      "Use noun types in academic and technical writing.",
      "Paraphrase sentences to use correct noun type idiomatically.",
      "Analyze authentic texts for advanced usage.",
    ],
    C1: [
      "Produce essays and presentations using advanced noun types.",
      "Identify and correct subtle errors in peer writing.",
      "Experiment with idiomatic and metaphorical uses.",
    ],
    C2: [
      "Master rare and highly abstract noun types.",
      "Critique and edit advanced texts for accuracy.",
      "Use noun types creatively in literary and academic contexts.",
    ],
  },
};
