// Comprehensive Irregular Plurals Data (A1-C2)
const irregular_plurals = {
  definition: {
    core_concept:
      "Irregular plurals are nouns that form their plural form in ways other than simply adding '-s' or '-es' to the singular form.",
    grammatical_status:
      "These nouns follow specific patterns or have completely unique plural forms that must be memorized.",
    linguistic_significance:
      "They represent historical language changes and exceptions to regular pluralization rules.",
    examples: [
      "child/children",
      "foot/feet",
      "tooth/teeth",
      "man/men",
      "woman/women",
      "person/people",
      "goose/geese",
      "mouse/mice",
      "louse/lice",
      "ox/oxen",
      "criterion/criteria",
      "phenomenon/phenomena",
      "analysis/analyses",
      "crisis/crises",
      "thesis/theses",
      "index/indices",
      "matrix/matrices",
      "vertex/vertices",
      "alumnus/alumni",
      "focus/foci",
      "nucleus/nuclei",
      "radius/radii",
      "stimulus/stimuli",
      "syllabus/syllabi",
      "fungus/fungi",
      "cactus/cacti",
      "octopus/octopi",
      "hippopotamus/hippopotami",
      "platypus/platypi",
      "corpus/corpora",
      "genus/genera",
      "opus/opera",
      "viscus/viscera",
      "larva/larvae",
      "alga/algae",
      "vertebra/vertebrae",
      "antenna/antennae",
      "formula/formulae",
      "nebula/nebulae",
      "villa/villae",
      "peninsula/peninsulae",
      "minutia/minutiae",
      "curriculum/curricula",
      "memorandum/memoranda",
      "datum/data",
      "medium/media",
      "bacterium/bacteria",
      "criterion/criteria",
      "phenomenon/phenomena",
      "automaton/automata",
      "polyhedron/polyhedra",
      "hedron/polyhedra",
      "polyhedron/polyhedra",
      "hedron/polyhedra",
    ],
  },
  cefrLevels: {
    A1: "Basic recognition of common irregular plurals (child/children, foot/feet, man/men)",
    A2: "Understanding of basic irregular patterns and common exceptions",
    B1: "Mastery of most common irregular plurals and their usage in context",
    B2: "Advanced irregular plurals including Latin/Greek derived words",
    C1: "Complex irregular plurals and academic/scientific terminology",
    C2: "Complete mastery of all irregular plural forms including rare and specialized terms",
  },
  forms: {
    basic: "Singular form → Irregular plural form",
    vowel_change: "foot → feet, tooth → teeth, goose → geese",
    en_ending: "child → children, ox → oxen",
    no_change: "sheep → sheep, deer → deer, fish → fish",
    latin_greek: "criterion → criteria, phenomenon → phenomena",
    es_ending: "analysis → analyses, crisis → crises",
  },
  usage: [
    "Common everyday objects and people",
    "Body parts and anatomy",
    "Animals and creatures",
    "Academic and scientific terms",
    "Latin and Greek derived words",
    "Technical and specialized vocabulary",
  ],
  examples: {
    basic: [
      "child/children",
      "foot/feet",
      "tooth/teeth",
      "man/men",
      "woman/women",
    ],
    body_parts: ["foot/feet", "tooth/teeth", "hand/hands", "eye/eyes"],
    animals: ["goose/geese", "mouse/mice", "louse/lice", "ox/oxen"],
    people: ["person/people", "man/men", "woman/women", "child/children"],
    academic: [
      "criterion/criteria",
      "phenomenon/phenomena",
      "analysis/analyses",
    ],
    technical: ["index/indices", "matrix/matrices", "vertex/vertices"],
  },
  practiceTypes: {
    A1: "Recognition exercises with common irregular plurals",
    A2: "Basic production exercises with everyday irregular plurals",
    B1: "Context-based exercises with irregular plurals in sentences",
    B2: "Advanced exercises with Latin/Greek derived irregular plurals",
    C1: "Complex exercises with academic and technical irregular plurals",
    C2: "Mastery exercises with rare and specialized irregular plurals",
  },
  commonMistakes: {
    beginners: [
      "Adding -s to irregular plurals",
      "Using regular patterns for irregular words",
    ],
    intermediate: [
      "Confusing similar irregular patterns",
      "Overgeneralizing irregular rules",
    ],
    advanced: [
      "Incorrect Latin/Greek plural forms",
      "Using archaic or incorrect forms",
    ],
  },
  recognition: [
    "Memorize common irregular patterns",
    "Learn Latin/Greek derived word patterns",
    "Understand historical language changes",
    "Practice with context clues",
  ],
  timeMarkers: ["Always", "In all contexts", "Regardless of time period"],
  pronounChanges: {
    basic: "Singular pronouns → Plural pronouns",
    advanced: "Complex pronoun agreement with irregular plurals",
  },
  reportingVerbs: ["Use", "Apply", "Recognize", "Memorize", "Practice"],
  exercises: {
    recognition: "Identify correct irregular plural forms",
    correction: "Correct incorrect irregular plural usage",
    production: "Use irregular plurals in context",
  },
  notes: [
    "Many irregular plurals have historical origins",
    "Latin and Greek words often follow classical plural patterns",
    "Some words have both regular and irregular plural forms",
    "Context determines which plural form is appropriate",
  ],
  culturalContexts: {
    daily_life: "Common irregular plurals in everyday conversation",
    academic: "Academic and scientific irregular plurals",
    idiomatic: "Idiomatic expressions with irregular plurals",
  },
  specialCases: {
    dual_forms: "Words with both regular and irregular plurals",
    archaic: "Archaic or rarely used irregular forms",
    regional: "Regional variations in irregular plural usage",
  },
  etymology: {
    origin: "Historical development of irregular plural forms",
    development: "How irregular plurals evolved over time",
    modernUsage: "Current usage patterns of irregular plurals",
  },
  crossLinguistic: {
    similarities: "Similar irregular patterns in other languages",
    differences: "How irregular plurals differ across languages",
    learnerChallenges: "Common challenges for language learners",
  },
  vocabulary: {
    A1: ["child/children", "foot/feet", "man/men", "woman/women"],
    A2: ["tooth/teeth", "goose/geese", "mouse/mice", "person/people"],
    B1: ["ox/oxen", "louse/lice", "sheep/sheep", "deer/deer"],
    B2: ["criterion/criteria", "phenomenon/phenomena", "analysis/analyses"],
    C1: [
      "index/indices",
      "matrix/matrices",
      "vertex/vertices",
      "alumnus/alumni",
    ],
    C2: ["opus/opera", "corpus/corpora", "genus/genera", "viscus/viscera"],
  },
  grammaticalPatterns: {
    article_usage: "Articles with irregular plurals",
    verb_agreement: "Verb agreement with irregular plural subjects",
    quantifiers: "Quantifiers with irregular plurals",
  },
  usageContexts: {
    A1: "Basic everyday contexts",
    A2: "Simple descriptive contexts",
    B1: "Narrative and explanatory contexts",
    B2: "Academic and professional contexts",
    C1: "Specialized and technical contexts",
    C2: "Advanced academic and research contexts",
  },
  errorPatterns: {
    A1: "Adding -s to irregular words",
    A2: "Confusing similar irregular patterns",
    B1: "Overgeneralizing irregular rules",
    B2: "Incorrect Latin/Greek forms",
    C1: "Using archaic forms",
    C2: "Contextual misuse of irregular plurals",
  },
  learningStrategies: {
    A1: "Memorization of common irregular plurals",
    A2: "Pattern recognition and grouping",
    B1: "Context-based learning and practice",
    B2: "Etymology-based understanding",
    C1: "Advanced pattern analysis",
    C2: "Mastery through extensive practice and exposure",
  },
};

const tense = {
  irregular_plurals,
};

export default tense;
