import { cleftSentencesType } from "@/types/grammars/grammar/grammar_advance/cleftSentences";

export const cleftSentencesData: cleftSentencesType = {
  id: 26,
  definition:
    "Cleft sentences are complex sentences that divide a simple sentence into two parts to emphasize a particular piece of information by moving the focus element to a prominent position in the sentence structure.",
  etymology:
    "The term 'cleft' comes from the past participle of 'cleave,' meaning to split or divide, reflecting how these sentences split information into two parts for emphasis.",
  purpose: [
    "To emphasize or focus on a specific part of a sentence (subject, object, adverbial)",
    "To highlight important information or create contrast between elements",
    "To add variety, clarity, and sophistication in writing and speaking",
    "To correct misunderstandings or provide clarification",
    "To create cohesion and improve information flow in discourse",
    "To achieve stylistic effects in formal and academic writing",
  ],
  levels: {
    A1: {
      description:
        "Basic understanding that cleft sentences put focus on one part of a sentence using simple 'It is/was' structures.",
      examples: [
        "It is John who is my best friend.",
        "It was yesterday that we met.",
        "It is my mother who cooks dinner.",
        "It was the cat that broke the vase.",
        "It is English that I study every day.",
        "It was at home that I forgot my keys.",
      ],
      structure: "It + be + focused element + who/that + rest of sentence",
      keyVocabulary: [
        "It is/was",
        "who",
        "that",
        "focus",
        "emphasis",
        "highlight",
      ],
      learningObjectives: [
        "Recognize basic cleft sentence structures",
        "Understand the concept of emphasis in sentences",
        "Use simple It-clefts with present and past tense",
      ],
      notes: [
        "Used mostly with 'it is' or 'it was'",
        "The focused part is usually a noun or noun phrase",
        "Use 'who' for people and 'that' for things, places, or time",
        "The original sentence is divided into two parts",
      ],
      commonPatterns: [
        "It + is + person + who + verb",
        "It + was + thing + that + happened",
        "It + is + place + where + action occurs",
      ],
      practiceActivities: [
        "Transform simple sentences into It-clefts",
        "Identify the focused element in cleft sentences",
        "Match cleft sentences with their original forms",
      ],
    },
    A2: {
      description:
        "Using cleft sentences to emphasize time, place, manner, or reason more clearly with expanded vocabulary and structures.",
      examples: [
        "It was at 5 o'clock that she arrived.",
        "It is the big red car that I like.",
        "It was because of the rain that we stayed home.",
        "It is in the library where I study best.",
        "It was with great care that he handled the antique.",
        "It is for this reason that we must act now.",
        "It was during the summer that they got married.",
        "It is by hard work that success is achieved.",
      ],
      additionalStructures: [
        "It + be + time expression + when/that + clause",
        "It + be + place expression + where/that + clause",
        "It + be + reason/cause + why/that + clause",
        "It + be + manner + how/that + clause",
      ],
      keyVocabulary: [
        "because of",
        "during",
        "where",
        "when",
        "why",
        "how",
        "for this reason",
        "with",
      ],
      learningObjectives: [
        "Emphasize different types of adverbials (time, place, manner, reason)",
        "Use appropriate wh-words in cleft structures",
        "Create clefts with prepositional phrases",
      ],
      notes: [
        "Can emphasize adverbials (time, place, manner, reason)",
        "More frequent use in spoken English for clarification",
        "Prepositional phrases can be clefted",
        "Choose appropriate relative words (where, when, why)",
      ],
      commonPatterns: [
        "It + was + time + when/that + event",
        "It + is + place + where + activity",
        "It + was + because of + reason + that + result",
      ],
      practiceActivities: [
        "Create clefts emphasizing different adverbials",
        "Choose correct relative words for cleft sentences",
        "Answer questions using cleft structures",
      ],
    },
    B1: {
      description:
        "Understanding various types of cleft sentences and how to use them for different emphasis, including It-clefts, Wh-clefts, and All-clefts.",
      types: [
        {
          name: "It-cleft",
          structure: "It + be + focused element + who/that/which + clause",
          example: "It was my brother who called last night.",
          additionalExamples: [
            "It is the results that matter most.",
            "It was with enthusiasm that she accepted the job.",
            "It is to Paris that we're traveling next month.",
          ],
          usage: [
            "Most common type",
            "Emphasizes any sentence element",
            "Formal and informal contexts",
          ],
        },
        {
          name: "Wh-cleft (Pseudo-cleft)",
          structure: "Wh-clause + be + focused element",
          example: "What I need is a good rest.",
          additionalExamples: [
            "Where she lives is a complete mystery.",
            "When he arrived was exactly at midnight.",
            "Why they left remains unclear.",
            "How she solved it was brilliant.",
          ],
          usage: [
            "Emphasizes the predicate",
            "Often used for definitions",
            "Common in explanations",
          ],
        },
        {
          name: "All-cleft",
          structure: "All + (that) + clause + be + focused element",
          example: "All I want is peace and quiet.",
          additionalExamples: [
            "All she did was complain about the weather.",
            "All that matters is your happiness.",
            "All we need is more time to finish.",
          ],
          usage: [
            "Emphasizes limitation or exclusivity",
            "Informal register",
            "Shows restriction",
          ],
        },
        {
          name: "Reverse Wh-cleft",
          structure: "Focused element + be + wh-clause",
          example: "A good rest is what I need.",
          additionalExamples: [
            "Patience is what you need most.",
            "Success is what everyone desires.",
          ],
          usage: [
            "Alternative to regular wh-clefts",
            "Slightly more formal",
            "Emphasizes the focused element",
          ],
        },
      ],
      usage: [
        "To clarify or explain complex information",
        "To respond to questions focusing on specific parts",
        "To create contrast or correction between alternatives",
        "To define or identify important concepts",
        "To show limitation or exclusivity",
      ],
      keyVocabulary: [
        "pseudo-cleft",
        "focus",
        "emphasis",
        "contrast",
        "identification",
        "clarification",
      ],
      learningObjectives: [
        "Distinguish between different types of cleft sentences",
        "Use clefts appropriately for different communicative purposes",
        "Transform sentences using various cleft structures",
      ],
      notes: [
        "It-clefts are the most common and versatile type",
        "Wh-clefts usually start with what, where, who, when, why, or how",
        "All-clefts express limitation and are more informal",
        "Choice of cleft type depends on what you want to emphasize",
      ],
      commonPatterns: [
        "What + clause + be + noun phrase",
        "All + (that) + subject + verb + be + complement",
        "It + be + noun phrase + that + clause",
      ],
      practiceActivities: [
        "Convert between different cleft types",
        "Choose appropriate cleft type for specific contexts",
        "Analyze cleft sentences in authentic texts",
      ],
    },
    B2: {
      description:
        "Using cleft sentences to express contrast, correction, or irony with more complex sentence patterns and sophisticated discourse functions.",
      examples: [
        "It was Jane, not Paul, who broke the vase.",
        "What he really wants is recognition, not money.",
        "It wasn't the money that motivated him, but the challenge.",
        "What surprised everyone was his sudden resignation.",
        "It is precisely because of this attitude that problems arise.",
        "All that remains is to implement the solution.",
        "It was only after the meeting that we understood the implications.",
        "What concerns me most is the lack of communication.",
      ],
      advancedStructures: [
        "It + be + focused element + who/that + clause with negation or contrast",
        "Wh-clefts with complex noun clauses and relative clauses",
        "Clefts with intensifying adverbs (precisely, exactly, only, just)",
        "Clefts with complex time and conditional expressions",
      ],
      usage: [
        "To emphasize correction or contrast between people, things, or ideas",
        "To create dramatic, ironic, or emphatic effects in discourse",
        "To highlight unexpected or surprising information",
        "To structure complex arguments and explanations",
      ],
      keyVocabulary: [
        "precisely",
        "exactly",
        "particularly",
        "specifically",
        "only",
        "just",
        "rather than",
        "instead of",
      ],
      learningObjectives: [
        "Use clefts for contrast and correction",
        "Employ clefts in argumentative and explanatory discourse",
        "Create sophisticated emphasis with intensifying adverbs",
      ],
      notes: [
        "Can be used to avoid repetition and add focus in complex texts",
        "Often found in formal and literary English",
        "Useful for creating suspense or dramatic effect",
        "Help organize information hierarchically",
      ],
      commonPatterns: [
        "It + be + not + X + but + Y + that/who + clause",
        "What + clause + be + not + X + but + Y",
        "It + be + only/just + when/after/because + clause",
      ],
      practiceActivities: [
        "Create clefts expressing contrast and correction",
        "Use clefts in argumentative writing",
        "Analyze clefts in formal texts and speeches",
      ],
      rhetoricalFunctions: [
        "Argumentation and persuasion",
        "Clarification and correction",
        "Creating emphasis and drama",
        "Structuring complex information",
      ],
    },
    C1: {
      description:
        "Mastering subtle uses of cleft sentences for stylistic effect and precise emphasis in both speech and writing, including academic and professional contexts.",
      examples: [
        "It is precisely this attitude that perpetuates the problem.",
        "What makes this theory particularly compelling is the empirical evidence.",
        "It was not until the data was analyzed that the pattern emerged.",
        "What distinguishes this approach from others is its comprehensive methodology.",
        "It is through careful observation that we gain true understanding.",
        "What remains to be determined is the long-term impact.",
        "It is in the intersection of these disciplines that innovation occurs.",
        "What the research ultimately demonstrates is a paradigm shift.",
      ],
      usage: [
        "To highlight abstract or complex ideas in academic discourse",
        "To create cohesion and logical flow in formal writing",
        "To emphasize key findings, conclusions, or insights",
        "To structure sophisticated arguments and analyses",
      ],
      keyVocabulary: [
        "precisely",
        "particularly",
        "ultimately",
        "fundamentally",
        "essentially",
        "specifically",
        "notably",
        "significantly",
      ],
      learningObjectives: [
        "Use clefts for academic and professional communication",
        "Create sophisticated textual cohesion with clefts",
        "Employ clefts for precise emphasis in complex discourse",
      ],
      notes: [
        "Cleft sentences help structure information logically in academic texts",
        "Useful in argumentation, analysis, and persuasive writing",
        "Create smooth transitions between ideas and paragraphs",
        "Essential for high-level written and spoken discourse",
      ],
      commonPatterns: [
        "It + be + through/by/in + abstract concept + that + result",
        "What + makes/distinguishes/characterizes + X + be + Y",
        "It + be + not until/only when + condition + that + result",
      ],
      practiceActivities: [
        "Use clefts in academic writing and presentations",
        "Create cohesive texts using various cleft structures",
        "Analyze clefts in scholarly articles and reports",
      ],
      rhetoricalFunctions: [
        "Academic argumentation and analysis",
        "Professional communication and presentation",
        "Sophisticated persuasion and influence",
        "Complex explanation and instruction",
      ],
      stylistics: [
        "Formal register and tone",
        "Academic and professional discourse",
        "Sophisticated emphasis and focus",
        "Elegant variation and style",
      ],
    },
    C2: {
      description:
        "Using cleft sentences flexibly and creatively to manipulate information focus and nuance in sophisticated discourse, combining with other advanced grammatical and rhetorical devices.",
      examples: [
        "It is in the nuances of linguistic expression that true meaning resides.",
        "What the comprehensive analysis ultimately reveals is a complex web of interconnected factors.",
        "It was through the synthesis of disparate theoretical frameworks that breakthrough understanding emerged.",
        "What distinguishes this paradigmatic approach from conventional methodologies is its holistic integration of multiple perspectives.",
        "It is not merely the quantitative data, but rather the qualitative insights that illuminate the phenomenon.",
        "What remains fundamentally challenging is the reconciliation of competing theoretical paradigms.",
        "It is precisely within these apparent contradictions that profound truths may be discovered.",
        "What the longitudinal study conclusively demonstrates is the multifaceted nature of the relationship.",
      ],
      advancedFeatures: [
        "Combining cleft sentences with inversion, fronting, and ellipsis for maximum stylistic effect",
        "Using clefts in high-level academic, literary, and professional contexts",
        "Creating complex information hierarchies through nested and coordinated clefts",
        "Employing clefts for subtle persuasion and rhetorical manipulation",
      ],
      keyVocabulary: [
        "paradigmatic",
        "multifaceted",
        "synthesis",
        "comprehensive",
        "longitudinal",
        "contradictions",
        "reconciliation",
        "holistic",
      ],
      learningObjectives: [
        "Master sophisticated cleft usage in professional and academic contexts",
        "Combine clefts with other advanced grammatical structures",
        "Use clefts for subtle rhetorical and stylistic effects",
      ],
      notes: [
        "Allows for fine-grained control over emphasis and contrast in complex discourse",
        "Helps guide the listener's or reader's interpretation with precision",
        "Essential for highest levels of academic and professional communication",
        "Demonstrates complete mastery of English information structure",
      ],
      commonPatterns: [
        "It + be + in/through/within + complex abstract concept + that + sophisticated insight",
        "What + complex analysis/study + ultimately/conclusively + reveals/demonstrates + be + nuanced finding",
        "It + be + not merely/simply + X + but rather + Y + that + explains phenomenon",
      ],
      practiceActivities: [
        "Create sophisticated academic and professional texts using advanced clefts",
        "Combine clefts with other rhetorical devices for maximum effect",
        "Analyze and emulate cleft usage in high-level publications",
      ],
      rhetoricalFunctions: [
        "Sophisticated academic argumentation",
        "High-level professional discourse",
        "Literary and artistic expression",
        "Complex theoretical exposition",
      ],
      stylistics: [
        "Mastery of formal register variations",
        "Sophisticated rhetorical manipulation",
        "Complex information architecture",
        "Elegant and precise expression",
      ],
      discourse: [
        "Academic paper writing and presentation",
        "Professional report composition",
        "Literary and creative writing",
        "Complex theoretical discussion",
      ],
    },
  },
  types: {
    "It-cleft": {
      definition:
        "A sentence starting with 'It is/was' that focuses on one part of the sentence by moving it to a prominent position.",
      structure: "It + be + focused element + who/that/which + clause",
      examples: [
        "It was the noise that woke me up.",
        "It is Sarah who will lead the team.",
        "It was because of the rain that we cancelled the picnic.",
        "It is in London where he was born.",
      ],
      variations: [
        "It + modal + be + focused element + who/that + clause",
        "It + perfect tense + be + focused element + who/that + clause",
      ],
      formalityLevel:
        "Neutral - suitable for both formal and informal contexts",
      frequency: "Most common type of cleft sentence",
    },
    "Wh-cleft (Pseudo-cleft)": {
      definition:
        "A cleft sentence beginning with a wh-word (what, where, who, when, why, how) that emphasizes the predicate.",
      structure: "Wh-clause + be + focused element",
      examples: [
        "What I want is a new car.",
        "Where she lives is a secret.",
        "What surprised me was his honesty.",
        "How he did it remains a mystery.",
      ],
      variations: [
        "Wh-clause + modal + be + focused element",
        "Wh-clause + present perfect + be + focused element",
      ],
      formalityLevel: "Slightly more formal than It-clefts",
      frequency: "Common in explanatory and definitional contexts",
    },
    "Reverse Wh-cleft": {
      definition:
        "A cleft sentence where the focused element comes first, followed by 'be' and then the wh-clause.",
      structure: "Focused element + be + wh-clause",
      examples: [
        "A good rest is what I need.",
        "Patience is what you need most.",
        "The main problem is what we're discussing.",
        "Hard work is what success requires.",
      ],
      variations: ["Focused element + modal + be + wh-clause"],
      formalityLevel: "Formal - more common in written English",
      frequency: "Less common than regular wh-clefts",
    },
    "All-cleft": {
      definition:
        "A cleft sentence starting with 'All' that emphasizes limitation or exclusivity of an action or state.",
      structure: "All + (that) + clause + be + focused element",
      examples: [
        "All I want is peace.",
        "All she did was cry.",
        "All that matters is your happiness.",
        "All we need is love.",
      ],
      variations: ["All + subject + modal + verb + be + focused element"],
      formalityLevel: "Informal - common in spoken English",
      frequency: "Moderate frequency in informal discourse",
    },
    "There-cleft": {
      definition:
        "A cleft sentence using existential 'there' construction to emphasize the existence or occurrence of something.",
      structure: "There + be + focused element + relative clause",
      examples: [
        "There's something I need to tell you.",
        "There was a man who helped me.",
        "There are people who believe in this.",
      ],
      variations: ["There + modal + be + focused element + relative clause"],
      formalityLevel: "Neutral",
      frequency: "Moderate frequency",
    },
    "Inferential cleft": {
      definition:
        "A cleft sentence that draws conclusions or makes inferences, often using 'the reason why' or 'the way'.",
      structure: "The reason why/way + clause + be + focused element",
      examples: [
        "The reason why he left is unclear.",
        "The way she solved it was brilliant.",
        "The place where it happened was here.",
      ],
      variations: ["The reason + clause + modal + be + focused element"],
      formalityLevel: "Formal",
      frequency: "Less common, used in analytical contexts",
    },
  },
  functions: [
    "Emphasize a specific part of a sentence for clarity or contrast",
    "Correct or contradict previous information",
    "Clarify or define concepts and relationships",
    "Add stylistic variety and sophistication to writing",
    "Create cohesion and improve information flow in discourse",
    "Structure complex arguments and explanations logically",
    "Highlight new or important information in context",
    "Create dramatic or rhetorical effects in communication",
  ],
  communicativePurposes: [
    "Information focus and highlighting",
    "Contrast and comparison",
    "Correction and clarification",
    "Emphasis and intensification",
    "Discourse organization and coherence",
    "Stylistic enhancement and variation",
  ],
  syntacticFeatures: [
    "Biclausal structure with main and subordinate clauses",
    "Movement of focused element to prominent position",
    "Use of relative pronouns (who, that, which, where, when)",
    "Subject-verb agreement in both clauses",
    "Tense and modal consistency across clauses",
  ],
  semanticAspects: [
    "Presupposition: the cleft clause is assumed to be true",
    "Focus: the clefted element receives primary attention",
    "Information structure: new vs. given information organization",
    "Exhaustive interpretation: implies exclusivity of the focused element",
  ],
  pragmaticUses: [
    "Responding to implicit or explicit questions",
    "Correcting misconceptions or false assumptions",
    "Introducing new topics or shifting focus",
    "Creating emphasis for persuasive effect",
    "Establishing contrast between alternatives",
    "Organizing complex information hierarchically",
  ],
  commonMistakes: [
    "Using cleft sentences unnecessarily, making writing wordy or awkward",
    "Incorrect subject-verb agreement in cleft clauses",
    "Mixing types incorrectly (e.g., It-cleft with incorrect wh-words)",
    "Wrong choice of relative pronoun (who vs. that vs. which)",
    "Overuse in contexts where simple sentences would be clearer",
    "Inconsistent tense between main and subordinate clauses",
    "Placing focus on elements that don't need emphasis",
    "Creating ambiguity through unclear cleft structures",
  ],
  teachingStrategies: [
    "Start with simple transformations from basic to cleft sentences",
    "Use question-answer patterns to practice focus",
    "Analyze authentic texts to see clefts in context",
    "Practice different types progressively from A1 to C2",
    "Use contrastive exercises to highlight differences",
    "Incorporate clefts into speaking and writing activities",
    "Provide extensive exposure through listening materials",
    "Use correction activities to address common mistakes",
  ],
  assessmentCriteria: [
    "Correct formation of cleft structures",
    "Appropriate choice of cleft type for context",
    "Proper use of relative pronouns and connectors",
    "Effective emphasis and focus achievement",
    "Integration with surrounding discourse",
    "Avoidance of unnecessary complexity",
    "Maintenance of clarity and coherence",
    "Demonstration of stylistic sophistication at higher levels",
  ],
  practicalApplications: [
    "Academic writing for emphasis and structure",
    "Professional presentations for highlighting key points",
    "Persuasive speaking for creating emphasis",
    "Formal debates for clarification and contrast",
    "Creative writing for stylistic effects",
    "Technical writing for precise focus",
    "News reporting for information highlighting",
    "Educational explanations for clarity",
  ],
  practiceTips: [
    "Start by identifying the part of the sentence you want to emphasize",
    "Choose the correct cleft type depending on what you want to highlight",
    "Use cleft sentences in responses to questions to practice focus",
    "Read and analyze examples in real contexts and authentic materials",
    "Practice transforming simple sentences into various cleft types",
    "Pay attention to the presupposed information in cleft sentences",
    "Use clefts sparingly to avoid overuse and maintain effectiveness",
    "Focus on natural integration with surrounding discourse",
    "Practice both recognition and production of cleft sentences",
    "Consider the formality level and appropriateness for context",
  ],
  crossLinguisticNotes: [
    "Not all languages have equivalent cleft sentence structures",
    "Some languages use different strategies for emphasis and focus",
    "Word order differences may affect cleft sentence formation",
    "Translation of clefts may require restructuring in other languages",
    "Cultural differences in emphasis patterns may influence usage",
  ],
  relatedGrammarPoints: [
    "Relative clauses and relative pronouns",
    "Subject-verb agreement in complex sentences",
    "Information structure and word order",
    "Fronting and topicalization",
    "Existential 'there' constructions",
    "Focus particles and intensifiers",
    "Inversion and emphasis structures",
    "Discourse markers and cohesion",
  ],
  references: [
    "Swan, M. (2016). Practical English Usage (4th edition). Oxford University Press.",
    "Quirk, R., Greenbaum, S., Leech, G., & Svartvik, J. (1985). A Comprehensive Grammar of the English Language. Longman.",
    "Huddleston, R., & Pullum, G. K. (2002). The Cambridge Grammar of the English Language. Cambridge University Press.",
    "Biber, D., Johansson, S., Leech, G., Conrad, S., & Finegan, E. (1999). Longman Grammar of Spoken and Written English. Longman.",
    "Carter, R., & McCarthy, M. (2006). Cambridge Grammar of English. Cambridge University Press.",
    "Collins, P. C. (1991). Cleft and Pseudo-cleft Constructions in English. Routledge.",
    "Prince, E. F. (1978). A comparison of wh-clefts and it-clefts in discourse. Language, 54(4), 883-906.",
    "Hedberg, N. (2000). The referential status of clefts. Language, 76(4), 891-920.",
  ],
  additionalResources: [
    "https://www.cambridge.org/core/journals/english-language-and-linguistics - Cambridge English Language and Linguistics",
    "https://www.oxfordlearnersdictionaries.com - Oxford Advanced Learner's Dictionary",
    "https://corpus.byu.edu/coca/ - Corpus of Contemporary American English for authentic examples",
    "https://www.englishgrammar.org - Comprehensive grammar explanations and exercises",
    "https://learnenglish.britishcouncil.org - British Council learning resources with cleft sentence materials",
  ],
};
