import { collocationsType } from "@/types/grammars/grammar/grammar_advance/collocations";

export const collocationsDatabaseData: collocationsType = {
  id: 27,
  topic: "Collocations",
  level: "A1–C2",
  definition:
    "Collocations are natural combinations of words that are commonly used together by native speakers. They sound 'right' because they frequently appear together in speech and writing.",
  importance: [
    "They make your English sound more natural and fluent.",
    "Improve understanding of native-level texts and conversations.",
    "Help avoid unnatural or incorrect word combinations.",
    "Enhance writing in academic, business, and everyday contexts.",
  ],
  categories: {
    basedOnWordType: {
      verbNoun: {
        definition: "A verb that collocates with a specific noun.",
        examples: [
          "make a decision",
          "do homework",
          "have lunch",
          "catch a cold",
          "break the ice",
        ],
      },
      adjectiveNoun: {
        definition: "An adjective that naturally combines with a noun.",
        examples: [
          "strong coffee",
          "heavy rain",
          "fast car",
          "great idea",
          "deep sleep",
        ],
      },
      nounNoun: {
        definition: "Two nouns that go together naturally.",
        examples: [
          "data analysis",
          "job satisfaction",
          "technology sector",
          "coffee machine",
        ],
      },
      adverbVerb: {
        definition: "An adverb that intensifies or modifies a verb.",
        examples: [
          "strongly agree",
          "deeply regret",
          "fully understand",
          "badly need",
        ],
      },
      verbAdverb: {
        definition: "Verbs that are typically used with certain adverbs.",
        examples: ["run quickly", "apologize sincerely", "work efficiently"],
      },
      adjectiveAdverb: {
        definition: "Adverbs modifying adjectives in fixed ways.",
        examples: ["deeply concerned", "highly successful", "utterly amazed"],
      },
      prepositionNoun: {
        definition: "Fixed prepositional phrases used in English.",
        examples: ["in trouble", "at risk", "on fire", "under pressure"],
      },
      nounPreposition: {
        definition: "Certain nouns that usually take specific prepositions.",
        examples: ["reason for", "increase in", "solution to"],
      },
      verbPreposition: {
        definition:
          "Verbs followed by particular prepositions (closely related to phrasal verbs).",
        examples: ["depend on", "believe in", "apologize for"],
      },
    },
    basedOnStrength: {
      strongCollocations: {
        definition: "Words that always go together and rarely change.",
        examples: [
          "make an effort",
          "utterly ridiculous",
          "blissfully unaware",
        ],
      },
      weakCollocations: {
        definition:
          "Words that go together but can be substituted more easily.",
        examples: ["walk slowly", "talk loudly"],
      },
    },
    basedOnRegister: {
      informal: {
        examples: ["grab a bite", "chill out", "have a blast"],
      },
      neutral: {
        examples: ["take notes", "pay attention", "lose weight"],
      },
      formal: {
        examples: [
          "reach a consensus",
          "conduct an investigation",
          "submit a proposal",
        ],
      },
      academic: {
        examples: [
          "pose a challenge",
          "exert influence",
          "present findings",
          "provide evidence",
        ],
      },
    },
  },
  collocationChunksByCEFR: {
    A1: {
      definition:
        "Basic collocations using high-frequency, everyday vocabulary. These are essential combinations that form the foundation of natural English communication.",
      keyFocus: [
        "Simple verb-noun combinations for daily activities",
        "Basic adjective-noun pairs for describing common objects",
        "Essential time expressions and basic phrases",
        "Common verbs: have, make, do, go, get, take",
      ],
      examples: [
        "have breakfast/lunch/dinner",
        "go home/to school/shopping",
        "make a cake/bed/noise",
        "do homework/exercise/work",
        "watch TV/a film",
        "listen to music",
        "take a photo/shower/bus",
        "get up/dressed/home",
      ],
      structures: ["Verb + Noun", "Verb + Preposition", "Basic Phrases"],
      commonPatterns: {
        verbNoun: [
          "have breakfast",
          "have lunch",
          "have dinner",
          "have a shower",
          "have fun",
          "make a cake",
          "make tea",
          "make friends",
          "make noise",
          "make a bed",
          "do homework",
          "do exercise",
          "do work",
          "do shopping",
          "go home",
          "go shopping",
          "go to school",
          "go to bed",
          "watch TV",
          "watch a film",
          "watch football",
          "listen to music",
          "listen to the radio",
          "take a photo",
          "take a shower",
          "take a bus",
          "get up",
          "get dressed",
          "get home",
          "get ready",
        ],
        adjectiveNoun: [
          "big house",
          "small car",
          "old man",
          "young girl",
          "good food",
          "bad weather",
          "hot coffee",
          "cold water",
          "nice day",
          "happy family",
        ],
        basicPhrases: [
          "at home",
          "at school",
          "at work",
          "in the morning",
          "in the evening",
          "on Monday",
          "on time",
          "by car",
          "by bus",
          "with friends",
        ],
      },
      mustKnowCollocations: [
        "have breakfast/lunch/dinner",
        "go to school/work/bed",
        "make friends/noise/tea",
        "do homework/exercise/shopping",
        "watch TV/film",
        "listen to music",
        "take a photo/shower/bus",
        "get up/dressed/ready",
        "at home/school/work",
        "in the morning/evening",
        "on time/Monday",
        "by car/bus",
      ],
    },
    A2: {
      definition:
        "Expanded collocations covering more daily situations, travel, and personal experiences. Introduction to phrasal verbs and more complex verb-noun combinations.",
      keyFocus: [
        "Travel and transportation collocations",
        "Health and body-related expressions",
        "Weather and time expressions",
        "Simple business and social interactions",
        "Basic phrasal verbs as collocations",
      ],
      examples: [
        "catch a cold/bus/train",
        "miss the bus/train/flight",
        "book a hotel/flight/table",
        "tell a story/joke/lie",
        "keep in touch/a secret/quiet",
        "lose weight/money/keys",
        "win a game/prize/competition",
        "break a leg/record/promise",
      ],
      structures: [
        "Verb + Noun",
        "Verb + Preposition",
        "Time Expressions",
        "Travel Phrases",
      ],
      commonPatterns: {
        verbNoun: [
          "catch a cold",
          "catch a bus",
          "catch a train",
          "catch a ball",
          "miss the bus",
          "miss a call",
          "miss a chance",
          "miss someone",
          "book a hotel",
          "book a flight",
          "book a table",
          "book tickets",
          "tell a story",
          "tell a joke",
          "tell the truth",
          "tell a lie",
          "keep quiet",
          "keep a secret",
          "keep in touch",
          "keep calm",
          "lose weight",
          "lose money",
          "lose keys",
          "lose time",
          "win a game",
          "win a prize",
          "win money",
          "win a competition",
          "break a leg",
          "break a record",
          "break a promise",
          "break down",
        ],
        adjectiveNoun: [
          "heavy rain",
          "light snow",
          "strong wind",
          "fresh air",
          "clean water",
          "fast car",
          "slow train",
          "cheap hotel",
          "expensive restaurant",
          "busy street",
          "quiet place",
          "safe area",
          "dangerous road",
        ],
        prepositionPhrases: [
          "at the airport",
          "at the station",
          "at the hotel",
          "at the beach",
          "in the city",
          "in the country",
          "in a hurry",
          "in trouble",
          "on holiday",
          "on business",
          "on foot",
          "on the phone",
        ],
        timeExpressions: [
          "next week",
          "last month",
          "this year",
          "every day",
          "all day",
          "in the future",
          "in the past",
          "at the moment",
          "at midnight",
        ],
      },
      mustKnowCollocations: [
        "catch a cold/bus",
        "miss the bus/call",
        "book a hotel/flight",
        "tell a story/truth",
        "keep quiet/secret",
        "lose weight/keys",
        "win a game/prize",
        "break a record/promise",
        "heavy rain/traffic",
        "fast car",
        "busy street",
        "at the airport/station",
        "on holiday/business",
        "next week",
        "last month",
        "in a hurry",
        "on the phone",
      ],
    },
    B1: {
      definition:
        "Intermediate collocations for expressing opinions, emotions, and more complex ideas. Introduction to formal and informal registers and workplace vocabulary.",
      keyFocus: [
        "Opinion and emotion expressions",
        "Workplace and education collocations",
        "Health and lifestyle vocabulary",
        "Technology and modern life expressions",
        "Distinction between make/do/take/give collocations",
      ],
      examples: [
        "make an effort/decision/mistake/progress",
        "take responsibility/notes/action/part",
        "pay attention/bills/compliments/respect",
        "give advice/support/permission/priority",
        "break the ice/news/silence/habit",
        "lose control/temper/patience/touch",
        "gain experience/weight/confidence/access",
        "raise awareness/money/standards/questions",
      ],
      structures: [
        "Verb + Noun",
        "Adjective + Noun",
        "Noun + Preposition",
        "Verb + Preposition",
        "Complex Expressions",
      ],
      commonPatterns: {
        verbNoun: [
          "make an effort",
          "make a decision",
          "make a mistake",
          "make progress",
          "make a difference",
          "make sense",
          "make money",
          "make plans",
          "take responsibility",
          "take notes",
          "take action",
          "take part",
          "take advantage",
          "take care",
          "take place",
          "take turns",
          "pay attention",
          "pay bills",
          "pay compliments",
          "pay respect",
          "pay a visit",
          "pay the price",
          "pay back",
          "pay off",
          "give advice",
          "give support",
          "give permission",
          "give priority",
          "give up",
          "give in",
          "give away",
          "give back",
        ],
        adjectiveNoun: [
          "serious problem",
          "major issue",
          "minor detail",
          "huge difference",
          "strong opinion",
          "weak argument",
          "clear explanation",
          "vague idea",
          "deep sleep",
          "light meal",
          "hard work",
          "easy task",
        ],
        nounPreposition: [
          "reason for",
          "solution to",
          "approach to",
          "attitude towards",
          "interest in",
          "experience of",
          "knowledge of",
          "awareness of",
        ],
        verbPreposition: [
          "depend on",
          "believe in",
          "agree with",
          "disagree with",
          "apologize for",
          "thank for",
          "worry about",
          "care about",
        ],
        expressionsWithMakeDoTakeGive: [
          "make an effort/decision/mistake/progress/difference/sense",
          "do business/research/damage/good/harm/justice",
          "take responsibility/action/part/advantage/care/place",
          "give advice/support/permission/priority/up/in",
        ],
      },
      mustKnowCollocations: [
        "make an effort/decision/mistake",
        "take responsibility/action/part",
        "pay attention/bills/respect",
        "give advice/support/permission",
        "break the ice/news",
        "lose control/temper",
        "gain experience/confidence",
        "serious problem",
        "strong opinion",
        "deep sleep",
        "reason for",
        "solution to",
        "depend on",
        "believe in",
        "agree with",
        "worry about",
      ],
    },
    B2: {
      definition:
        "Upper-intermediate collocations for academic, professional, and social contexts. Emphasis on formal register and precise expression of complex ideas.",
      keyFocus: [
        "Academic and professional vocabulary",
        "Business and workplace communications",
        "Abstract concepts and complex relationships",
        "Formal and semi-formal expressions",
        "Media and technology collocations",
      ],
      examples: [
        "conduct research/business/interview/survey",
        "achieve goals/success/results/balance",
        "establish relationships/contact/reputation/rules",
        "maintain standards/contact/balance/silence",
        "implement policies/changes/solutions/strategies",
        "enhance performance/reputation/skills/understanding",
        "foster relationships/growth/development/cooperation",
        "tackle problems/issues/challenges/questions",
      ],
      structures: [
        "Verb + Noun",
        "Adjective + Noun",
        "Noun + Preposition",
        "Verb + Preposition",
        "Adverb + Adjective",
        "Business Expressions",
        "Academic Expressions",
      ],
      commonPatterns: {
        verbNoun: [
          "conduct research",
          "conduct business",
          "conduct an interview",
          "conduct a survey",
          "achieve goals",
          "achieve success",
          "achieve results",
          "achieve balance",
          "establish relationships",
          "establish contact",
          "establish reputation",
          "establish rules",
          "maintain standards",
          "maintain contact",
          "maintain balance",
          "maintain silence",
          "implement policies",
          "implement changes",
          "implement solutions",
          "implement strategies",
          "enhance performance",
          "enhance reputation",
          "enhance skills",
          "enhance understanding",
        ],
        adjectiveNoun: [
          "sustainable development",
          "renewable energy",
          "artificial intelligence",
          "virtual reality",
          "comprehensive study",
          "thorough investigation",
          "detailed analysis",
          "extensive research",
          "significant impact",
          "considerable effort",
          "substantial progress",
          "remarkable achievement",
        ],
        nounPreposition: [
          "access to",
          "exposure to",
          "commitment to",
          "dedication to",
          "contribution to",
          "reaction to",
          "response to",
          "adaptation to",
        ],
        verbPreposition: [
          "specialize in",
          "concentrate on",
          "focus on",
          "rely on",
          "invest in",
          "engage in",
          "participate in",
          "excel in",
        ],
        adverbAdjective: [
          "highly successful",
          "deeply concerned",
          "utterly confused",
          "completely satisfied",
          "thoroughly prepared",
          "carefully planned",
          "strategically important",
          "financially viable",
        ],
        businessCollocations: [
          "market share",
          "profit margin",
          "cash flow",
          "business model",
          "competitive advantage",
          "customer service",
          "quality control",
          "supply chain",
        ],
        academicCollocations: [
          "research methodology",
          "data analysis",
          "literature review",
          "hypothesis testing",
          "peer review",
          "academic achievement",
          "scholarly work",
          "empirical evidence",
        ],
      },
      mustKnowCollocations: [
        "conduct research/business/interview",
        "achieve goals/success/balance",
        "establish relationships/contact/reputation",
        "maintain standards/contact",
        "implement policies/changes/strategies",
        "enhance performance/skills",
        "sustainable development",
        "artificial intelligence",
        "comprehensive study",
        "significant impact",
        "access to",
        "commitment to",
        "specialize in",
        "focus on",
        "highly successful",
        "deeply concerned",
        "market share",
        "competitive advantage",
        "research methodology",
        "data analysis",
      ],
    },
    C1: {
      definition:
        "Advanced collocations for sophisticated communication in academic, professional, and cultural contexts. Mastery of formal register and nuanced expression.",
      keyFocus: [
        "Sophisticated academic and professional discourse",
        "Cultural and social commentary vocabulary",
        "Legal, medical, and technical terminology",
        "Literary and journalistic expressions",
        "Nuanced emotional and psychological concepts",
      ],
      examples: [
        "adhere to principles/standards/guidelines/regulations",
        "undermine authority/confidence/efforts/credibility",
        "substantiate claims/arguments/theories/allegations",
        "mitigate risks/effects/consequences/damage",
        "consolidate power/position/gains/resources",
        "perpetuate myths/stereotypes/inequality/violence",
        "reconcile differences/accounts/conflicting views",
        "transcend boundaries/limitations/expectations/cultures",
      ],
      structures: [
        "Verb + Noun",
        "Adjective + Noun",
        "Noun + Preposition",
        "Verb + Preposition",
        "Adverb + Adjective",
        "Formal Register",
        "Academic Writing",
        "Business Communication",
        "Literary Expressions",
      ],
      commonPatterns: {
        verbNoun: [
          "adhere to principles",
          "adhere to standards",
          "adhere to guidelines",
          "adhere to regulations",
          "undermine authority",
          "undermine confidence",
          "undermine efforts",
          "undermine credibility",
          "substantiate claims",
          "substantiate arguments",
          "substantiate theories",
          "substantiate allegations",
          "mitigate risks",
          "mitigate effects",
          "mitigate consequences",
          "mitigate damage",
          "consolidate power",
          "consolidate position",
          "consolidate gains",
          "consolidate resources",
          "perpetuate myths",
          "perpetuate stereotypes",
          "perpetuate inequality",
          "perpetuate violence",
        ],
        adjectiveNoun: [
          "intrinsic value",
          "inherent flaws",
          "underlying assumptions",
          "prevailing attitudes",
          "unprecedented challenges",
          "innovative solutions",
          "revolutionary changes",
          "paradigmatic shifts",
          "meticulous attention",
          "scrupulous honesty",
          "unwavering commitment",
          "steadfast determination",
        ],
        nounPreposition: [
          "propensity for",
          "predisposition to",
          "inclination towards",
          "susceptibility to",
          "adherence to",
          "compliance with",
          "conformity to",
          "allegiance to",
        ],
        verbPreposition: [
          "allude to",
          "adhere to",
          "succumb to",
          "capitulate to",
          "embark on",
          "elaborate on",
          "expound on",
          "ruminate on",
        ],
        adverbAdjective: [
          "inexorably linked",
          "inextricably connected",
          "fundamentally flawed",
          "inherently biased",
          "categorically denied",
          "unequivocally stated",
          "tentatively suggested",
          "provisionally accepted",
        ],
        formalRegister: [
          "pursuant to",
          "notwithstanding",
          "henceforth",
          "heretofore",
          "whereby",
          "wherein",
          "thereof",
          "nonetheless",
        ],
        academicWriting: [
          "empirical evidence",
          "theoretical framework",
          "methodological approach",
          "analytical perspective",
          "conceptual model",
          "preliminary findings",
          "conclusive results",
          "definitive proof",
        ],
        businessCommunication: [
          "strategic alliance",
          "corporate governance",
          "due diligence",
          "stakeholder engagement",
          "operational efficiency",
          "fiscal responsibility",
          "market penetration",
          "brand recognition",
        ],
        literaryExpressions: [
          "poetic justice",
          "tragic irony",
          "dramatic tension",
          "narrative voice",
          "literary device",
          "symbolic meaning",
          "allegorical representation",
          "metaphorical significance",
        ],
      },
      mustKnowCollocations: [
        "adhere to principles/standards",
        "undermine authority/confidence",
        "substantiate claims/arguments",
        "mitigate risks/consequences",
        "consolidate power/position",
        "perpetuate myths/stereotypes",
        "intrinsic value",
        "underlying assumptions",
        "unprecedented challenges",
        "innovative solutions",
        "propensity for",
        "adherence to",
        "allude to",
        "embark on",
        "inexorably linked",
        "fundamentally flawed",
        "empirical evidence",
        "theoretical framework",
        "strategic alliance",
        "due diligence",
        "poetic justice",
        "symbolic meaning",
      ],
    },
    C2: {
      definition:
        "Mastery-level collocations demonstrating native-like proficiency. Includes idiomatic expressions, specialized terminology, and culturally nuanced language use.",
      keyFocus: [
        "Idiomatic and culturally specific expressions",
        "Specialized professional and academic terminology",
        "Literary and sophisticated journalistic language",
        "Legal, medical, and technical precision",
        "Subtle distinctions in meaning and register",
      ],
      examples: [
        "tender one's resignation/apologies/condolences",
        "mount a campaign/challenge/defense/offensive",
        "render a verdict/service/assistance/judgment",
        "foil an attempt/plot/plan/scheme",
        "invoke authority/privilege/sanctions/procedures",
        "brook no interference/opposition/delay/dissent",
        "wreak havoc/vengeance/destruction/chaos",
        "galvanize support/opposition/action/opinion",
      ],
      structures: [
        "Verb + Noun",
        "Adjective + Noun",
        "Noun + Preposition",
        "Verb + Preposition",
        "Adverb + Adjective",
        "Idiomatic Collocations",
        "Technical Collocations",
        "Literary Collocations",
        "Legal/Business Collocations",
        "Advanced Academic Collocations",
      ],
      commonPatterns: {
        verbNoun: [
          "tender one's resignation",
          "tender apologies",
          "tender condolences",
          "tender one's thanks",
          "mount a campaign",
          "mount a challenge",
          "mount a defense",
          "mount an offensive",
          "render a verdict",
          "render service",
          "render assistance",
          "render judgment",
          "foil an attempt",
          "foil a plot",
          "foil a plan",
          "foil a scheme",
          "invoke authority",
          "invoke privilege",
          "invoke sanctions",
          "invoke procedures",
          "brook no interference",
          "brook no opposition",
          "brook no delay",
          "brook no dissent",
        ],
        adjectiveNoun: [
          "incontrovertible evidence",
          "irrefutable proof",
          "indisputable facts",
          "unassailable position",
          "quintessential example",
          "archetypal figure",
          "paradigmatic case",
          "prototypical instance",
          "inexorable decline",
          "irreversible damage",
          "immutable laws",
          "indelible impression",
        ],
        nounPreposition: [
          "predilection for",
          "proclivity towards",
          "penchant for",
          "propensity towards",
          "antithesis of",
          "epitome of",
          "embodiment of",
          "manifestation of",
        ],
        verbPreposition: [
          "expatiate on",
          "ruminate over",
          "pontificate about",
          "capitulate to",
          "acquiesce in",
          "connive at",
          "collude with",
          "conspire against",
        ],
        adverbAdjective: [
          "patently obvious",
          "manifestly clear",
          "demonstrably false",
          "ostensibly neutral",
          "purportedly independent",
          "allegedly corrupt",
          "supposedly objective",
          "reputedly honest",
        ],
        idiomaticCollocations: [
          "pull strings",
          "cut corners",
          "jump ship",
          "burn bridges",
          "toe the line",
          "rock the boat",
          "spill the beans",
          "break the mold",
        ],
        technicalCollocations: [
          "algorithmic complexity",
          "quantum entanglement",
          "genetic predisposition",
          "neurological pathways",
          "pharmaceutical intervention",
          "surgical precision",
          "diagnostic criteria",
          "therapeutic approach",
        ],
        literaryCollocations: [
          "lyrical beauty",
          "prosaic reality",
          "narrative arc",
          "thematic resonance",
          "stylistic flourish",
          "rhetorical device",
          "allegorical interpretation",
          "metaphysical contemplation",
        ],
        legalBusinessCollocations: [
          "contractual obligation",
          "fiduciary responsibility",
          "statutory requirement",
          "regulatory compliance",
          "intellectual property",
          "corporate liability",
          "shareholder equity",
          "market capitalization",
        ],
        advancedAcademicCollocations: [
          "epistemological framework",
          "ontological assumptions",
          "phenomenological approach",
          "hermeneutical interpretation",
          "dialectical relationship",
          "paradigmatic shift",
          "heuristic device",
          "axiological considerations",
        ],
      },
      mustKnowCollocations: [
        "tender one's resignation/apologies",
        "mount a campaign/challenge",
        "render a verdict/service",
        "foil an attempt/plot",
        "invoke authority/privilege",
        "brook no interference/opposition",
        "incontrovertible evidence",
        "quintessential example",
        "inexorable decline",
        "predilection for",
        "antithesis of",
        "expatiate on",
        "acquiesce in",
        "patently obvious",
        "manifestly clear",
        "pull strings",
        "cut corners",
        "algorithmic complexity",
        "quantum entanglement",
        "lyrical beauty",
        "narrative arc",
        "contractual obligation",
        "fiduciary responsibility",
        "epistemological framework",
        "paradigmatic shift",
      ],
    },
  },
  specialTopics: {
    collocationsWithMakeVsDo: {
      make: ["make a cake", "make a decision", "make money", "make an excuse"],
      do: ["do homework", "do business", "do the dishes", "do a job"],
    },
    collocationsWithTakeVsGet: {
      take: ["take a break", "take responsibility", "take notes"],
      get: ["get a job", "get married", "get ready"],
    },
    collocationsWithHaveVsGet: {
      have: ["have fun", "have lunch", "have an idea"],
      get: ["get lost", "get angry", "get home"],
    },
  },
  commonErrors: [
    "❌ make homework → ✅ do homework",
    "❌ do a decision → ✅ make a decision",
    "❌ take attention → ✅ pay attention",
  ],
  learningTips: [
    "Use collocation dictionaries (e.g., Oxford Collocations, Longman)",
    "Read widely and highlight word combinations",
    "Practice using collocations in writing and speaking",
    "Use flashcards to remember fixed expressions",
    "Group collocations by topic (e.g., health, travel, emotions)",
  ],
  activities: [
    "Collocation matching exercises",
    "Gap-fill quizzes",
    "Collocation dominoes/cards",
    "Story completion using collocations",
    "Essay writing with required collocations",
  ],
  references: {
    books: [
      "English Collocations in Use: Advanced by Felicity O'Dell and Michael McCarthy (Cambridge University Press, 2008)",
      "Oxford Collocations Dictionary for Students of English by Diana Lea (Oxford University Press, 2009)",
      "Longman Collocations Dictionary and Thesaurus by Pearson Education (2013)",
      "The BBI Combinatory Dictionary of English by Morton Benson, Evelyn Benson, and Robert Ilson (John Benjamins Publishing, 2009)",
      "Collocation Applications and Implications by Andrew Partington (John Benjamins Publishing, 1998)",
      "Phraseology: Theory, Analysis, and Applications by Anthony P. Cowie (Oxford University Press, 1998)",
      "Natural English: Reading and Writing Skills by Ruth Gairns and Stuart Redman (Oxford University Press, 2003)",
    ],
    dictionaries: [
      "Oxford Collocations Dictionary for Students of English (Second Edition)",
      "Cambridge Advanced Learner's Dictionary with Collocations",
      "Longman Dictionary of Contemporary English with Collocations",
      "Macmillan Collocations Dictionary",
      "Collins COBUILD Advanced Dictionary with Collocations",
      "Merriam-Webster's Dictionary of English Usage",
    ],
    websites: [
      "https://www.oxfordlearnersdictionaries.com/ - Oxford Advanced Learner's Dictionary with extensive collocation examples",
      "https://dictionary.cambridge.org/ - Cambridge Dictionary with collocation sections",
      "https://www.ldoceonline.com/ - Longman Dictionary Online with collocation boxes",
      "https://www.macmillandictionary.com/ - Macmillan Dictionary with collocation information",
      "https://www.merriam-webster.com/ - Merriam-Webster Dictionary with usage examples",
      "https://corpus.byu.edu/coca/ - Corpus of Contemporary American English for collocation research",
      "https://www.english-corpora.org/ - English Corpora for authentic collocation examples",
      "https://www.skell.sketchengine.eu/ - Sketch Engine Language Learning for collocation patterns",
      "https://www.just-the-word.com/ - Academic collocation database",
      "https://www.eapfoundation.com/ - EAP Foundation for academic collocations",
    ],
    academicSources: [
      "Hoey, M. (2005). Lexical Priming: A New Theory of Words and Language. London: Routledge.",
      "Sinclair, J. (1991). Corpus, Concordance, Collocation. Oxford: Oxford University Press.",
      "Hunston, S. & Francis, G. (2000). Pattern Grammar: A Corpus-driven Approach to the Lexical Grammar of English. Amsterdam: John Benjamins.",
      "Lewis, M. (2000). Teaching Collocation: Further Developments in the Lexical Approach. Hove: Language Teaching Publications.",
      "Nation, I.S.P. (2001). Learning Vocabulary in Another Language. Cambridge: Cambridge University Press.",
      "Wray, A. (2002). Formulaic Language and the Lexicon. Cambridge: Cambridge University Press.",
      "Granger, S. & Meunier, F. (Eds.) (2008). Phraseology: An Interdisciplinary Perspective. Amsterdam: John Benjamins.",
    ],
  },
};
