import { CEFRLevel } from "@/types/grammars/grammars_type";

// CEFR Level mapping for ALL tenses (expanded to cover all 118 items)
export const CEFR_TENSE_MAPPING: { [key: string]: CEFRLevel[] } = {
  // A1 Level Tenses (Basic)
  Simple_Present: ["A1"],
  Present_Continuous: ["A1"],
  Simple_Past: ["A1"],
  Simple_Future: ["A1"],
  Articles: ["A1"],
  Nouns: ["A1"],
  Pronouns: ["A1"],
  Adjective: ["A1"],
  Preposition: ["A1"],

  // A2 Level Tenses (Elementary)
  Past_Continuous: ["A2"],
  Present_Perfect: ["A2"],
  Comparative: ["A2"],
  Superlative: ["A2"],
  Future_Continuous: ["A2"],
  Adverb: ["A2"],
  Determiners: ["A2"],
  Quantifiers: ["A2"],
  Imperatives: ["A2"],
  QuestionForms: ["A2"],
  Possessives: ["A2"],
  AdjectiveOrder: ["A2"],
  Negation: ["A2"],

  // B1 Level Tenses (Intermediate)
  Present_Perfect_Continuous: ["B1"],
  Past_Perfect: ["B1"],
  Conditionals: ["B1"],
  Reported_Speech: ["B1"],
  PassiveVoice: ["B1"],
  ModalVerbs: ["B1"],
  Relative_Clauses: ["B1"],
  PhrasalVerbs: ["B1"],
  GerundsAndInfinitives: ["B1"],
  Conjunctions: ["B1"],
  ReflexivePronouns: ["B1"],
  TagQuestions: ["B1"],
  SubjectVerbAgreement: ["B1"],
  WordOrder: ["B1"],
  SentenceTypes: ["B1"],
  TimeExpressions: ["B1"],
  Infinitives: ["B1"],

  // B2 Level Tenses (Upper Intermediate)
  Past_Perfect_Continuous: ["B2"],
  Future_Perfect: ["B2"],
  Future_Perfect_Continuous: ["B2"],
  advancedConditionals: ["B2"],
  DirectAndIndirectSpeech: ["B2"],
  ReportedQuestions: ["B2"],
  Inversion: ["B2"],
  CausativeForm: ["B2"],
  SubjunctiveMood: ["B2"],
  reducedRelativeClauses: ["B2"],
  TenseConsistency: ["B2"],
  WordFormationSentences: ["B2"],
  Comparisons: ["B2"],
  DoubleComparative: ["B2"],
  EqualityComparison: ["B2"],
  RepeatedComparative: ["B2"],

  // C1 Level Tenses (Advanced)
  TenseShiftInReportedSpeech: ["C1"],
  Emphasis: ["C1"],
  cleftSentences: ["C1"],
  emphaticCleftSentences: ["C1"],
  FocusStructures: ["C1"],
  Nominalisation: ["C1"],
  EllipsisAndSubstitution: ["C1"],
  verbToVOrVingAdvanced: ["C1"],
  nounClauseGrammar: ["C1"],
  adverbialClauseAdvanced: ["C1"],
  FutureInThePast: ["C1"],

  // C2 Level Tenses (Proficiency)
  DiscourseMarkers: ["C2"],
  Hedging: ["C2"],
  IdiomaticLanguage: ["C2"],
  binomials: ["C2"],
  collocations: ["C2"],
  fixedExpressions: ["C2"],
  parallelStructuresData: ["C2"],
  purposeResultConditionClauses: ["C2"],
  transitionPhrasesAcademicWriting: ["C2"],
  expressingAgreementDisagreementSuggestionsRequestsResponses: ["C2"],
  politeVsDirectLanguage: ["C2"],
  Interjections: ["C2"],

  // Multi-level items (appear across multiple levels)
  Verbs: ["A1", "A2", "B1"],

  // Special categories and advanced forms
  adjectivesNoComparison: ["B1", "B2"],
  adjectivesUsedAsNouns: ["B2", "C1"],
  adjectivesWithPluralNouns: ["A2", "B1"],
  compoundAdjectives: ["B1", "B2"],
  emotionAdjectives: ["A2", "B1"],
  possessiveAndEmphaticAdjectives: ["B1", "B2"],
  postpositiveAdjectives: ["B2", "C1"],
  quantitativeAdjectives: ["A2", "B1"],
  specialPositionAdjectives: ["B2", "C1"],

  // Advanced adverbs
  adverbFrontingInversion: ["B2", "C1"],
  adverbPositionMeaningChange: ["B1", "B2"],
  adverbsEndingLyVsIdenticalAdjectives: ["B1", "B2"],
  adverbsInversionAndEmphasis: ["B2", "C1"],
  adverbsNotEndingLy: ["A2", "B1"],
  adverbsOfCertainty: ["B1", "B2"],
  adverbsOfFrequency: ["A1", "A2"],
  degreeAdverbs: ["B1", "B2"],
  emphasizingAdverbs: ["B2", "C1"],
  linkingAdverbs: ["B2", "C1"],

  // Advanced noun types
  abstractNouns: ["B1", "B2"],
  CollectiveNouns: ["A2", "B1"],
  CountableVsUncountableNouns: ["A1", "A2"],
  DualUsageNouns: ["B1", "B2"],
  irregularPlurals: ["A2", "B1"],
  PluralOnlyNouns: ["B1", "B2"],
  pluraliaTantum: ["B2", "C1"],
  singularOnlyNouns: ["B1", "B2"],
  singulariaTantum: ["B2", "C1"],
  uncountableNouns: ["A2", "B1"],

  // Advanced verb types
  CausativeVerbs: ["B2", "C1"],
  infinitivePatterns: ["B1", "B2"],
  IrregularVerbs: ["A1", "A2", "B1"],
  LinkingVerbs: ["A2", "B1"],
  PerceptionVerbs: ["B1", "B2"],
  phrasalVerbs: ["B1", "B2"],
  ReflexiveVerbs: ["B1", "B2"],
  ReportingVerbs: ["B1", "B2"],
  StatisticVerbs: ["B2", "C1"],
  transitiveIntransitiveVerbs: ["B1", "B2"],
  VerbsOfPerception: ["B1", "B2"],
};
