// Fill-in-Blank Exercise Backup Database
import {
  Question,
  CEFRLevel,
  CertificateType,
  TypeExcercise,
} from "@/types/grammars/grammars_type";

export const FILL_IN_BLANK_BACKUPS = {
  "present simple": {
    A1: {
      default: [
        {
          id: 1,
          question: "My sister _____ (work) in a hospital.",
          correct: "works",
          explanation: "Third person singular takes -s: work → works",
          tip: "Add -s or -es to verbs with he/she/it in present simple.",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "We _____ (not/like) spicy food.",
          correct: "don't like",
          explanation:
            "Negative present simple: subject + don't/doesn't + base verb",
          tip: "Use don't with I/you/we/they, doesn't with he/she/it.",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "They _____ (play) football every weekend.",
          correct: "play",
          explanation: "Plural subjects use base form of the verb",
          tip: "They/we/you use base verb form in present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question: "He _____ (study) English every day.",
          correct: "studies",
          explanation:
            "Third person singular: study → studies (y changes to ies)",
          tip: "Verbs ending in consonant + y: change y to ies",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "I _____ (drink) coffee in the morning.",
          correct: "drink",
          explanation: "First person singular uses base form",
          tip: "I/you/we/they use base verb form",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "She _____ (not/eat) meat.",
          correct: "doesn't eat",
          explanation: "Third person negative: doesn't + base verb",
          tip: "Doesn't with he/she/it, don't with others",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "The cat _____ (sleep) on the sofa.",
          correct: "sleeps",
          explanation: "Animals are third person singular",
          tip: "Animals use he/she/it grammar rules",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "We _____ (go) to school by bus.",
          correct: "go",
          explanation: "Plural subject 'we' uses base form",
          tip: "Plural subjects don't add -s to verbs",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "_____ you _____ (like) pizza?",
          correct: "Do, like",
          explanation: "Present simple questions: Do + subject + base verb?",
          tip: "Questions need auxiliary 'do' or 'does'",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "My parents _____ (watch) TV every evening.",
          correct: "watch",
          explanation: "Plural 'parents' uses base form 'watch'",
          tip: "Plural subjects use base verb form",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      IELTS: [
        {
          id: 1,
          question:
            "The data _____ (reveal) interesting patterns in consumer behavior.",
          correct: "reveals",
          explanation:
            "'Data' can be singular or plural, but in formal academic writing often treated as singular.",
          tip: "IELTS: data reveals/shows/indicates (formal academic style)",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "Governments _____ (implement) new policies to address climate change.",
          correct: "implement",
          explanation: "Plural 'governments' uses base form 'implement'.",
          tip: "IELTS Writing: governments implement/introduce/adopt policies",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question:
            "Research _____ (indicate) that exercise improves mental health.",
          correct: "indicates",
          explanation: "Uncountable 'research' is singular",
          tip: "Academic writing: research indicates/shows/suggests",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question:
            "Students who _____ (practice) regularly achieve better results.",
          correct: "practice",
          explanation: "Plural 'students' uses base form",
          tip: "IELTS: describe habits and routines with present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "The graph _____ (show) a significant increase in sales.",
          correct: "shows",
          explanation: "Singular 'graph' takes -s form",
          tip: "IELTS Task 1: describing charts and graphs",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Many countries _____ (face) environmental challenges.",
          correct: "face",
          explanation: "Plural 'countries' uses base form",
          tip: "Global issues discussion in IELTS",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "Technology _____ (play) an important role in education.",
          correct: "plays",
          explanation: "Uncountable 'technology' is singular",
          tip: "IELTS topics: technology's role in society",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question:
            "The majority of people _____ (believe) that education is important.",
          correct: "believe",
          explanation: "'Majority of people' is plural",
          tip: "IELTS Writing: expressing general opinions",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question:
            "This approach _____ (ensure) better outcomes for students.",
          correct: "ensures",
          explanation: "Singular 'approach' takes -s form",
          tip: "Academic vocabulary for IELTS Writing",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "Statistics _____ (show) that crime rates are decreasing.",
          correct: "show",
          explanation: "'Statistics' as data is plural",
          tip: "IELTS: statistics show/indicate/demonstrate",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      VSTEP: [
        {
          id: 1,
          question:
            "Vietnamese students _____ (study) English from primary school.",
          correct: "study",
          explanation: "Plural 'students' uses base form",
          tip: "VSTEP: describing education system in Vietnam",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "The weather in Vietnam _____ (be) hot and humid.",
          correct: "is",
          explanation: "Singular 'weather' uses 'is'",
          tip: "VSTEP: describing Vietnamese climate",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "Many families _____ (celebrate) Tet festival together.",
          correct: "celebrate",
          explanation: "Plural 'families' uses base form",
          tip: "VSTEP: Vietnamese cultural traditions",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question: "Ho Chi Minh City _____ (have) many universities.",
          correct: "has",
          explanation: "Singular city name uses 'has'",
          tip: "VSTEP: describing Vietnamese cities",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "Rice _____ (grow) in the Mekong Delta.",
          correct: "grows",
          explanation: "Uncountable 'rice' is singular",
          tip: "VSTEP: Vietnamese agriculture and economy",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Young people _____ (use) social media frequently.",
          correct: "use",
          explanation: "Plural 'people' uses base form",
          tip: "VSTEP: modern life and technology",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "The government _____ (promote) English education.",
          correct: "promotes",
          explanation: "Singular 'government' takes -s form",
          tip: "VSTEP: education policy discussions",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "Traffic in Hanoi _____ (be) very busy.",
          correct: "is",
          explanation: "Uncountable 'traffic' is singular",
          tip: "VSTEP: urban life challenges",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "Most workers _____ (commute) by motorbike.",
          correct: "commute",
          explanation: "Plural 'workers' uses base form",
          tip: "VSTEP: transportation and daily life",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "Vietnamese cuisine _____ (include) many herbs and spices.",
          correct: "includes",
          explanation: "Uncountable 'cuisine' is singular",
          tip: "VSTEP: Vietnamese food and culture",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
    A2: {
      default: [
        {
          id: 1,
          question: "The teacher _____ (explain) the lesson clearly.",
          correct: "explains",
          explanation: "Third person singular: explain → explains",
          tip: "Regular verbs add -s with he/she/it",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "My friends _____ (visit) me every month.",
          correct: "visit",
          explanation: "Plural 'friends' uses base form",
          tip: "Frequency expressions with present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "She _____ (not/understand) the instructions.",
          correct: "doesn't understand",
          explanation: "Third person negative: doesn't + base verb",
          tip: "Negative forms in present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question: "The train _____ (arrive) at 9 AM every day.",
          correct: "arrives",
          explanation: "Schedules and timetables use present simple",
          tip: "Transport schedules = present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "We _____ (have) dinner at 7 PM usually.",
          correct: "have",
          explanation: "Daily routines with time expressions",
          tip: "Habits and routines use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "The shop _____ (close) at 6 PM on weekdays.",
          correct: "closes",
          explanation: "Opening and closing times",
          tip: "Business hours use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "Children _____ (need) at least 8 hours of sleep.",
          correct: "need",
          explanation: "General truths and facts",
          tip: "Scientific facts use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "_____ your brother _____ (work) in the city?",
          correct: "Does, work",
          explanation: "Present simple questions with third person",
          tip: "Does + he/she/it + base verb?",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "The weather here _____ (change) quickly.",
          correct: "changes",
          explanation: "Weather patterns and characteristics",
          tip: "Weather descriptions use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "Most people _____ (prefer) tea to coffee.",
          correct: "prefer",
          explanation: "General preferences and opinions",
          tip: "Preferences and opinions use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      IELTS: [
        {
          id: 1,
          question: "Urban areas _____ (experience) rapid population growth.",
          correct: "experience",
          explanation: "Plural 'areas' uses base form",
          tip: "IELTS: urbanization topics",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "Education _____ (provide) opportunities for social mobility.",
          correct: "provides",
          explanation: "Uncountable 'education' is singular",
          tip: "IELTS: education and society topics",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "Many employers _____ (require) specific qualifications.",
          correct: "require",
          explanation: "Plural 'employers' uses base form",
          tip: "IELTS: employment and skills topics",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question: "The internet _____ (connect) people worldwide.",
          correct: "connects",
          explanation: "Singular 'internet' takes -s form",
          tip: "IELTS: technology and communication",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "Climate change _____ (affect) agricultural production.",
          correct: "affects",
          explanation: "Uncountable 'climate change' is singular",
          tip: "IELTS: environmental issues",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Public transport _____ (reduce) air pollution.",
          correct: "reduces",
          explanation: "Uncountable 'public transport' is singular",
          tip: "IELTS: transport and environment",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "Young adults _____ (face) many challenges today.",
          correct: "face",
          explanation: "Plural 'young adults' uses base form",
          tip: "IELTS: youth and society topics",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "Tourism _____ (contribute) to economic growth.",
          correct: "contributes",
          explanation: "Uncountable 'tourism' is singular",
          tip: "IELTS: tourism and economy",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "Social media _____ (influence) consumer behavior.",
          correct: "influences",
          explanation: "Uncountable 'social media' is singular",
          tip: "IELTS: media and society",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "Renewable energy sources _____ (become) more popular.",
          correct: "become",
          explanation: "Plural 'sources' uses base form",
          tip: "IELTS: energy and environment",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      VSTEP: [
        {
          id: 1,
          question:
            "The education system _____ (emphasize) both theory and practice.",
          correct: "emphasizes",
          explanation: "Singular 'system' takes -s form",
          tip: "VSTEP: Vietnamese education system",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "Traditional festivals _____ (play) an important role in Vietnamese culture.",
          correct: "play",
          explanation: "Plural 'festivals' uses base form",
          tip: "VSTEP: Vietnamese traditions and culture",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question:
            "Economic development _____ (bring) both opportunities and challenges.",
          correct: "brings",
          explanation: "Uncountable 'development' is singular",
          tip: "VSTEP: Vietnam's economic growth",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question:
            "Foreign tourists _____ (appreciate) Vietnamese hospitality.",
          correct: "appreciate",
          explanation: "Plural 'tourists' uses base form",
          tip: "VSTEP: tourism in Vietnam",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question:
            "The Mekong River _____ (support) millions of people's livelihoods.",
          correct: "supports",
          explanation: "Singular 'river' takes -s form",
          tip: "VSTEP: Vietnamese geography and economy",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Technology companies _____ (invest) heavily in Vietnam.",
          correct: "invest",
          explanation: "Plural 'companies' uses base form",
          tip: "VSTEP: foreign investment and technology",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question:
            "Vietnamese literature _____ (reflect) the country's history.",
          correct: "reflects",
          explanation: "Uncountable 'literature' is singular",
          tip: "VSTEP: Vietnamese arts and culture",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "Urban planning _____ (focus) on sustainable development.",
          correct: "focuses",
          explanation: "Uncountable 'urban planning' is singular",
          tip: "VSTEP: city development and planning",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question:
            "International cooperation _____ (strengthen) Vietnam's position.",
          correct: "strengthens",
          explanation: "Uncountable 'cooperation' is singular",
          tip: "VSTEP: Vietnam's international relations",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question:
            "Small businesses _____ (contribute) significantly to the economy.",
          correct: "contribute",
          explanation: "Plural 'businesses' uses base form",
          tip: "VSTEP: Vietnamese economy and entrepreneurship",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      TOEIC: [
        {
          id: 1,
          question: "The company _____ (manufacture) electronic components.",
          correct: "manufactures",
          explanation: "Singular 'company' takes -s form",
          tip: "TOEIC: business and manufacturing",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "Employees _____ (receive) annual performance reviews.",
          correct: "receive",
          explanation: "Plural 'employees' uses base form",
          tip: "TOEIC: workplace procedures",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "The meeting _____ (start) at 9 AM sharp.",
          correct: "starts",
          explanation: "Meeting schedules use present simple",
          tip: "TOEIC: business meetings and schedules",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question:
            "Our products _____ (meet) international quality standards.",
          correct: "meet",
          explanation: "Plural 'products' uses base form",
          tip: "TOEIC: quality and standards",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "The sales team _____ (report) to the regional manager.",
          correct: "reports",
          explanation: "Collective noun 'team' is usually singular",
          tip: "TOEIC: organizational structure",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Customer service _____ (handle) all inquiries promptly.",
          correct: "handles",
          explanation: "Department name is singular",
          tip: "TOEIC: customer service operations",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "The budget _____ (include) all operational costs.",
          correct: "includes",
          explanation: "Singular 'budget' takes -s form",
          tip: "TOEIC: financial planning",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "International clients _____ (prefer) email communication.",
          correct: "prefer",
          explanation: "Plural 'clients' uses base form",
          tip: "TOEIC: business communication",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "The warehouse _____ (store) inventory efficiently.",
          correct: "stores",
          explanation: "Singular 'warehouse' takes -s form",
          tip: "TOEIC: logistics and storage",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "Market research _____ (indicate) strong demand.",
          correct: "indicates",
          explanation: "Uncountable 'market research' is singular",
          tip: "TOEIC: market analysis",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      TOEFL: [
        {
          id: 1,
          question: "Academic research _____ (require) systematic methodology.",
          correct: "requires",
          explanation: "Uncountable 'research' is singular",
          tip: "TOEFL: academic research methods",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "University students _____ (participate) in various activities.",
          correct: "participate",
          explanation: "Plural 'students' uses base form",
          tip: "TOEFL: campus life and activities",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "The library _____ (provide) extensive digital resources.",
          correct: "provides",
          explanation: "Singular 'library' takes -s form",
          tip: "TOEFL: academic facilities",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question:
            "Scientific studies _____ (demonstrate) clear correlations.",
          correct: "demonstrate",
          explanation: "Plural 'studies' uses base form",
          tip: "TOEFL: scientific methodology",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "Higher education _____ (prepare) students for careers.",
          correct: "prepares",
          explanation: "Uncountable 'higher education' is singular",
          tip: "TOEFL: education and career preparation",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Academic writing _____ (follow) specific conventions.",
          correct: "follows",
          explanation: "Uncountable 'academic writing' is singular",
          tip: "TOEFL: academic writing standards",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "Graduate programs _____ (attract) international students.",
          correct: "attract",
          explanation: "Plural 'programs' uses base form",
          tip: "TOEFL: graduate education",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question:
            "The curriculum _____ (emphasize) critical thinking skills.",
          correct: "emphasizes",
          explanation: "Singular 'curriculum' takes -s form",
          tip: "TOEFL: educational curriculum",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question:
            "Laboratory experiments _____ (validate) theoretical concepts.",
          correct: "validate",
          explanation: "Plural 'experiments' uses base form",
          tip: "TOEFL: scientific research methods",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "Distance learning _____ (offer) flexibility to students.",
          correct: "offers",
          explanation: "Uncountable 'distance learning' is singular",
          tip: "TOEFL: modern education methods",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      Cambridge: [
        {
          id: 1,
          question: "British culture _____ (value) politeness and queuing.",
          correct: "values",
          explanation: "Uncountable 'culture' is singular",
          tip: "Cambridge: British cultural topics",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "The BBC _____ (broadcast) programs worldwide.",
          correct: "broadcasts",
          explanation: "Organization name (BBC) is singular",
          tip: "Cambridge: British media and broadcasting",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "London museums _____ (attract) millions of visitors.",
          correct: "attract",
          explanation: "Plural 'museums' uses base form",
          tip: "Cambridge: British tourism and culture",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question: "The NHS _____ (provide) free healthcare to residents.",
          correct: "provides",
          explanation: "Organization (NHS) is singular",
          tip: "Cambridge: British public services",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "English literature _____ (include) many famous authors.",
          correct: "includes",
          explanation: "Uncountable 'literature' is singular",
          tip: "Cambridge: British literature and arts",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Public transport _____ (connect) all major cities.",
          correct: "connects",
          explanation: "Uncountable 'public transport' is singular",
          tip: "Cambridge: British transport system",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question:
            "British universities _____ (maintain) high academic standards.",
          correct: "maintain",
          explanation: "Plural 'universities' uses base form",
          tip: "Cambridge: British higher education",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "The monarchy _____ (play) a ceremonial role.",
          correct: "plays",
          explanation: "Singular 'monarchy' takes -s form",
          tip: "Cambridge: British political system",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question:
            "Regional accents _____ (vary) significantly across Britain.",
          correct: "vary",
          explanation: "Plural 'accents' uses base form",
          tip: "Cambridge: British dialects and language",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question:
            "British cuisine _____ (combine) traditional and modern elements.",
          correct: "combines",
          explanation: "Uncountable 'cuisine' is singular",
          tip: "Cambridge: British food and dining",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      PTE: [
        {
          id: 1,
          question: "Digital technology _____ (transform) modern workplaces.",
          correct: "transforms",
          explanation: "Uncountable 'technology' is singular",
          tip: "PTE: technology and workplace",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "Australian universities _____ (rank) highly internationally.",
          correct: "rank",
          explanation: "Plural 'universities' uses base form",
          tip: "PTE: Australian education system",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "The healthcare system _____ (adapt) to changing needs.",
          correct: "adapts",
          explanation: "Singular 'system' takes -s form",
          tip: "PTE: healthcare and social systems",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question: "Renewable energy _____ (become) increasingly important.",
          correct: "becomes",
          explanation: "Uncountable 'energy' is singular",
          tip: "PTE: environmental sustainability",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "Global markets _____ (influence) local economies.",
          correct: "influence",
          explanation: "Plural 'markets' uses base form",
          tip: "PTE: globalization and economics",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "Scientific research _____ (contribute) to innovation.",
          correct: "contributes",
          explanation: "Uncountable 'research' is singular",
          tip: "PTE: science and innovation",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question: "Multicultural societies _____ (benefit) from diversity.",
          correct: "benefit",
          explanation: "Plural 'societies' uses base form",
          tip: "PTE: multiculturalism and society",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question:
            "Online learning _____ (provide) flexible education options.",
          correct: "provides",
          explanation: "Uncountable 'online learning' is singular",
          tip: "PTE: education and technology",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "Immigration policies _____ (affect) social dynamics.",
          correct: "affect",
          explanation: "Plural 'policies' uses base form",
          tip: "PTE: immigration and social issues",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question:
            "Environmental conservation _____ (require) collective action.",
          correct: "requires",
          explanation: "Uncountable 'conservation' is singular",
          tip: "PTE: environmental responsibility",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
      SAT: [
        {
          id: 1,
          question: "The research methodology _____ (ensure) reliable results.",
          correct: "ensures",
          explanation: "Singular 'methodology' takes -s form",
          tip: "SAT: academic research vocabulary",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "Historical documents _____ (provide) valuable insights.",
          correct: "provide",
          explanation: "Plural 'documents' uses base form",
          tip: "SAT: history and documentation",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "Literary analysis _____ (reveal) deeper meanings.",
          correct: "reveals",
          explanation: "Uncountable 'analysis' is singular",
          tip: "SAT: literature and critical thinking",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question:
            "Mathematical concepts _____ (build) upon previous knowledge.",
          correct: "build",
          explanation: "Plural 'concepts' uses base form",
          tip: "SAT: mathematics and logical thinking",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "Scientific evidence _____ (support) the hypothesis.",
          correct: "supports",
          explanation: "Uncountable 'evidence' is singular",
          tip: "SAT: scientific reasoning",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question:
            "Critical thinking skills _____ (develop) through practice.",
          correct: "develop",
          explanation: "Plural 'skills' uses base form",
          tip: "SAT: cognitive development",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question:
            "The conclusion _____ (follow) logically from the premises.",
          correct: "follows",
          explanation: "Singular 'conclusion' takes -s form",
          tip: "SAT: logical reasoning",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "Data analysis _____ (require) statistical knowledge.",
          correct: "requires",
          explanation: "Uncountable 'analysis' is singular",
          tip: "SAT: statistics and data interpretation",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "Academic standards _____ (maintain) educational quality.",
          correct: "maintain",
          explanation: "Plural 'standards' uses base form",
          tip: "SAT: educational excellence",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "College preparation _____ (involve) multiple components.",
          correct: "involves",
          explanation: "Uncountable 'preparation' is singular",
          tip: "SAT: college readiness",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
    B1: {
      default: [
        {
          id: 1,
          question: "The new policy _____ (affect) all employees equally.",
          correct: "affects",
          explanation: "Singular 'policy' takes -s form",
          tip: "Present simple for facts and policies",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "Research _____ (indicate) that exercise improves mental health.",
          correct: "indicates",
          explanation: "Uncountable 'research' is singular",
          tip: "Academic contexts often use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "Most teenagers _____ (spend) hours on social media daily.",
          correct: "spend",
          explanation: "Plural 'teenagers' uses base form",
          tip: "Statistics and general trends use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question: "The organization _____ (not/support) this initiative.",
          correct: "doesn't support",
          explanation: "Singular organization uses 'doesn't'",
          tip: "Organizational positions and policies",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question: "Water _____ (boil) at 100 degrees Celsius.",
          correct: "boils",
          explanation: "Scientific facts use present simple",
          tip: "Universal truths and scientific facts",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "The committee _____ (meet) monthly to discuss progress.",
          correct: "meets",
          explanation: "Collective noun 'committee' is usually singular",
          tip: "Regular schedules and meetings",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question:
            "Online shopping _____ (offer) convenience but reduces social interaction.",
          correct: "offers",
          explanation: "Uncountable 'online shopping' is singular",
          tip: "Modern lifestyle descriptions",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question: "Neither of the solutions _____ (seem) practical.",
          correct: "seems",
          explanation: "Neither + singular verb",
          tip: "Neither/either take singular verbs",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question: "The news _____ (report) increasing crime rates.",
          correct: "reports",
          explanation: "'News' is uncountable and singular",
          tip: "Media and information are usually singular",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question: "Everyone _____ (deserve) equal opportunities.",
          correct: "deserves",
          explanation: "Everyone is singular despite plural meaning",
          tip: "Everyone/everybody always takes singular verb",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
    B2: {
      default: [
        {
          id: 1,
          question:
            "The phenomenon _____ (occur) in various cultural contexts.",
          correct: "occurs",
          explanation: "Singular 'phenomenon' takes -s form",
          tip: "Academic vocabulary: phenomenon (singular) vs phenomena (plural)",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "Statistics _____ (show) that crime rates are declining.",
          correct: "show",
          explanation: "'Statistics' as data is plural",
          tip: "Statistics (data) = plural, statistic = singular",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question:
            "The majority of citizens _____ (support) the new legislation.",
          correct: "support",
          explanation: "Majority of + plural noun = plural verb",
          tip: "Majority of + plural = plural verb",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 4,
          question:
            "Rarely _____ such dedication _____ (see) in young professionals.",
          correct: "do we see",
          explanation: "Inverted word order after negative adverbs",
          tip: "Rarely/seldom + auxiliary + subject + verb",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 5,
          question:
            "Each of the proposals _____ (require) careful consideration.",
          correct: "requires",
          explanation: "Each + singular verb",
          tip: "Each/every + of + plural noun = singular verb",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 6,
          question: "The criteria _____ (be) too strict for most applicants.",
          correct: "are",
          explanation: "Criteria is plural (singular: criterion)",
          tip: "Criterion (singular) vs criteria (plural)",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 7,
          question:
            "Not only _____ students _____ (benefit), but teachers also gain experience.",
          correct: "do, benefit",
          explanation: "Not only + auxiliary + subject inversion",
          tip: "Not only...but also requires inversion",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 8,
          question:
            "The data _____ (indicate) a clear trend in consumer behavior.",
          correct: "indicate",
          explanation: "Data is plural (singular: datum)",
          tip: "Data = plural, information = singular",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 9,
          question:
            "Should the situation _____ (deteriorate), we will intervene.",
          correct: "deteriorate",
          explanation: "Conditional sentences: should + base form",
          tip: "Should + subject + base verb (formal condition)",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 10,
          question:
            "The research _____ (carry) significant implications for policy.",
          correct: "carries",
          explanation:
            "Academic formal language: research carries implications",
          tip: "Formal academic expressions use present simple",
          tense: "present simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
  },

  "past simple": {
    A1: {
      default: [
        {
          id: 1,
          question: "They _____ (arrive) at 8 PM yesterday.",
          correct: "arrived",
          explanation:
            "Regular verbs add -ed for past simple: arrive → arrived",
          tip: "Regular past simple: base verb + -ed",
          tense: "past simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "I _____ (not/see) him last week.",
          correct: "didn't see",
          explanation: "Past simple negative: subject + didn't + base verb",
          tip: "Didn't is used for all subjects in past simple negative.",
          tense: "past simple",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 3,
          question: "She _____ (go) to Paris last summer.",
          correct: "went",
          explanation: "Irregular verb: go → went in past simple",
          tip: "Irregular verbs have special past forms",
          tense: "past simple",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
  },

  "present perfect": {
    A2: {
      default: [
        {
          id: 1,
          question: "She _____ (live) here for five years.",
          correct: "has lived",
          explanation: "Present perfect for duration: has + past participle",
          tip: "Use present perfect with 'for' and 'since' for time periods.",
          tense: "present perfect",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "I _____ never _____ (be) to Japan.",
          correct: "have never been",
          explanation:
            "Present perfect for experience: have + never + past participle",
          tip: "Experience: have/has + ever/never + past participle",
          tense: "present perfect",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
  },

  modals: {
    A2: {
      default: [
        {
          id: 1,
          question: "You _____ (should/wear) a coat. It's cold.",
          correct: "should wear",
          explanation: "Modal + base verb: should wear",
          tip: "Modals are followed by base verb (no 'to')",
          tense: "modals",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "She _____ (can/speak) three languages.",
          correct: "can speak",
          explanation: "Can + base verb shows ability",
          tip: "Can = ability, no -s needed even with he/she/it",
          tense: "modals",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
  },

  articles: {
    A1: {
      default: [
        {
          id: 1,
          question: "I saw _____ cat in _____ garden.",
          correct: "a / the",
          explanation: "First mention uses 'a', specific garden uses 'the'",
          tip: "First mention = a/an, specific/known = the",
          tense: "articles",
          type: "fill-in-blank" as TypeExcercise,
        },
        {
          id: 2,
          question: "_____ sun is shining today.",
          correct: "The",
          explanation: "Unique objects like the sun use 'the'",
          tip: "Unique things (sun, moon, earth) always use 'the'",
          tense: "articles",
          type: "fill-in-blank" as TypeExcercise,
        },
      ],
    },
  },
};

export function getFillInBlankBackup(
  grammarTopic: string,
  proficiencyLevel: CEFRLevel,
  certificateType?: CertificateType,
  numQuestions: number = 5
): Question[] {
  const topicData =
    FILL_IN_BLANK_BACKUPS[
      grammarTopic.toLowerCase() as keyof typeof FILL_IN_BLANK_BACKUPS
    ];
  if (!topicData) return [];

  const levelData = (topicData as any)[proficiencyLevel];
  if (!levelData) return [];

  const certificateKey = certificateType || "default";
  const questions = levelData[certificateKey] || levelData["default"] || [];

  return questions.slice(0, numQuestions);
}

export default FILL_IN_BLANK_BACKUPS;
