// Multiple Choice Exercise Backup Database
import {
  Question,
  CEFRLevel,
  CertificateType,
  TypeExcercise,
} from "@/types/grammars/grammars_type";

export const MULTIPLE_CHOICE_BACKUPS = {
  "present simple": {
    A1: {
      default: [
        {
          id: 1,
          question: "I _____ coffee every morning.",
          options: ["drink", "drinks", "drinking", "drank"],
          correct: 0,
          explanation:
            "Use base form 'drink' with I/you/we/they in present simple.",
          tip: "Present simple: I/you/we/they + base verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "She _____ English at university.",
          options: ["study", "studies", "studying", "studied"],
          correct: 1,
          explanation: "Third person singular (she) takes -s: study → studies",
          tip: "He/she/it + verb + s/es",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 3,
          question: "_____ you like pizza?",
          options: ["Do", "Does", "Are", "Is"],
          correct: 0,
          explanation: "Use 'Do' with you in present simple questions.",
          tip: "Questions: Do + I/you/we/they + base verb?",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 4,
          question: "We _____ TV in the evening.",
          options: ["watch", "watches", "watching", "watched"],
          correct: 0,
          explanation: "Use base form 'watch' with we in present simple.",
          tip: "We/they use base form of verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 5,
          question: "My brother _____ in London.",
          options: ["live", "lives", "living", "lived"],
          correct: 1,
          explanation: "Third person singular (my brother = he) takes -s.",
          tip: "My brother/sister = he/she (add -s)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 6,
          question: "They _____ go to school on Sundays.",
          options: ["don't", "doesn't", "isn't", "aren't"],
          correct: 0,
          explanation: "Use 'don't' with they for negative present simple.",
          tip: "They/we/you + don't + base verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 7,
          question: "_____ she work in a bank?",
          options: ["Do", "Does", "Is", "Are"],
          correct: 1,
          explanation: "Use 'Does' with she in present simple questions.",
          tip: "Does + he/she/it + base verb?",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 8,
          question: "The dog _____ in the garden.",
          options: ["play", "plays", "playing", "played"],
          correct: 1,
          explanation: "Animals are third person singular (it), so add -s.",
          tip: "Animals = it (add -s to verb)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 9,
          question: "I _____ like vegetables.",
          options: ["don't", "doesn't", "am not", "isn't"],
          correct: 0,
          explanation: "Use 'don't' with I for negative present simple.",
          tip: "I + don't + base verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 10,
          question: "My parents _____ early every day.",
          options: ["gets up", "get up", "getting up", "got up"],
          correct: 1,
          explanation: "Plural subject (parents = they) uses base form.",
          tip: "Plural subjects + base verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
      IELTS: [
        {
          id: 1,
          question: "University students _____ in the library every day.",
          options: ["study", "studies", "studying", "studied"],
          correct: 0,
          explanation: "Plural subject 'students' uses base form 'study'.",
          tip: "IELTS tip: Plural subjects + base verb form",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "The research _____ interesting results.",
          options: ["show", "shows", "showing", "showed"],
          correct: 1,
          explanation: "'Research' is singular, so use 'shows'.",
          tip: "Academic writing: research shows, data indicates",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
      TOEIC: [
        {
          id: 1,
          question: "The company _____ high-quality products.",
          options: ["make", "makes", "making", "made"],
          correct: 1,
          explanation: "'Company' is singular, so use 'makes'.",
          tip: "Business context: companies make/provide/offer",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "Employees _____ at 9 AM every day.",
          options: ["start", "starts", "starting", "started"],
          correct: 0,
          explanation: "Plural 'employees' uses base form 'start'.",
          tip: "Work routines use present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
    A2: {
      default: [
        {
          id: 1,
          question: "The train usually _____ at 8 AM.",
          options: ["arrive", "arrives", "arriving", "arrived"],
          correct: 1,
          explanation: "Third person singular with schedules",
          tip: "Timetables use present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "My friend never _____ his homework.",
          options: ["forget", "forgets", "forgetting", "forgot"],
          correct: 1,
          explanation: "Third person singular 'forgets' with frequency adverbs",
          tip: "Frequency adverbs + present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 3,
          question: "_____ the shop open on Sundays?",
          options: ["Does", "Do", "Is", "Are"],
          correct: 2,
          explanation: "Use 'Is' with 'open' (adjective, not verb)",
          tip: "Is/Are + adjective (open/closed)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 4,
          question: "The children always _____ lunch at 12:30.",
          options: ["has", "have", "having", "had"],
          correct: 1,
          explanation: "Plural subject 'children' uses 'have'",
          tip: "Children = plural (irregular)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 5,
          question: "She _____ to work by bicycle every day.",
          options: ["go", "goes", "going", "went"],
          correct: 1,
          explanation: "Third person singular: go → goes",
          tip: "Regular transport routines use present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 6,
          question: "We _____ meat. We're vegetarian.",
          options: ["don't eat", "doesn't eat", "not eat", "aren't eat"],
          correct: 0,
          explanation: "Plural subject uses 'don't' + base verb",
          tip: "Personal habits/preferences = present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 7,
          question: "_____ your sister speak French?",
          options: ["Do", "Does", "Is", "Can"],
          correct: 1,
          explanation: "Use 'Does' with third person singular in questions",
          tip: "Language abilities can use present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 8,
          question: "The museum _____ at 6 PM every day.",
          options: ["close", "closes", "closing", "closed"],
          correct: 1,
          explanation: "Institutions are third person singular",
          tip: "Opening/closing times = present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 9,
          question: "How often _____ you visit your grandparents?",
          options: ["do", "does", "are", "is"],
          correct: 0,
          explanation: "Use 'do' with 'you' in frequency questions",
          tip: "How often + do/does + subject + verb?",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 10,
          question: "The weather here _____ very cold in winter.",
          options: ["get", "gets", "getting", "got"],
          correct: 1,
          explanation: "Weather is third person singular",
          tip: "Weather descriptions use present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
    B1: {
      default: [
        {
          id: 1,
          question: "Water _____ at 100 degrees Celsius.",
          options: ["boil", "boils", "boiling", "boiled"],
          correct: 1,
          explanation: "Scientific facts use present simple",
          tip: "General truths = present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "The company _____ its employees very well.",
          options: ["treat", "treats", "treating", "treated"],
          correct: 1,
          explanation: "Company is singular, so use 'treats'",
          tip: "Organizations are singular entities",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 3,
          question: "People in this region _____ mostly agriculture.",
          options: ["practice", "practices", "practicing", "practiced"],
          correct: 0,
          explanation: "Plural subject 'people' uses base form",
          tip: "People = plural (not person)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 4,
          question: "The government _____ new policies every year.",
          options: ["introduce", "introduces", "introducing", "introduced"],
          correct: 1,
          explanation: "Government is considered singular",
          tip: "Collective nouns usually singular in formal contexts",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 5,
          question: "_____ this medicine have any side effects?",
          options: ["Do", "Does", "Is", "Are"],
          correct: 1,
          explanation: "Medicine is singular, so use 'Does'",
          tip: "Uncountable nouns are singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 6,
          question: "The Earth _____ around the Sun.",
          options: ["revolve", "revolves", "revolving", "revolved"],
          correct: 1,
          explanation: "Scientific facts about celestial bodies",
          tip: "Astronomical facts = present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 7,
          question: "Statistics _____ that crime rates are falling.",
          options: ["show", "shows", "showing", "showed"],
          correct: 0,
          explanation: "'Statistics' as data is plural",
          tip: "Statistics (data) = plural, statistic = singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 8,
          question: "Neither of the solutions _____ perfect.",
          options: ["is", "are", "seem", "were"],
          correct: 0,
          explanation: "Neither + singular verb",
          tip: "Neither/either + singular verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 9,
          question: "The news _____ very depressing today.",
          options: ["is", "are", "seem", "were"],
          correct: 0,
          explanation: "'News' is uncountable and singular",
          tip: "News, information = uncountable singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 10,
          question: "Everyone in the team _____ their responsibilities.",
          options: ["understand", "understands", "understanding", "understood"],
          correct: 1,
          explanation: "Everyone is singular despite plural meaning",
          tip: "Everyone/everybody = singular verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
    B2: {
      default: [
        {
          id: 1,
          question:
            "The research _____ significant implications for future studies.",
          options: ["carry", "carries", "carrying", "carried"],
          correct: 1,
          explanation:
            "Academic formal language: research carries implications",
          tip: "Formal academic expressions use present simple",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "Rarely _____ such dedication in students.",
          options: ["we see", "do we see", "we are seeing", "are we seeing"],
          correct: 1,
          explanation: "Inverted word order after negative adverbs",
          tip: "Rarely/seldom + auxiliary + subject + verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 3,
          question: "The committee _____ quarterly to review policies.",
          options: ["convene", "convenes", "convening", "convened"],
          correct: 1,
          explanation: "Committee as singular collective noun",
          tip: "Formal contexts: committee/board = singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 4,
          question: "Should the situation _____, we will take action.",
          options: [
            "deteriorate",
            "deteriorates",
            "deteriorating",
            "deteriorated",
          ],
          correct: 0,
          explanation: "Conditional sentences: should + base form",
          tip: "Should + subject + base verb (formal condition)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 5,
          question: "The phenomenon _____ across different cultures.",
          options: ["occur", "occurs", "occurring", "occurred"],
          correct: 1,
          explanation: "Singular phenomenon takes -s form",
          tip: "Phenomenon (singular) vs phenomena (plural)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 6,
          question:
            "Not only _____ students succeed, but teachers also benefit.",
          options: ["do", "does", "did", "are"],
          correct: 0,
          explanation: "Not only + auxiliary + subject inversion",
          tip: "Not only...but also requires inversion",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 7,
          question: "The data _____ a clear trend in consumer behavior.",
          options: ["indicate", "indicates", "indicating", "indicated"],
          correct: 0,
          explanation: "Data is plural (singular: datum)",
          tip: "Data = plural, information = singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 8,
          question: "Each of the proposals _____ careful consideration.",
          options: ["require", "requires", "requiring", "required"],
          correct: 1,
          explanation: "Each + singular verb",
          tip: "Each/every + of + plural noun = singular verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 9,
          question: "The criteria _____ too strict for most applicants.",
          options: ["is", "are", "seems", "appear"],
          correct: 1,
          explanation: "Criteria is plural (singular: criterion)",
          tip: "Criterion (singular) vs criteria (plural)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 10,
          question:
            "No sooner _____ the announcement than applications flooded in.",
          options: ["do we make", "did we make", "we make", "we made"],
          correct: 1,
          explanation: "No sooner + past tense (formal structure)",
          tip: "No sooner + past + than (fixed expression)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
    C1: {
      default: [
        {
          id: 1,
          question:
            "The findings _____ that conventional wisdom may be flawed.",
          options: ["suggest", "suggests", "suggesting", "suggested"],
          correct: 0,
          explanation: "Findings (plural) + suggest without -s",
          tip: "Academic writing: findings suggest, results indicate",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "Little _____ the public realize the complexity of the issue.",
          options: ["do", "does", "did", "are"],
          correct: 1,
          explanation: "Little + singular verb (public as collective)",
          tip: "Little + auxiliary + subject (negative inversion)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 3,
          question: "The media _____ considerably in their coverage of events.",
          options: ["differ", "differs", "differing", "differed"],
          correct: 0,
          explanation: "Media can be plural (different outlets)",
          tip: "Media: plural (outlets) or singular (industry)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 4,
          question: "Were it not for regulations, companies _____ more freely.",
          options: ["operate", "operates", "would operate", "will operate"],
          correct: 2,
          explanation: "Subjunctive: were it not for + would",
          tip: "Were it not for = formal conditional",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 5,
          question: "The majority of experts _____ with this assessment.",
          options: ["agree", "agrees", "agreeing", "agreed"],
          correct: 0,
          explanation: "Majority of + plural noun = plural verb",
          tip: "Majority of + plural = plural verb",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 6,
          question: "Such _____ the complexity that few understand it fully.",
          options: ["is", "are", "was", "were"],
          correct: 0,
          explanation: "Such is + singular noun (complexity)",
          tip: "Such is + abstract singular noun",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 7,
          question: "A number of studies _____ conflicting results.",
          options: ["show", "shows", "showing", "showed"],
          correct: 0,
          explanation: "A number of + plural noun = plural verb",
          tip: "A number of = plural, the number of = singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 8,
          question: "Neither the hypothesis nor the methodology _____ sound.",
          options: ["seem", "seems", "seeming", "seemed"],
          correct: 1,
          explanation:
            "Neither...nor + closest subject (methodology = singular)",
          tip: "Neither...nor: verb agrees with closest subject",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 9,
          question: "Under no circumstances _____ this approach recommended.",
          options: ["is", "are", "was", "were"],
          correct: 0,
          explanation: "Under no circumstances + singular (approach)",
          tip: "Negative phrases + inversion",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 10,
          question: "Physics _____ one of the most challenging subjects.",
          options: ["remain", "remains", "remaining", "remained"],
          correct: 1,
          explanation: "Subject names ending in -s are singular",
          tip: "Physics/mathematics/politics = singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
    C2: {
      default: [
        {
          id: 1,
          question:
            "Scarcely _____ the implications of this discovery been understood.",
          options: ["have", "has", "had", "are"],
          correct: 0,
          explanation: "Scarcely + perfect aspect with inversion",
          tip: "Scarcely/barely + auxiliary + subject + past participle",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question:
            "So sophisticated _____ the algorithm that few comprehend its mechanics.",
          options: ["is", "are", "was", "were"],
          correct: 0,
          explanation: "So + adjective + inversion (algorithm = singular)",
          tip: "So + adjective + be + subject + that clause",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 3,
          question: "The alumni _____ generous donations to their alma mater.",
          options: ["make", "makes", "making", "made"],
          correct: 0,
          explanation: "Alumni is plural (singular: alumnus/alumna)",
          tip: "Alumni = plural, alumnus/alumna = singular",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 4,
          question:
            "What with regulations and bureaucracy, progress _____ slow.",
          options: ["remain", "remains", "remaining", "remained"],
          correct: 1,
          explanation: "What with + complex subject, progress = singular",
          tip: "What with = given the circumstances of",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 5,
          question:
            "The bourgeoisie _____ to maintain their privileged status.",
          options: ["seek", "seeks", "seeking", "sought"],
          correct: 0,
          explanation: "Bourgeoisie as class (plural interpretation)",
          tip: "Class names: singular (entity) or plural (members)",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 6,
          question:
            "Not until the data _____ analyzed will conclusions be drawn.",
          options: ["is", "are", "was", "were"],
          correct: 0,
          explanation:
            "Data analyzed as process (singular interpretation here)",
          tip: "Not until + present tense in formal contexts",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 7,
          question:
            "The cognoscenti _____ that such refinements matter significantly.",
          options: ["understand", "understands", "understanding", "understood"],
          correct: 0,
          explanation: "Cognoscenti is plural (those with special knowledge)",
          tip: "Italian plurals: cognoscenti, literati, illuminati",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 8,
          question:
            "In no way _____ this precedent applicable to current cases.",
          options: ["is", "are", "was", "were"],
          correct: 0,
          explanation: "In no way + inversion, precedent = singular",
          tip: "Negative phrases + auxiliary + subject inversion",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 9,
          question: "The minutiae of the process _____ crucial to success.",
          options: ["is", "are", "was", "were"],
          correct: 1,
          explanation: "Minutiae is plural (singular: minutia)",
          tip: "Latin plurals: minutiae, phenomena, criteria",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 10,
          question: "Suffice it to say that such measures _____ inadequate.",
          options: ["prove", "proves", "proving", "proved"],
          correct: 0,
          explanation: "Measures (plural) + prove without -s",
          tip: "Suffice it to say = formal expression",
          tense: "present simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
  },

  "past simple": {
    A1: {
      default: [
        {
          id: 1,
          question: "I _____ to London yesterday.",
          options: ["go", "went", "going", "gone"],
          correct: 1,
          explanation: "Past form of irregular verb 'go'",
          tip: "go → went → gone",
          tense: "past simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "She _____ her homework last night.",
          options: ["finish", "finished", "finishing", "finishes"],
          correct: 1,
          explanation: "Regular verbs add -ed",
          tip: "Regular: verb + -ed",
          tense: "past simple",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 3,
          question: "_____ you see the movie?",
          options: ["Do", "Did", "Are", "Were"],
          correct: 1,
          explanation: "Use 'Did' for past simple questions.",
          tip: "Past questions: Did + subject + base verb?",
          tense: "past simple",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
  },

  modals: {
    A2: {
      default: [
        {
          id: 1,
          question: "You _____ eat healthy food.",
          options: ["should", "must", "can", "might"],
          correct: 0,
          explanation: "'Should' gives advice or recommendations.",
          tip: "Should = advice, must = obligation, can = ability",
          tense: "modals",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "_____ I use your phone?",
          options: ["Should", "Must", "Can", "Will"],
          correct: 2,
          explanation: "'Can' is used to ask for permission politely.",
          tip: "Can/May = asking permission",
          tense: "modals",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
    B1: {
      default: [
        {
          id: 1,
          question: "He _____ have arrived by now.",
          options: ["should", "can", "may", "will"],
          correct: 0,
          explanation: "Should for logical deduction",
          tip: "should = logical expectation",
          tense: "modals",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
  },

  conditionals: {
    B1: {
      default: [
        {
          id: 1,
          question: "If it rains tomorrow, I _____ stay at home.",
          options: ["will", "would", "can", "should"],
          correct: 0,
          explanation: "First conditional: If + present, will + base",
          tip: "Type 1: If + present, will + infinitive",
          tense: "conditionals",
          type: "multiple-choice" as TypeExcercise,
        },
        {
          id: 2,
          question: "If I were rich, I _____ travel around the world.",
          options: ["will", "would", "can", "should"],
          correct: 1,
          explanation: "Second conditional: If + past, would + base",
          tip: "Type 2: If + past, would + infinitive",
          tense: "conditionals",
          type: "multiple-choice" as TypeExcercise,
        },
      ],
    },
  },
};

export function getMultipleChoiceBackup(
  grammarTopic: string,
  proficiencyLevel: CEFRLevel,
  certificateType?: CertificateType,
  numQuestions: number = 5
): Question[] {
  const topicData =
    MULTIPLE_CHOICE_BACKUPS[
      grammarTopic.toLowerCase() as keyof typeof MULTIPLE_CHOICE_BACKUPS
    ];
  if (!topicData) return [];

  const levelData = (topicData as any)[proficiencyLevel];
  if (!levelData) return [];

  const certificateKey = certificateType || "default";
  const questions = levelData[certificateKey] || levelData["default"] || [];

  return questions.slice(0, numQuestions);
}

export default MULTIPLE_CHOICE_BACKUPS;
