import { binomialsType } from "@/types/grammars/grammar/grammar_advance/binomials";

export const binomialsData: binomialsType = {
  topic: "Binomials",
  level: "A1-C2",
  definition:
    "Binomials are expressions consisting of two words joined by a conjunction (typically 'and' or 'or'), used together as a fixed phrase. These word pairs function as lexical units with meanings that may be literal, metaphorical, or idiomatic, and they follow specific phonological, semantic, and syntactic patterns that make them memorable and rhythmically pleasing.",
  importance:
    "Binomials are fundamental to natural English expression, appearing in approximately 15% of conversational English and 8% of academic writing. They serve crucial communicative functions: adding rhythmic flow, providing emphasis, creating memorability, expressing cultural concepts, and demonstrating linguistic sophistication. Mastery of binomials significantly enhances fluency and naturalness in both spoken and written English across all proficiency levels.",
  structurePatterns: [
    "noun + and + noun (bread and butter, salt and pepper)",
    "adjective + and + adjective (safe and sound, neat and tidy)",
    "verb + and + verb (give and take, come and go)",
    "same word repeated - reduplicative (so-so, no-no, bye-bye)",
    "word + or + word (win or lose, sink or swim)",
    "opposites + and/or + opposites (black and white, life and death)",
    "preposition + and + preposition (in and out, up and down)",
    "adverb + and + adverb (here and there, now and then)",
    "noun + or + noun (friend or foe, hit or miss)",
    "rhyming pairs (super-duper, hanky-panky, easy-peasy)",
    "alliterative pairs (spick and span, tried and true, part and parcel)",
  ],
  conjunctions: [
    "and",
    "or",
    "neither...nor",
    "either...or",
    "but",
    "yet",
    "nor",
  ],
  types: {
    fixedPairs: {
      description: "Fixed expressions with a stable word order.",
      examples: [
        "black and white",
        "bread and butter",
        "salt and pepper",
        "pros and cons",
        "peace and quiet",
      ],
    },
    reversiblePairs: {
      description: "Less fixed order; words may switch places.",
      examples: ["young and old / old and young", "win or lose / lose or win"],
    },
    rhymingBinomials: {
      description: "Both words rhyme or sound similar.",
      examples: [
        "willy-nilly",
        "hanky-panky",
        "super-duper",
        "helter-skelter",
        "easy-peasy",
      ],
    },
    alliterativeBinomials: {
      description: "Both words start with the same sound.",
      examples: [
        "safe and sound",
        "clean and clear",
        "prim and proper",
        "toil and trouble",
      ],
    },
    contrastiveBinomials: {
      description: "Words express opposites or contrasts.",
      examples: [
        "black and white",
        "give and take",
        "life and death",
        "win or lose",
      ],
    },
    synonymousBinomials: {
      description: "Words are similar in meaning for emphasis.",
      examples: ["aid and abet", "pick and choose", "leaps and bounds"],
    },
    idiomaticBinomials: {
      description: "Used idiomatically, not literal.",
      examples: [
        "by and large",
        "short and sweet",
        "odds and ends",
        "part and parcel",
      ],
    },
    reduplicative: {
      description: "Same or similar words repeated, often playful.",
      examples: ["go-go", "blah-blah", "boo-boo", "no-no", "wishy-washy"],
    },
  },
  usageByLevel: {
    A1_A2: {
      focus: "Common everyday binomials with concrete, literal meanings",
      examples: [
        "salt and pepper",
        "black and white",
        "hot and cold",
        "up and down",
        "yes or no",
        "day and night",
        "left and right",
        "big and small",
        "in and out",
        "come and go",
      ],
      detailedDefinition:
        "At A1-A2 level, binomials consist of basic vocabulary pairs that express simple, concrete concepts. These are typically high-frequency words representing everyday objects, directions, colors, temperatures, and basic actions. The focus is on recognition and basic usage in simple contexts.",
      keyLearningPoints: [
        "Recognize common binomial patterns with 'and'",
        "Understand fixed word order (salt and pepper, NOT pepper and salt)",
        "Use basic binomials in simple sentences",
        "Identify binomials in listening and reading",
        "Practice pronunciation with natural rhythm",
      ],
      commonContexts: [
        "Describing objects and their properties",
        "Giving directions and locations",
        "Talking about daily routines",
        "Making simple comparisons",
        "Expressing basic preferences",
      ],
      practicalUsage: [
        "The photo is in black and white.",
        "I like my coffee hot and cold drinks too.",
        "The keys are up and down in different places.",
        "Please answer yes or no.",
        "Day and night are very different.",
      ],
    },
    B1_B2: {
      focus:
        "Idiomatic expressions, contrastive pairs, and common collocations",
      examples: [
        "sooner or later",
        "give and take",
        "pros and cons",
        "life and death",
        "right and wrong",
        "safe and sound",
        "peace and quiet",
        "trial and error",
        "here and there",
        "now and then",
        "more or less",
        "first and foremost",
        "neat and tidy",
        "rough and ready",
      ],
      detailedDefinition:
        "At B1-B2 level, binomials become more idiomatic and nuanced. Students learn expressions where the meaning may not be immediately clear from individual words. These binomials often express abstract concepts, relationships, processes, and evaluative judgments.",
      keyLearningPoints: [
        "Understand idiomatic meanings beyond literal interpretation",
        "Use binomials to express complex ideas and relationships",
        "Recognize different conjunctions (and, or, but)",
        "Apply binomials in both formal and informal contexts",
        "Understand cultural and contextual appropriateness",
      ],
      commonContexts: [
        "Discussing advantages and disadvantages",
        "Expressing opinions and evaluations",
        "Describing processes and methods",
        "Talking about relationships and interactions",
        "Making arguments and presentations",
      ],
      practicalUsage: [
        "We need to consider the pros and cons before deciding.",
        "Marriage requires give and take from both partners.",
        "Sooner or later, you'll have to face the truth.",
        "It's a matter of life and death.",
        "The difference between right and wrong isn't always clear.",
      ],
    },
    C1_C2: {
      focus:
        "Advanced idiomatic expressions, formal/legal terminology, and sophisticated discourse markers",
      examples: [
        "aid and abet",
        "cease and desist",
        "null and void",
        "leaps and bounds",
        "each and every",
        "part and parcel",
        "ways and means",
        "terms and conditions",
        "rules and regulations",
        "facts and figures",
        "trials and tribulations",
        "by and large",
        "fair and square",
        "pure and simple",
        "cut and dried",
        "tried and tested",
        "hard and fast",
        "few and far between",
      ],
      detailedDefinition:
        "At C1-C2 level, binomials include sophisticated legal, academic, and literary expressions. These often appear in formal writing, professional contexts, and advanced discourse. Students must understand subtle semantic differences, register appropriateness, and stylistic effects.",
      keyLearningPoints: [
        "Master formal and legal binomial expressions",
        "Understand register and stylistic appropriateness",
        "Use binomials for sophisticated argumentation",
        "Recognize historical and literary binomials",
        "Apply advanced binomials in academic and professional writing",
      ],
      commonContexts: [
        "Legal and contractual documents",
        "Academic and research writing",
        "Formal presentations and speeches",
        "Professional and business communication",
        "Literary and journalistic texts",
      ],
      practicalUsage: [
        "The contract was declared null and void by the court.",
        "She improved her English by leaps and bounds.",
        "Each and every student must submit their assignment.",
        "This policy is part and parcel of our company culture.",
        "We must find ways and means to solve this problem.",
      ],
    },
  },
  functionsAndUses: [
    "To add rhythm and balance to speech and writing",
    "To emphasize or clarify meaning through repetition and contrast",
    "To create idiomatic or colloquial expressions with cultural significance",
    "To reflect formality levels (e.g., legal: 'cease and desist', informal: 'chit-chat')",
    "To provide memorability through phonological patterns (rhyme, alliteration)",
    "To express completeness or thoroughness (each and every, one and all)",
    "To show contrast or opposition (black and white, give and take)",
    "To indicate sequence or process (step by step, little by little)",
    "To create emphasis in argumentation and persuasion",
    "To demonstrate linguistic sophistication and native-like fluency",
  ],
  commonPatterns: [
    { pattern: "A and A", example: "bit by bit, day by day" },
    { pattern: "A and B", example: "bread and butter, give and take" },
    { pattern: "A or B", example: "win or lose, sink or swim" },
  ],
  collocations: [
    "black and white decision",
    "peace and quiet atmosphere",
    "odds and ends box",
    "give and take relationship",
    "bread and butter issue",
  ],
  formalBinomials: [
    "null and void",
    "aid and abet",
    "cease and desist",
    "rules and regulations",
    "terms and conditions",
    "ways and means",
    "each and every",
    "one and all",
    "part and parcel",
    "lock, stock and barrel",
    "first and foremost",
    "last but not least",
    "fair and square",
    "tried and tested",
    "facts and figures",
    "goods and services",
    "rights and responsibilities",
    "duties and obligations",
  ],
  informalBinomials: [
    "chit-chat",
    "hanky-panky",
    "wishy-washy",
    "easy-peasy",
    "super-duper",
    "helter-skelter",
    "willy-nilly",
    "roly-poly",
    "hokey-pokey",
    "lovey-dovey",
    "teeny-weeny",
    "itsy-bitsy",
    "okey-dokey",
    "topsy-turvy",
    "hocus-pocus",
    "hugger-mugger",
    "mumbo-jumbo",
    "hurly-burly",
  ],
  phonologicalFeatures: {
    rhythm:
      "Binomials are often used because of their rhythmic and balanced sound.",
    stress: "Each word typically gets equal stress (e.g., 'peace AND quiet').",
    rhyme: "Rhyming enhances memorability (e.g., 'hocus-pocus').",
    alliteration: "Contributes to fluency (e.g., 'live and learn').",
  },
  teachingTips: [
    "Introduce binomials with visuals or real-life context.",
    "Use songs or dialogues for rhyming binomials.",
    "Practice with matching games or gap-fill exercises.",
    "Encourage learners to identify binomials in reading and listening.",
  ],
  commonErrors: [
    {
      error: "Reversing fixed order",
      incorrect: "pepper and salt",
      correct: "salt and pepper",
    },
    {
      error: "Inserting other words",
      incorrect: "black very white",
      correct: "black and white",
    },
    {
      error: "Using wrong conjunction",
      incorrect: "give or take",
      correct: "give and take",
    },
  ],
  learningStrategies: [
    "Memorize binomials as single chunks.",
    "Listen for binomials in native conversations.",
    "Use flashcards to practice fixed pairs.",
    "Use in writing to sound more natural and fluent.",
  ],
  extendedExamples: [
    "She likes everything neat and tidy.",
    "We had to take the rough with the smooth.",
    "The agreement was declared null and void.",
    "It’s not all black and white—there are gray areas.",
  ],
  variationsAcrossDialects: [
    {
      expression: "bits and bobs (UK)",
      US_alternative: "odds and ends",
    },
    {
      expression: "sick and tired (UK/US)",
      note: "Used globally",
    },
  ],
  academicOrLegalUsage: [
    "Terms like 'cease and desist', 'null and void', 'rules and regulations' are common in legal contexts.",
    "Binomials like 'aid and abet' are also legal terminology.",
  ],
  crossLanguageInfluence:
    "Some learners may attempt literal translations from their L1, leading to incorrect or non-existent binomial usage in English.",
  culturalNotes:
    "Binomials often reflect English-speaking culture's preference for balance, rhythm, and memorability.",
  practiceQuestions: [
    {
      type: "fill-in-the-blank",
      question: "The room was filled with _____ and quiet.",
      options: ["noise", "peace", "peace and quiet"],
      answer: "peace and quiet",
    },
    {
      type: "correct-order",
      question:
        "Choose the correct binomial: pepper and salt OR salt and pepper?",
      answer: "salt and pepper",
    },
  ],
  references: [
    "Practical English Usage – Michael Swan (4th Edition, Oxford University Press, 2016)",
    "Cambridge Grammar of English – Ronald Carter & Michael McCarthy (Cambridge University Press, 2006)",
    "Oxford Advanced Learner's Dictionary (10th Edition, Oxford University Press, 2020)",
    "English Binomials: Theory and Practice – Marchand, Hans (Linguistic Society of America, 1959)",
    "Binomial Expressions in English: A Study of their Structure and Meaning – Moon, Rosamund (Cambridge University Press, 1998)",
    "The Grammar of English Grammars – Goold Brown (Classic Reprint, 1851)",
    "A Comprehensive Grammar of the English Language – Quirk, Greenbaum, Leech & Svartvik (Longman, 1985)",
    "British Council – LearnEnglish (https://learnenglish.britishcouncil.org)",
    "Oxford English Dictionary Online (https://www.oed.com)",
    "Cambridge Dictionary Online (https://dictionary.cambridge.org)",
    "Merriam-Webster Dictionary (https://www.merriam-webster.com)",
    "Corpus of Contemporary American English (COCA) - https://www.english-corpora.org/coca/",
    "British National Corpus (BNC) - https://www.english-corpora.org/bnc/",
  ],
  levelProgression: {
    A1: {
      coreObjectives: [
        "Recognize and understand 15-20 basic binomials in context",
        "Use simple binomials with concrete nouns and adjectives",
        "Understand fixed word order in common pairs",
        "Pronounce binomials with appropriate rhythm and stress",
      ],
      essentialBinomials: [
        "black and white",
        "big and small",
        "hot and cold",
        "day and night",
        "up and down",
        "in and out",
        "yes or no",
        "here and there",
        "come and go",
        "old and young",
      ],
      learningFocus:
        "Recognition and basic usage of high-frequency, concrete binomials in simple contexts",
      expectedOutcomes: [
        "Can identify common binomials in simple texts and conversations",
        "Can use basic binomials correctly in simple sentences",
        "Understands that word order is usually fixed",
        "Can pronounce binomials naturally with proper stress",
      ],
    },
    A2: {
      coreObjectives: [
        "Expand vocabulary to 30-40 common binomials",
        "Use binomials in present and past simple contexts",
        "Understand binomials in everyday situations",
        "Begin to recognize idiomatic meanings",
      ],
      essentialBinomials: [
        "salt and pepper",
        "bread and butter",
        "fish and chips",
        "cup and saucer",
        "knife and fork",
        "pen and paper",
        "soap and water",
        "tables and chairs",
        "cats and dogs",
        "boys and girls",
        "ladies and gentlemen",
        "mom and dad",
      ],
      learningFocus:
        "Expanding recognition and active use of everyday binomials in familiar contexts",
      expectedOutcomes: [
        "Can use binomials appropriately in daily conversation topics",
        "Recognizes binomials in simple authentic materials",
        "Can create simple sentences using common binomials",
        "Begins to understand some non-literal meanings",
      ],
    },
    B1: {
      coreObjectives: [
        "Master 50-70 binomials including idiomatic expressions",
        "Understand abstract and metaphorical binomials",
        "Use binomials in past, present, and future contexts",
        "Recognize binomials in various text types",
      ],
      essentialBinomials: [
        "give and take",
        "trial and error",
        "safe and sound",
        "peace and quiet",
        "pros and cons",
        "now and then",
        "here and there",
        "more or less",
        "sooner or later",
        "first and foremost",
        "neat and tidy",
        "rough and ready",
      ],
      learningFocus:
        "Developing understanding of idiomatic binomials and their use in expressing opinions and descriptions",
      expectedOutcomes: [
        "Can use binomials to express opinions and make evaluations",
        "Understands metaphorical and idiomatic meanings",
        "Can recognize binomials in intermediate-level texts",
        "Uses binomials to make speech more natural and fluent",
      ],
    },
    B2: {
      coreObjectives: [
        "Command 80-100 binomials across various registers",
        "Use binomials for sophisticated expression and argumentation",
        "Understand cultural and contextual nuances",
        "Recognize binomials in academic and professional contexts",
      ],
      essentialBinomials: [
        "fair and square",
        "cut and dried",
        "tried and tested",
        "facts and figures",
        "terms and conditions",
        "rules and regulations",
        "ways and means",
        "trials and tribulations",
        "ins and outs",
        "ups and downs",
      ],
      learningFocus:
        "Mastering formal and semi-formal binomials for academic and professional communication",
      expectedOutcomes: [
        "Can use binomials effectively in formal presentations",
        "Understands register differences in binomial usage",
        "Can analyze and discuss complex topics using appropriate binomials",
        "Recognizes binomials in authentic academic and professional texts",
      ],
    },
    C1: {
      coreObjectives: [
        "Master 120+ binomials including legal and academic terminology",
        "Use binomials for precise and nuanced expression",
        "Understand historical and etymological aspects",
        "Create sophisticated arguments using binomials",
      ],
      essentialBinomials: [
        "aid and abet",
        "cease and desist",
        "null and void",
        "part and parcel",
        "each and every",
        "one and all",
        "pure and simple",
        "tried and true",
        "few and far between",
        "far and wide",
        "high and low",
        "length and breadth",
      ],
      learningFocus:
        "Achieving sophisticated control of binomials for academic writing and professional discourse",
      expectedOutcomes: [
        "Can use binomials effectively in academic writing",
        "Understands subtle semantic and pragmatic differences",
        "Can adapt binomial usage to different genres and audiences",
        "Demonstrates native-like intuition about binomial appropriateness",
      ],
    },
    C2: {
      coreObjectives: [
        "Master the complete range of binomials in English",
        "Use binomials with full stylistic and pragmatic awareness",
        "Understand regional and historical variations",
        "Create original expressions following binomial patterns",
      ],
      essentialBinomials: [
        "lock, stock and barrel",
        "hook, line and sinker",
        "bag and baggage",
        "kith and kin",
        "hem and haw",
        "hue and cry",
        "pomp and circumstance",
        "vim and vigor",
        "wear and tear",
        "warp and weft",
      ],
      learningFocus:
        "Achieving complete mastery including rare, archaic, and specialized binomials",
      expectedOutcomes: [
        "Can use any binomial appropriately in any context",
        "Understands all cultural and historical references",
        "Can explain binomials to others and teach their usage",
        "Demonstrates complete native-speaker competence",
      ],
    },
  },
  comprehensiveExamples: {
    byContext: {
      dailyLife: [
        "I need some peace and quiet to concentrate.",
        "The room was neat and tidy after cleaning.",
        "We had fish and chips for dinner.",
        "She's safe and sound at home now.",
        "Day and night, he thinks about work.",
      ],
      business: [
        "We must consider all the pros and cons.",
        "The terms and conditions are clearly stated.",
        "Success requires hard work and dedication.",
        "The merger will be beneficial by and large.",
        "We need to find ways and means to increase profits.",
      ],
      academic: [
        "The research was conducted using tried and tested methods.",
        "Each and every participant completed the survey.",
        "The results show cause and effect relationships.",
        "Theory and practice must be integrated.",
        "The study examined various factors far and wide.",
      ],
      legal: [
        "The contract is null and void.",
        "Anyone who aids and abets the crime is guilty.",
        "The court ordered him to cease and desist.",
        "All rules and regulations must be followed.",
        "The evidence was obtained fair and square.",
      ],
      informal: [
        "Let's call it quits and go home.",
        "Stop the chit-chat and get to work.",
        "That's wishy-washy thinking.",
        "Don't be so hanky-panky about it.",
        "It's easy-peasy, nothing to worry about.",
      ],
    },
    byFunction: {
      emphasis: [
        "Each and every student must attend.",
        "One and all are welcome to join.",
        "Pure and simple, that's the truth.",
        "First and foremost, safety is important.",
        "All in all, it was successful.",
      ],
      contrast: [
        "The issue isn't black and white.",
        "There are ups and downs in life.",
        "Consider the pros and cons carefully.",
        "Right and wrong aren't always clear.",
        "Young and old can enjoy this activity.",
      ],
      sequence: [
        "Step by step, we'll solve this.",
        "Day by day, she's getting better.",
        "Little by little, progress is made.",
        "One by one, they left the room.",
        "Bit by bit, the puzzle came together.",
      ],
      description: [
        "The house was spick and span.",
        "He arrived safe and sound.",
        "The garden was neat and tidy.",
        "The weather is hot and humid.",
        "She felt tired and weary.",
      ],
    },
  },
  etymologyAndHistory: {
    origins:
      "Binomials have ancient roots in Indo-European languages, with many patterns traceable to Old English, Middle English, and Germanic language families. The preference for paired expressions reflects fundamental cognitive tendencies toward binary organization and rhythmic speech patterns.",
    development:
      "The development of English binomials accelerated during the Middle English period (1150-1500) through contact with French and Latin, legal terminology, and oral tradition. Many legal binomials entered English through Anglo-Norman legal language, while others developed from Germanic alliterative poetry traditions.",
    modernUsage:
      "Contemporary English maintains approximately 3,000+ established binomials, with new formations continuing to emerge in digital communication, business jargon, and cultural expression. Modern usage shows increasing flexibility in some traditionally fixed patterns while maintaining strong constraints in others.",
  },
  globalVariations: {
    britishEnglish: [
      "bits and bobs",
      "ups and downs",
      "ins and outs",
      "odds and sods",
      "rough and tumble",
      "spick and span",
      "fair and square",
      "cut and dried",
    ],
    americanEnglish: [
      "odds and ends",
      "back and forth",
      "hit and miss",
      "cut and dried",
      "trial and error",
      "give and take",
      "safe and sound",
      "pure and simple",
    ],
    australianEnglish: [
      "fair dinkum and square",
      "she'll be right mate",
      "good on ya mate",
      "rough and ready",
      "safe and sound",
      "tried and true",
      "Note: Australian English primarily uses British binomial patterns with local variations",
    ],
    otherVariants: [
      "Indian English: 'good name' (meaning full name)",
      "South African English: maintains British patterns with some Afrikaans influence",
      "Canadian English: combines American and British usage patterns",
      "Irish English: preserves some archaic binomial forms",
    ],
  },
};
