import { emotionAdjectivesType } from "@/types/grammars/grammar/adjective_special/emotionAdjectives";

export const emotionAdjectivesData: emotionAdjectivesType = {
  category: "Emotion Adjectives",
  topic: "Tính từ chỉ cảm xúc vs. gây cảm xúc",
  levels: ["A1", "A2", "B1", "B2", "C1", "C2"],
  description:
    "Phân biệt giữa các tính từ mô tả cảm xúc cá nhân (feeling adjectives) và các tính từ gây ra cảm xúc cho người khác (emotion-causing adjectives), ví dụ: 'interested' vs. 'interesting'. Đây là một trong những điểm ngữ pháp quan trọng nhất trong tiếng Anh, giúp người học diễn đạt chính xác cảm xúc và mô tả tác động của sự vật, sự việc lên con người.",

  levelDefinitions: [
    {
      level: "A1",
      description:
        "Giới thiệu các tính từ cảm xúc cơ bản nhất trong cuộc sống hàng ngày",
      keyFeatures: [
        "Học các tính từ cảm xúc đơn giản và phổ biến nhất",
        "Hiểu cấu trúc cơ bản 'I am + adjective'",
        "Phân biệt giữa cảm giác tích cực và tiêu cực",
        "Sử dụng trong câu đơn giản",
      ],
      adjectives: ["happy", "sad", "angry", "tired", "scared", "good", "bad"],
      examples: ["I am happy.", "She is sad.", "He is angry.", "We are tired."],
      focusAreas: [
        "Từ vựng cảm xúc cơ bản",
        "Cấu trúc câu đơn giản với 'be'",
        "Phân biệt tích cực/tiêu cực",
      ],
    },
    {
      level: "A2",
      description:
        "Mở rộng từ vựng và bắt đầu hiểu sự khác biệt giữa -ed và -ing",
      keyFeatures: [
        "Học thêm tính từ cảm xúc phổ biến",
        "Giới thiệu khái niệm -ed vs -ing cơ bản",
        "Sử dụng trong ngữ cảnh đơn giản",
        "Mô tả cảm xúc trong các tình huống quen thuộc",
      ],
      adjectives: [
        "excited",
        "bored",
        "interested",
        "worried",
        "surprised",
        "relaxed",
      ],
      examples: [
        "I am excited about the party.",
        "The movie is boring.",
        "She is interested in music.",
        "This book is interesting.",
      ],
      focusAreas: [
        "Phân biệt cơ bản -ed/-ing",
        "Từ vựng trong các tình huống hàng ngày",
        "Cấu trúc với giới từ đơn giản",
      ],
    },
    {
      level: "B1",
      description: "Củng cố và mở rộng hiểu biết về emotion adjectives",
      keyFeatures: [
        "Sử dụng chính xác -ed và -ing adjectives",
        "Hiểu ngữ cảnh và tình huống sử dụng",
        "Mô tả cảm xúc phức tạp hơn",
        "Sử dụng trong giao tiếp thực tế",
      ],
      adjectives: [
        "frustrated",
        "amazing",
        "disappointing",
        "thrilled",
        "exhausting",
        "fascinating",
      ],
      examples: [
        "I was frustrated by the traffic.",
        "The traffic was frustrating.",
        "She found the lecture fascinating.",
        "He looked exhausted after work.",
      ],
      focusAreas: [
        "Ngữ cảnh sử dụng chính xác",
        "Cấu trúc câu phức tạp hơn",
        "Giao tiếp trong tình huống thực tế",
      ],
    },
    {
      level: "B2",
      description: "Thành thạo và sử dụng linh hoạt trong nhiều ngữ cảnh",
      keyFeatures: [
        "Sử dụng tự nhiên và chính xác",
        "Hiểu các ngoại lệ và trường hợp đặc biệt",
        "Kết hợp với các cấu trúc ngữ pháp khác",
        "Sử dụng trong văn viết và nói học thuật",
      ],
      adjectives: [
        "overwhelming",
        "bewildering",
        "inspiring",
        "devastating",
        "uplifting",
        "demoralizing",
      ],
      examples: [
        "The amount of information was overwhelming.",
        "I felt overwhelmed by all the choices.",
        "His speech was truly inspiring.",
        "She felt inspired to change her career.",
      ],
      focusAreas: [
        "Sử dụng trong ngữ cảnh học thuật",
        "Kết hợp với các cấu trúc phức tạp",
        "Hiểu sắc thái nghĩa",
      ],
    },
    {
      level: "C1",
      description: "Sử dụng tinh tế và hiểu các sắc thái nghĩa sâu sắc",
      keyFeatures: [
        "Hiểu và sử dụng các tính từ cảm xúc tinh tế",
        "Nắm vững các pattern và exception",
        "Sử dụng trong viết và nói chuyên nghiệp",
        "Hiểu các biến thể và collocation",
      ],
      adjectives: [
        "exhilarating",
        "mortifying",
        "stupefying",
        "riveting",
        "harrowing",
        "electrifying",
      ],
      examples: [
        "The performance was absolutely electrifying.",
        "She felt mortified by her mistake.",
        "The documentary was harrowing yet necessary.",
        "His analysis was stupefying in its complexity.",
      ],
      focusAreas: [
        "Sử dụng chuyên nghiệp",
        "Hiểu collocation và idiom",
        "Viết học thuật và văn học",
      ],
    },
    {
      level: "C2",
      description:
        "Thành thạo như người bản xứ với hiểu biết sâu sắc về ngôn ngữ học",
      keyFeatures: [
        "Sử dụng như người bản xứ",
        "Hiểu etymology và linguistic patterns",
        "Tạo ra các cách diễn đạt mới",
        "Nhận biết và sử dụng register phù hợp",
      ],
      adjectives: [
        "stupendous",
        "transcendent",
        "sublime",
        "ineffable",
        "poignant",
        "visceral",
      ],
      examples: [
        "The symphony evoked a visceral response from the audience.",
        "Her prose has a transcendent quality that defies categorization.",
        "The ineffable sadness in his eyes spoke volumes.",
        "The landscape possessed a sublime beauty.",
      ],
      focusAreas: [
        "Sử dụng trong văn học và nghệ thuật",
        "Hiểu biết ngôn ngữ học sâu sắc",
        "Tạo ra các expression độc đáo",
      ],
    },
  ],

  structurePatterns: [
    {
      structure: "S + be + [feeling adjective]",
      meaning: "Chủ ngữ cảm thấy thế nào",
      example: "She is bored.",
      level: "A1",
    },
    {
      structure: "S + be + [emotion-causing adjective]",
      meaning: "Chủ ngữ gây ra cảm xúc cho người khác",
      example: "The movie is boring.",
      level: "A2",
    },
    {
      structure: "S + feel + [feeling adjective] + about/by + N",
      meaning: "Cảm thấy thế nào về điều gì",
      example: "I feel excited about the trip.",
      level: "B1",
    },
    {
      structure: "S + find + O + [emotion-causing adjective]",
      meaning: "Nhận thấy cái gì đó có tính chất gây cảm xúc",
      example: "I find this book fascinating.",
      level: "B1",
    },
    {
      structure: "It + be + [emotion-causing adjective] + that + clause",
      meaning: "Việc gì đó có tính chất gây cảm xúc",
      example: "It's amazing that he succeeded.",
      level: "B2",
    },
    {
      structure: "S + make + O + feel + [feeling adjective]",
      meaning: "Làm ai đó cảm thấy thế nào",
      example: "The news made me feel worried.",
      level: "B2",
    },
    {
      structure: "S + leave + O + [feeling adjective]",
      meaning: "Để lại cho ai đó cảm giác gì",
      example: "The performance left the audience mesmerized.",
      level: "C1",
    },
    {
      structure: "[Emotion-causing adjective] + as + it + may + seem",
      meaning: "Dù có vẻ như thế nào đi nữa",
      example: "Surprising as it may seem, he actually enjoyed the lecture.",
      level: "C1",
    },
  ],

  emotion_Adjectives_vocab: {
    positive: [
      "happy",
      "glad",
      "pleased",
      "joyful",
      "delighted",
      "cheerful",
      "hopeful",
      "confident",
      "excited",
      "ecstatic",
      "elated",
      "content",
      "grateful",
      "thankful",
      "satisfied",
      "enthusiastic",
      "relieved",
      "relaxed",
      "inspired",
      "proud",
      "amused",
      "loved",
      "optimistic",
      "compassionate",
      "touched",
      "affectionate",
      "thrilled",
      "radiant",
      "buoyant",
      "playful",
      "curious",
      "trusting",
      "peaceful",
      "fulfilled",
      "energetic",
      "secure",
      "serene",
      "invigorated",
      "exhilarated",
      "uplifted",
      "blissful",
      "euphoric",
      "overjoyed",
      "jubilant",
      "triumphant",
      "rejuvenated",
      "revitalized",
      "enchanted",
      "mesmerized",
      "captivated",
      "spellbound",
      "enthralled",
    ],

    negative: [
      "sad",
      "unhappy",
      "angry",
      "annoyed",
      "upset",
      "depressed",
      "anxious",
      "afraid",
      "scared",
      "worried",
      "nervous",
      "frustrated",
      "disappointed",
      "bitter",
      "resentful",
      "jealous",
      "lonely",
      "miserable",
      "guilty",
      "ashamed",
      "embarrassed",
      "discouraged",
      "defeated",
      "hopeless",
      "desperate",
      "pessimistic",
      "heartbroken",
      "terrified",
      "furious",
      "envious",
      "tense",
      "panicked",
      "stressed",
      "moody",
      "grumpy",
      "unsettled",
      "threatened",
      "vulnerable",
      "overwhelmed",
      "devastated",
      "traumatized",
      "mortified",
      "humiliated",
      "agitated",
      "distressed",
      "tormented",
      "anguished",
      "despondent",
      "disheartened",
      "demoralized",
      "crushed",
      "shattered",
    ],

    neutral_or_contextual: [
      "surprised",
      "shocked",
      "confused",
      "bored",
      "indifferent",
      "numb",
      "tired",
      "sleepy",
      "restless",
      "uneasy",
      "blank",
      "distracted",
      "detached",
      "insecure",
      "reserved",
      "hesitant",
      "quiet",
      "pensive",
      "dazed",
      "thoughtful",
      "uncertain",
      "ambivalent",
      "bewildered",
      "perplexed",
      "puzzled",
      "startled",
      "stunned",
      "stupefied",
      "awestruck",
      "contemplative",
      "reflective",
      "meditative",
      "introspective",
    ],

    ce_fr_levels: {
      A1_A2: [
        "happy",
        "sad",
        "angry",
        "tired",
        "scared",
        "worried",
        "glad",
        "upset",
        "bored",
        "excited",
        "good",
        "bad",
        "nice",
        "fine",
        "okay",
      ],
      B1_B2: [
        "confident",
        "frustrated",
        "grateful",
        "jealous",
        "lonely",
        "guilty",
        "embarrassed",
        "nervous",
        "relaxed",
        "amused",
        "ashamed",
        "anxious",
        "hopeful",
        "curious",
        "disappointed",
        "relieved",
        "satisfied",
        "enthusiastic",
        "proud",
        "content",
      ],
      C1_C2: [
        "ecstatic",
        "elated",
        "resentful",
        "pessimistic",
        "heartbroken",
        "inspired",
        "fulfilled",
        "overwhelmed",
        "compassionate",
        "affectionate",
        "radiant",
        "buoyant",
        "invigorated",
        "serene",
        "ambivalent",
        "detached",
        "desperate",
        "euphoric",
        "mortified",
        "exhilarated",
        "devastated",
        "spellbound",
        "mesmerized",
        "transcendent",
      ],
    },

    emotion_categories: {
      happiness: [
        "happy",
        "glad",
        "joyful",
        "delighted",
        "cheerful",
        "content",
        "ecstatic",
        "elated",
        "jubilant",
        "euphoric",
        "blissful",
        "overjoyed",
        "radiant",
        "buoyant",
      ],
      sadness: [
        "sad",
        "miserable",
        "heartbroken",
        "unhappy",
        "depressed",
        "hopeless",
        "lonely",
        "despondent",
        "disheartened",
        "demoralized",
        "crushed",
        "shattered",
      ],
      anger: [
        "angry",
        "furious",
        "annoyed",
        "bitter",
        "resentful",
        "jealous",
        "frustrated",
        "enraged",
        "livid",
        "incensed",
        "irate",
        "indignant",
      ],
      fear: [
        "afraid",
        "scared",
        "terrified",
        "nervous",
        "worried",
        "tense",
        "panicked",
        "petrified",
        "horrified",
        "apprehensive",
        "fearful",
        "timid",
      ],
      surprise: [
        "surprised",
        "shocked",
        "stunned",
        "dazed",
        "startled",
        "amazed",
        "astonished",
        "astounded",
        "flabbergasted",
        "bewildered",
        "stupefied",
        "awestruck",
      ],
      love: [
        "loved",
        "affectionate",
        "touched",
        "compassionate",
        "grateful",
        "thankful",
        "devoted",
        "adoring",
        "cherished",
        "treasured",
        "endeared",
      ],
      anxiety: [
        "anxious",
        "stressed",
        "overwhelmed",
        "insecure",
        "uneasy",
        "restless",
        "agitated",
        "flustered",
        "perturbed",
        "troubled",
        "distressed",
      ],
      calm: [
        "relaxed",
        "serene",
        "peaceful",
        "secure",
        "invigorated",
        "tranquil",
        "composed",
        "centered",
        "balanced",
        "harmonious",
        "placid",
      ],
      shame: [
        "ashamed",
        "guilty",
        "embarrassed",
        "humiliated",
        "mortified",
        "sheepish",
        "remorseful",
        "contrite",
        "regretful",
        "disgraced",
      ],
      excitement: [
        "excited",
        "thrilled",
        "exhilarated",
        "enthusiastic",
        "eager",
        "animated",
        "stimulated",
        "energized",
        "electrified",
        "pumped",
        "hyped",
      ],
      confusion: [
        "confused",
        "bewildered",
        "perplexed",
        "puzzled",
        "baffled",
        "mystified",
        "befuddled",
        "disoriented",
        "muddled",
        "stumped",
      ],
    },
  },

  adjectivePairs: [
    { feeling: "bored", causing: "boring" },
    { feeling: "tired", causing: "tiring" },
    { feeling: "interested", causing: "interesting" },
    { feeling: "excited", causing: "exciting" },
    { feeling: "amused", causing: "amusing" },
    { feeling: "confused", causing: "confusing" },
    { feeling: "embarrassed", causing: "embarrassing" },
    { feeling: "frustrated", causing: "frustrating" },
    { feeling: "annoyed", causing: "annoying" },
    { feeling: "worried", causing: "worrying" },
    { feeling: "disappointed", causing: "disappointing" },
    { feeling: "depressed", causing: "depressing" },
    { feeling: "amazed", causing: "amazing" },
    { feeling: "satisfied", causing: "satisfying" },
    { feeling: "shocked", causing: "shocking" },
    { feeling: "thrilled", causing: "thrilling" },
    { feeling: "exhausted", causing: "exhausting" },
    { feeling: "fascinated", causing: "fascinating" },
    { feeling: "scared", causing: "scary" },
    { feeling: "relaxed", causing: "relaxing" },
    { feeling: "terrified", causing: "terrifying" },
    { feeling: "overwhelmed", causing: "overwhelming" },
    { feeling: "surprised", causing: "surprising" },
    { feeling: "disgusted", causing: "disgusting" },
    { feeling: "alarmed", causing: "alarming" },
    { feeling: "motivated", causing: "motivating" },
    { feeling: "discouraged", causing: "discouraging" },
    { feeling: "encouraged", causing: "encouraging" },
    { feeling: "challenged", causing: "challenging" },
    { feeling: "stimulated", causing: "stimulating" },
  ],

  notes: {
    ed: "Tính từ kết thúc bằng '-ed' thường mô tả cảm xúc của con người khi chịu tác động.",
    ing: "Tính từ kết thúc bằng '-ing' mô tả bản chất của sự vật/sự việc gây ra cảm xúc.",
  },

  usageTypes: [
    "Mô tả trạng thái cảm xúc của bản thân (I feel bored).",
    "Mô tả tính chất gây cảm xúc của sự việc (The lecture is boring).",
    "Diễn tả phản ứng cảm xúc trong quá khứ (I was shocked by the news).",
    "Mô tả tác động lâu dài (The experience was life-changing).",
    "Sử dụng trong câu điều kiện (If I were more relaxed, I would perform better).",
    "Kết hợp với các động từ khác (seem, appear, look, sound, etc.).",
  ],

  commonMistakes: [
    {
      mistake: "I'm boring in the class.",
      correction: "I'm bored in the class.",
      explanation:
        "'Boring' là tính chất của thứ gì đó, không phải cảm giác của người.",
      level: "A2",
    },
    {
      mistake: "The book was very bored.",
      correction: "The book was very boring.",
      explanation:
        "The book gây ra cảm giác → dùng 'boring', không phải 'bored'.",
      level: "A2",
    },
    {
      mistake: "She is very interesting in science.",
      correction: "She is very interested in science.",
      explanation: "Người có cảm giác về science → dùng 'interested'.",
      level: "B1",
    },
    {
      mistake: "The movie made me very exciting.",
      correction: "The movie made me very excited.",
      explanation: "Cảm giác của người xem → dùng 'excited'.",
      level: "B1",
    },
    {
      mistake: "I felt very confusing about the instructions.",
      correction: "I felt very confused about the instructions.",
      explanation: "Cảm giác cá nhân → dùng 'confused'.",
      level: "B1",
    },
    {
      mistake: "The lesson was very interested.",
      correction: "The lesson was very interesting.",
      explanation: "Tính chất của lesson → dùng 'interesting'.",
      level: "B1",
    },
    {
      mistake: "He is embarrassing about his mistake.",
      correction: "He is embarrassed about his mistake.",
      explanation: "Cảm giác của he → dùng 'embarrassed'.",
      level: "B2",
    },
    {
      mistake: "The news was very worried.",
      correction: "The news was very worrying.",
      explanation: "Tính chất của news gây lo lắng → dùng 'worrying'.",
      level: "B2",
    },
  ],

  grammarTips: [
    "Đừng nhầm lẫn giữa '-ed' và '-ing' - đây là lỗi phổ biến nhất.",
    "Chỉ dùng '-ed' cho người khi nói về cảm xúc cá nhân họ đang trải qua.",
    "Dùng '-ing' cho vật, sự việc, người gây ra cảm xúc cho người khác.",
    "Nhớ rằng: -ed = receiver of emotion, -ing = cause of emotion.",
    "Với tính từ không theo quy tắc (như 'afraid' thay vì 'afraided'), cần học thuộc lòng.",
    "Sử dụng ngữ cảnh để xác định đúng tính từ: ai/cái gì cảm thấy vs ai/cái gì gây ra cảm xúc.",
    "Chú ý các exception như 'scary' (không phải 'scaring') cho 'scared'.",
    "Trong văn viết học thuật, ưu tiên sử dụng các tính từ cảm xúc chính xác và trang trọng.",
    "Khi doubt, hãy tự hỏi: 'Who/what feels the emotion?' và 'Who/what causes the emotion?'",
    "Practice với real-life situations để internalize các patterns.",
  ],

  advancedPairs: [
    { feeling: "delighted", causing: "delightful" },
    { feeling: "saddened", causing: "saddening" },
    { feeling: "moved", causing: "moving" },
    { feeling: "touched", causing: "touching" },
    { feeling: "offended", causing: "offensive" },
    { feeling: "disturbed", causing: "disturbing" },
    { feeling: "tempted", causing: "tempting" },
    { feeling: "enchanted", causing: "enchanting" },
    { feeling: "inspired", causing: "inspiring" },
    { feeling: "fulfilled", causing: "fulfilling" },
  ],

  recognitionPatterns: {
    feeling: "Adj + -ed → feeling (e.g., tired, amazed)",
    causing: "Adj + -ing → causing (e.g., tiring, amazing)",
  },

  quizzes: [
    {
      question: "The movie was so _____ that I couldn't stop laughing.",
      options: ["amused", "amusing"],
      answer: "amusing",
      level: "A2",
      explanation: "Movie gây ra cảm xúc → dùng 'amusing'",
    },
    {
      question: "He looked really ____ after the long trip.",
      options: ["tired", "tiring"],
      answer: "tired",
      level: "A2",
      explanation: "He cảm thấy mệt → dùng 'tired'",
    },
    {
      question: "I find quantum physics absolutely ____.",
      options: ["fascinated", "fascinating"],
      answer: "fascinating",
      level: "B1",
      explanation:
        "Quantum physics có tính chất gây fascination → dùng 'fascinating'",
    },
    {
      question: "She was ____ by the unexpected news.",
      options: ["shocked", "shocking"],
      answer: "shocked",
      level: "B1",
      explanation: "She nhận cảm xúc từ news → dùng 'shocked'",
    },
  ],

  extraExamples: [
    {
      sentence: "The news was shocking.",
      type: "causing",
      level: "B1",
      context: "News report",
    },
    {
      sentence: "She was shocked by the news.",
      type: "feeling",
      level: "B1",
      context: "Personal reaction",
    },
    {
      sentence: "The exam was exhausting.",
      type: "causing",
      level: "B2",
      context: "Academic",
    },
    {
      sentence: "I felt exhausted after the exam.",
      type: "feeling",
      level: "B2",
      context: "Personal experience",
    },
    {
      sentence: "The speech was inspiring.",
      type: "causing",
      level: "B2",
      context: "Public speaking",
    },
    {
      sentence: "I felt inspired by the speech.",
      type: "feeling",
      level: "B2",
      context: "Audience reaction",
    },
    {
      sentence: "The performance was electrifying.",
      type: "causing",
      level: "C1",
      context: "Entertainment",
    },
    {
      sentence: "The audience was electrified.",
      type: "feeling",
      level: "C1",
      context: "Audience response",
    },
  ],

  learningTips: [
    "Khi mô tả cảm xúc của bản thân → dùng '-ed'.",
    "Khi mô tả điều gì gây ra cảm xúc → dùng '-ing'.",
    "Đọc nhiều ví dụ sẽ giúp phân biệt tự nhiên hơn.",
    "So sánh từng cặp để ghi nhớ sự khác biệt.",
    "Practice với real situations để develop intuition.",
    "Focus vào context: ai/cái gì là nguồn gốc của emotion?",
    "Sử dụng visual aids để remember patterns.",
    "Create personal examples với own experiences.",
    "Watch movies với subtitles để see usage in context.",
    "Keep emotion diary bằng tiếng Anh để practice daily.",
  ],

  references: [
    {
      title: "English Grammar in Use",
      author: "Raymond Murphy",
      publisher: "Cambridge University Press",
      type: "book",
      relevantChapters: [
        "Unit 98: Adjectives ending in -ing and -ed",
        "Unit 99: Adjectives: word order",
      ],
    },
    {
      title: "Practical English Usage",
      author: "Michael Swan",
      publisher: "Oxford University Press",
      type: "book",
      relevantChapters: [
        "Adjectives: position and order",
        "Participle adjectives",
      ],
    },
    {
      title: "Oxford Advanced Learner's Dictionary",
      publisher: "Oxford University Press",
      url: "https://www.oxfordlearnersdictionaries.com/",
      type: "dictionary",
      relevantChapters: [
        "Emotion adjectives section",
        "Usage notes on -ed/-ing adjectives",
      ],
    },
    {
      title: "Cambridge English Grammar",
      author: "Ronald Carter, Michael McCarthy",
      publisher: "Cambridge University Press",
      type: "book",
      relevantChapters: [
        "Chapter 15: Adjectives and adjective phrases",
        "Participle adjectives",
      ],
    },
    {
      title: "BBC Learning English - Grammar",
      url: "https://www.bbc.co.uk/learningenglish/english/grammar",
      type: "website",
      relevantChapters: [
        "Adjectives ending -ed and -ing",
        "Emotion vocabulary",
      ],
    },
    {
      title: "Longman Grammar of Spoken and Written English",
      author:
        "Douglas Biber, Stig Johansson, Geoffrey Leech, Susan Conrad, Edward Finegan",
      publisher: "Longman",
      type: "academic",
      relevantChapters: [
        "Chapter 7: Adjectives and adverbs",
        "Participial adjectives",
      ],
    },
    {
      title: "Collins COBUILD English Grammar",
      publisher: "Collins",
      type: "book",
      relevantChapters: ["Section 3.4: Adjectives", "Emotion and feeling"],
    },
    {
      title: "Merriam-Webster Online Dictionary",
      url: "https://www.merriam-webster.com/",
      type: "website",
      relevantChapters: ["Usage notes", "Grammar explanations"],
    },
  ],

  advancedEmotionPairs: [
    { feeling: "disillusioned", causing: "disillusioning" },
    { feeling: "bewildered", causing: "bewildering" },
    { feeling: "intimidated", causing: "intimidating" },
    { feeling: "appalled", causing: "appalling" },
    { feeling: "aghast", causing: "ghastly" },
    { feeling: "flattered", causing: "flattering" },
    { feeling: "overjoyed", causing: "joyful" },
    { feeling: "startled", causing: "startling" },
    { feeling: "devastated", causing: "devastating" },
    { feeling: "enchanted", causing: "enchanting" },
    { feeling: "mesmerized", causing: "mesmerizing" },
    { feeling: "captivated", causing: "captivating" },
    { feeling: "stupefied", causing: "stupefying" },
    { feeling: "mortified", causing: "mortifying" },
    { feeling: "exhilarated", causing: "exhilarating" },
  ],

  idiomaticUsage: [
    {
      idiom: "I was floored by the news.",
      meaning: "I was extremely shocked.",
      type: "feeling",
      level: "C1",
      context: "Informal conversation",
    },
    {
      idiom: "His words were cutting and demoralizing.",
      meaning: "His words caused pain and reduced morale.",
      type: "causing",
      level: "C1",
      context: "Formal/literary",
    },
    {
      idiom: "The speech left me spellbound.",
      meaning: "The speech was so amazing that I was captivated.",
      type: "causing",
      level: "C1",
      context: "Literary/academic",
    },
    {
      idiom: "She was beside herself with worry.",
      meaning: "She was extremely worried.",
      type: "feeling",
      level: "C1",
      context: "Informal",
    },
    {
      idiom: "The performance was absolutely riveting.",
      meaning: "The performance was completely captivating.",
      type: "causing",
      level: "C2",
      context: "Formal review",
    },
  ],

  rarePatterns: [
    {
      structure: "It + be + [emotion-causing adjective] + that + clause",
      example: "It's terrifying that the storm is getting worse.",
      level: "B2",
      usage: "Formal writing, news reports",
    },
    {
      structure: "[emotion-causing adjective] + as + clause",
      example: "Interesting as it may seem, he never actually graduated.",
      level: "C1",
      usage: "Academic writing, formal speech",
    },
    {
      structure: "To feel + [emotion adjective] + about + noun/gerund",
      example: "She felt overwhelmed about the exam results.",
      level: "B2",
      usage: "Personal reflection, counseling",
    },
    {
      structure: "What + be + [emotion-causing adj] + be + clause",
      example: "What was fascinating was how he solved the problem.",
      level: "C1",
      usage: "Analytical writing",
    },
  ],

  comparativeUsage: [
    {
      structure: "S + find + O + [emotion-causing adj]",
      example: "He found the instructions confusing.",
      level: "B1",
      context: "Opinion expression",
    },
    {
      structure: "S + make + O + feel + [feeling adj]",
      example: "The film made her feel uplifted.",
      level: "B2",
      context: "Causative constructions",
    },
    {
      structure: "S + consider + O + [emotion-causing adj]",
      example: "Many considered the proposal alarming.",
      level: "B2",
      context: "Formal evaluation",
    },
    {
      structure: "S + strike + O + as + [emotion-causing adj]",
      example: "His behavior struck me as disturbing.",
      level: "C1",
      context: "Subjective impression",
    },
  ],

  emotionChains: [
    {
      sentence:
        "She was deeply moved by the touching story, which left her inspired and grateful.",
      explanation:
        "Một chuỗi cảm xúc bắt đầu từ 'touching' (gây cảm xúc) → 'moved' (bị tác động) → tiếp tục 'inspired' & 'grateful' (trạng thái sau cùng).",
      level: "B2",
    },
    {
      sentence:
        "The overwhelming situation became increasingly frustrating, leaving everyone exhausted and demoralized.",
      explanation:
        "Chuỗi từ tình huống gây áp lực đến kết quả cảm xúc tiêu cực cho mọi người.",
      level: "C1",
    },
    {
      sentence:
        "His mesmerizing performance was so captivating that the audience remained spellbound and utterly transfixed.",
      explanation:
        "Chuỗi mô tả tác động mạnh mẽ từ performance đến audience reaction.",
      level: "C2",
    },
  ],

  academicAnalysis: {
    explanation:
      "Trong ngữ pháp tiếng Anh, tính từ dạng '-ed' thường đóng vai trò là **participle adjectives** thể hiện kết quả cảm xúc, trong khi '-ing' là **causative adjectives** thể hiện tác nhân. Đây là dạng chuyển hóa từ phân từ hiện tại & quá khứ sang tính từ.",
    example:
      "'Surprised' là quá khứ phân từ của 'surprise', nhưng khi dùng như adjective thì đóng vai trò mô tả người nhận cảm xúc.",
    linguisticTerms: [
      "Participle adjectives",
      "Causative adjectives",
      "Semantic roles",
      "Agent vs. Patient",
      "Grammaticalization",
    ],
    references: [
      "Quirk, R. et al. A Comprehensive Grammar of the English Language",
      "Huddleston, R. & Pullum, G. K. The Cambridge Grammar of the English Language",
    ],
  },

  suffixExceptions: [
    {
      suffix: "ful",
      note: "Một số tính từ không theo đuôi -ing nhưng vẫn có tác dụng gây cảm xúc",
      pairs: [
        { feeling: "touched", causing: "touching" },
        { feeling: "grateful", causing: "gratifying" },
        { feeling: "encouraged", causing: "encouraging" },
        { feeling: "motivated", causing: "motivating" },
      ],
    },
    {
      suffix: "y",
      note: "Một số tính từ dùng đuôi -y thay vì -ing",
      pairs: [
        { feeling: "scared", causing: "scary" },
        { feeling: "worried", causing: "worrying" },
        { feeling: "annoyed", causing: "annoying" },
      ],
    },
  ],

  errorPatterns: [
    {
      error: "He is confusing about the instructions.",
      correction: "He is confused about the instructions.",
      explanation:
        "Người nhận cảm xúc → dùng 'confused', không phải 'confusing'.",
      level: "B1",
      frequency: "common",
    },
    {
      error: "The result was very satisfied.",
      correction: "The result was very satisfying.",
      explanation: "'Result' là tác nhân gây cảm xúc → dùng 'satisfying'.",
      level: "B2",
      frequency: "common",
    },
    {
      error: "I am very interesting in this topic.",
      correction: "I am very interested in this topic.",
      explanation: "Subject có feeling về topic → dùng 'interested'.",
      level: "B1",
      frequency: "common",
    },
    {
      error: "The movie was very excited.",
      correction: "The movie was very exciting.",
      explanation: "Movie gây ra excitement → dùng 'exciting'.",
      level: "B1",
      frequency: "occasional",
    },
  ],

  speakingTips: [
    "Sử dụng -ed để mô tả cảm xúc khi nói về bản thân trong IELTS Speaking Part 2.",
    "Dùng -ing để mô tả trải nghiệm trong Speaking Part 3 (e.g., 'It was a fascinating experience').",
    "Combine emotion adjectives với adverbs để tăng expressiveness (extremely excited, utterly exhausted).",
    "Use emotion adjectives trong storytelling để make more engaging.",
    "Practice intonation với emotion words để convey feelings effectively.",
    "Learn emotion collocations để sound more natural (deeply moved, thoroughly confused).",
  ],

  writingTips: [
    "Trong IELTS Writing Task 2, dùng -ing để nói về hiện tượng gây ra tác động (e.g., 'This trend is worrying').",
    "Dùng -ed để thể hiện lập trường cá nhân (e.g., 'I am concerned about this issue').",
    "Vary emotion vocabulary để avoid repetition trong academic writing.",
    "Use emotion adjectives trong conclusion để strengthen impact.",
    "Combine với hedging language khi appropriate (somewhat concerned, rather disappointing).",
    "Use emotion adjectives trong narrative writing để create atmosphere.",
  ],

  collocations: [
    {
      adj: "alarming",
      collocatesWith: ["trend", "increase", "news", "situation", "rate"],
      level: "B2",
    },
    {
      adj: "thrilled",
      collocatesWith: ["to bits", "beyond words", "by the result", "to pieces"],
      level: "B2",
    },
    {
      adj: "devastated",
      collocatesWith: ["by the loss", "emotionally", "utterly", "completely"],
      level: "C1",
    },
    {
      adj: "fascinating",
      collocatesWith: ["topic", "idea", "culture", "world", "subject"],
      level: "B2",
    },
    {
      adj: "overwhelming",
      collocatesWith: ["response", "support", "evidence", "majority"],
      level: "C1",
    },
    {
      adj: "mortified",
      collocatesWith: ["absolutely", "utterly", "completely", "deeply"],
      level: "C1",
    },
  ],

  referencePhrases: [
    "I found it extremely... (e.g., frustrating).",
    "What I found most... was... (e.g., inspiring was her attitude).",
    "It made me feel... (e.g., empowered, appreciated).",
    "The thing that struck me as... was...",
    "I was particularly... by...",
    "What came across as... was...",
    "I couldn't help feeling... when...",
    "It left me feeling... about...",
  ],

  detailedLevelBreakdown: {
    A1: {
      coreAdjectives: [
        "happy",
        "sad",
        "angry",
        "tired",
        "scared",
        "good",
        "bad",
      ],
      basicPatterns: ["I am happy", "She is sad", "We are tired"],
      essentialConcepts: [
        "Basic emotions vocabulary",
        "Simple 'be' constructions",
        "Positive vs negative feelings",
      ],
      practiceActivities: [
        "Match emotions to faces",
        "Complete simple sentences",
        "Describe own feelings",
      ],
    },
    A2: {
      expandedVocabulary: [
        "excited",
        "bored",
        "interested",
        "worried",
        "surprised",
        "relaxed",
      ],
      introductoryPairs: [
        { feeling: "bored", causing: "boring" },
        { feeling: "interested", causing: "interesting" },
        { feeling: "excited", causing: "exciting" },
      ],
      basicDistinctions: [
        "Introduction to -ed vs -ing",
        "Person feels vs thing causes",
        "Basic context recognition",
      ],
      commonSituations: [
        "Talking about movies and books",
        "Describing school subjects",
        "Weekend activities",
      ],
    },
    B1: {
      intermediateAdjectives: [
        "frustrated",
        "amazing",
        "disappointing",
        "thrilled",
        "exhausting",
        "fascinating",
      ],
      patternRecognition: [
        "Consistent use of -ed/-ing",
        "Recognition in context",
        "Error correction ability",
      ],
      contextualUsage: [
        "Workplace emotions",
        "Travel experiences",
        "Learning situations",
      ],
      communicativeActivities: [
        "Describe past experiences",
        "Give opinions about topics",
        "Express reactions to news",
      ],
    },
    B2: {
      advancedVocabulary: [
        "overwhelming",
        "bewildering",
        "inspiring",
        "devastating",
        "uplifting",
        "demoralizing",
      ],
      nuancedDistinctions: [
        "Subtle meaning differences",
        "Register awareness",
        "Collocation patterns",
      ],
      complexPatterns: [
        "It + be + adj + that clauses",
        "Find/consider + obj + adj",
        "Make + feel constructions",
      ],
      academicUsage: [
        "Essay writing",
        "Formal presentations",
        "Academic discussions",
      ],
    },
    C1: {
      sophisticatedAdjectives: [
        "exhilarating",
        "mortifying",
        "stupefying",
        "riveting",
        "harrowing",
        "electrifying",
      ],
      subtleDistinctions: [
        "Connotative differences",
        "Stylistic variation",
        "Cultural nuances",
      ],
      advancedPatterns: [
        "Participial constructions",
        "Cleft sentences with emotions",
        "Inversion with emotion adverbs",
      ],
      professionalUsage: [
        "Business communication",
        "Academic writing",
        "Professional presentations",
      ],
    },
    C2: {
      masterLevelAdjectives: [
        "stupendous",
        "transcendent",
        "sublime",
        "ineffable",
        "poignant",
        "visceral",
      ],
      expertUsage: [
        "Literary applications",
        "Creative expression",
        "Sophisticated analysis",
      ],
      linguisticAwareness: [
        "Etymology understanding",
        "Cross-linguistic influences",
        "Historical development",
      ],
      nativelikeExpressions: [
        "Idiomatic combinations",
        "Creative metaphorical use",
        "Style variation mastery",
      ],
    },
  },
};