import { transitiveIntransitiveVerbsType } from "@/types/grammars/grammar/verb_special/transitiveIntransitive_verbs";

export const transitiveIntransitiveVerbsData: transitiveIntransitiveVerbsType =
  {
    topic: "Transitive vs. Intransitive Verbs",
    levels: ["A1", "A2", "B1", "B2", "C1", "C2"],
    definitions: {
      transitive:
        "A transitive verb is a verb that requires a direct object to complete its meaning. The action passes from the subject to the object.",
      intransitive:
        "An intransitive verb does not take a direct object; the meaning is complete without one. The action does not pass to any object.",
      ditransitive:
        "A verb that takes both a direct object and an indirect object (give, send, tell, show).",
      complexTransitive:
        "A verb that requires a direct object and an object complement to complete its meaning (make, call, consider).",
      linking:
        "Verbs that connect the subject to a subject complement rather than showing action (be, seem, become).",
    },

    levelProgression: {
      A1: {
        learningObjectives: [
          "Recognize basic transitive verbs that need an object (eat, drink, see)",
          "Identify simple intransitive verbs that don't need objects (go, come, sleep)",
          "Use common daily life verbs correctly in simple sentences",
          "Understand the difference between 'I eat' vs 'I eat food'",
        ],
        coreVerbs: {
          transitive: [
            "eat",
            "drink",
            "see",
            "watch",
            "like",
            "love",
            "want",
            "need",
            "have",
            "buy",
          ],
          intransitive: [
            "go",
            "come",
            "sleep",
            "walk",
            "run",
            "sit",
            "stand",
            "cry",
            "laugh",
            "die",
          ],
          dual: ["read", "write", "sing", "play", "work"],
        },
        basicPatterns: [
          "Subject + Verb + Object (I eat food)",
          "Subject + Verb (I sleep)",
          "Subject + Verb + Adverb (I walk slowly)",
        ],
        commonMistakes: [
          "❌ I go to home → ✅ I go home",
          "❌ I like → ✅ I like chocolate",
          "❌ He sleep → ✅ He sleeps",
        ],
        keyPoints: [
          "Some verbs always need something after them",
          "Some verbs can stand alone",
          "Ask 'what?' after the verb to check if it needs an object",
        ],
      },
      A2: {
        learningObjectives: [
          "Use more complex transitive verbs with confidence",
          "Recognize when the same verb can be both transitive and intransitive",
          "Form basic passive voice with simple transitive verbs",
          "Use prepositions correctly with intransitive verbs",
        ],
        coreVerbs: {
          transitive: [
            "bring",
            "take",
            "give",
            "send",
            "tell",
            "ask",
            "teach",
            "learn",
            "find",
            "lose",
          ],
          intransitive: [
            "arrive",
            "happen",
            "exist",
            "appear",
            "disappear",
            "wait",
            "travel",
            "stay",
          ],
          dual: ["start", "stop", "open", "close", "change", "move"],
        },
        patterns: [
          "Subject + Verb + Object + Preposition + Object (I put the book on the table)",
          "Subject + Verb + Preposition + Object (I wait for the bus)",
          "Object + be + past participle (The door was opened)",
        ],
        commonMistakes: [
          "❌ I arrived to the station → ✅ I arrived at the station",
          "❌ I wait the bus → ✅ I wait for the bus",
          "❌ He explained me → ✅ He explained to me",
        ],
        keyPoints: [
          "Intransitive verbs often use prepositions",
          "Some verbs change meaning when they're transitive vs intransitive",
          "Passive voice only works with transitive verbs",
        ],
      },
      B1: {
        learningObjectives: [
          "Master ergative verbs that can be both transitive and intransitive",
          "Understand causative structures with transitive verbs",
          "Use phrasal verbs correctly (transitive vs intransitive)",
          "Recognize subtle differences in meaning with dual-usage verbs",
        ],
        coreVerbs: {
          transitive: [
            "develop",
            "create",
            "destroy",
            "build",
            "repair",
            "fix",
            "complete",
            "achieve",
          ],
          intransitive: [
            "grow",
            "improve",
            "succeed",
            "fail",
            "occur",
            "remain",
            "continue",
            "proceed",
          ],
          dual: [
            "break",
            "burn",
            "drop",
            "increase",
            "decrease",
            "develop",
            "improve",
          ],
          ergative: ["boil", "melt", "freeze", "cook", "sink", "float", "hang"],
        },
        patterns: [
          "Causative: Subject + make/let/have + Object + Verb",
          "Ergative: The subject causes (She melted the chocolate) vs The action happens (The chocolate melted)",
          "Phrasal verbs: turn on (transitive) vs turn up (intransitive)",
        ],
        commonMistakes: [
          "❌ The water is boiling by me → ✅ I am boiling the water",
          "❌ He made me to go → ✅ He made me go",
          "❌ I turned up the volume up → ✅ I turned up the volume",
        ],
        keyPoints: [
          "Ergative verbs show whether something happens naturally or is caused",
          "Causative verbs always need an object and another verb",
          "Phrasal verbs can completely change their transitivity",
        ],
      },
      B2: {
        learningObjectives: [
          "Master ditransitive verbs (verbs with two objects)",
          "Use complex sentence structures with embedded clauses",
          "Understand register differences in verb choice",
          "Manipulate voice and focus in complex sentences",
        ],
        coreVerbs: {
          transitive: [
            "accomplish",
            "establish",
            "demonstrate",
            "illustrate",
            "constitute",
            "comprise",
          ],
          intransitive: [
            "emerge",
            "evolve",
            "deteriorate",
            "flourish",
            "persist",
            "prevail",
          ],
          dual: [
            "expand",
            "contract",
            "extend",
            "reduce",
            "transform",
            "convert",
          ],
          ergative: [
            "dissolve",
            "evaporate",
            "condense",
            "crystallize",
            "solidify",
          ],
          ditransitive: [
            "give",
            "send",
            "tell",
            "show",
            "teach",
            "offer",
            "promise",
            "deny",
          ],
        },
        patterns: [
          "Ditransitive: Subject + Verb + Indirect Object + Direct Object",
          "Complex transitive: Subject + Verb + Object + Complement",
          "Cleft sentences: It was the book that he read (focus on object)",
        ],
        commonMistakes: [
          "❌ He said me the truth → ✅ He told me the truth",
          "❌ She explained me the problem → ✅ She explained the problem to me",
          "❌ I consider him as intelligent → ✅ I consider him intelligent",
        ],
        keyPoints: [
          "Ditransitive verbs can often be restructured with prepositions",
          "Some verbs require specific prepositions in their intransitive form",
          "Object complements complete the meaning of complex transitive verbs",
        ],
      },
      C1: {
        learningObjectives: [
          "Master complex transitive verbs with object complements",
          "Use sophisticated ergative and causative constructions",
          "Employ stylistic variation through voice manipulation",
          "Understand semantic subtleties in verb transitivity",
        ],
        coreVerbs: {
          transitive: [
            "substantiate",
            "corroborate",
            "vindicate",
            "consolidate",
            "perpetuate",
            "facilitate",
          ],
          intransitive: [
            "culminate",
            "emanate",
            "permeate",
            "proliferate",
            "predominate",
            "deteriorate",
          ],
          dual: [
            "accelerate",
            "decelerate",
            "fluctuate",
            "oscillate",
            "alternate",
            "rotate",
          ],
          ergative: [
            "disintegrate",
            "decompose",
            "coagulate",
            "precipitate",
            "sublimate",
          ],
          ditransitive: [
            "accord",
            "afford",
            "allot",
            "assign",
            "attribute",
            "credit",
          ],
          complexTransitive: [
            "render",
            "deem",
            "designate",
            "proclaim",
            "declare",
            "appoint",
          ],
        },
        patterns: [
          "Complex passive: The decision was deemed inappropriate by the committee",
          "Ergative with cause: The heat disintegrated the material vs The material disintegrated",
          "Formal register: The data substantiates our hypothesis",
        ],
        commonMistakes: [
          "❌ The theory was proven by evidence → ✅ The evidence proved the theory",
          "❌ He was appointed as director → ✅ He was appointed director",
          "❌ The committee decided him guilty → ✅ The committee found him guilty",
        ],
        keyPoints: [
          "Many formal verbs have specific transitivity requirements",
          "Object complements often don't require articles or prepositions",
          "Academic writing favors specific transitive constructions",
        ],
      },
      C2: {
        learningObjectives: [
          "Master pseudo-transitive and exceptional constructions",
          "Use sophisticated stylistic devices involving transitivity",
          "Understand historical and dialectical variations",
          "Manipulate transitivity for rhetorical effect",
        ],
        coreVerbs: {
          transitive: [
            "exemplify",
            "epitomize",
            "incarnate",
            "personify",
            "characterize",
            "typify",
          ],
          intransitive: [
            "materialize",
            "crystallize",
            "manifest",
            "transpire",
            "ensue",
            "supersede",
          ],
          dual: [
            "metamorphose",
            "transfigure",
            "transmute",
            "transpose",
            "extrapolate",
          ],
          ergative: [
            "amalgamate",
            "coalesce",
            "congeal",
            "liquefy",
            "vaporize",
          ],
          ditransitive: ["bequeath", "bestow", "confer", "impart", "vouchsafe"],
          complexTransitive: [
            "constitute",
            "represent",
            "signify",
            "symbolize",
            "embody",
          ],
          pseudo: ["resemble", "equal", "cost", "weigh", "measure", "last"],
        },
        patterns: [
          "Pseudo-transitive: He resembles his father (father is not a true object)",
          "Stylistic passive: By whom was this decision made? (formal questioning)",
          "Historical present: Shakespeare writes Hamlet in 1600 (narrative style)",
        ],
        commonMistakes: [
          "❌ This equals to that → ✅ This equals that",
          "❌ The book costs to me $20 → ✅ The book costs me $20",
          "❌ He was resembled by his father → ✅ He resembled his father",
        ],
        keyPoints: [
          "Pseudo-transitive verbs appear transitive but behave differently",
          "Some constructions resist passivization despite appearing transitive",
          "Register and style affect acceptable transitivity patterns",
        ],
      },
    },
    keyCharacteristics: {
      transitive: [
        "Requires a direct object (noun or pronoun) to receive the action.",
        "Answers the question 'what?' or 'whom?' after the verb.",
        "Cannot stand alone without an object.",
      ],
      intransitive: [
        "Does not require a direct object.",
        "Often followed by an adverb, prepositional phrase, or nothing at all.",
        "Answers questions like 'how?', 'when?', 'where?'",
      ],
    },
    structurePatterns: {
      transitive: "Subject + Verb + Direct Object",
      intransitive: "Subject + Verb (+ Adverbial/Prepositional Phrase)",
    },
    transitive_intransitive_verbs_vocab: {
      transitive_verbs: [
        "want",
        "need",
        "like",
        "love",
        "hate",
        "prefer",
        "buy",
        "make",
        "bring",
        "take",
        "give",
        "send",
        "tell",
        "ask",
        "offer",
        "eat",
        "drink",
        "see",
        "watch",
        "know",
        "remember",
        "forget",
        "understand",
        "use",
        "open",
        "close",
        "start",
        "finish",
        "move (sth)",
        "build",
        "fix",
        "repair",
      ],

      intransitive_verbs: [
        "arrive",
        "go",
        "come",
        "exist",
        "happen",
        "occur",
        "fall",
        "sleep",
        "sit",
        "stand",
        "wait",
        "stay",
        "cry",
        "laugh",
        "die",
        "live",
        "swim",
        "run",
        "jump",
        "sneeze",
        "travel",
        "fade",
        "remain",
        "appear",
        "disappear",
      ],

      dual_usage_verbs: [
        "read",
        "write",
        "eat",
        "study",
        "sing",
        "play",
        "change",
        "begin",
        "start",
        "stop",
        "move",
        "burn",
        "drop",
        "boil",
        "increase",
        "decrease",
        "grow",
        "turn",
        "open",
        "close",
        "break",
        "melt",
        "ring",
        "finish",
      ],

      structure_patterns: {
        transitive: "Subject + Verb + Object",
        intransitive: "Subject + Verb",
        dual: [
          "He opened the door. (Transitive)",
          "The door opened. (Intransitive)",
          "She broke the glass. (T)",
          "The glass broke. (I)",
        ],
      },

      ce_fr_levels: {
        A1_A2: {
          transitive: [
            "want",
            "need",
            "like",
            "love",
            "hate",
            "buy",
            "eat",
            "drink",
            "see",
            "watch",
            "have",
            "get",
            "put",
            "take",
            "give",
            "make",
            "wear",
            "use",
            "help",
            "know",
          ],
          intransitive: [
            "go",
            "come",
            "arrive",
            "sleep",
            "cry",
            "laugh",
            "walk",
            "run",
            "sit",
            "stand",
            "wait",
            "stay",
            "travel",
            "jump",
            "fall",
            "die",
          ],
          dual: [
            "read",
            "write",
            "play",
            "start",
            "stop",
            "work",
            "sing",
            "dance",
            "cook",
            "clean",
          ],
        },
        B1_B2: {
          transitive: [
            "explain",
            "describe",
            "build",
            "send",
            "repair",
            "develop",
            "create",
            "destroy",
            "achieve",
            "complete",
            "establish",
            "demonstrate",
            "accomplish",
            "illustrate",
            "expand",
            "reduce",
          ],
          intransitive: [
            "appear",
            "disappear",
            "happen",
            "exist",
            "occur",
            "remain",
            "continue",
            "proceed",
            "emerge",
            "evolve",
            "deteriorate",
            "flourish",
            "persist",
            "prevail",
          ],
          dual: [
            "move",
            "burn",
            "open",
            "close",
            "break",
            "change",
            "increase",
            "decrease",
            "improve",
            "grow",
            "develop",
            "transform",
            "convert",
            "boil",
            "melt",
            "freeze",
          ],
        },
        C1_C2: {
          transitive: [
            "acknowledge",
            "convey",
            "justify",
            "undertake",
            "substantiate",
            "corroborate",
            "vindicate",
            "consolidate",
            "perpetuate",
            "facilitate",
            "exemplify",
            "epitomize",
            "characterize",
            "constitute",
            "represent",
          ],
          intransitive: [
            "linger",
            "vanish",
            "commence",
            "reside",
            "culminate",
            "emanate",
            "permeate",
            "proliferate",
            "predominate",
            "materialize",
            "crystallize",
            "manifest",
            "transpire",
            "ensue",
            "supersede",
          ],
          dual: [
            "increase",
            "decrease",
            "develop",
            "alter",
            "collapse",
            "accelerate",
            "fluctuate",
            "oscillate",
            "alternate",
            "metamorphose",
            "transmute",
            "amalgamate",
            "coalesce",
            "disintegrate",
            "sublimate",
          ],
        },
      },
      common_mistakes: [
        "❌ He explained me the problem. → ✅ He explained the problem to me.",
        "❌ She arrived the station. → ✅ She arrived **at** the station.",
        "❌ I waited the bus. → ✅ I waited **for** the bus.",
        "❌ Please turn on. → ✅ Please turn on **the light**.",
        "❌ She enjoys very much. → ✅ She enjoys **it** very much.",
        "❌ The water is boiling by me. → ✅ **I am boiling** the water.",
        "❌ I consider him as intelligent. → ✅ I consider him intelligent.",
        "❌ This equals to that. → ✅ This equals that.",
        "❌ He made me to go. → ✅ He made me go.",
        "❌ The station was arrived by her. → ✅ She arrived at the station.",
      ],
    },
    examples: {
      transitive: [
        "She **reads** a book.",
        "They **watch** movies every weekend.",
        "He **kicked** the ball.",
        "We **need** more time.",
      ],
      intransitive: [
        "He **sleeps** peacefully.",
        "The baby **cried** loudly.",
        "They **arrived** late.",
        "She **runs** every morning.",
      ],
    },
    dualUsageVerbs: {
      description:
        "Some verbs can be both transitive and intransitive depending on how they are used.",
      examples: [
        {
          verb: "run",
          transitive: "She **ran** the company efficiently.",
          intransitive: "He **runs** every day.",
        },
        {
          verb: "open",
          transitive: "She **opened** the door.",
          intransitive: "The door **opened** slowly.",
        },
        {
          verb: "break",
          transitive: "He **broke** the glass.",
          intransitive: "The glass **broke** easily.",
        },
        {
          verb: "change",
          transitive: "She **changed** her clothes.",
          intransitive: "The weather **changed** suddenly.",
        },
      ],
    },
    advancedUsage: {
      causative: {
        explanation:
          "In transitive use, the subject causes the object to perform an action.",
        example: "The teacher **made** the students write essays.",
      },
      ergativeVerbs: {
        description:
          "Verbs that are transitive when the subject causes the action, but intransitive when the action happens by itself.",
        examples: [
          {
            verb: "boil",
            transitive: "She **boiled** the water.",
            intransitive: "The water **boiled** quickly.",
          },
          {
            verb: "melt",
            transitive: "The sun **melted** the ice.",
            intransitive: "The ice **melted** slowly.",
          },
          {
            verb: "dissolve",
            transitive: "She **dissolved** the sugar in water.",
            intransitive: "The sugar **dissolved** completely.",
          },
          {
            verb: "freeze",
            transitive: "The cold weather **froze** the lake.",
            intransitive: "The lake **froze** overnight.",
          },
        ],
      },
      passiveVoice: {
        applicable: "Only to transitive verbs.",
        example: "The cake was **eaten** by the child.",
      },
      ditransitiveVerbs: {
        description:
          "Verbs that take both direct and indirect objects, or can be restructured with prepositions.",
        examples: [
          "She gave him a book. / She gave a book to him.",
          "They sent me a letter. / They sent a letter to me.",
          "He told us the story. / He told the story to us.",
          "She showed them the way. / She showed the way to them.",
        ],
      },
      complexTransitiveVerbs: {
        description:
          "Verbs that require a direct object and an object complement to complete the meaning.",
        examples: [
          "They elected her president.",
          "He painted the wall blue.",
          "She made him happy.",
          "We consider them friends.",
          "The committee appointed him chairman.",
        ],
      },
    },
    timeMarkers: {
      transitive: ["always", "often", "every day", "yesterday", "last week"],
      intransitive: ["suddenly", "quickly", "late", "soon", "now"],
    },
    recognitionTips: {
      transitive: [
        "Check if there's a direct object receiving the action.",
        "Ask 'what?' or 'whom?' after the verb.",
      ],
      intransitive: [
        "Check if the verb stands alone or is followed by an adverb/preposition.",
        "Ask 'how?', 'when?', or 'where?' after the verb.",
      ],
    },
    commonMistakes: [
      {
        mistake: "Using an intransitive verb with a direct object.",
        wrong: "She arrived the station.",
        correct: "She arrived at the station.",
      },
      {
        mistake: "Leaving out the object for a transitive verb.",
        wrong: "He borrowed.",
        correct: "He borrowed a pen.",
      },
      {
        mistake: "Confusing transitive and intransitive phrasal verbs.",
        wrong: "Please turn on.",
        correct: "Please turn on the light.",
      },
      {
        mistake: "Using wrong preposition with intransitive verbs.",
        wrong: "I wait the bus.",
        correct: "I wait for the bus.",
      },
      {
        mistake: "Incorrect ditransitive verb structure.",
        wrong: "He explained me the problem.",
        correct: "He explained the problem to me.",
      },
      {
        mistake: "Using transitive verb without required object.",
        wrong: "She enjoys very much.",
        correct: "She enjoys it very much.",
      },
      {
        mistake: "Confusing ergative verb usage.",
        wrong: "The water is boiling by me.",
        correct: "I am boiling the water.",
      },
      {
        mistake: "Incorrect passive formation with intransitive verbs.",
        wrong: "The station was arrived by her.",
        correct: "She arrived at the station.",
      },
      {
        mistake: "Wrong structure with complex transitive verbs.",
        wrong: "I consider him as intelligent.",
        correct: "I consider him intelligent.",
      },
      {
        mistake: "Incorrect use of pseudo-transitive verbs.",
        wrong: "This equals to that.",
        correct: "This equals that.",
      },
    ],
    verbLists: {
      transitiveVerbs: [
        // A1-A2 Level
        "make",
        "need",
        "want",
        "love",
        "buy",
        "see",
        "hear",
        "invite",
        "teach",
        "ask",
        "take",
        "bring",
        "give",
        "borrow",
        "carry",
        "eat",
        "drink",
        "watch",
        "like",
        "have",
        "get",
        "put",
        "wear",
        "use",
        "help",
        // B1-B2 Level
        "develop",
        "create",
        "destroy",
        "build",
        "repair",
        "fix",
        "complete",
        "achieve",
        "establish",
        "demonstrate",
        "accomplish",
        "illustrate",
        "constitute",
        "comprise",
        "expand",
        "reduce",
        "transform",
        "convert",
        // C1-C2 Level
        "substantiate",
        "corroborate",
        "vindicate",
        "consolidate",
        "perpetuate",
        "facilitate",
        "exemplify",
        "epitomize",
        "incarnate",
        "personify",
        "characterize",
        "typify",
        "constitute",
        "represent",
        "signify",
        "symbolize",
        "embody",
      ],
      intransitiveVerbs: [
        // A1-A2 Level
        "go",
        "arrive",
        "sleep",
        "cry",
        "happen",
        "exist",
        "come",
        "jump",
        "fall",
        "die",
        "appear",
        "sneeze",
        "run",
        "swim",
        "work",
        "walk",
        "sit",
        "stand",
        "laugh",
        "travel",
        "stay",
        "wait",
        // B1-B2 Level
        "grow",
        "improve",
        "succeed",
        "fail",
        "occur",
        "remain",
        "continue",
        "proceed",
        "emerge",
        "evolve",
        "deteriorate",
        "flourish",
        "persist",
        "prevail",
        "culminate",
        "emanate",
        // C1-C2 Level
        "permeate",
        "proliferate",
        "predominate",
        "materialize",
        "crystallize",
        "manifest",
        "transpire",
        "ensue",
        "supersede",
        "disintegrate",
        "decompose",
        "coagulate",
        "precipitate",
        "sublimate",
      ],
      dualVerbs: [
        // A1-A2 Level
        "run",
        "start",
        "open",
        "close",
        "break",
        "change",
        "move",
        "grow",
        "stop",
        "drop",
        "burn",
        "sink",
        "read",
        "write",
        "sing",
        "play",
        "work",
        // B1-B2 Level
        "increase",
        "decrease",
        "develop",
        "improve",
        "expand",
        "contract",
        "extend",
        "reduce",
        "transform",
        "convert",
        "boil",
        "melt",
        "freeze",
        "cook",
        "hang",
        "float",
        // C1-C2 Level
        "accelerate",
        "decelerate",
        "fluctuate",
        "oscillate",
        "alternate",
        "rotate",
        "metamorphose",
        "transfigure",
        "transmute",
        "transpose",
        "extrapolate",
        "amalgamate",
        "coalesce",
        "congeal",
        "liquefy",
        "vaporize",
      ],
    },
    learningTips: [
      "Use a comprehensive dictionary (Oxford, Cambridge, Longman) to check verb transitivity patterns and example sentences.",
      "Practice with verbs in authentic contexts from news articles, academic texts, and literature to understand natural usage.",
      "Create your own sentence pairs: 'The door opened' (intransitive) vs 'She opened the door' (transitive).",
      "Learn common prepositions that follow intransitive verbs: arrive at, wait for, listen to, look at.",
      "Study phrasal verbs systematically as their transitivity often differs from base verbs.",
      "Use the passive voice test: if you can make a sentence passive, the verb is transitive.",
      "Pay attention to ergative verbs in scientific and technical contexts where they're frequently used.",
      "Read academic texts to see how complex transitive and ditransitive verbs function in formal register.",
      "Practice with corpus-based examples from COCA (Corpus of Contemporary American English) or BNC (British National Corpus).",
      "Focus on verb + preposition combinations that are fixed patterns in English.",
      "Learn semantic categories: motion verbs, mental verbs, communication verbs often have specific transitivity patterns.",
      "Use visual aids and mind maps to connect related transitive and intransitive verbs.",
    ],
    references: [
      "Huddleston, R., & Pullum, G. K. (2002). The Cambridge Grammar of the English Language. Cambridge University Press.",
      "Quirk, R., Greenbaum, S., Leech, G., & Svartvik, J. (1985). A Comprehensive Grammar of the English Language. Longman.",
      "Biber, D., Johansson, S., Leech, G., Conrad, S., & Finegan, E. (1999). Longman Grammar of Spoken and Written English. Pearson Education.",
      "Carter, R., & McCarthy, M. (2006). Cambridge Grammar of English: A Comprehensive Guide. Cambridge University Press.",
      "Swan, M. (2016). Practical English Usage (4th ed.). Oxford University Press.",
      "Eastwood, J. (2021). Oxford English Grammar Course: Advanced. Oxford University Press.",
      "Thomson, A. J., & Martinet, A. V. (1986). A Practical English Grammar (4th ed.). Oxford University Press.",
      "Murphy, R. (2019). English Grammar in Use (5th ed.). Cambridge University Press.",
      "Parrott, M. (2010). Grammar for English Language Teachers (2nd ed.). Cambridge University Press.",
      "https://www.cambridge.org/core/books/cambridge-grammar-of-the-english-language",
      "https://www.oxfordlearnersdictionaries.com/grammar/",
      "https://dictionary.cambridge.org/grammar/",
      "https://www.merriam-webster.com/grammar",
      "https://www.grammarly.com/blog/transitive-and-intransitive-verbs/",
    ],
    CEFRNotes: {
      A1: "Master basic transitive verbs (eat, drink, see, like) and intransitive verbs (go, come, sleep). Understand that some verbs need objects and others don't. Use simple present and past tenses correctly.",
      A2: "Expand verb vocabulary and use prepositions correctly with intransitive verbs. Begin using dual-function verbs and understand basic passive voice with common transitive verbs. Recognize phrasal verbs.",
      B1: "Master ergative verbs and causative constructions. Understand how the same verb can change meaning based on transitivity. Use complex sentence structures with embedded clauses. Handle phrasal verbs confidently.",
      B2: "Master ditransitive verbs and complex transitive constructions. Use sophisticated passive and active voice manipulations. Understand register differences and choose appropriate verbs for formal/informal contexts.",
      C1: "Master complex transitive verbs with object complements. Use sophisticated ergative and causative constructions for stylistic effect. Employ advanced academic and formal register appropriately. Understand semantic subtleties.",
      C2: "Master all exceptional cases including pseudo-transitive verbs. Use transitivity for sophisticated stylistic and rhetorical effects. Understand historical and dialectical variations. Manipulate voice and focus for precise meaning and emphasis.",
    },
    syntacticStructure: {
      description:
        "The presence or absence of a direct object influences sentence pattern.",
      patternComparisons: [
        {
          label: "Intransitive",
          pattern: "S + V (+ Adv/Prep Phrase)",
          example: "She dances gracefully.",
        },
        {
          label: "Transitive",
          pattern: "S + V + DO",
          example: "She performs a ballet.",
        },
      ],
    },
    semanticTypes: {
      actionVerbs: {
        transitiveOnly: ["complete", "achieve", "build", "destroy"],
        intransitiveOnly: ["exist", "occur", "vanish", "proceed"],
      },
      mentalVerbs: {
        transitive: ["understand", "remember", "believe"],
        intransitive: ["meditate", "dream", "think (when used alone)"],
      },
      speechVerbs: {
        mixed: [
          {
            verb: "speak",
            transitiveUse: "She spoke fluent Spanish.",
            intransitiveUse: "She spoke slowly.",
          },
          {
            verb: "talk",
            transitiveUse: "He talked politics all night.",
            intransitiveUse: "He talked for hours.",
          },
        ],
      },
    },
    idiomaticUsage: {
      notes:
        "Some idioms use verbs in strictly intransitive or transitive ways that may not follow the literal logic.",
      examples: [
        {
          expression: "let it go",
          verbType: "transitive",
          structure: "let (V) + it (DO) + go (bare infinitive)",
        },
        {
          expression: "give in",
          verbType: "intransitive",
          structure: "phrasal verb with no direct object",
        },
      ],
    },
    diagnosticTests: {
      objectTest: {
        description: "Can you ask 'what?' or 'whom?' after the verb?",
        example: {
          sentence: "He reads.",
          test: "Reads what? (No answer = intransitive)",
          transformation: "He reads novels. (novels = object → transitive)",
        },
      },
      passiveTest: {
        description:
          "If a verb can be used in the passive voice, it's transitive.",
        example: {
          active: "She painted a picture.",
          passive: "A picture was painted (by her).",
        },
      },
    },
    relatedGrammarConcepts: {
      ditransitiveVerbs: {
        description: "Verbs that take two objects: direct and indirect.",
        examples: ["She gave him a gift.", "He told me a story."],
      },
      complexTransitiveVerbs: {
        description:
          "Verbs that require a direct object and an object complement.",
        examples: ["They elected her president.", "He painted the wall blue."],
      },
      linkingVerbsOverlap: {
        note: "Linking verbs appear intransitive but function differently.",
        example: "She became angry. (Not action but state transition)",
      },
    },
    academicUseCases: {
      stylisticFunction: {
        transitive:
          "Used for precision and control in technical or formal writing.",
        intransitive: "Used to maintain flow or suggest general action/state.",
      },
      genreApplication: {
        scientific:
          "Transitive favored for stating results clearly: 'We observed a reaction.'",
        literary:
          "Intransitive favored for ambiguity: 'She faded into silence.'",
      },
    },
    contrastTable: [
      {
        feature: "Needs Object",
        transitive: "Yes",
        intransitive: "No",
      },
      {
        feature: "Can Form Passive",
        transitive: "Yes",
        intransitive: "No",
      },
      {
        feature: "Common with Adverbs",
        transitive: "Less often",
        intransitive: "Frequently",
      },
      {
        feature: "Common in Instructions",
        transitive: "Yes (e.g., 'Take the pill.')",
        intransitive: "Sometimes (e.g., 'Wait.')",
      },
    ],
    rareCases: {
      pseudoTransitiveVerbs: {
        description:
          "Verbs followed by a noun phrase but not true direct objects.",
        example: {
          sentence: "He resembles his father.",
          explanation:
            "‘His father’ is not an object but part of a stative structure.",
        },
      },
      verbsOfMotion: {
        dualUse: [
          {
            verb: "fly",
            transitive: "He flew a kite.",
            intransitive: "The bird flew away.",
          },
          {
            verb: "drive",
            transitive: "She drove a car.",
            intransitive: "She drove all night.",
          },
        ],
      },
    },
    pragmaticNotes: {
      spokenLanguage: "Intransitive verbs are more common in casual speech.",
      writtenLanguage:
        "Transitive verbs dominate academic and instructional writing.",
      culturalPatterns:
        "Some languages prefer intransitive patterns, so ESL learners may omit needed objects.",
    },
    reflectionQuestions: [
      "Can the verb make sense on its own?",
      "Can you form a passive version of the sentence?",
      "Is something receiving the action of the verb?",
    ],
  };
