import { singularOnlyNounsType } from "@/types/grammars/grammar/noun_special/singular_only_nouns";

export const singularOnlyNounsData: singularOnlyNounsType = {
  definition: {
    core_concept:
      "Singular-only nouns are nouns that are used exclusively in the singular form and do not have a standard plural counterpart in English.",
    grammatical_status:
      "These nouns always take singular verb agreement and are treated as individual, unique, or uncountable entities.",
    linguistic_significance:
      "They highlight the concept of uniqueness, indivisibility, or abstractness in language.",
    examples: [
      "information",
      "advice",
      "furniture",
      "luggage",
      "bread",
      "happiness",
      "music",
      "news",
      "progress",
      "equipment",
      "homework",
      "knowledge",
      "research",
      "traffic",
      "weather",
      "work",
    ],
    detailed_explanation:
      "Singular-only nouns, also known as uncountable or mass nouns, represent a fundamental grammatical category in English. They denote substances, concepts, or entities that cannot be enumerated individually using standard counting methods. These nouns challenge the typical count/mass distinction and require specific grammatical treatment, including the use of singular verbs, specific quantifiers, and partitive expressions for measurement.",
    etymology:
      "The concept of mass nouns has its roots in Indo-European language structure, where the distinction between countable and uncountable entities was grammaticalized differently across various language families.",
    cross_linguistic_comparison:
      "While most languages have some form of mass/count distinction, English singular-only nouns often correspond to countable nouns in other languages, creating significant learning challenges for second language learners.",
  },

  classification: {
    uncountable_substances: {
      definition:
        "Physical substances that cannot be counted individually but exist as continuous masses",
      examples: [
        "water",
        "milk",
        "sand",
        "gold",
        "oil",
        "flour",
        "sugar",
        "salt",
      ],
      level: "A1-A2",
      usage_notes: [
        "Often require partitive expressions (a glass of water, a grain of sand)",
        "Can be measured by volume, weight, or quantity",
        "Never take indefinite articles (a/an) directly",
      ],
    },
    abstract_concepts: {
      definition:
        "Intangible ideas, emotions, or qualities that exist conceptually",
      examples: [
        "happiness",
        "knowledge",
        "wisdom",
        "freedom",
        "justice",
        "love",
      ],
      level: "A2-C2",
      usage_notes: [
        "Represent mental or emotional states",
        "Often philosophical or psychological in nature",
        "May be used metaphorically in higher registers",
      ],
    },
    collective_categories: {
      definition:
        "Terms that represent groups or collections viewed as single entities",
      examples: ["furniture", "equipment", "luggage", "jewelry", "stationery"],
      level: "B1-B2",
      usage_notes: [
        "Represent categories of objects rather than individual items",
        "Require specific quantifiers (much, little, some)",
        "Often appear in domestic or professional contexts",
      ],
    },
    academic_technical: {
      definition:
        "Specialized terminology used in academic, scientific, or professional discourse",
      examples: ["research", "evidence", "data", "information", "literature"],
      level: "B2-C2",
      usage_notes: [
        "Essential for academic writing",
        "Often appear in formal registers",
        "May have different meanings in specialized contexts",
      ],
    },
    mass_nouns: {
      definition:
        "Nouns referring to substances or concepts perceived as homogeneous masses",
      examples: ["air", "time", "space", "money", "energy", "matter"],
      level: "A1-C2",
      usage_notes: [
        "Fundamental to expressing quantity and measurement",
        "Often appear in scientific or technical contexts",
        "May be used both literally and metaphorically",
      ],
    },
  },
  singular_only_nouns_vocab: {
    "Abstract Concepts": [
      "information",
      "advice",
      "knowledge",
      "progress",
      "furniture",
      "homework",
      "equipment",
      "research",
      "work",
      "traffic",
      "weather",
      "news",
      "education",
      "violence",
      "happiness",
      "sadness",
      "anger",
      "beauty",
      "truth",
      "fun",
      "luck",
      "freedom",
      "patience",
      "courage",
      "justice",
      "hope",
      "chaos",
      "fear",
      "love",
      "honesty",
      "bravery",
      "humor",
      "greed",
      "confidence",
      "leadership",
      "citizenship",
      "generosity",
      "loyalty",
      "discipline",
      "wisdom",
      "creativity",
    ],

    "Mass & Material Substances": [
      "water",
      "milk",
      "oil",
      "sugar",
      "salt",
      "flour",
      "butter",
      "cheese",
      "bread",
      "rice",
      "meat",
      "fruit",
      "coffee",
      "tea",
      "alcohol",
      "sand",
      "dust",
      "smoke",
      "air",
      "ice",
      "snow",
      "mud",
      "glass",
      "plastic",
      "wood",
      "cotton",
      "wool",
      "leather",
      "rubber",
      "oxygen",
      "hydrogen",
      "helium",
      "nitrogen",
      "carbon",
      "gold",
      "silver",
      "iron",
      "steel",
      "bronze",
      "aluminum",
      "mercury",
      "cement",
      "concrete",
      "asphalt",
      "gasoline",
      "fuel",
      "ink",
      "paint",
      "dirt",
    ],

    "Academic Subjects & Sciences": [
      "mathematics",
      "physics",
      "chemistry",
      "biology",
      "history",
      "geography",
      "economics",
      "ethics",
      "linguistics",
      "phonetics",
      "aesthetics",
      "politics",
      "classics",
      "sociology",
      "psychology",
      "literature",
      "architecture",
      "philosophy",
      "cybernetics",
      "astronomy",
      "anthropology",
      "ecology",
      "theology",
      "neurology",
      "paleontology",
      "nanotechnology",
      "biotechnology",
      "genetics",
      "robotics",
      "informatics",
      "microbiology",
      "zoology",
      "botany",
    ],

    "Time, Space & Measurement": [
      "time",
      "space",
      "speed",
      "length",
      "breadth",
      "depth",
      "height",
      "energy",
      "power",
      "pressure",
      "voltage",
      "temperature",
      "distance",
      "weight",
      "volume",
      "density",
      "mass",
      "momentum",
      "gravity",
      "light",
      "darkness",
      "acceleration",
      "radiation",
      "motion",
      "rotation",
      "balance",
    ],

    "Philosophy & Metaphysics": [
      "being",
      "existence",
      "consciousness",
      "reality",
      "truth",
      "wisdom",
      "mind",
      "spirit",
      "soul",
      "nirvana",
      "zen",
      "eternity",
      "destiny",
      "morality",
      "intuition",
      "awareness",
      "emptiness",
      "self",
      "enlightenment",
    ],

    "Health, Medicine & Human Condition": [
      "pain",
      "stress",
      "suffering",
      "anxiety",
      "sleep",
      "fatigue",
      "rest",
      "blood",
      "cholesterol",
      "sugar",
      "cancer",
      "diabetes",
      "medicine",
      "treatment",
      "therapy",
      "recovery",
      "nutrition",
      "health",
      "disease",
      "injury",
      "healing",
      "aging",
      "rehabilitation",
    ],

    "Business, Finance & Economics": [
      "money",
      "cash",
      "capital",
      "currency",
      "wealth",
      "poverty",
      "debt",
      "profit",
      "loss",
      "income",
      "revenue",
      "finance",
      "commerce",
      "marketing",
      "trade",
      "advertising",
      "accounting",
      "pricing",
      "inflation",
      "investment",
      "consumption",
      "banking",
      "merchandise",
      "taxation",
      "insurance",
      "interest",
    ],

    "Weather & Natural Phenomena": [
      "weather",
      "rain",
      "snow",
      "fog",
      "thunder",
      "lightning",
      "sunshine",
      "climate",
      "heat",
      "cold",
      "humidity",
      "pollution",
      "gravity",
      "darkness",
      "daylight",
      "wind",
      "hail",
      "dew",
      "mist",
      "frost",
    ],

    "Communication, Art & Media": [
      "music",
      "art",
      "poetry",
      "drama",
      "literature",
      "news",
      "information",
      "feedback",
      "media",
      "gossip",
      "knowledge",
      "imagery",
      "language",
      "rhetoric",
      "humor",
      "advertising",
      "photography",
      "cinema",
      "theater",
      "dialogue",
      "conversation",
      "silence",
    ],

    "Household & Common Objects": [
      "furniture",
      "luggage",
      "baggage",
      "rubbish",
      "garbage",
      "equipment",
      "clothing",
      "jewelry",
      "cutlery",
      "machinery",
      "stationery",
      "lighting",
      "plumbing",
      "wiring",
      "carpeting",
      "upholstery",
      "kitchenware",
      "bedding",
      "glassware",
      "silverware",
      "hardware",
      "software",
      "mail",
      "mailbox",
      "laundry",
    ],

    "Law, Government & Institutions": [
      "law",
      "justice",
      "evidence",
      "legislation",
      "bureaucracy",
      "corruption",
      "authority",
      "policy",
      "permission",
      "property",
      "ownership",
      "governance",
      "citizenship",
      "leadership",
      "surveillance",
      "torture",
      "espionage",
    ],

    "Behavioral & Social Traits": [
      "behavior",
      "conduct",
      "leadership",
      "citizenship",
      "bravery",
      "honesty",
      "generosity",
      "hospitality",
      "kindness",
      "humor",
      "courtesy",
      "confidence",
      "etiquette",
      "morality",
      "reputation",
      "maturity",
      "discipline",
      "modesty",
    ],
  },
  cefrLevels: {
    A1: {
      description:
        "Basic recognition and use of common singular-only nouns in daily life",
      vocabulary: [
        "bread",
        "water",
        "music",
        "air",
        "rice",
        "milk",
        "sand",
        "sugar",
        "salt",
        "money",
      ],
      key_concepts: [
        "Recognition of basic uncountable nouns",
        "Understanding that some nouns don't have plurals",
        "Using singular verbs with uncountable nouns",
      ],
      grammar_focus: [
        "Singular verb agreement",
        "Basic quantifiers (some, a little)",
        "No use of a/an with uncountable nouns",
      ],
      communicative_functions: [
        "Ordering food and drinks",
        "Talking about basic needs",
        "Simple descriptions of substances",
      ],
    },
    A2: {
      description:
        "Expanded vocabulary and use in simple descriptions and requests",
      vocabulary: [
        "advice",
        "homework",
        "furniture",
        "luggage",
        "traffic",
        "weather",
        "news",
        "progress",
        "equipment",
        "information",
      ],
      key_concepts: [
        "Using partitive expressions (a piece of advice)",
        "Understanding collective categories",
        "Distinguishing count vs uncountable nouns",
      ],
      grammar_focus: [
        "Partitive expressions",
        "Quantifiers (much, little, a lot of)",
        "This/that with singular-only nouns",
      ],
      communicative_functions: [
        "Giving and asking for advice",
        "Describing possessions",
        "Talking about school and work",
      ],
    },
    B1: {
      description: "Use in explanations, opinions, and more abstract contexts",
      vocabulary: [
        "knowledge",
        "research",
        "evidence",
        "machinery",
        "clothing",
        "literature",
        "media",
        "software",
        "hardware",
        "data",
      ],
      key_concepts: [
        "Abstract concept comprehension",
        "Academic and professional contexts",
        "Complex quantification methods",
      ],
      grammar_focus: [
        "Advanced quantifiers",
        "Abstract noun usage",
        "Formal register adaptation",
      ],
      communicative_functions: [
        "Expressing opinions and ideas",
        "Academic discussions",
        "Professional communication",
      ],
    },
    B2: {
      description: "Use in academic, professional, and technical contexts",
      vocabulary: [
        "terminology",
        "poetry",
        "scenery",
        "content",
        "criteria",
        "phenomena",
        "stationery",
        "machinery",
        "bureaucracy",
        "surveillance",
      ],
      key_concepts: [
        "Technical and academic precision",
        "Formal writing conventions",
        "Specialized domain knowledge",
      ],
      grammar_focus: [
        "Formal register usage",
        "Complex sentence structures",
        "Academic writing conventions",
      ],
      communicative_functions: [
        "Academic writing",
        "Professional presentations",
        "Technical discussions",
      ],
    },
    C1: {
      description: "Nuanced use in formal, academic, and idiomatic expressions",
      vocabulary: [
        "iconography",
        "imagery",
        "lexicon",
        "paraphernalia",
        "foliage",
        "prose",
        "eloquence",
        "rhetoric",
        "aesthetics",
        "metaphysics",
      ],
      key_concepts: [
        "Sophisticated academic discourse",
        "Idiomatic and metaphorical usage",
        "Register flexibility",
      ],
      grammar_focus: [
        "Stylistic variation",
        "Metaphorical extensions",
        "Academic precision",
      ],
      communicative_functions: [
        "Academic research",
        "Literary analysis",
        "Formal presentations",
      ],
    },
    C2: {
      description:
        "Mastery of rare, idiomatic, and highly abstract singular-only nouns",
      vocabulary: [
        "jurisprudence",
        "pedagogy",
        "epistemology",
        "phenomenology",
        "hermeneutics",
        "dialectics",
        "semiotics",
        "ontology",
        "teleology",
        "cosmology",
      ],
      key_concepts: [
        "Philosophical and theoretical mastery",
        "Creative and artistic expression",
        "Academic research proficiency",
      ],
      grammar_focus: [
        "Scholarly precision",
        "Creative usage",
        "Theoretical discourse",
      ],
      communicative_functions: [
        "Scholarly research",
        "Creative writing",
        "Theoretical discussion",
      ],
    },
  },
  forms: {
    basic:
      "S + singular-only noun + singular verb • e.g., The information is useful.",
    with_article:
      "S + a piece of/some + singular-only noun • e.g., I need a piece of advice.",
    with_quantifier:
      "S + much/little + singular-only noun • e.g., There is much traffic.",
    with_no_article:
      "S + singular-only noun (no article) • e.g., Music helps me relax.",
    partitive_expressions: [
      "a piece of (advice, information, furniture)",
      "a bit of (help, luck, time)",
      "an item of (clothing, equipment, news)",
      "a drop of (water, oil)",
      "a slice of (bread, cake)",
      "a sheet of (paper, music)",
      "a work of (art, literature)",
    ],
    formal_register: [
      "The research indicates...",
      "Evidence suggests that...",
      "Literature review shows...",
      "Data analysis reveals...",
      "The information provided...",
    ],
  },
  usage: [
    {
      type: "Uncountable substances and materials",
      description:
        "Nouns that refer to substances or materials that cannot be counted individually.",
      examples: ["water", "bread", "rice", "sand", "air", "gold", "milk"],
      level: "A1-A2",
      context: "Daily life, food, basic materials",
      register: "Informal to neutral",
    },
    {
      type: "Abstract concepts",
      description:
        "Nouns that refer to ideas, qualities, or states that are not concrete objects.",
      examples: [
        "happiness",
        "advice",
        "progress",
        "knowledge",
        "love",
        "anger",
      ],
      level: "A2-B1",
      context: "Personal experiences, emotions, learning",
      register: "Neutral to formal",
    },
    {
      type: "Collective/General categories",
      description:
        "Nouns that refer to a category or group as a whole, not individual items.",
      examples: ["furniture", "luggage", "equipment", "machinery", "clothing"],
      level: "B1-B2",
      context: "Home, travel, work environments",
      register: "Neutral to formal",
    },
    {
      type: "Academic/Professional/Technical",
      description:
        "Nouns used in academic, scientific, or professional contexts.",
      examples: ["research", "evidence", "terminology", "literature", "poetry"],
      level: "B2-C2",
      context: "Education, science, professional discourse",
      register: "Formal to academic",
    },
    {
      type: "News and media",
      description:
        "Nouns that refer to information or communication as a whole.",
      examples: ["news", "media", "information"],
      level: "B1-C1",
      context: "Journalism, communication, public discourse",
      register: "Neutral to formal",
    },
  ],
  examples: {
    basic: {
      direct: "I need information.",
      correct: "I need some information.",
      incorrect: "I need informations.",
      context: "Requesting help (A1)",
      explanation:
        "Information is uncountable and cannot take a plural form. Use 'some' as a quantifier.",
    },
    with_article: {
      direct: "Can you give me advice?",
      correct: "Can you give me a piece of advice?",
      incorrect: "Can you give me an advice?",
      context: "Seeking suggestions (A2)",
      explanation:
        "Advice is uncountable. Use 'a piece of' to make it countable when referring to one suggestion.",
    },
    with_quantifier: {
      direct: "There is much traffic today.",
      correct: "There is a lot of traffic today.",
      incorrect: "There are many traffics today.",
      context: "Describing conditions (B1)",
      explanation:
        "Traffic is uncountable and takes singular verbs. Use 'much' or 'a lot of' not 'many'.",
    },
    academic: {
      direct: "The research shows new results.",
      correct: "Research shows new results.",
      incorrect: "The researches show new results.",
      context: "Academic writing (B2)",
      explanation:
        "Research is uncountable in academic contexts. It can be used without 'the' when referring to research in general.",
    },
    idiomatic: {
      direct: "The news is good.",
      correct: "This is good news.",
      incorrect: "These are good news.",
      context: "Reacting to information (B1)",
      explanation:
        "News is uncountable and always takes singular verbs and demonstratives.",
    },
    advanced: {
      direct: "The evidence supports this theory.",
      correct: "Evidence supports this theory.",
      incorrect: "Evidences support this theory.",
      context: "Scientific discourse (C1)",
      explanation:
        "Evidence is uncountable in formal academic writing and doesn't require the definite article when used generally.",
    },
    specialized: {
      direct: "His poetry reflects modern themes.",
      correct: "His poetry reflects modern themes.",
      incorrect: "His poetries reflect modern themes.",
      context: "Literary criticism (C2)",
      explanation:
        "Poetry as an art form is uncountable, though individual poems are countable.",
    },
  },
  practiceTypes: {
    A1: [
      "Identify singular-only nouns in simple sentences",
      "Choose correct verb agreement with singular-only nouns",
      "Match nouns to pictures (e.g., bread, water, music)",
      "Fill in the blank with a singular-only noun",
    ],
    A2: [
      "Use a piece of/some with singular-only nouns",
      "Distinguish between countable and singular-only nouns",
      "Correct sentences with article errors",
      "Simple gap-filling with singular-only nouns",
    ],
    B1: [
      "Use quantifiers (much/little/a lot of) with singular-only nouns",
      "Rewrite incorrect plural forms to correct singular-only forms",
      "Use singular-only nouns in short paragraphs",
      "Identify abstract singular-only nouns in context",
    ],
    B2: [
      "Use singular-only nouns in academic and professional writing",
      "Paraphrase sentences to use singular-only nouns idiomatically",
      "Correct advanced errors with singular-only nouns",
      "Explain the meaning of abstract singular-only nouns",
    ],
    C1: [
      "Use singular-only nouns in formal and academic registers",
      "Analyze idiomatic and metaphorical uses of singular-only nouns",
      "Identify subtle errors in advanced writing",
      "Produce essays using a range of singular-only nouns",
    ],
    C2: [
      "Master rare and highly abstract singular-only nouns",
      "Critique and edit advanced texts for singular-only noun accuracy",
      "Use singular-only nouns in creative and literary writing",
      "Demonstrate register flexibility with singular-only nouns",
    ],
  },
  commonMistakes: {
    beginners: [
      "Adding -s to singular-only nouns: ❌ informations ✅ information",
      "Using 'a/an' with uncountable nouns: ❌ an advice ✅ a piece of advice",
      "Plural verb agreement: ❌ The news are good ✅ The news is good",
      "Using 'many' with singular-only nouns: ❌ many furniture ✅ much furniture",
    ],
    intermediate: [
      "Confusing countable and singular-only nouns: ❌ a bread ✅ a loaf of bread",
      "Incorrect quantifiers: ❌ few equipment ✅ little equipment",
      "Wrong article: ❌ a research ✅ research",
      "Using 'these/those' with singular-only nouns: ❌ these information ✅ this information",
    ],
    advanced: [
      "Overusing 'the' with abstract nouns: ❌ the happiness is important ✅ happiness is important",
      "Incorrect idiomatic use: ❌ a good news ✅ good news",
      "Mixing countable and uncountable forms: ❌ advices ✅ advice",
      "Using plural forms in academic writing: ❌ researches show ✅ research shows",
    ],
  },
  recognition: [
    "Singular-only nouns never take -s for plural",
    "They always use singular verb agreement",
    "Often refer to substances, materials, abstract ideas, or collective categories",
    "Require quantifiers or partitive expressions for counting (e.g., a piece of, a bit of, some)",
    "Cannot be used with 'many', 'few', 'these', 'those'",
    "Often used without an article, or with 'the' for specificity",
  ],
  timeMarkers: [
    "now",
    "today",
    "yesterday",
    "tomorrow",
    "this week",
    "last year",
    "at the moment",
    "recently",
    "soon",
  ],
  pronounChanges: {
    basic: {
      it: "It is important.",
      this: "This is useful information.",
      that: "That is good advice.",
    },
    advanced: {
      what: "What I need is evidence.",
      all: "All that matters is progress.",
    },
  },
  reportingVerbs: [
    "have",
    "need",
    "give",
    "receive",
    "show",
    "find",
    "provide",
    "offer",
    "bring",
    "contain",
  ],
  notes: [
    "Singular-only nouns are often uncountable, but not all uncountable nouns are singular-only.",
    "Some nouns can be both countable and uncountable with different meanings (e.g., 'paper' as material vs. 'a paper' as an article).",
    "Use partitive structures (a piece of, a bit of, an item of) to count singular-only nouns.",
    "In academic writing, avoid using plural forms for research, evidence, advice, etc.",
    "Some singular-only nouns are used idiomatically (e.g., 'good news', 'bad weather').",
    "Be careful with false friends in other languages that may be countable.",
  ],
  culturalContexts: {
    daily_life: {
      description: "Common in daily requests, shopping, and conversation",
      examples: [
        "Can I have some bread?",
        "I need information.",
        "The weather is nice today.",
      ],
    },
    academic: {
      description: "Essential in academic and professional writing",
      examples: ["Research shows...", "There is evidence that..."],
    },
    idiomatic: {
      description: "Used in idiomatic expressions and news/media",
      examples: ["That's good news!", "Bad weather delayed the flight."],
    },
  },
  specialCases: {
    idiomatic: {
      description: "Fixed expressions and idioms with singular-only nouns",
      examples: [
        "a piece of cake",
        "bread and butter",
        "make progress",
        "give advice",
        "do homework",
        "make an effort",
      ],
    },
    academic: {
      description: "Academic and technical terms that are always singular",
      examples: [
        "evidence",
        "research",
        "literature",
        "terminology",
        "machinery",
      ],
    },
    false_friends: {
      description:
        "Words that are countable in other languages but singular-only in English",
      examples: ["advice", "information", "furniture", "luggage", "news"],
    },
  },
  etymology: {
    origin:
      "Many singular-only nouns derive from Old English, Latin, or French, often reflecting abstract or mass concepts.",
    development:
      "The distinction between countable and uncountable nouns developed over centuries as English absorbed vocabulary from other languages.",
    modernUsage:
      "Singular-only nouns are now common in both spoken and written English, especially in academic and professional contexts.",
  },
  crossLinguistic: {
    similarities:
      "Many languages have uncountable or mass nouns, but the specific list and usage rules vary.",
    differences:
      "Some nouns that are singular-only in English are countable in other languages (e.g., 'advice' in French: 'un conseil').",
    learnerChallenges:
      "Learners often overgeneralize plural forms or use incorrect articles due to interference from their native language.",
  },
  vocabulary: {
    A1: [
      "bread",
      "water",
      "music",
      "air",
      "rice",
      "milk",
      "sand",
      "sugar",
      "salt",
      "money",
    ],
    A2: [
      "advice",
      "homework",
      "furniture",
      "luggage",
      "traffic",
      "weather",
      "news",
      "progress",
      "equipment",
    ],
    B1: [
      "information",
      "knowledge",
      "research",
      "evidence",
      "machinery",
      "clothing",
      "literature",
      "media",
    ],
    B2: [
      "terminology",
      "poetry",
      "scenery",
      "software",
      "hardware",
      "data",
      "content",
      "work",
    ],
    C1: [
      "criteria",
      "evidence",
      "machinery",
      "literature",
      "poetry",
      "terminology",
      "progress",
    ],
    C2: [
      "iconography",
      "imagery",
      "syntax",
      "semantics",
      "lexicon",
      "paraphernalia",
      "foliage",
      "prose",
    ],
  },
  grammaticalPatterns: {
    article_usage: {
      correct: ["some information", "a piece of advice", "the furniture"],
      incorrect: ["an information", "an advice", "the advices"],
    },
    verb_agreement: {
      correct: ["The news is good.", "The equipment works well."],
      incorrect: ["The news are good.", "The equipment work well."],
    },
    quantifiers: {
      correct: ["much information", "little progress", "a lot of bread"],
      incorrect: ["many informations", "few progresses", "many breads"],
    },
  },
  usageContexts: {
    A1: ["shopping", "food and drink", "music", "weather", "basic needs"],
    A2: [
      "schoolwork",
      "giving/receiving advice",
      "home and furniture",
      "travel (luggage)",
    ],
    B1: [
      "news and media",
      "traffic reports",
      "progress updates",
      "information requests",
    ],
    B2: [
      "academic writing",
      "technical descriptions",
      "professional communication",
    ],
    C1: [
      "formal essays",
      "research papers",
      "literary analysis",
      "advanced presentations",
    ],
    C2: [
      "creative writing",
      "critical reviews",
      "specialized academic discourse",
    ],
  },
  errorPatterns: {
    A1: ["❌ musics ✅ music", "❌ a bread ✅ bread", "❌ a water ✅ water"],
    A2: ["❌ an advice ✅ a piece of advice", "❌ homeworks ✅ homework"],
    B1: ["❌ informations ✅ information", "❌ traffics ✅ traffic"],
    B2: ["❌ researches ✅ research", "❌ softwares ✅ software"],
    C1: ["❌ evidences ✅ evidence", "❌ terminologies ✅ terminology"],
    C2: ["❌ iconographies ✅ iconography", "❌ foliages ✅ foliage"],
  },
  learningStrategies: {
    A1: [
      "Memorize common singular-only nouns with pictures and examples.",
      "Practice using correct verb agreement.",
      "Listen for singular-only nouns in simple conversations.",
    ],
    A2: [
      "Use partitive structures (a piece of, some) in speaking and writing.",
      "Compare countable and singular-only nouns in context.",
      "Correct common mistakes in exercises.",
    ],
    B1: [
      "Practice using quantifiers (much, little, a lot of) with singular-only nouns.",
      "Write short texts using a variety of singular-only nouns.",
      "Edit sentences for correct singular-only noun usage.",
    ],
    B2: [
      "Use singular-only nouns in academic and technical writing.",
      "Paraphrase sentences to use singular-only nouns idiomatically.",
      "Analyze authentic texts for advanced usage.",
    ],
    C1: [
      "Produce essays and presentations using advanced singular-only nouns.",
      "Identify and correct subtle errors in peer writing.",
      "Experiment with idiomatic and metaphorical uses.",
    ],
    C2: [
      "Master rare and highly abstract singular-only nouns.",
      "Critique and edit advanced texts for accuracy.",
      "Use singular-only nouns creatively in literary and academic contexts.",
    ],
  },

  references: {
    academic_sources: [
      {
        title: "The Grammar of English: A Comprehensive Guide",
        author: "Huddleston, Rodney & Pullum, Geoffrey K.",
        year: 2005,
        publisher: "Cambridge University Press",
        pages: "334-398",
        url: "https://www.cambridge.org/core/books/cambridge-grammar-of-the-english-language",
      },
      {
        title: "Countability and Number in English Nouns",
        author: "Pelletier, Francis Jeffry",
        year: 2012,
        publisher: "Oxford University Press",
        pages: "156-189",
      },
      {
        title:
          "Mass and Count in Linguistics, Philosophy, and Cognitive Science",
        author: "Gillon, Brendan S.",
        year: 2019,
        publisher: "John Benjamins Publishing",
        pages: "45-78",
      },
      {
        title: "The Semantics of English Mass and Count Nouns",
        author: "Rothstein, Susan",
        year: 2017,
        publisher: "Cambridge University Press",
        pages: "123-167",
      },
      {
        title: "Uncountable Nouns in Second Language Acquisition",
        author: "White, Lydia & Genesee, Fred",
        year: 2018,
        publisher: "Language Learning Research",
        pages: "89-112",
      },
    ],
    grammar_books: [
      {
        title: "Practical English Usage",
        author: "Swan, Michael",
        publisher: "Oxford University Press",
        edition: "4th Edition",
        isbn: "978-0194202411",
      },
      {
        title: "English Grammar in Use",
        author: "Murphy, Raymond",
        publisher: "Cambridge University Press",
        edition: "5th Edition",
        isbn: "978-1108457651",
      },
      {
        title: "A Comprehensive Grammar of the English Language",
        author: "Quirk, Randolph et al.",
        publisher: "Longman",
        isbn: "978-0582517349",
      },
      {
        title: "The Cambridge Grammar of the English Language",
        author: "Huddleston, Rodney & Pullum, Geoffrey K.",
        publisher: "Cambridge University Press",
        isbn: "978-0521431460",
      },
      {
        title: "Advanced Grammar in Use",
        author: "Hewings, Martin",
        publisher: "Cambridge University Press",
        edition: "3rd Edition",
        isbn: "978-1107539303",
      },
    ],
    online_resources: [
      {
        title: "Cambridge English Grammar Reference",
        website: "Cambridge Dictionary",
        url: "https://dictionary.cambridge.org/grammar/british-grammar/",
        access_date: "2024",
      },
      {
        title: "Oxford Learners' Grammar Guide",
        website: "Oxford Learner's Dictionaries",
        url: "https://www.oxfordlearnersdictionaries.com/grammar/",
        access_date: "2024",
      },
      {
        title: "BBC Learning English Grammar",
        website: "BBC Learning English",
        url: "https://www.bbc.co.uk/learningenglish/english/features/grammar",
        access_date: "2024",
      },
      {
        title: "British Council English Grammar",
        website: "British Council",
        url: "https://learnenglish.britishcouncil.org/grammar",
        access_date: "2024",
      },
      {
        title: "Grammarly Grammar Guide",
        website: "Grammarly",
        url: "https://www.grammarly.com/blog/mass-nouns/",
        access_date: "2024",
      },
    ],
    linguistic_studies: [
      {
        title: "Cross-linguistic studies of mass/count distinction",
        author: "Chierchia, Gennaro",
        journal: "Natural Language Semantics",
        year: 2010,
        volume: "18",
        pages: "351-389",
      },
      {
        title: "The Acquisition of English Mass/Count Syntax",
        author: "Gordon, Peter",
        journal: "Journal of Child Language",
        year: 2015,
        volume: "42",
        pages: "772-804",
      },
      {
        title: "Semantic Properties of Uncountable Nouns in English",
        author: "Borer, Hagit",
        journal: "Linguistic Inquiry",
        year: 2016,
        volume: "47",
        pages: "611-656",
      },
      {
        title: "Processing of Mass and Count Nouns by L2 Learners",
        author: "Jiang, Nan",
        journal: "Applied Linguistics",
        year: 2020,
        volume: "41",
        pages: "234-261",
      },
      {
        title: "Countability across Languages: A Comparative Study",
        author: "Doetjes, Jenny",
        journal: "Linguistics and Philosophy",
        year: 2019,
        volume: "42",
        pages: "467-503",
      },
    ],
    pedagogical_materials: [
      {
        title: "Teaching Uncountable Nouns Effectively",
        author: "Crystal, David",
        publisher: "Longman ELT",
        level: "B1-C2",
        type: "Teaching guide",
      },
      {
        title: "Grammar for English Language Teachers",
        author: "Parrott, Martin",
        publisher: "Cambridge University Press",
        level: "Teachers",
        type: "Professional development",
      },
      {
        title: "Understanding and Using English Grammar",
        author: "Azar, Betty Schrampfer",
        publisher: "Pearson",
        level: "B2-C1",
        type: "Student textbook",
      },
      {
        title: "Focus on Grammar Series",
        author: "Fuchs, Marjorie & Bonner, Margaret",
        publisher: "Pearson Longman",
        level: "A1-C2",
        type: "Course series",
      },
      {
        title: "Grammar Sense Series",
        author: "Bland, Susan Kesner",
        publisher: "Oxford University Press",
        level: "A2-C1",
        type: "Grammar course",
      },
    ],
  },

  detailed_analysis: {
    morphological_properties: [
      "Lack of plural morphology (-s suffix)",
      "Resistance to indefinite article (a/an)",
      "Compatibility with mass quantifiers (much, little, some)",
      "Inability to be directly counted (*one information, *two advices)",
    ],
    syntactic_behavior: [
      "Always takes singular verb agreement",
      "Cannot be preceded by numerals or many/few",
      "Requires partitive constructions for counting",
      "Often appears without determiners in generic contexts",
    ],
    semantic_characteristics: [
      "Denotes substances, abstractions, or collective entities",
      "Conceptualized as homogeneous or undifferentiated",
      "Often refers to qualities, states, or continuous phenomena",
      "May have different countable meanings in specific contexts",
    ],
    pragmatic_considerations: [
      "Register variation affects usage (formal vs informal)",
      "Cultural specificity in count/mass distinctions",
      "Context-dependent interpretation",
      "Metaphorical extensions in specialized discourse",
    ],
  },

  cognitive_aspects: {
    mental_representation:
      "Singular-only nouns are mentally represented as continuous, unbounded entities without natural units of counting, reflecting conceptual differences in how speakers categorize and quantify aspects of reality.",
    processing_difficulties: [
      "L1 interference from languages with different count/mass distinctions",
      "Difficulty in acquiring partitive expressions",
      "Overgeneralization of plural morphology",
      "Problems with quantifier selection",
    ],
    acquisition_stages: [
      "Stage 1: Recognition of basic mass nouns (water, bread)",
      "Stage 2: Understanding singular verb agreement",
      "Stage 3: Learning partitive expressions (a piece of)",
      "Stage 4: Mastering abstract and academic mass nouns",
      "Stage 5: Developing register sensitivity and metaphorical uses",
    ],
  },

  teaching_methodology: {
    presentation_techniques: [
      "Visual aids for concrete mass nouns (water, sand)",
      "Concept mapping for abstract nouns",
      "Contrastive analysis with countable nouns",
      "Corpus-based examples from authentic texts",
      "Multisensory approaches for kinesthetic learners",
    ],
    practice_activities: [
      "Quantifier matching exercises",
      "Error correction tasks",
      "Gap-filling with appropriate forms",
      "Translation and back-translation",
      "Register-appropriate usage practice",
    ],
    assessment_methods: [
      "Discrete-point grammar tests",
      "Contextualized usage tasks",
      "Error identification and correction",
      "Production tasks in academic contexts",
      "Peer review and editing activities",
    ],
    error_correction: [
      "Focus on form through recast",
      "Explicit rule explanation",
      "Contrastive feedback",
      "Metalinguistic explanation",
      "Pattern practice and drilling",
    ],
  },
};
