import { IdiomaticLanguageType } from "@/types/grammars/grammar/IdiomaticLanguage";

export const IdiomaticLanguageData: IdiomaticLanguageType = {
  id: 88,
  definition:
    "Idiomatic language consists of phrases or expressions whose meanings are different from the literal meanings of the individual words. Idioms are deeply embedded in cultural context and are essential for achieving native-like fluency in English communication. They reflect cultural values, historical events, and social practices, making them crucial for understanding English-speaking cultures.",
  purpose: [
    "To make language more natural, colorful, and expressive.",
    "To demonstrate native-like fluency and understanding.",
    "To engage the listener with vivid imagery or emotion.",
    "To connect with native speakers on a cultural level.",
    "To express complex ideas in concise, memorable ways.",
    "To add personality and authenticity to communication.",
    "To understand cultural references and historical contexts.",
    "To navigate social situations with appropriate language choices.",
  ],
  levels: {
    A1: {
      description:
        "Basic everyday expressions for beginners - Foundation of polite communication",
      examples: [
        {
          idiom: "thank you",
          meaning: "expression of gratitude",
          example: "Thank you for your help.",
          context: "Basic politeness",
          literal: "No literal meaning",
          usageNotes: "Most basic polite expression, used in all situations",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 1,
        },
        {
          idiom: "you're welcome",
          meaning: "response to thank you",
          example: "You're welcome, it was my pleasure.",
          context: "Basic politeness",
          literal: "No literal meaning",
          usageNotes: "Standard response to thank you",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 1,
        },
        {
          idiom: "excuse me",
          meaning: "polite way to get attention or apologize",
          example: "Excuse me, could you help me?",
          context: "Basic politeness",
          literal: "No literal meaning",
          usageNotes:
            "Used to interrupt politely or apologize for minor mistakes",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 1,
        },
        {
          idiom: "nice to meet you",
          meaning: "polite greeting when meeting someone",
          example: "Nice to meet you, I'm John.",
          context: "Social introductions",
          literal: "No literal meaning",
          usageNotes: "Standard greeting for first meetings",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 1,
        },
        {
          idiom: "see you later",
          meaning: "goodbye expression",
          example: "See you later, have a good day!",
          context: "Farewells",
          literal: "No literal meaning",
          usageNotes: "Casual goodbye, implies future meeting",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 1,
        },
      ],
      learningTips: [
        "Focus on basic polite expressions first",
        "Learn them as complete phrases, not separate words",
        "Practice in simple conversations",
        "Use them in daily interactions immediately",
        "Pay attention to pronunciation and intonation",
      ],
      vocabularyFocus: [
        "Basic greetings and farewells",
        "Polite expressions",
        "Simple social phrases",
        "Common courtesy words",
      ],
      culturalNotes: [
        "Politeness varies by culture - these are universal English basics",
        "Eye contact and body language accompany these expressions",
        "Tone of voice is as important as the words",
      ],
      practiceScenarios: [
        "Meeting new people",
        "Ordering food at restaurants",
        "Asking for directions",
        "Shopping interactions",
      ],
      commonMistakes: [
        "Forgetting to use polite expressions",
        "Using formal expressions in casual situations",
        "Not matching tone with words",
      ],
      assessmentCriteria: [
        "Can use basic greetings appropriately",
        "Understands when to use polite expressions",
        "Can respond to common social situations",
      ],
      recommendedStudyTime: "2-3 hours per week",
      prerequisites: [
        "Basic English vocabulary",
        "Understanding of simple sentence structure",
      ],
      nextLevelPreparation: [
        "Start learning casual vs formal expressions",
        "Practice with native speakers",
        "Begin noticing cultural differences",
      ],
    },
    A2: {
      description:
        "Common expressions for basic communication - Building conversational skills",
      examples: [
        {
          idiom: "how are you?",
          meaning: "polite way to ask about someone's well-being",
          example: "How are you today?",
          context: "Social greetings",
          literal: "No literal meaning",
          usageNotes: "Standard greeting, often rhetorical",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 2,
        },
        {
          idiom: "I'm fine, thanks",
          meaning: "polite response to how are you",
          example: "I'm fine, thanks. How about you?",
          context: "Social greetings",
          literal: "No literal meaning",
          usageNotes:
            "Standard response, often followed by reciprocal question",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 2,
        },
        {
          idiom: "what's up?",
          meaning: "casual way to ask what's happening",
          example: "Hey, what's up?",
          context: "Casual greetings",
          literal: "No literal meaning",
          usageNotes: "Very casual, used with friends and peers",
          formality: "informal",
          region: ["Primarily American English"],
          difficulty: 2,
        },
        {
          idiom: "no problem",
          meaning: "casual way to say you're welcome",
          example: "No problem, I'm happy to help.",
          context: "Casual responses",
          literal: "No literal meaning",
          usageNotes: "More casual than 'you're welcome'",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 2,
        },
        {
          idiom: "take care",
          meaning: "expression of concern when saying goodbye",
          example: "Take care, see you soon!",
          context: "Farewells",
          literal: "No literal meaning",
          usageNotes: "Shows genuine concern for someone's well-being",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 2,
        },
      ],
      learningTips: [
        "Start using common greetings and responses",
        "Learn casual vs. formal expressions",
        "Practice with simple social interactions",
        "Pay attention to context and relationship",
        "Begin understanding cultural nuances",
      ],
      vocabularyFocus: [
        "Casual vs formal expressions",
        "Common social phrases",
        "Basic conversational responses",
        "Regional variations",
      ],
      culturalNotes: [
        "Americans tend to be more casual than British speakers",
        "Australians use more informal expressions",
        "Context determines formality level",
      ],
      practiceScenarios: [
        "Casual conversations with friends",
        "Workplace interactions",
        "Social media communication",
        "Phone conversations",
      ],
      commonMistakes: [
        "Using casual expressions in formal situations",
        "Not understanding cultural context",
        "Overusing certain expressions",
      ],
      assessmentCriteria: [
        "Can distinguish between formal and informal expressions",
        "Uses appropriate greetings for different situations",
        "Understands basic cultural context",
      ],
      recommendedStudyTime: "3-4 hours per week",
      prerequisites: [
        "A1 level idiomatic expressions",
        "Basic conversational skills",
        "Understanding of social contexts",
      ],
      nextLevelPreparation: [
        "Start learning figurative expressions",
        "Practice with more complex social situations",
        "Begin understanding metaphorical language",
      ],
    },
    B1: {
      description:
        "Intermediate idioms for everyday situations - Understanding figurative language",
      examples: [
        {
          idiom: "a piece of cake",
          meaning: "something very easy",
          example: "That test was a piece of cake!",
          context: "Describing difficulty",
          literal: "Not about actual cake",
          usageNotes: "Very common, used in casual conversation",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 3,
        },
        {
          idiom: "break the ice",
          meaning: "to start a conversation in a relaxed way",
          example: "He told a joke to break the ice at the meeting.",
          context: "Social situations",
          literal: "Not about actual ice",
          usageNotes: "Used in social or professional settings",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 3,
        },
        {
          idiom: "under the weather",
          meaning: "feeling sick or unwell",
          example: "I'm feeling a bit under the weather today.",
          context: "Health and well-being",
          literal: "Not about actual weather",
          usageNotes: "Polite way to say you're not feeling well",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 3,
        },
        {
          idiom: "hit the nail on the head",
          meaning: "to describe exactly what is causing a situation",
          example: "You hit the nail on the head with that analysis.",
          context: "Agreement and accuracy",
          literal: "Not about actual nails",
          usageNotes:
            "Used to express agreement with someone's accurate assessment",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 3,
        },
        {
          idiom: "let the cat out of the bag",
          meaning: "to reveal a secret",
          example: "He let the cat out of the bag about the surprise party.",
          context: "Secrets and revelations",
          literal: "Not about actual cats",
          usageNotes:
            "Often used when someone accidentally reveals information",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 3,
        },
      ],
      learningTips: [
        "Learn idioms in context, not in isolation",
        "Understand both literal and figurative meanings",
        "Practice using them in conversations",
        "Pay attention to when native speakers use them",
        "Learn the cultural background of idioms",
      ],
      vocabularyFocus: [
        "Figurative expressions",
        "Common metaphorical phrases",
        "Context-appropriate usage",
        "Cultural references",
      ],
      culturalNotes: [
        "Many idioms have historical origins",
        "Some idioms are becoming less common",
        "Regional variations exist within countries",
      ],
      practiceScenarios: [
        "Workplace conversations",
        "Social gatherings",
        "Academic discussions",
        "Media consumption",
      ],
      commonMistakes: [
        "Using idioms in wrong contexts",
        "Not understanding cultural references",
        "Overusing idioms in formal writing",
      ],
      assessmentCriteria: [
        "Can use idioms appropriately in context",
        "Understands figurative vs literal meaning",
        "Can explain idioms to others",
      ],
      recommendedStudyTime: "4-5 hours per week",
      prerequisites: [
        "A2 level conversational skills",
        "Understanding of basic figurative language",
        "Comfort with casual conversation",
      ],
      nextLevelPreparation: [
        "Learn more complex idiomatic expressions",
        "Study idioms for specific contexts",
        "Begin understanding subtle nuances",
      ],
    },
    B2: {
      description:
        "Upper-intermediate idioms for complex communication - Mastering contextual usage",
      examples: [
        {
          idiom: "burn the midnight oil",
          meaning: "to work late into the night",
          example: "She had to burn the midnight oil to finish her thesis.",
          context: "Work and study",
          literal: "Not about actual oil",
          usageNotes: "Used to describe intense work or study sessions",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 4,
        },
        {
          idiom: "pull your weight",
          meaning: "to do your fair share of work",
          example: "Everyone needs to pull their weight in this project.",
          context: "Work and responsibility",
          literal: "Not about actual weight",
          usageNotes: "Often used in team or group situations",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 4,
        },
        {
          idiom: "learn the ropes",
          meaning: "to learn how to do a job or activity",
          example: "It took me a few weeks to learn the ropes at my new job.",
          context: "Learning and adaptation",
          literal: "Not about actual ropes",
          usageNotes: "Used when starting something new",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 4,
        },
        {
          idiom: "give it your best shot",
          meaning: "to try as hard as you can",
          example: "Just give it your best shot and see what happens.",
          context: "Effort and determination",
          literal: "Not about actual shooting",
          usageNotes: "Encouraging expression, often used before challenges",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 4,
        },
        {
          idiom: "beat around the bush",
          meaning: "to avoid talking about something directly",
          example: "Stop beating around the bush and tell me what happened.",
          context: "Communication style",
          literal: "Not about actual bushes",
          usageNotes: "Often used when someone is being evasive",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 4,
        },
      ],
      learningTips: [
        "Learn idioms for specific contexts (work, study, social)",
        "Understand subtle differences between similar idioms",
        "Practice using them in complex sentences",
        "Study idioms in authentic materials",
        "Pay attention to register and formality",
      ],
      vocabularyFocus: [
        "Professional and academic idioms",
        "Context-specific expressions",
        "Nuanced meanings",
        "Register-appropriate usage",
      ],
      culturalNotes: [
        "Workplace idioms reflect corporate culture",
        "Academic idioms show educational background",
        "Some idioms are industry-specific",
      ],
      practiceScenarios: [
        "Professional meetings",
        "Academic presentations",
        "Complex social situations",
        "Media interviews",
      ],
      commonMistakes: [
        "Using idioms in wrong professional contexts",
        "Not understanding subtle differences",
        "Overusing idioms in formal settings",
      ],
      assessmentCriteria: [
        "Can use idioms appropriately in professional contexts",
        "Understands subtle differences between similar idioms",
        "Can adapt usage to different registers",
      ],
      recommendedStudyTime: "5-6 hours per week",
      prerequisites: [
        "B1 level idiomatic understanding",
        "Professional communication skills",
        "Understanding of different registers",
      ],
      nextLevelPreparation: [
        "Learn advanced idiomatic expressions",
        "Study idioms for sophisticated contexts",
        "Begin understanding cultural nuances",
      ],
    },
    C1: {
      description:
        "Advanced idioms for sophisticated communication - Native-like proficiency",
      examples: [
        {
          idiom: "the ball is in your court",
          meaning: "it's your turn to make a decision or take action",
          example: "I've made my offer, so the ball is in your court now.",
          context: "Decision-making and responsibility",
          literal: "Not about actual sports",
          usageNotes:
            "Often used in negotiations or decision-making situations",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 5,
        },
        {
          idiom: "throw in the towel",
          meaning: "to give up or admit defeat",
          example:
            "After three failed attempts, he finally threw in the towel.",
          context: "Surrender and acceptance",
          literal: "Not about actual towels",
          usageNotes: "Used when someone decides to stop trying",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 5,
        },
        {
          idiom: "hit the ground running",
          meaning: "to start something with great energy and enthusiasm",
          example: "She hit the ground running in her new role.",
          context: "Starting new activities",
          literal: "Not about actual running",
          usageNotes: "Used to describe immediate success in new situations",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 5,
        },
        {
          idiom: "think outside the box",
          meaning: "to think creatively and find new solutions",
          example: "We need to think outside the box to solve this problem.",
          context: "Creativity and problem-solving",
          literal: "Not about actual boxes",
          usageNotes: "Very common in business and creative contexts",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 5,
        },
        {
          idiom: "get the ball rolling",
          meaning: "to start a process or activity",
          example: "Let's get the ball rolling on this project.",
          context: "Initiating activities",
          literal: "Not about actual balls",
          usageNotes: "Often used in meetings or project discussions",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 5,
        },
      ],
      learningTips: [
        "Master idioms for professional and academic contexts",
        "Understand nuanced meanings and cultural implications",
        "Use them naturally in complex discussions",
        "Study idioms in authentic academic and professional materials",
        "Practice with native speakers in sophisticated contexts",
      ],
      vocabularyFocus: [
        "Sophisticated idiomatic expressions",
        "Academic and professional idioms",
        "Cultural and historical references",
        "Nuanced usage patterns",
      ],
      culturalNotes: [
        "Many advanced idioms have historical origins",
        "Some idioms reflect specific cultural values",
        "Usage varies by generation and region",
      ],
      practiceScenarios: [
        "Academic presentations",
        "Professional negotiations",
        "Complex discussions",
        "Cultural exchanges",
      ],
      commonMistakes: [
        "Using idioms inappropriately in formal contexts",
        "Not understanding cultural implications",
        "Overusing idioms in academic writing",
      ],
      assessmentCriteria: [
        "Can use idioms naturally in sophisticated contexts",
        "Understands cultural and historical implications",
        "Can adapt usage to different audiences",
      ],
      recommendedStudyTime: "6-8 hours per week",
      prerequisites: [
        "B2 level idiomatic mastery",
        "Advanced communication skills",
        "Understanding of cultural contexts",
      ],
      nextLevelPreparation: [
        "Achieve native-like mastery",
        "Understand cultural nuances",
        "Use idioms creatively and appropriately",
      ],
    },
    C2: {
      description:
        "Mastery-level idioms for native-like proficiency - Cultural fluency",
      examples: [
        {
          idiom: "the elephant in the room",
          meaning: "an obvious problem that no one wants to discuss",
          example:
            "The budget cuts are the elephant in the room at this meeting.",
          context: "Unspoken issues",
          literal: "Not about actual elephants",
          usageNotes: "Used to describe uncomfortable but obvious topics",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 6,
        },
        {
          idiom: "bite the bullet",
          meaning: "to face a difficult situation bravely",
          example:
            "We'll just have to bite the bullet and tell them the truth.",
          context: "Facing difficulties",
          literal: "Not about actual bullets",
          usageNotes: "Used when accepting something unpleasant but necessary",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 6,
        },
        {
          idiom: "pull someone's leg",
          meaning: "to tease or joke with someone",
          example: "I'm just pulling your leg, don't take it seriously.",
          context: "Humor and teasing",
          literal: "Not about actual legs",
          usageNotes: "Used when joking or teasing someone",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 6,
        },
        {
          idiom: "the last straw",
          meaning: "the final problem that makes a situation unbearable",
          example: "When he was late again, that was the last straw.",
          context: "Breaking points",
          literal: "Not about actual straw",
          usageNotes: "Used to describe the final unacceptable action",
          formality: "neutral",
          region: ["All English-speaking countries"],
          difficulty: 6,
        },
        {
          idiom: "get cold feet",
          meaning: "to become nervous and want to back out of something",
          example: "She got cold feet about the wedding at the last minute.",
          context: "Nervousness and hesitation",
          literal: "Not about actual feet temperature",
          usageNotes: "Used when someone becomes nervous about a commitment",
          formality: "informal",
          region: ["All English-speaking countries"],
          difficulty: 6,
        },
      ],
      learningTips: [
        "Achieve native-like mastery of idiomatic expressions",
        "Understand cultural nuances and historical origins",
        "Use them creatively and appropriately in all contexts",
        "Study idioms in literature and sophisticated media",
        "Practice with native speakers in all contexts",
      ],
      vocabularyFocus: [
        "Mastery of all idiomatic expressions",
        "Cultural and historical understanding",
        "Creative and appropriate usage",
        "Native-like fluency",
      ],
      culturalNotes: [
        "C2 level requires deep cultural understanding",
        "Many idioms reflect historical events",
        "Usage shows cultural sophistication",
      ],
      practiceScenarios: [
        "All communication contexts",
        "Cultural exchanges",
        "Sophisticated discussions",
        "Creative expression",
      ],
      commonMistakes: [
        "Rare at this level",
        "Occasional overuse in formal contexts",
        "Minor cultural misunderstandings",
      ],
      assessmentCriteria: [
        "Native-like mastery of idiomatic expressions",
        "Deep cultural understanding",
        "Creative and appropriate usage",
      ],
      recommendedStudyTime: "8-10 hours per week",
      prerequisites: [
        "C1 level idiomatic mastery",
        "Native-like communication skills",
        "Deep cultural understanding",
      ],
      nextLevelPreparation: [
        "Maintain and refine skills",
        "Continue cultural learning",
        "Use idioms creatively",
      ],
    },
  },
  types: {
    "Everyday Idioms": [
      "break the ice",
      "hit the nail on the head",
      "under the weather",
      "a piece of cake",
      "let the cat out of the bag",
    ],
    Proverbs: [
      "Actions speak louder than words",
      "The early bird catches the worm",
      "When in Rome, do as the Romans do",
    ],
    "Slang/Informal Idioms": [
      "hang out",
      "beat around the bush",
      "chill out",
      "hit the books",
    ],
    "Fixed Phrases/Chunks": [
      "at the end of the day",
      "by and large",
      "in the long run",
    ],
    "Work/Study Idioms": [
      "pull your weight",
      "learn the ropes",
      "give it your best shot",
      "burn the midnight oil",
    ],
  },
  examples: [
    {
      idiom: "a piece of cake",
      meaning: "something very easy",
      example: "That test was a piece of cake!",
    },
    {
      idiom: "break the ice",
      meaning: "to start a conversation in a relaxed way",
      example: "He told a joke to break the ice at the meeting.",
    },
    {
      idiom: "burn the midnight oil",
      meaning: "to work late into the night",
      example: "She had to burn the midnight oil to finish her thesis.",
    },
    {
      idiom: "under the weather",
      meaning: "feeling sick or unwell",
      example: "I'm feeling a bit under the weather today.",
    },
    {
      idiom: "let the cat out of the bag",
      meaning: "to reveal a secret",
      example: "He let the cat out of the bag about the surprise party.",
    },
  ],
  recognitionTips: [
    "Idioms often can't be understood word-for-word (non-literal).",
    "Usually used more in speaking and informal writing.",
    "Native speakers use them naturally without explaining the meaning.",
    "Context is crucial for understanding idiomatic expressions.",
    "Many idioms have historical or cultural origins.",
  ],
  commonErrors: [
    "Using idioms incorrectly or in the wrong context.",
    "Translating idioms directly from your native language.",
    "Overusing idioms – makes the speech sound unnatural or forced.",
    "Using formal idioms in casual contexts and vice versa.",
    "Not understanding cultural implications of idioms.",
  ],
  ieltsTips: {
    "Band7+": "Using a few well-chosen idioms naturally can impress examiners.",
    AvoidCliché:
      "Use idioms that are relevant and fit the context – don't force them.",
    Practice:
      "Listen to native speakers, learn idioms in context, and apply them in mock speaking.",
  },
  learningResources: [
    {
      type: "book",
      title: "English Idioms in Use",
      author: "Michael McCarthy, Felicity O'Dell",
      description:
        "Comprehensive guide to English idioms with exercises and practice",
      level: ["B1", "B2", "C1"],
      cost: "$25-30",
      rating: 4.8,
      keyFeatures: [
        "Organized by topic and difficulty",
        "Includes practice exercises",
        "CD with audio examples",
        "Suitable for self-study",
      ],
    },
    {
      type: "website",
      title: "The Free Dictionary - Idioms",
      url: "https://idioms.thefreedictionary.com/",
      description:
        "Extensive online database of English idioms with meanings and examples",
      level: ["A2", "B1", "B2", "C1", "C2"],
      cost: "Free",
      rating: 4.5,
      keyFeatures: [
        "Searchable database",
        "Multiple examples per idiom",
        "User-contributed content",
        "Mobile-friendly",
      ],
    },
    {
      type: "app",
      title: "Idioms and Phrases",
      description:
        "Mobile app for learning English idioms with quizzes and flashcards",
      level: ["A2", "B1", "B2"],
      cost: "Free with premium features",
      rating: 4.3,
      keyFeatures: [
        "Flashcard learning system",
        "Quiz mode",
        "Offline access",
        "Progress tracking",
      ],
    },
    {
      type: "course",
      title: "Coursera - English for Business and Entrepreneurship",
      description:
        "University-level course covering business idioms and expressions",
      level: ["B2", "C1"],
      cost: "Free to audit, $49 for certificate",
      rating: 4.6,
      keyFeatures: [
        "University-level instruction",
        "Business context focus",
        "Peer-reviewed assignments",
        "Certificate upon completion",
      ],
    },
    {
      type: "video",
      title: "BBC Learning English - The English We Speak",
      url: "https://www.bbc.co.uk/learningenglish/english/features/the-english-we-speak",
      description:
        "Weekly video series explaining common English idioms and expressions",
      level: ["B1", "B2", "C1"],
      cost: "Free",
      rating: 4.7,
      keyFeatures: [
        "Regular new content",
        "Native speaker explanations",
        "Cultural context included",
        "Downloadable transcripts",
      ],
    },
  ],
  culturalContext: {
    americanIdioms: [
      "hit the road",
      "break a leg",
      "piece of cake",
      "hit the nail on the head",
    ],
    britishIdioms: [
      "Bob's your uncle",
      "not my cup of tea",
      "cheeky monkey",
      "keep your pecker up",
    ],
    australianIdioms: [
      "fair dinkum",
      "no worries",
      "she'll be right",
      "good on ya",
    ],
    canadianIdioms: ["eh", "double-double", "toque", "poutine"],
    historicalOrigins: {
      "break a leg":
        "Theater superstition - wishing good luck by saying the opposite",
      "piece of cake": "From the 1930s, meaning something easy to accomplish",
      "hit the nail on the head": "From carpentry, meaning to be exactly right",
      "let the cat out of the bag":
        "From medieval markets where pigs were sold in bags, but cats were substituted",
    },
    modernUsage: {
      "break a leg": "Used to wish good luck, especially in performing arts",
      "piece of cake": "Very common in casual conversation",
      "hit the nail on the head": "Used in both casual and formal contexts",
      "let the cat out of the bag":
        "Used when secrets are accidentally revealed",
    },
  },
  difficultyProgression: {
    beginner: {
      focus: [
        "Basic polite expressions",
        "Simple greetings and farewells",
        "Common courtesy phrases",
      ],
      timeToMaster: "2-3 months",
      practiceMethods: [
        "Daily conversation practice",
        "Role-playing scenarios",
        "Listening to native speakers",
      ],
    },
    intermediate: {
      focus: [
        "Figurative expressions",
        "Context-appropriate usage",
        "Cultural understanding",
      ],
      timeToMaster: "6-12 months",
      practiceMethods: [
        "Reading authentic materials",
        "Watching movies and TV shows",
        "Conversation with native speakers",
      ],
    },
    advanced: {
      focus: [
        "Sophisticated expressions",
        "Cultural nuances",
        "Creative usage",
      ],
      timeToMaster: "1-2 years",
      practiceMethods: [
        "Academic and professional contexts",
        "Cultural immersion",
        "Creative writing and speaking",
      ],
    },
  },
};
