import { politeVsDirectLanguageType } from "@/types/grammars/grammar/communication_advance/politeVsDirectLanguage";

export const politeVsDirectLanguageData: politeVsDirectLanguageType = {
  id: 21,
  topic: "Ngôn ngữ lịch sự vs. trực tiếp (Polite vs. Direct Language)",
  levels: ["A1", "A2", "B1", "B2", "C1", "C2"],
  description:
    "Sự khác biệt giữa cách dùng ngôn ngữ lịch sự và trực tiếp trong giao tiếp tiếng Anh. Ngôn ngữ lịch sự thường được dùng để thể hiện sự tôn trọng, lịch thiệp, còn ngôn ngữ trực tiếp thường mang tính rõ ràng, nhanh gọn nhưng đôi khi có thể bị coi là thô lỗ nếu không đúng ngữ cảnh.",

  definitions: {
    politeLanguage: {
      definition:
        "Polite language refers to linguistic choices that show respect, consideration, and social awareness. It involves using indirect expressions, softening devices, and formal structures to maintain positive relationships and avoid causing offense.",
      characteristics: [
        "Uses indirect speech acts and implications",
        "Employs modal verbs for uncertainty and respect",
        "Contains hedging and softening devices",
        "Shows consideration for the listener's feelings",
        "Maintains social harmony and face-saving",
        "Often longer and more complex structures",
        "Demonstrates cultural and social awareness",
      ],
      purposes: [
        "Maintain positive social relationships",
        "Show respect and consideration",
        "Avoid causing offense or embarrassment",
        "Create comfortable communication environment",
        "Demonstrate cultural competence",
        "Build trust and rapport",
        "Handle sensitive topics diplomatically",
      ],
    },
    directLanguage: {
      definition:
        "Direct language involves straightforward, explicit communication that prioritizes clarity and efficiency over social niceties. It expresses meaning clearly without ambiguity or unnecessary softening.",
      characteristics: [
        "Uses explicit and clear statements",
        "Employs shorter, simpler sentence structures",
        "Contains strong modal verbs (must, should)",
        "Prioritizes efficiency over social considerations",
        "Uses imperative forms and direct commands",
        "Minimal use of hedging or softening",
        "Focuses on task completion and results",
      ],
      purposes: [
        "Ensure clear understanding",
        "Save time and increase efficiency",
        "Provide immediate feedback",
        "Give precise instructions",
        "Handle urgent situations",
        "Express strong opinions or emotions",
        "Establish authority or leadership",
      ],
    },
  },

  usage: {
    polite: {
      functions: [
        "Yêu cầu lịch sự (making polite requests)",
        "Đề nghị giúp đỡ (offering help politely)",
        "Từ chối lịch sự (polite refusal)",
        "Tránh xung đột (avoiding confrontation)",
        "Phàn nàn một cách lịch sự (making polite complaints)",
        "Thể hiện ý kiến một cách nhẹ nhàng (softening opinions)",
        "Đưa ra lời khuyên nhẹ nhàng (gentle advice)",
        "Xin lỗi và bày tỏ sự hối tiếc (apologizing and expressing regret)",
        "Đưa ra lời mời một cách trang trọng (making formal invitations)",
        "Thương lượng và thảo luận (negotiating and discussing)",
      ],
      typicalStructures: [
        "Would you mind...?",
        "Could you possibly...?",
        "I was wondering if...",
        "Would it be possible to...?",
        "Would you be so kind as to...?",
        "I'm afraid I can't...",
        "I'd appreciate it if you could...",
        "May I suggest that...?",
        "It would be great if...",
        "I hope you don't mind my asking...",
      ],
      modalVerbsUsed: [
        "could",
        "would",
        "may",
        "might",
        "shall (formal offers)",
        "ought to",
        "would rather",
      ],
      hedgingWords: [
        "perhaps",
        "maybe",
        "a bit",
        "kind of",
        "sort of",
        "rather",
        "quite",
        "somewhat",
        "fairly",
        "relatively",
      ],
      softeners: [
        "I'm not sure, but...",
        "It seems that...",
        "It might be better if...",
        "I tend to think that...",
        "If I may say so...",
        "With all due respect...",
        "I believe...",
        "In my opinion...",
      ],
      politenessPhrases: [
        "Please",
        "Thank you",
        "If you don't mind",
        "Excuse me",
        "I'm sorry to bother you",
        "Would you be so kind",
        "I'd be grateful if",
        "If it's not too much trouble",
        "At your convenience",
        "When you have a moment",
      ],
      indirectSpeechActs: [
        "It's rather warm in here (request to open window)",
        "I wonder if you could help me (request for assistance)",
        "That's an interesting point of view (polite disagreement)",
        "Perhaps we could consider another option (suggestion)",
        "I'm having trouble understanding this (request for explanation)",
        "It might be helpful if... (gentle advice)",
        "I was hoping you might... (polite request)",
      ],
    },

    direct: {
      functions: [
        "Yêu cầu nhanh gọn (giving quick requests)",
        "Ra lệnh hoặc hướng dẫn (giving orders/instructions)",
        "Nêu ý kiến thẳng thắn (stating opinions directly)",
        "Phản hồi tức thì (immediate feedback)",
        "Phàn nàn rõ ràng (clear complaints)",
        "Đưa ra quyết định cuối cùng (making final decisions)",
        "Thể hiện sự không đồng ý mạnh mẽ (strong disagreement)",
        "Yêu cầu hành động ngay lập tức (demanding immediate action)",
      ],
      typicalStructures: [
        "Give me that.",
        "Do it now.",
        "I want you to...",
        "This is wrong.",
        "That's not true.",
        "You're wrong.",
        "Tell me the answer.",
        "Stop doing that.",
        "Listen to me.",
        "Pay attention.",
      ],
      modalVerbsUsed: [
        "must",
        "have to",
        "need to",
        "should (strong)",
        "will",
        "shall (commands)",
      ],
      intensifiers: [
        "absolutely",
        "totally",
        "completely",
        "really",
        "definitely",
        "certainly",
        "obviously",
        "clearly",
      ],
      commandForms: [
        "Imperatives (Do it!)",
        "Short directives (Now! Hurry!)",
        "Direct questions (What are you doing?)",
        "Statements of fact (You need to...)",
      ],
      directSpeechActs: [
        "Open the window (direct command)",
        "Help me with this (direct request)",
        "I disagree with you (direct disagreement)",
        "You should do this instead (direct advice)",
        "Explain this to me (direct demand)",
        "That's wrong (direct criticism)",
        "I want this done now (direct order)",
      ],
    },
  },

  comparison: {
    keyDifferences: [
      {
        point: "Cấu trúc",
        polite: "Sử dụng cấu trúc dài, phức tạp hơn và nhiều modal verbs mềm",
        direct: "Cấu trúc ngắn, đơn giản, rõ ràng",
      },
      {
        point: "Tông giọng",
        polite: "Âm điệu nhẹ nhàng, giảm thiểu rủi ro gây xúc phạm",
        direct: "Âm điệu rõ ràng, dứt khoát, có thể gây áp lực",
      },
      {
        point: "Ngữ cảnh sử dụng",
        polite:
          "Sử dụng trong môi trường chuyên nghiệp, với người lạ, người lớn tuổi",
        direct:
          "Sử dụng với bạn bè thân thiết, người dưới cấp, hoặc trong tình huống khẩn cấp",
      },
      {
        point: "Hiệu quả giao tiếp",
        polite: "Ưu tiên mối quan hệ và sự hòa hợp xã hội",
        direct: "Ưu tiên rõ ràng thông tin và hiệu quả công việc",
      },
    ],
    appropriatenessFactors: [
      "Relationship between speakers (formal vs informal)",
      "Power dynamics (superior to subordinate)",
      "Cultural background and expectations",
      "Urgency of the situation",
      "Professional vs personal context",
      "Age and social status differences",
      "Purpose of communication",
      "Potential consequences of miscommunication",
    ],
    culturalConsiderations: [
      "In Anglo cultures, indirect politeness is often preferred in professional settings",
      "Asian cultures may favor more indirect communication styles",
      "Germanic cultures may appreciate directness in business contexts",
      "Mediterranean cultures often blend directness with emotional expression",
      "Understanding face-saving concepts in different cultures",
      "Awareness of high-context vs low-context communication preferences",
    ],
  },

  levelsByCEFR: {
    A1: {
      description: "Sử dụng cấu trúc yêu cầu cơ bản lịch sự hoặc trực tiếp.",
      keyLearningObjectives: [
        "Recognize basic polite expressions (please, thank you)",
        "Use simple modal verbs (can, could) for polite requests",
        "Distinguish between direct commands and polite requests",
        "Understand when to use 'please' and 'thank you'",
        "Learn basic greeting and farewell expressions",
        "Practice basic apologizing (sorry, excuse me)",
      ],
      examples: {
        polite: [
          "Can I have a pen, please?",
          "Please help me.",
          "Could you open the door?",
          "Thank you very much.",
          "Excuse me, where is the bathroom?",
          "Sorry, I don't understand.",
        ],
        direct: [
          "Give me a pen.",
          "Help me.",
          "Open the door.",
          "Thanks.",
          "Where is the bathroom?",
          "I don't understand.",
        ],
      },
      vocabulary: {
        polite: [
          "please",
          "thank you",
          "excuse me",
          "sorry",
          "could you",
          "can I",
          "would you",
          "may I",
          "pardon me",
          "I'm sorry",
        ],
        direct: [
          "give",
          "help",
          "open",
          "close",
          "come",
          "go",
          "stop",
          "start",
          "tell me",
          "show me",
        ],
      },
      commonPatterns: {
        polite: [
          "Can I + verb + please?",
          "Could you + verb + please?",
          "Please + verb",
          "Thank you + for + noun/gerund",
          "Excuse me + statement/question",
          "Sorry + for + noun/gerund",
        ],
        direct: [
          "Imperative + object",
          "I want + noun",
          "Give me + noun",
          "Tell me + question word",
          "Show me + noun",
          "Help me + infinitive",
        ],
      },
      culturalNotes: [
        "Always say 'please' when asking for something",
        "Use 'thank you' when someone helps you",
        "Say 'excuse me' before asking a question to strangers",
        "'Sorry' is used for small inconveniences",
        "Smiling helps make requests sound more polite",
        "Direct commands without 'please' may sound rude",
      ],
    },

    A2: {
      description: "Biết phân biệt yêu cầu nhẹ nhàng hơn và trực tiếp hơn.",
      keyLearningObjectives: [
        "Use 'would like' for polite requests and preferences",
        "Understand the difference between 'can' and 'could' for politeness",
        "Learn to soften requests with 'maybe' and 'perhaps'",
        "Practice making suggestions politely",
        "Use appropriate intonation for polite vs direct speech",
        "Learn basic phrases for declining politely",
      ],
      examples: {
        polite: [
          "Could you help me with this?",
          "I'd like some coffee.",
          "Would you mind closing the window?",
          "Perhaps we could meet tomorrow?",
          "I'm sorry, but I can't come today.",
          "That sounds like a good idea.",
        ],
        direct: [
          "I want coffee.",
          "Help me now.",
          "Close the window.",
          "Let's meet tomorrow.",
          "I can't come today.",
          "Good idea.",
        ],
      },
      vocabulary: {
        polite: [
          "would like",
          "could you",
          "would you mind",
          "perhaps",
          "maybe",
          "I'm afraid",
          "I'm sorry but",
          "that sounds",
          "if possible",
        ],
        direct: [
          "I want",
          "I need",
          "you must",
          "you should",
          "don't",
          "can't",
          "won't",
          "listen",
          "look",
          "wait",
        ],
      },
      commonPatterns: {
        polite: [
          "I'd like + noun/to infinitive",
          "Would you mind + gerund?",
          "Perhaps + we/you + could + verb",
          "I'm afraid + I can't + verb",
          "That sounds + adjective",
          "If possible, + request",
        ],
        direct: [
          "I want + noun",
          "You should + verb",
          "Don't + verb",
          "I can't + verb",
          "You need to + verb",
          "Let's + verb",
        ],
      },
      culturalNotes: [
        "Use 'would like' instead of 'want' in polite situations",
        "'Could' is more polite than 'can' for requests",
        "Add 'perhaps' or 'maybe' to make suggestions softer",
        "Use 'I'm afraid' to soften negative responses",
        "Intonation rising at the end makes statements sound less direct",
        "Learn when directness is appropriate (emergencies, close friends)",
      ],
    },

    B1: {
      description:
        "Bắt đầu sử dụng các cấu trúc lịch sự dài hơn và biết tránh gây khó chịu.",
      keyLearningObjectives: [
        "Master longer polite structures with embedded clauses",
        "Use conditional forms for polite requests (would, could, might)",
        "Learn to express disagreement politely without causing offense",
        "Practice hedging language to soften strong statements",
        "Understand register switching between formal and informal contexts",
        "Develop awareness of cultural communication styles",
      ],
      examples: {
        polite: [
          "Would it be OK if I borrowed your book?",
          "I was wondering if you could help me.",
          "I don't suppose you'd be able to...",
          "I hope you don't mind my saying this, but...",
          "Would there be any chance of getting this done today?",
          "I'm not entirely convinced that this approach will work.",
        ],
        direct: [
          "Let me borrow your book.",
          "You should help me.",
          "Get this done today.",
          "This approach won't work.",
          "You're making a mistake.",
          "I disagree completely.",
        ],
      },
      vocabulary: {
        polite: [
          "I was wondering",
          "I don't suppose",
          "would there be",
          "I hope you don't mind",
          "not entirely",
          "tend to think",
          "it seems to me",
          "as far as I know",
        ],
        direct: [
          "you should",
          "you need to",
          "that's wrong",
          "I disagree",
          "definitely not",
          "absolutely",
          "completely",
          "totally",
        ],
      },
      commonPatterns: {
        polite: [
          "I was wondering if + subject + could + verb",
          "Would there be any chance of + gerund?",
          "I hope you don't mind + gerund",
          "I'm not entirely + adjective + that + clause",
          "I tend to think + that + clause",
          "It seems to me + that + clause",
        ],
        direct: [
          "You should + verb",
          "That's + adjective (wrong/stupid)",
          "I disagree + with + noun",
          "Definitely + not/yes",
          "You need to + verb",
          "Stop + gerund",
        ],
      },
      culturalNotes: [
        "Longer structures show more consideration and respect",
        "Hedging helps maintain relationships while expressing disagreement",
        "Cultural differences in directness become more apparent at this level",
        "Professional contexts require more polite language",
        "Learn to read social cues for appropriate register",
        "Understanding that some cultures prefer more indirect communication",
      ],
      advancedStructures: {
        polite: [
          "Conditional structures (If it wouldn't be too much trouble...)",
          "Embedded questions (I wonder if you might...)",
          "Negative questions (Don't you think...?)",
          "Tag questions for softening (That's right, isn't it?)",
          "Past tense for present politeness (I was hoping...)",
        ],
        direct: [
          "Imperative mood (Do this now!)",
          "Simple present statements (You are wrong)",
          "Strong modal auxiliaries (You must...)",
          "Short, clipped responses (No. Yes. Maybe.)",
          "Direct questions (Why did you do that?)",
        ],
      },
    },

    B2: {
      description:
        "Sử dụng tốt ngôn ngữ giảm nhẹ và thay đổi ngữ điệu trong giao tiếp chuyên nghiệp.",
      keyLearningObjectives: [
        "Master sophisticated hedging and diplomatic language",
        "Use indirect criticism and feedback effectively",
        "Develop skills in professional negotiation language",
        "Learn to manage difficult conversations diplomatically",
        "Understand subtle differences in register and appropriateness",
        "Practice code-switching between formal and informal styles",
      ],
      examples: {
        polite: [
          "I appreciate your help, but I think we should try another way.",
          "Would you mind explaining it again?",
          "While I see your point, I wonder if we might consider...",
          "I'm inclined to think that perhaps we could...",
          "Would it be possible to have a word with you about this?",
          "I hate to be the bearer of bad news, but...",
        ],
        direct: [
          "You're wrong. This is better.",
          "Explain again.",
          "That idea is terrible.",
          "We're doing it my way.",
          "I need to talk to you now.",
          "This is bad news.",
        ],
      },
      vocabulary: {
        polite: [
          "I appreciate",
          "while I see your point",
          "I'm inclined to think",
          "would it be possible",
          "I hate to be",
          "bearer of bad news",
          "I wonder if we might",
          "it strikes me that",
        ],
        direct: [
          "that's terrible",
          "that's ridiculous",
          "you're completely wrong",
          "I refuse to",
          "that's impossible",
          "forget it",
          "no way",
        ],
      },
      commonPatterns: {
        polite: [
          "While I + verb, I wonder if + clause",
          "I'm inclined to think + that + clause",
          "Would it be possible to + infinitive?",
          "I hate to + infinitive, but + clause",
          "It strikes me that + clause",
          "I appreciate + noun/gerund, but + clause",
        ],
        direct: [
          "That's + extremely + adjective",
          "I refuse to + infinitive",
          "There's no way + clause",
          "That's completely + adjective",
          "I won't + infinitive",
          "Forget about + gerund",
        ],
      },
      culturalNotes: [
        "Professional contexts require sophisticated diplomatic language",
        "Learn to give negative feedback without damaging relationships",
        "Understand power dynamics in workplace communication",
        "Cultural sensitivity becomes crucial in international business",
        "Master the art of saying 'no' politely",
        "Develop skills in conflict resolution through language",
      ],
      advancedStructures: {
        polite: [
          "Complex conditional sentences (If I were in your position...)",
          "Subjunctive mood (I suggest that he be...)",
          "Passive constructions to avoid blame (Mistakes were made...)",
          "Nominalization (Your consideration of this matter...)",
          "Euphemisms and understatement (slightly concerned, minor issue)",
        ],
        direct: [
          "Direct confrontation (You did this wrong)",
          "Blunt assessments (This is a disaster)",
          "Immediate imperatives (Fix this now)",
          "Stark alternatives (Either do this or leave)",
          "Unvarnished truth (The reality is...)",
        ],
      },
      professionalContext: {
        polite: [
          "Meeting language: 'Perhaps we could table this for now'",
          "Email politeness: 'I hope this email finds you well'",
          "Feedback delivery: 'There might be room for improvement in...'",
          "Negotiation: 'What would it take to make this work?'",
          "Conflict resolution: 'I understand your concerns, and...'",
        ],
        direct: [
          "Meeting language: 'This isn't working'",
          "Email directness: 'I need this today'",
          "Feedback delivery: 'This is wrong'",
          "Negotiation: 'Take it or leave it'",
          "Conflict resolution: 'You're not listening'",
        ],
      },
    },

    C1: {
      description:
        "Sử dụng ngôn ngữ lịch sự để thể hiện quan điểm, thuyết phục, từ chối, phản đối.",
      keyLearningObjectives: [
        "Master nuanced expressions of disagreement and criticism",
        "Use sophisticated diplomatic language for sensitive topics",
        "Develop expertise in persuasive and influential communication",
        "Learn to navigate complex social and professional hierarchies",
        "Understand subtle implications and subtext in communication",
        "Practice advanced register control and style switching",
      ],
      examples: {
        polite: [
          "While I understand your point, I believe there's another perspective.",
          "I'm afraid I can't agree with that entirely.",
          "With respect, I think there may be some room for discussion here.",
          "I wonder if I might venture to suggest an alternative approach.",
          "While your proposal has merit, I'm somewhat concerned about...",
          "I hope you'll forgive me for raising this, but...",
        ],
        direct: [
          "I disagree. That doesn't make sense.",
          "You're mistaken about that.",
          "That proposal is flawed.",
          "Here's a better way.",
          "That's a bad idea.",
          "You're wrong about this.",
        ],
      },
      vocabulary: {
        polite: [
          "with respect",
          "I wonder if I might venture",
          "has merit",
          "somewhat concerned",
          "you'll forgive me",
          "I'm somewhat skeptical",
          "it strikes me as",
          "I'm rather doubtful",
        ],
        direct: [
          "that's nonsense",
          "you're completely off base",
          "that's ridiculous",
          "I categorically reject",
          "that's unacceptable",
          "absolutely not",
        ],
      },
      commonPatterns: {
        polite: [
          "While + clause, I + adverb + verb + that + clause",
          "With respect, I think + there may be + noun + for + noun",
          "I wonder if I might venture to + infinitive",
          "While + noun + has + noun, I'm + adverb + adjective + about + noun",
          "I hope you'll forgive me for + gerund, but + clause",
          "I'm somewhat + adjective + that + clause",
        ],
        direct: [
          "I categorically + verb + noun",
          "That's + adverb + adjective",
          "You're completely + adjective + about + noun",
          "I + adverb + disagree with + noun",
          "That's + absolutely + adjective",
          "There's no + noun + that + clause",
        ],
      },
      culturalNotes: [
        "Master the art of diplomatic disagreement without offense",
        "Understand subtle power plays in communication",
        "Learn to read between the lines in professional discourse",
        "Develop sensitivity to face-saving in different cultures",
        "Practice sophisticated persuasion techniques",
        "Understand the role of politeness in maintaining professional relationships",
      ],
      advancedStructures: {
        polite: [
          "Litotes (not unimpressive, not entirely convinced)",
          "Tentative language (it would seem, appears to be)",
          "Complex hedging (to some extent, in certain respects)",
          "Diplomatic contradictions (Yes, but..., That's true, however...)",
          "Sophisticated modality (It might be worth considering...)",
        ],
        direct: [
          "Categorical statements (It is absolutely clear that...)",
          "Emphatic structures (What you need to understand is...)",
          "Direct challenges (I challenge that assumption)",
          "Unmitigated criticism (That approach is fundamentally flawed)",
          "Strong modal expressions (You must realize that...)",
        ],
      },
      professionalContext: {
        polite: [
          "Board meeting language: 'The board might wish to consider...'",
          "Diplomatic negotiations: 'We would be amenable to...'",
          "Academic discourse: 'The evidence suggests that...'",
          "Legal language: 'It is respectfully submitted that...'",
          "International relations: 'We would welcome the opportunity to...'",
        ],
        direct: [
          "Board meeting language: 'The board must decide now'",
          "Diplomatic negotiations: 'We demand...'",
          "Academic discourse: 'This proves that...'",
          "Legal language: 'The facts clearly show...'",
          "International relations: 'We insist that...'",
        ],
      },
      nuancedExpressions: {
        polite: [
          "Gradual disagreement: 'I'm not entirely convinced', 'I have some reservations'",
          "Diplomatic refusal: 'That might be challenging', 'I'm not sure that's feasible'",
          "Sophisticated suggestion: 'It might be worth exploring', 'Perhaps we could consider'",
          "Elegant correction: 'I believe there may be a misunderstanding', 'If I may clarify'",
          "Tactful criticism: 'There might be room for refinement', 'This could perhaps be strengthened'",
        ],
        direct: [
          "Blunt disagreement: 'That's wrong', 'I completely disagree'",
          "Direct refusal: 'No', 'That's impossible'",
          "Straightforward suggestion: 'Do this instead', 'Here's what we should do'",
          "Direct correction: 'You're mistaken', 'That's incorrect'",
          "Frank criticism: 'This is poor quality', 'This doesn't work'",
        ],
      },
    },

    C2: {
      description:
        "Điều chỉnh phong cách ngôn ngữ linh hoạt theo ngữ cảnh xã hội/phức tạp.",
      keyLearningObjectives: [
        "Achieve native-like control of register and style variation",
        "Master the most sophisticated forms of diplomatic communication",
        "Develop expertise in implicit and inferential communication",
        "Learn to manipulate linguistic choices for strategic effect",
        "Understand the full spectrum of politeness strategies across cultures",
        "Practice seamless code-switching in complex social situations",
      ],
      examples: {
        polite: [
          "With all due respect, I'd like to challenge that viewpoint.",
          "Might I suggest a different approach, if I may?",
          "I wonder if I might be permitted to offer an alternative perspective.",
          "While I wouldn't presume to question your expertise...",
          "If I may be so bold as to suggest...",
          "I trust you won't take it amiss if I venture to propose...",
        ],
        direct: [
          "That's not right and we need to fix it.",
          "I strongly oppose that view.",
          "Here's what we're going to do.",
          "Your expertise is questionable here.",
          "I'm going to be blunt.",
          "You're going to hate this, but...",
        ],
      },
      vocabulary: {
        polite: [
          "with all due respect",
          "might I be permitted",
          "wouldn't presume to",
          "if I may be so bold",
          "you won't take it amiss",
          "venture to propose",
          "I trust",
          "if I might make so bold",
          "with your permission",
        ],
        direct: [
          "I strongly oppose",
          "that's categorically wrong",
          "I'm going to be blunt",
          "you're going to hate this",
          "let me be frank",
          "to put it bluntly",
        ],
      },
      commonPatterns: {
        polite: [
          "With all due respect, I'd like to + infinitive + noun",
          "Might I + verb + noun, if I may?",
          "I wonder if I might be permitted to + infinitive",
          "While I wouldn't presume to + infinitive...",
          "If I may be so bold as to + infinitive...",
          "I trust you won't take it amiss if + clause",
        ],
        direct: [
          "I strongly + verb + noun",
          "That's categorically + adjective",
          "Let me be + adjective",
          "To put it bluntly, + clause",
          "I'm going to be + adjective",
          "You're going to + verb + this, but + clause",
        ],
      },
      culturalNotes: [
        "Master the highest levels of diplomatic language use",
        "Understand cultural variations in extreme politeness",
        "Learn to navigate the most complex social and political situations",
        "Develop sensitivity to historical and cultural contexts in communication",
        "Practice the most sophisticated forms of face-saving and face-threatening acts",
        "Achieve native-like intuition about appropriateness across all contexts",
      ],
      advancedStructures: {
        polite: [
          "Archaic politeness forms (If I may make so bold, With your kind permission)",
          "Elaborate circumlocution (The matter we discussed earlier might benefit from...)",
          "Sophisticated understatement (This presents certain challenges)",
          "Elaborate hedging (It would not be entirely unreasonable to suggest...)",
          "Classical rhetorical devices (If I may venture to submit...)",
        ],
        direct: [
          "Brutal honesty (This is a disaster, pure and simple)",
          "Aggressive confrontation (I'm calling you out on this)",
          "Unvarnished assessment (This is completely unacceptable)",
          "Stark ultimatums (Either fix this or find another job)",
          "Raw emotional expression (I'm furious about this)",
        ],
      },
      professionalContext: {
        polite: [
          "Diplomatic protocol: 'His Excellency would be gratified to learn...'",
          "High-level negotiations: 'We would be favorably disposed to consider...'",
          "Academic ceremony: 'It is my distinct honor and privilege to...'",
          "Corporate governance: 'The board would be well-advised to...'",
          "Legal proceedings: 'With the greatest respect to the court...'",
        ],
        direct: [
          "Diplomatic protocol: 'We reject this proposal outright'",
          "High-level negotiations: 'Take it or leave it'",
          "Academic ceremony: 'This person deserves recognition'",
          "Corporate governance: 'The board must act now'",
          "Legal proceedings: 'The evidence proves our case'",
        ],
      },
      nuancedExpressions: {
        polite: [
          "Exquisite disagreement: 'I find myself unable to concur with that assessment'",
          "Elaborate refusal: 'While the proposal has considerable merit, circumstances prevent...'",
          "Sophisticated criticism: 'The approach, while innovative, might benefit from refinement'",
          "Diplomatic warning: 'It might be prudent to consider the potential ramifications'",
          "Elegant persuasion: 'I wonder if you might find it advantageous to consider...'",
        ],
        direct: [
          "Brutal disagreement: 'That's complete nonsense'",
          "Blunt refusal: 'Absolutely not'",
          "Harsh criticism: 'This is amateurish work'",
          "Direct warning: 'You're making a huge mistake'",
          "Forceful persuasion: 'You need to do this now'",
        ],
      },
      sophisticatedRegister: {
        polite: [
          "Ceremonial language: 'It is with profound honor that I...'",
          "Diplomatic discourse: 'We would view with favor any initiative that...'",
          "Academic formality: 'The research would seem to indicate...'",
          "Legal precision: 'It is respectfully submitted that the evidence demonstrates...'",
          "Corporate diplomacy: 'The organization would benefit substantially from...'",
        ],
        direct: [
          "Ceremonial language: 'I'm proud to...'",
          "Diplomatic discourse: 'We support...'",
          "Academic formality: 'The research shows...'",
          "Legal precision: 'The evidence proves...'",
          "Corporate diplomacy: 'The company needs...'",
        ],
      },
    },
  },

  registerAwareness: {
    formalVsInformal: {
      formalPoliteExamples: [
        "Would you be able to clarify that for me, please?",
        "I was hoping you might assist me.",
        "I would be most grateful if you could...",
        "Might I trouble you to...",
        "I wonder if it would be possible to...",
      ],
      informalPoliteExamples: [
        "Could you give me a hand?",
        "Do you think you could help me out?",
        "Would you mind...?",
        "I was wondering if...",
        "Any chance you could...?",
      ],
      informalDirectExamples: [
        "Give me a hand.",
        "Tell me what's going on.",
        "Come here.",
        "What's up?",
        "Help me out.",
      ],
      formalDirectExamples: [
        "I require your assistance immediately.",
        "You must complete this today.",
        "This is unacceptable.",
        "I demand an explanation.",
        "Your attention is required.",
      ],
    },
    contextualFactors: [
      "Power relationships (boss to employee, teacher to student)",
      "Social distance (strangers, acquaintances, friends, family)",
      "Urgency of the situation (emergency vs routine)",
      "Cultural background of participants",
      "Professional vs personal setting",
      "Public vs private communication",
      "Written vs spoken communication",
      "Emotional state of speakers",
    ],
    appropriatenessGuidelines: [
      "Use formal politeness with strangers and in professional contexts",
      "Informal politeness works well with colleagues and acquaintances",
      "Informal directness is acceptable with close friends and family",
      "Formal directness may be needed in crisis situations or with authority",
      "Consider cultural expectations about hierarchy and respect",
      "Adjust for the specific communication context and purpose",
      "Monitor reactions and adjust accordingly",
      "When in doubt, err on the side of politeness",
    ],
  },

  strategies: {
    softenDirectness: [
      "Use modals (could, would, might)",
      "Add softeners ('just', 'a bit', 'maybe')",
      "Use questions instead of commands",
      "Use passive voice to depersonalize",
      "Use indirect language ('I wonder if…', 'Is there any chance…')",
      "Add hedging words (perhaps, possibly, probably)",
      "Use tentative language (seems, appears, tends to)",
      "Employ conditional structures (If you could..., It would be great if...)",
    ],
    beMoreDirect: [
      "Use imperatives",
      "Be concise and clear",
      "Drop hedging or modal language",
      "Use strong verbs (need, must, want)",
      "Employ present tense for immediacy",
      "Use short, simple sentences",
      "State facts without qualification",
      "Use active voice for clarity",
    ],
    registerSwitching: [
      "Monitor the social context continuously",
      "Observe how others are speaking",
      "Adjust formality level to match the situation",
      "Switch between registers within the same conversation",
      "Use discourse markers to signal register changes",
      "Practice code-switching between formal and informal styles",
      "Develop sensitivity to register mismatches",
      "Learn to repair register errors smoothly",
    ],
    contextualAdaptation: [
      "Assess power dynamics before speaking",
      "Consider cultural background of interlocutors",
      "Evaluate the urgency and importance of the message",
      "Adapt to the physical and social setting",
      "Monitor emotional temperature of the interaction",
      "Adjust for written vs spoken communication",
      "Consider potential consequences of communication choices",
      "Practice flexibility in communication style",
    ],
  },

  commonMistakes: [
    "Dùng ngôn ngữ quá trực tiếp trong tình huống cần lịch sự (ví dụ: với người lạ, sếp, thầy cô)",
    "Hiểu nhầm rằng nói ngắn gọn là thô lỗ, trong khi thực tế có thể điều chỉnh bằng tông giọng",
    "Không sử dụng softeners hoặc hedging khi đưa ra ý kiến phản đối",
    "Sử dụng register không phù hợp với ngữ cảnh (quá formal hoặc quá informal)",
    "Không nhận biết được cultural expectations về politeness",
    "Overusing 'please' và 'sorry' đến mức mất đi ý nghĩa",
    "Sử dụng direct language khi cần diplomacy trong professional settings",
    "Mixing registers inappropriately within the same conversation",
    "Không thích ứng với power dynamics trong giao tiếp",
    "Sử dụng polite language trong emergency situations khi cần directness",
  ],

  learningTips: [
    "Quan sát cách nói của người bản xứ trong các tình huống trang trọng và thân mật.",
    "Luyện tập viết lại câu trực tiếp thành câu lịch sự.",
    "Ghi chú lại những cụm từ mềm hóa bạn thấy trong email, phim, hội thoại.",
    "Chọn lựa ngôn ngữ theo người nghe: bạn bè hay đồng nghiệp/sếp.",
    "Sử dụng công cụ AI hoặc bạn học để luyện đối thoại với 2 vai trò: lịch sự & trực tiếp.",
    "Practice register switching exercises regularly",
    "Record yourself speaking in different styles and analyze the differences",
    "Study email communication styles in professional contexts",
    "Watch business meetings and diplomatic negotiations for advanced examples",
    "Practice saying 'no' politely in various scenarios",
    "Learn to give feedback diplomatically",
    "Develop cultural awareness through international communication experiences",
  ],

  practiceActivities: {
    A1: [
      "Role-play basic shopping scenarios with polite requests",
      "Practice greeting and thanking in different situations",
      "Convert direct commands to polite requests using 'please'",
      "Practice basic apologies and excuses",
      "Learn telephone politeness basics",
    ],
    A2: [
      "Practice making suggestions using 'perhaps' and 'maybe'",
      "Role-play declining invitations politely",
      "Convert 'I want' statements to 'I would like'",
      "Practice asking for help in different ways",
      "Learn basic email politeness formulas",
    ],
    B1: [
      "Practice hedging in opinion exchanges",
      "Role-play giving negative feedback diplomatically",
      "Practice register switching in workplace scenarios",
      "Learn to disagree without offending",
      "Practice making complaints politely",
    ],
    B2: [
      "Advanced negotiation role-plays",
      "Practice diplomatic criticism in team meetings",
      "Learn to manage difficult conversations",
      "Practice professional presentation styles",
      "Advanced email and formal letter writing",
    ],
    C1: [
      "Practice high-level diplomatic language",
      "Advanced debate and argumentation with politeness",
      "Practice giving presentations to senior executives",
      "Learn to navigate complex social hierarchies",
      "Practice cross-cultural communication strategies",
    ],
    C2: [
      "Master ceremonial and formal speech styles",
      "Practice the most sophisticated diplomatic negotiations",
      "Learn historical and cultural politeness variations",
      "Practice seamless register control in complex scenarios",
      "Master implicit and inferential communication",
    ],
  },

  assessmentCriteria: {
    appropriateness: [
      "Matches register to context and relationship",
      "Shows cultural sensitivity and awareness",
      "Demonstrates understanding of power dynamics",
      "Uses appropriate level of formality",
      "Shows awareness of social distance",
    ],
    clarity: [
      "Message is understood despite politeness strategies",
      "Balances politeness with communicative efficiency",
      "Uses clear structure even in complex polite forms",
      "Avoids ambiguity while maintaining politeness",
      "Achieves communicative goals effectively",
    ],
    effectiveness: [
      "Maintains positive relationships while communicating",
      "Achieves desired outcomes through appropriate style",
      "Demonstrates flexibility in communication approach",
      "Shows sensitivity to listener's reactions",
      "Adapts style when initial approach is ineffective",
    ],
  },

  references: [
    {
      title: "Politeness: Some universals in language usage",
      author: "Penelope Brown and Stephen Levinson",
      publisher: "Cambridge University Press",
      year: 1987,
      type: "book",
      description:
        "Foundational work on politeness theory and cross-cultural communication strategies.",
    },
    {
      title: "The Cambridge Encyclopedia of the English Language",
      author: "David Crystal",
      publisher: "Cambridge University Press",
      year: 2019,
      type: "book",
      description:
        "Comprehensive guide to English language use including register and style variation.",
    },
    {
      title: "English Grammar in Use",
      author: "Raymond Murphy",
      publisher: "Cambridge University Press",
      year: 2019,
      type: "book",
      description:
        "Practical grammar guide with extensive coverage of modal verbs and polite expressions.",
    },
    {
      title: "Oxford Word Skills – Advanced",
      author: "Ruth Gairns and Stuart Redman",
      publisher: "Oxford University Press",
      year: 2018,
      type: "book",
      description:
        "Advanced vocabulary and expressions for sophisticated communication styles.",
    },
    {
      title: "Common European Framework of Reference for Languages (CEFR)",
      author: "Council of Europe",
      publisher: "Cambridge University Press",
      year: 2020,
      type: "book",
      description:
        "Official guidelines for language learning including pragmatic competence and register control.",
    },
    {
      title: "Speaking Politely - British Council",
      url: "https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/polite-requests",
      type: "website",
      description:
        "Comprehensive online resource for learning polite English expressions and cultural norms.",
    },
    {
      title: "Business English Communication",
      author: "Mary Ellen Guffey and Dana Loewy",
      publisher: "Cengage Learning",
      year: 2021,
      type: "book",
      description:
        "Professional communication guide focusing on diplomatic and effective business language.",
    },
    {
      title: "Intercultural Communication: A Discourse Approach",
      author: "Ron Scollon and Suzanne Wong Scollon",
      publisher: "Wiley-Blackwell",
      year: 2012,
      type: "book",
      description:
        "Academic text on cross-cultural communication patterns and politeness strategies.",
    },
    {
      title: "VOA Learning English - How to Be Polite",
      url: "https://learningenglish.voanews.com/z/4692",
      type: "website",
      description:
        "Free online resource with audio examples of polite vs direct communication styles.",
    },
    {
      title: "Cambridge Assessment English - Language Functions",
      url: "https://www.cambridgeenglish.org/learning-english/",
      type: "website",
      description:
        "Official Cambridge resource for learning language functions including politeness strategies.",
    },
  ],
};
