import { CollectiveNounsType } from "@/types/grammars/grammar/noun_special/collective_nouns";

// Comprehensive Collective Nouns Data (A1-C2)
export const CollectiveNounsData: CollectiveNounsType = {
  id: 36,
  definition: {
    core_concept:
      "Collective nouns refer to a group of people, animals, or things considered as a single unit.",
    grammatical_status:
      "Collective nouns can take either singular or plural verb agreement depending on whether the group is seen as a unit or as individuals.",
    linguistic_significance:
      "They allow speakers to refer to multiple entities as a single entity, and their verb agreement can vary by dialect and context.",
    detailed_explanation:
      "Collective nouns represent one of the most fascinating aspects of English grammar, embodying the language's flexibility in conceptualizing groups. These nouns function as semantic bridges between singular and plural concepts, allowing speakers to treat multiple entities as unified wholes while maintaining the option to emphasize individual members. The complexity arises from their dual nature: morphologically singular but semantically plural, creating unique challenges in verb agreement, pronoun reference, and determiner selection. This duality reflects deeper cognitive processes about how humans categorize and perceive group entities in social, natural, and abstract domains.",
    etymology:
      "The term 'collective noun' derives from Latin 'collectivus' (gathered together) and represents an ancient linguistic universal found across Indo-European languages. Many English collective nouns trace their origins to Old English, Old French, and Latin, reflecting historical social structures, hunting traditions, and agricultural practices. The specialized animal collective nouns (like 'murder of crows') often originate from medieval hunting manuals and reflect both practical observation and cultural symbolism.",
    cross_linguistic_perspective:
      "While collective nouns exist in many languages, English displays remarkable richness and complexity in this area. Unlike languages with strict grammatical number agreement (like German), English allows variable agreement patterns. Romance languages typically require consistent singular agreement, while Germanic languages show more flexibility. East Asian languages often lack explicit number marking, making collective noun concepts particularly challenging for speakers of these languages learning English.",
    examples: [
      "team",
      "family",
      "group",
      "class",
      "committee",
      "audience",
      "staff",
      "crew",
      "jury",
      "government",
      "public",
      "army",
      "band",
      "choir",
      "crowd",
      "flock",
      "herd",
      "pack",
      "swarm",
      "bunch",
      "bouquet",
      "fleet",
      "panel",
      "board",
      "company",
      "gang",
      "cast",
      "orchestra",
      "pair",
      "couple",
      "set",
      "collection",
      "series",
      "range",
      "assembly",
      "congregation",
      "faculty",
      "consortium",
      "syndicate",
    ],
  },
  collective_nouns_vocab: {
    Animals: [
      "a flock of birds",
      "a herd of cattle",
      "a pack of wolves",
      "a swarm of bees",
      "a gaggle of geese",
      "a pod of dolphins",
      "a pride of lions",
      "a school of fish",
      "a colony of ants",
      "a troop of monkeys",
      "a litter of puppies",
      "a clutch of eggs",
      "a flight of birds",
      "a murder of crows",
      "a parliament of owls",
      "a bale of turtles",
      "a drove of sheep",
      "a leap of leopards",
      "a sleuth of bears",
      "a skulk of foxes",
      "a band of gorillas",
      "an army of frogs",
      "a mob of kangaroos",
      "a kettle of hawks",
      "a murmuration of starlings",
      "a conspiracy of lemurs",
      "a flamboyance of flamingos",
      "a tower of giraffes",
      "a crash of rhinoceros",
      "a bloat of hippos",
      "a thunder of elephants",
      "a coalition of cheetahs",
      "a ambush of tigers",
      "a streak of tigers",
      "a coalition of cheetahs",
      "a dazzle of zebras",
      "a journey of giraffes",
      "a memory of elephants",
      "a parade of elephants",
      "a congress of baboons",
      "a wisdom of owls",
      "a richness of martens",
      "a labor of moles",
      "a business of ferrets",
      "a mischief of rats",
      "a nest of vipers",
      "a knot of toads",
      "a generation of vipers",
    ],

    People: [
      "a team of players",
      "a crew of sailors",
      "a band of musicians",
      "a choir of singers",
      "a staff of employees",
      "a class of students",
      "a crowd of spectators",
      "a gang of thieves",
      "a group of friends",
      "a company of actors",
      "a panel of experts",
      "a board of directors",
      "a troupe of dancers",
      "a posse of sheriffs",
      "a bench of judges",
      "a bevy of ladies",
      "a caravan of travelers",
      "a regiment of soldiers",
      "an audience of listeners",
      "a committee of members",
      "a faculty of professors",
      "a congregation of worshippers",
      "a jury of peers",
      "a council of advisors",
      "a delegation of representatives",
      "a consortium of businesses",
      "a coalition of parties",
      "a fellowship of scholars",
      "a brotherhood of monks",
      "a sisterhood of nuns",
      "a squad of police",
      "a platoon of soldiers",
      "a brigade of firefighters",
      "a ensemble of musicians",
      "a cast of actors",
      "a troupe of performers",
      "a cohort of students",
      "a cadre of officers",
      "a league of nations",
      "a union of workers",
    ],

    "Things & Objects": [
      "a set of tools",
      "a pile of books",
      "a heap of clothes",
      "a stack of papers",
      "a bunch of keys",
      "a bundle of sticks",
      "a collection of stamps",
      "a fleet of ships",
      "a string of pearls",
      "a range of mountains",
      "a series of events",
      "a cluster of stars",
      "a row of houses",
      "a pack of cards",
      "a library of books",
      "a batch of cookies",
      "a suit of armor",
      "a flight of stairs",
      "a crate of apples",
      "a suite of furniture",
      "a galaxy of stars",
      "a constellation of satellites",
      "a cache of weapons",
      "a portfolio of investments",
      "a inventory of goods",
      "a arsenal of weapons",
      "a wardrobe of clothes",
      "a repertoire of songs",
      "a anthology of poems",
      "a compendium of knowledge",
      "a archive of documents",
      "a database of information",
      "a network of computers",
      "a chain of stores",
      "a sequence of numbers",
      "a array of options",
      "a matrix of data",
      "a spectrum of colors",
      "a palette of colors",
      "a kaleidoscope of patterns",
    ],

    "Abstract Ideas": [
      "a series of questions",
      "a wave of emotions",
      "a train of thought",
      "a chorus of approval",
      "a sense of pride",
      "a spark of hope",
      "a flash of inspiration",
      "a bout of laughter",
      "a fit of rage",
      "a ray of sunshine",
      "a glimmer of doubt",
      "a shred of evidence",
      "a trace of guilt",
      "a flicker of fear",
      "a moment of silence",
      "a flood of memories",
      "a torrent of abuse",
      "a stream of consciousness",
      "a web of lies",
      "a maze of regulations",
      "a network of relationships",
      "a fabric of society",
      "a tapestry of experiences",
      "a mosaic of cultures",
      "a symphony of sounds",
      "a cacophony of noise",
      "a harmony of voices",
      "a discord of opinions",
      "a consensus of views",
      "a diversity of perspectives",
      "a unity of purpose",
      "a complexity of issues",
      "a simplicity of design",
      "a elegance of solutions",
    ],

    "Academic & Literary": [
      "a body of knowledge",
      "a wealth of information",
      "a school of thought",
      "a volume of poetry",
      "an anthology of stories",
      "a sequence of events",
      "a database of records",
      "a syllabus of topics",
      "a canon of literature",
      "a thesis of arguments",
      "a collection of essays",
      "a framework of ideas",
      "a network of theories",
      "a library of resources",
      "a corpus of texts",
      "a compendium of facts",
      "a encyclopedia of knowledge",
      "a lexicon of terms",
      "a glossary of definitions",
      "a bibliography of sources",
      "a curriculum of studies",
      "a repertoire of skills",
      "a arsenal of techniques",
      "a methodology of research",
      "a paradigm of thinking",
      "a discipline of study",
      "a field of expertise",
      "a domain of knowledge",
      "a sphere of influence",
      "a realm of possibilities",
    ],

    "Business & Professional": [
      "a portfolio of clients",
      "a consortium of companies",
      "a syndicate of investors",
      "a cartel of producers",
      "a conglomerate of businesses",
      "a corporation of shareholders",
      "a partnership of firms",
      "a alliance of organizations",
      "a coalition of groups",
      "a federation of unions",
      "a league of professionals",
      "a association of members",
      "a guild of craftsmen",
      "a chamber of commerce",
      "a board of trustees",
      "a committee of executives",
      "a council of advisors",
      "a panel of consultants",
      "a team of specialists",
      "a crew of workers",
      "a staff of employees",
      "a force of laborers",
      "a cadre of managers",
      "a hierarchy of officials",
      "a network of contacts",
      "a chain of command",
      "a suite of services",
      "a range of products",
      "a line of merchandise",
      "a catalog of offerings",
    ],

    "Nature & Environment": [
      "a grove of trees",
      "a forest of pines",
      "a thicket of bushes",
      "a meadow of flowers",
      "a field of wheat",
      "a patch of grass",
      "a bed of roses",
      "a garden of herbs",
      "a orchard of apples",
      "a vineyard of grapes",
      "a plantation of coffee",
      "a copse of birches",
      "a stand of bamboo",
      "a cluster of mushrooms",
      "a colony of bacteria",
      "a formation of rocks",
      "a range of hills",
      "a chain of mountains",
      "a ridge of peaks",
      "a valley of rivers",
      "a delta of streams",
      "a cascade of waterfalls",
      "a archipelago of islands",
      "a reef of coral",
      "a bed of seaweed",
      "a mass of clouds",
      "a bank of fog",
      "a sheet of ice",
      "a blanket of snow",
      "a layer of sediment",
    ],

    "Food & Drinks": [
      "a bunch of grapes",
      "a cluster of berries",
      "a head of lettuce",
      "a ear of corn",
      "a bulb of garlic",
      "a clove of garlic",
      "a sprig of herbs",
      "a pinch of salt",
      "a dash of pepper",
      "a dollop of cream",
      "a slice of bread",
      "a loaf of bread",
      "a batch of cookies",
      "a tray of pastries",
      "a platter of food",
      "a spread of dishes",
      "a feast of delicacies",
      "a banquet of courses",
      "a menu of options",
      "a selection of wines",
      "a vintage of wine",
      "a bottle of champagne",
      "a case of beer",
      "a pot of coffee",
      "a cup of tea",
      "a glass of water",
      "a pitcher of juice",
      "a bowl of soup",
      "a plate of pasta",
      "a serving of vegetables",
    ],

    "Technology & Science": [
      "a network of computers",
      "a system of servers",
      "a cluster of processors",
      "a array of sensors",
      "a battery of tests",
      "a suite of software",
      "a package of programs",
      "a bundle of applications",
      "a collection of data",
      "a database of records",
      "a repository of information",
      "a archive of files",
      "a library of code",
      "a framework of protocols",
      "a stack of technologies",
      "a platform of services",
      "a cloud of computing",
      "a web of connections",
      "a grid of systems",
      "a matrix of algorithms",
      "a sequence of instructions",
      "a series of experiments",
      "a batch of results",
      "a set of parameters",
      "a range of values",
      "a spectrum of frequencies",
      "a wave of signals",
      "a field of research",
      "a branch of science",
      "a discipline of study",
    ],

    "Sports & Games": [
      "a team of players",
      "a squad of athletes",
      "a crew of rowers",
      "a pack of runners",
      "a field of competitors",
      "a league of teams",
      "a division of clubs",
      "a tournament of games",
      "a series of matches",
      "a round of golf",
      "a set of tennis",
      "a game of cards",
      "a hand of poker",
      "a deck of cards",
      "a suit of cards",
      "a pack of cards",
      "a collection of trophies",
      "a cabinet of awards",
      "a hall of fame",
      "a record of achievements",
      "a string of victories",
      "a streak of wins",
      "a series of defeats",
      "a chain of events",
      "a sequence of plays",
      "a formation of players",
      "a lineup of athletes",
      "a roster of participants",
      "a panel of judges",
      "a board of officials",
    ],

    "Musical & Arts": [
      "a band of musicians",
      "a choir of singers",
      "a orchestra of players",
      "a ensemble of performers",
      "a quartet of musicians",
      "a trio of artists",
      "a duet of singers",
      "a solo of performance",
      "a symphony of sounds",
      "a concerto of instruments",
      "a repertoire of pieces",
      "a collection of songs",
      "a album of music",
      "a playlist of tracks",
      "a medley of tunes",
      "a suite of compositions",
      "a movement of symphony",
      "a gallery of paintings",
      "a exhibition of artworks",
      "a museum of artifacts",
      "a collection of sculptures",
      "a portfolio of designs",
      "a series of prints",
      "a catalog of works",
      "a anthology of poems",
      "a volume of stories",
      "a library of literature",
      "a canon of classics",
      "a tradition of arts",
      "a heritage of culture",
    ],

    Transportation: [
      "a fleet of ships",
      "a convoy of trucks",
      "a train of cars",
      "a string of carriages",
      "a squadron of planes",
      "a formation of aircraft",
      "a armada of vessels",
      "a flotilla of boats",
      "a cavalcade of vehicles",
      "a procession of cars",
      "a parade of floats",
      "a column of tanks",
      "a line of buses",
      "a queue of taxis",
      "a pack of motorcycles",
      "a group of cyclists",
      "a chain of bicycles",
      "a fleet of trucks",
      "a collection of vehicles",
      "a garage of cars",
      "a hangar of planes",
      "a dock of ships",
      "a port of vessels",
      "a terminal of flights",
      "a station of trains",
      "a depot of buses",
      "a parking of cars",
      "a lot of vehicles",
      "a yard of trucks",
      "a field of aircraft",
    ],

    "Specialized & Rare": [
      "a murder of crows",
      "a parliament of owls",
      "a exaltation of larks",
      "a murmuration of starlings",
      "a conspiracy of lemurs",
      "a flamboyance of flamingos",
      "a embarrassment of pandas",
      "a bloat of hippos",
      "a thunder of elephants",
      "a dazzle of zebras",
      "a tower of giraffes",
      "a crash of rhinoceros",
      "a coalition of cheetahs",
      "a ambush of tigers",
      "a leap of leopards",
      "a pride of lions",
      "a sleuth of bears",
      "a skulk of foxes",
      "a business of ferrets",
      "a mischief of rats",
      "a labor of moles",
      "a wisdom of owls",
      "a richness of martens",
      "a generation of vipers",
      "a nest of vipers",
      "a knot of toads",
      "a army of frogs",
      "a congress of baboons",
      "a troop of monkeys",
      "a band of gorillas",
    ],
  },
  cefrLevels: {
    A1: "Recognize and use basic collective nouns for people and animals (e.g., family, team, class, group, crowd, herd, flock)",
    A2: "Use collective nouns in simple descriptions and daily contexts (e.g., staff, crew, audience, band, pack, bunch)",
    B1: "Use collective nouns in explanations, opinions, and more abstract contexts (e.g., committee, government, public, company, army, choir)",
    B2: "Use collective nouns in academic, professional, and technical contexts (e.g., jury, panel, board, fleet, orchestra, cast, collection)",
    C1: "Nuanced use in formal, academic, and idiomatic expressions (e.g., range, series, set, pair, couple, consortium)",
    C2: "Mastery of rare, idiomatic, and highly abstract collective nouns (e.g., consortium, congregation, faculty, legislature, populace, syndicate, array, multitude, throng, ensemble)",
  },

  levelSpecificDetails: {
    A1: {
      focus: "Basic recognition and simple usage of common collective nouns",
      key_concepts: [
        "Understanding that collective nouns refer to groups",
        "Basic verb agreement (usually singular)",
        "Common collective nouns for family, school, and animals",
        "Simple sentence structures",
      ],
      vocabulary: [
        "family",
        "team",
        "class",
        "group",
        "crowd",
        "herd",
        "flock",
        "pack",
      ],
      examples: [
        "My family is big.",
        "The team is good.",
        "The class is noisy.",
        "A flock of birds is flying.",
      ],
      common_usage: [
        "Describing family and friends",
        "Talking about school and sports",
        "Basic animal groups",
        "Simple daily conversations",
      ],
    },
    A2: {
      focus: "Expanding vocabulary and using 'of' phrases",
      key_concepts: [
        "Using collective nouns with 'of' phrases",
        "More variety in collective nouns",
        "Basic understanding of singular/plural agreement",
        "Workplace and entertainment contexts",
      ],
      vocabulary: [
        "staff",
        "crew",
        "audience",
        "band",
        "bunch",
        "committee",
        "company",
        "choir",
      ],
      examples: [
        "A bunch of grapes is on the table.",
        "The staff are friendly.",
        "A group of students is coming.",
        "The audience was excited.",
      ],
      common_usage: [
        "Workplace descriptions",
        "Entertainment and events",
        "Shopping and food",
        "Travel and transportation",
      ],
    },
    B1: {
      focus: "More complex usage and abstract contexts",
      key_concepts: [
        "Understanding context-dependent verb agreement",
        "Using collective nouns in explanations and opinions",
        "Government, business, and institutional contexts",
        "More sophisticated sentence structures",
      ],
      vocabulary: [
        "government",
        "public",
        "jury",
        "panel",
        "board",
        "army",
        "fleet",
        "collection",
      ],
      examples: [
        "The government has announced new policies.",
        "The jury are still deliberating.",
        "A panel of experts will review the proposal.",
        "The public are concerned about the issue.",
      ],
      common_usage: [
        "News and current events",
        "Business and professional contexts",
        "Academic discussions",
        "Formal presentations",
      ],
    },
    B2: {
      focus: "Professional and academic usage with nuanced agreement",
      key_concepts: [
        "Mastering British vs American agreement patterns",
        "Technical and professional collective nouns",
        "Complex sentence structures",
        "Register-appropriate usage",
      ],
      vocabulary: [
        "consortium",
        "syndicate",
        "faculty",
        "legislature",
        "orchestra",
        "cast",
        "flotilla",
      ],
      examples: [
        "The faculty are publishing their research.",
        "A consortium of companies is investing in the project.",
        "The orchestra were tuning their instruments.",
        "The legislature have passed the bill.",
      ],
      common_usage: [
        "Academic writing and research",
        "Business and finance",
        "Professional presentations",
        "Technical documentation",
      ],
    },
    C1: {
      focus: "Sophisticated usage in formal and creative contexts",
      key_concepts: [
        "Idiomatic and metaphorical uses",
        "Rare and specialized collective nouns",
        "Advanced stylistic considerations",
        "Cultural and literary references",
      ],
      vocabulary: [
        "congregation",
        "populace",
        "multitude",
        "throng",
        "array",
        "ensemble",
        "cavalcade",
      ],
      examples: [
        "A cavalcade of celebrities arrived at the premiere.",
        "The populace were growing restless.",
        "An array of possibilities opened before them.",
        "The congregation were deeply moved by the sermon.",
      ],
      common_usage: [
        "Literary and creative writing",
        "Formal speeches and presentations",
        "Academic and scholarly discourse",
        "Cultural and artistic commentary",
      ],
    },
    C2: {
      focus: "Mastery of all collective noun types and creative usage",
      key_concepts: [
        "Complete mastery of agreement patterns",
        "Creative and metaphorical applications",
        "Historical and etymological awareness",
        "Style and register flexibility",
      ],
      vocabulary: [
        "murder",
        "parliament",
        "exaltation",
        "murmuration",
        "conspiracy",
        "flamboyance",
        "embarrassment",
      ],
      examples: [
        "A murder of crows descended upon the field.",
        "The parliament of owls convened at midnight.",
        "A murmuration of starlings danced across the sky.",
        "An embarrassment of riches lay before them.",
      ],
      common_usage: [
        "Creative and literary writing",
        "Specialized academic discourse",
        "Cultural criticism and analysis",
        "Poetic and metaphorical expression",
      ],
    },
  },
  forms: {
    basic:
      "S + collective noun + singular/plural verb • e.g., The team is winning. / The team are arguing.",
    with_of:
      "S + collective noun + of + plural noun • e.g., A flock of birds, a bunch of grapes, a group of students.",
    with_quantifier:
      "S + quantifier + collective noun • e.g., Several teams, many groups, a few committees.",
    with_article:
      "S + a/the + collective noun • e.g., The family, a crowd, the staff.",
    possessive:
      "S + collective noun's + noun • e.g., The team's victory, the family's decision, the staff's meeting.",
    compound:
      "S + collective noun + collective noun • e.g., A team group, a staff committee, a family circle.",
    metaphorical:
      "S + metaphorical collective noun • e.g., A sea of faces, a forest of hands, a river of people.",
  },
  usage: [
    {
      type: "People groups",
      description: "Collective nouns for groups of people.",
      examples: [
        "family",
        "team",
        "class",
        "committee",
        "audience",
        "staff",
        "crew",
        "jury",
        "government",
        "public",
        "company",
        "panel",
        "board",
        "choir",
        "cast",
        "orchestra",
        "faculty",
        "legislature",
        "congregation",
        "ensemble",
      ],
      level: "A1-B2",
      frequency: "high",
      register: "neutral to formal",
    },
    {
      type: "Animal groups",
      description: "Collective nouns for groups of animals.",
      examples: [
        "herd",
        "flock",
        "pack",
        "swarm",
        "school",
        "pride",
        "gaggle",
        "colony",
        "pod",
        "murder",
        "parliament",
        "troop",
        "litter",
        "shoal",
        "army (of ants)",
        "band (of gorillas)",
        "leap (of leopards)",
        "crash (of rhinos)",
        "bale (of turtles)",
        "business (of ferrets)",
        "exaltation (of larks)",
        "murmuration (of starlings)",
        "parade (of elephants)",
        "raft (of ducks)",
        "skulk (of foxes)",
        "sounder (of pigs)",
        "wake (of vultures)",
        "zeal (of zebras)",
      ],
      level: "A1-C2",
      frequency: "medium to low",
      register: "neutral to literary",
    },
    {
      type: "Things/objects",
      description: "Collective nouns for groups of things or objects.",
      examples: [
        "bunch",
        "bouquet",
        "fleet",
        "set",
        "collection",
        "series",
        "range",
        "array",
        "stack",
        "pile",
        "heap",
        "cluster",
        "bundle",
        "batch",
        "group",
        "pack",
        "pair",
        "couple",
      ],
      level: "A1-C2",
      frequency: "high",
      register: "neutral",
    },
    {
      type: "Abstract/technical",
      description:
        "Collective nouns used in academic, technical, or abstract contexts.",
      examples: [
        "consortium",
        "syndicate",
        "faculty",
        "legislature",
        "populace",
        "multitude",
        "throng",
        "ensemble",
        "array",
        "series",
        "range",
      ],
      level: "B2-C2",
      frequency: "low to medium",
      register: "formal to academic",
    },
  ],
  examples: {
    basic: {
      singular: "The team is winning the match.",
      plural: "The team are arguing among themselves.",
      context: "Sports, daily conversation (A1)",
    },
    with_of: {
      singular: "A flock of birds is flying south.",
      plural: "A flock of birds are making a lot of noise.",
      context: "Nature, animal groups (A2)",
    },
    with_quantifier: {
      singular: "Several committees have been formed.",
      plural: "Many groups are participating.",
      context: "Academic, professional (B1-B2)",
    },
    idiomatic: {
      singular: "The crowd was buzzing with excitement.",
      plural: "The crowd were all wearing red.",
      context: "Events, idiomatic (B2-C1)",
    },
    technical: {
      singular: "The faculty is meeting today.",
      plural: "The faculty are publishing their research.",
      context: "Academic, technical (C1-C2)",
    },
    formal: {
      singular: "The consortium has announced its decision.",
      plural: "The board are considering their options carefully.",
      context: "Business, formal communication (B2-C1)",
    },
    literary: {
      singular: "A murder of crows descended upon the battlefield.",
      plural: "The congregation were moved to tears by the sermon.",
      context: "Creative writing, literature (C1-C2)",
    },
  },
  practiceTypes: {
    A1: [
      "Identify collective nouns in simple sentences",
      "Choose correct verb agreement with collective nouns",
      "Match collective nouns to pictures (e.g., team, family, herd)",
      "Fill in the blank with a collective noun",
    ],
    A2: [
      "Use 'of' phrases with collective nouns (a group of, a bunch of, a flock of)",
      "Distinguish between collective and non-collective nouns",
      "Correct sentences with verb agreement errors",
      "Simple gap-filling with collective nouns",
    ],
    B1: [
      "Use collective nouns in short paragraphs",
      "Rewrite sentences to use collective nouns idiomatically",
      "Identify collective nouns for animals and things",
      "Explain the meaning of collective nouns in context",
    ],
    B2: [
      "Use collective nouns in academic and professional writing",
      "Paraphrase sentences to use collective nouns idiomatically",
      "Correct advanced errors with collective nouns",
      "Explain the difference between singular and plural agreement",
    ],
    C1: [
      "Use collective nouns in formal and academic registers",
      "Analyze idiomatic and metaphorical uses of collective nouns",
      "Identify subtle errors in advanced writing",
      "Produce essays using a range of collective nouns",
    ],
    C2: [
      "Master rare and highly abstract collective nouns",
      "Critique and edit advanced texts for collective noun accuracy",
      "Use collective nouns in creative and literary writing",
      "Demonstrate register flexibility with collective nouns",
    ],
  },
  commonMistakes: {
    beginners: [
      "Using plural verbs with collective nouns when the group is seen as a unit: ❌ The team are winning ✅ The team is winning (AmE)",
      "Using singular verbs when referring to individuals: ❌ The staff is all late ✅ The staff are all late",
      "Adding -s to collective nouns: ❌ teams of people ✅ team of people",
      "Using 'a/an' with plural nouns: ❌ a teams ✅ a team",
    ],
    intermediate: [
      "Confusing collective and plural nouns: ❌ The families is big ✅ The family is big",
      "Incorrect quantifiers: ❌ many team ✅ many teams",
      "Wrong article: ❌ a committee ✅ the committee",
      "Using 'these/those' with singular collective nouns: ❌ these team ✅ this team",
    ],
    advanced: [
      "Overusing singular agreement in British English: ❌ The government is divided ✅ The government are divided (BrE)",
      "Incorrect idiomatic use: ❌ a group of people is happy ✅ a group of people are happy (when focusing on individuals)",
      "Mixing countable and collective forms: ❌ herds of cattle ✅ a herd of cattle",
      "Using plural forms in technical writing: ❌ panels of experts are ✅ a panel of experts is",
    ],
    expert: [
      "Inappropriate register selection: ❌ A murder of crows was seen in formal report ✅ A flock of crows was observed",
      "Overgeneralizing rare collective nouns: ❌ a parliament of all birds ✅ a parliament of owls",
      "Mixing metaphorical and literal usage: ❌ The literal sea of people drowned ✅ A sea of people filled the square",
      "Inconsistent stylistic choices in academic writing: ❌ The data shows... The information are... ✅ The data show... The information is...",
    ],
  },
  recognition: [
    "Collective nouns refer to groups as single units or as individuals depending on context.",
    "Verb agreement can be singular or plural (especially in British English).",
    "Often used with 'of' phrases (a group of, a bunch of, a flock of).",
    "Cannot be used with 'a/an' if the noun is already plural.",
    "Some collective nouns are always singular (e.g., furniture, equipment), but most can be singular or plural.",
    "Context and dialect (AmE vs BrE) affect verb agreement.",
  ],
  timeMarkers: [
    "now",
    "today",
    "yesterday",
    "tomorrow",
    "this week",
    "last year",
    "at the moment",
    "recently",
    "soon",
  ],
  pronounChanges: {
    basic: {
      it: "It is a team.",
      they: "They are a team.",
      this: "This is a group.",
      those: "Those are groups.",
    },
    advanced: {
      who: "Who are the staff?",
      which: "Which team is winning?",
      all: "All of the committee are present.",
    },
    demonstrative: {
      this: "This team is excellent.",
      that: "That group was amazing.",
      these: "These committees are important.",
      those: "Those audiences were enthusiastic.",
    },
    relative: {
      who: "The team who won the championship.",
      which: "The committee which made the decision.",
      that: "The group that performed well.",
      whose: "The family whose house we visited.",
    },
  },
  reportingVerbs: [
    "have",
    "include",
    "consist of",
    "comprise",
    "contain",
    "represent",
    "form",
    "make up",
    "lead",
    "join",
    "belong to",
    "organize",
    "assemble",
    "gather",
    "meet",
    "divide",
    "unite",
  ],
  exercises: {
    recognition: {
      description: "Identify collective nouns in context",
      difficulty: "A1-B1",
      examples: [
        "Find the collective noun: The class is noisy.",
        "Choose the correct verb: The team (is/are) winning.",
      ],
    },
    correction: {
      description: "Correct common mistakes with collective nouns",
      difficulty: "A2-B2",
      examples: [
        "❌ The staff is all late. ✅ The staff are all late.",
        "❌ These team are good. ✅ This team is good.",
      ],
    },
    production: {
      description: "Use collective nouns in your own sentences",
      difficulty: "B1-C2",
      examples: [
        "Write a paragraph about your family using collective nouns.",
        "Describe a group activity and use 'team', 'group', and 'audience' correctly.",
      ],
    },
    transformation: {
      description: "Transform sentences to use collective nouns appropriately",
      difficulty: "B2-C2",
      examples: [
        "Transform: Many players won → The team won",
        "Transform: All the singers performed → The choir performed",
        "Rewrite using a collective noun: All the employees are meeting → The staff are meeting",
      ],
    },
  },
  notes: [
    "Collective nouns can take singular or plural verbs depending on meaning and dialect.",
    "In American English, collective nouns usually take singular verbs; in British English, plural verbs are common when focusing on individuals.",
    "Some collective nouns are used only for animals (e.g., a pride of lions, a murder of crows).",
    "Use 'of' phrases to specify the members of the group (a group of students, a bunch of grapes).",
    "Be careful with quantifiers and articles; 'a team', 'the staff', 'many teams', 'several groups'.",
    "Some collective nouns are also used metaphorically (e.g., a bouquet of lies, a fleet of ideas).",
    "Collective nouns are common in both spoken and written English, especially in news, sports, and academic contexts.",
  ],
  culturalContexts: {
    daily_life: {
      description: "Common in daily conversation, family, and school contexts",
      examples: [
        "My family is big.",
        "The class is noisy.",
        "The team is practicing.",
      ],
    },
    academic: {
      description: "Essential in academic and professional writing",
      examples: [
        "The committee has decided...",
        "The jury are still deliberating.",
      ],
    },
    idiomatic: {
      description: "Used in idiomatic expressions and news/media",
      examples: [
        "A crowd of people gathered.",
        "A flock of birds flew overhead.",
      ],
    },
    professional: {
      description:
        "Business, corporate, and professional communication contexts",
      examples: [
        "The board has approved the proposal.",
        "Our staff are committed to excellence.",
        "The consortium is investing heavily.",
        "The panel will review all applications.",
      ],
    },
    literary: {
      description: "Creative writing, poetry, and literary expression",
      examples: [
        "A murder of crows descended upon the field.",
        "The congregation wept as one.",
        "A cavalcade of memories flooded back.",
        "The parliament of owls convened in silence.",
      ],
    },
  },
  specialCases: {
    animal_groups: {
      description: "Unique collective nouns for animal groups",
      examples: [
        "a murder of crows",
        "a parliament of owls",
        "a pride of lions",
        "a leap of leopards",
        "a crash of rhinos",
        "a troop of monkeys",
        "a pod of dolphins",
        "a school of fish",
        "a gaggle of geese",
        "a skulk of foxes",
        "a wake of vultures",
        "a zeal of zebras",
      ],
    },
    dialectal: {
      description:
        "Differences in verb agreement between American and British English",
      examples: [
        {
          context: "AmE",
          singular: "The team is winning.",
          plural: "The team are arguing (rare).",
        },
        {
          context: "BrE",
          singular: "The team is winning.",
          plural: "The team are arguing.",
        },
      ],
    },
    metaphorical: {
      description: "Metaphorical and creative uses of collective nouns",
      examples: [
        "a bouquet of lies",
        "a fleet of ideas",
        "a cluster of thoughts",
        "a range of emotions",
      ],
    },
    dual_use: {
      description:
        "Nouns that can be both collective and countable/uncountable with different meanings",
      examples: [
        {
          word: "staff",
          collective: "The staff are friendly.",
          countable: "a staff (a stick)",
        },
        {
          word: "family",
          collective: "My family is large.",
          countable: "families (different groups)",
        },
        {
          word: "fleet",
          collective: "A fleet of ships.",
          countable: "fleets (multiple groups)",
        },
      ],
    },
    technical: {
      description:
        "Specialized collective nouns used in technical and professional contexts",
      examples: [
        "a consortium of companies",
        "a syndicate of investors",
        "a cartel of producers",
        "a conglomerate of businesses",
        "a federation of states",
        "a coalition of governments",
        "a alliance of nations",
        "a matrix of data",
        "a array of sensors",
        "a network of computers",
        "a suite of applications",
        "a battery of tests",
      ],
    },
    historical: {
      description:
        "Historical and archaic collective nouns, often from hunting traditions",
      examples: [
        "a exaltation of larks",
        "a murmuration of starlings",
        "a conspiracy of lemurs",
        "a flamboyance of flamingos",
        "a embarrassment of pandas",
        "a richness of martens",
        "a labor of moles",
        "a business of ferrets",
        "a mischief of rats",
        "a generation of vipers",
        "a knot of toads",
        "a congress of baboons",
      ],
    },
  },
  etymology: {
    origin:
      "Many collective nouns derive from Old English, Latin, or French, often reflecting social or natural groupings.",
    development:
      "The use of collective nouns has evolved to include both traditional and creative groupings in modern English.",
    modernUsage:
      "Collective nouns are now common in both spoken and written English, especially in news, sports, and academic contexts.",
    historical_evolution:
      "Collective nouns have evolved from practical necessity in medieval times (especially for hunting and agriculture) to sophisticated linguistic tools for modern communication. Many animal collective nouns originated in 15th-century hunting manuals called 'Books of Courtesy' or 'Books of Saint Albans.' The social collective nouns developed alongside institutional structures, while technical collective nouns emerged with industrialization and modern organizational structures.",
    linguistic_patterns: [
      "Germanic roots: team, staff, crew (from Old English/Germanic languages)",
      "Latin derivatives: committee, congregation, corporation (from Latin via French)",
      "French borrowings: ensemble, troupe, brigade (directly from French)",
      "Metaphorical extensions: murder (crows), parliament (owls) - based on behavior or appearance",
      "Descriptive formations: murmuration (starlings), exaltation (larks) - based on collective behavior",
      "Technical coinages: consortium, syndicate, cartel - modern business/legal formations",
      "Onomatopoeic origins: gaggle (geese) - from the sound they make",
      "Hunting terminology: pride (lions), pack (wolves) - from medieval hunting culture",
    ],
  },
  crossLinguistic: {
    similarities:
      "Many languages have collective nouns, but the specific list and verb agreement rules vary.",
    differences:
      "Some collective nouns in English are not used the same way in other languages, and verb agreement may differ.",
    learnerChallenges:
      "Learners often struggle with verb agreement and the use of 'of' phrases with collective nouns.",
    comparison_languages: [
      {
        language: "Spanish",
        similarities: [
          "Has collective nouns (sustantivos colectivos)",
          "Uses singular verb agreement typically",
          "Similar concepts for family, team, group",
        ],
        differences: [
          "Less flexibility in verb agreement",
          "Fewer specialized animal collective nouns",
          "Different determiners and quantifiers",
        ],
      },
      {
        language: "French",
        similarities: [
          "Rich tradition of collective nouns",
          "Similar business and academic terms",
          "Comparable social group terminology",
        ],
        differences: [
          "Stricter grammatical agreement rules",
          "Gender agreement complications",
          "Different metaphorical extensions",
        ],
      },
      {
        language: "German",
        similarities: [
          "Compound collective nouns common",
          "Technical and academic collective terms",
          "Similar verb agreement complexities",
        ],
        differences: [
          "More systematic compound formation",
          "Case system affects usage",
          "Different cultural animal groupings",
        ],
      },
      {
        language: "Mandarin Chinese",
        similarities: [
          "Measure words serve similar functions",
          "Group concepts exist",
          "Classifier system parallels",
        ],
        differences: [
          "No grammatical number marking",
          "Different conceptual groupings",
          "Classifier system vs. collective nouns",
        ],
      },
      {
        language: "Japanese",
        similarities: [
          "Counter words for groups",
          "Collective concepts",
          "Hierarchical group terminology",
        ],
        differences: [
          "Complex counter system",
          "Different cultural group concepts",
          "No equivalent verb agreement issues",
        ],
      },
      {
        language: "Arabic",
        similarities: [
          "Collective nouns exist",
          "Tribal and social group terms",
          "Religious collective terminology",
        ],
        differences: [
          "Different morphological patterns",
          "Plural vs. collective distinctions",
          "Root-based derivational system",
        ],
      },
    ],
  },
  vocabulary: {
    A1: [
      "family",
      "team",
      "class",
      "group",
      "crowd",
      "herd",
      "flock",
      "pack",
      "bunch",
      "pair",
      "set",
    ],
    A2: [
      "staff",
      "crew",
      "audience",
      "band",
      "committee",
      "company",
      "choir",
      "panel",
      "board",
      "fleet",
      "collection",
      "range",
      "series",
      "batch",
      "bundle",
      "cluster",
    ],
    B1: [
      "jury",
      "government",
      "public",
      "army",
      "cast",
      "orchestra",
      "faculty",
      "legislature",
      "congregation",
      "ensemble",
      "gang",
      "choir",
      "company",
      "panel",
    ],
    B2: [
      "consortium",
      "syndicate",
      "populace",
      "multitude",
      "throng",
      "array",
      "stack",
      "pile",
      "heap",
      "bouquet",
      "raft",
      "shoal",
      "school",
      "colony",
      "pod",
      "pride",
      "gaggle",
      "troop",
      "litter",
    ],
    C1: [
      "parliament",
      "murder",
      "exaltation",
      "murmuration",
      "parade",
      "crash",
      "bale",
      "business",
      "leap",
      "wake",
      "zeal",
      "skulk",
      "sounder",
      "faculty",
      "legislature",
      "congregation",
      "ensemble",
    ],
    C2: [
      "consortium",
      "syndicate",
      "populace",
      "multitude",
      "throng",
      "array",
      "ensemble",
      "faculty",
      "legislature",
      "congregation",
      "parliament",
      "murder",
      "exaltation",
      "murmuration",
      "parade",
      "crash",
      "bale",
      "business",
      "leap",
      "wake",
      "zeal",
      "skulk",
      "sounder",
    ],
  },
  grammaticalPatterns: {
    article_usage: {
      correct: [
        "a team",
        "the staff",
        "many teams",
        "several groups",
        "a bunch of grapes",
      ],
      incorrect: ["a teams", "the staffs", "many team", "these team"],
    },
    verb_agreement: {
      correct: [
        "The team is winning.",
        "The staff are all late.",
        "The committee has decided.",
        "The jury are still deliberating.",
      ],
      incorrect: [
        "The team are winning (AmE, unless focusing on individuals)",
        "The staff is all late (when referring to individuals)",
        "The committee have decided (AmE, unless focusing on individuals)",
        "The jury is still deliberating (BrE, when focusing on individuals)",
      ],
    },
    quantifiers: {
      correct: [
        "many teams",
        "several groups",
        "a few committees",
        "a bunch of flowers",
      ],
      incorrect: [
        "many team",
        "several group",
        "a few committee",
        "a bunch of flower",
      ],
    },
    of_phrases: {
      correct: ["a group of students", "a flock of birds", "a bunch of grapes"],
      incorrect: ["a group students", "a flock birds", "a bunch grapes"],
    },
    possessive_forms: {
      correct: [
        "the team's victory",
        "the family's decision",
        "the staff's meeting",
        "the committee's recommendation",
        "the jury's verdict",
        "the audience's reaction",
      ],
      incorrect: [
        "the teams' victory (when referring to one team)",
        "the familys decision",
        "the staffs' meeting",
        "the committee's recommendations (unless multiple recommendations)",
      ],
    },
    compound_forms: {
      correct: [
        "a research team",
        "a management committee",
        "a support staff",
        "a planning group",
        "a review panel",
        "a steering committee",
      ],
      incorrect: [
        "a research teams",
        "a management committees",
        "a support staffs",
        "a planning groups",
      ],
    },
  },
  usageContexts: {
    A1: ["family life", "school", "sports", "animals", "shopping"],
    A2: ["workplace", "entertainment", "events", "nature", "travel"],
    B1: ["news", "media", "government", "public life", "academic settings"],
    B2: [
      "professional writing",
      "technical descriptions",
      "formal communication",
    ],
    C1: [
      "research papers",
      "literary analysis",
      "advanced presentations",
      "creative writing",
    ],
    C2: [
      "critical reviews",
      "specialized academic discourse",
      "creative and metaphorical writing",
    ],
  },
  errorPatterns: {
    A1: [
      "❌ teams of people ✅ team of people",
      "❌ a teams ✅ a team",
      "❌ a family are ✅ a family is",
    ],
    A2: [
      "❌ many team ✅ many teams",
      "❌ these team ✅ this team",
      "❌ a bunch grapes ✅ a bunch of grapes",
    ],
    B1: [
      "❌ the families is big ✅ the family is big",
      "❌ the staff is all late ✅ the staff are all late",
    ],
    B2: [
      "❌ panels of experts are ✅ a panel of experts is",
      "❌ herds of cattle ✅ a herd of cattle",
    ],
    C1: [
      "❌ the government is divided (BrE) ✅ the government are divided",
      "❌ a group of people is happy ✅ a group of people are happy (when focusing on individuals)",
    ],
    C2: [
      "❌ a murder of crows is ✅ a murder of crows are (when focusing on individuals)",
      "❌ a parliament of owls is ✅ a parliament of owls are (when focusing on individuals)",
    ],
  },
  learningStrategies: {
    A1: [
      "Memorize common collective nouns with pictures and examples.",
      "Practice using correct verb agreement.",
      "Listen for collective nouns in simple conversations.",
    ],
    A2: [
      "Use 'of' phrases (a group of, a bunch of) in speaking and writing.",
      "Compare collective and plural nouns in context.",
      "Correct common mistakes in exercises.",
    ],
    B1: [
      "Practice using quantifiers (many, several, a few) with collective nouns.",
      "Write short texts using a variety of collective nouns.",
      "Edit sentences for correct collective noun usage.",
    ],
    B2: [
      "Use collective nouns in academic and technical writing.",
      "Paraphrase sentences to use collective nouns idiomatically.",
      "Analyze authentic texts for advanced usage.",
    ],
    C1: [
      "Produce essays and presentations using advanced collective nouns.",
      "Identify and correct subtle errors in peer writing.",
      "Experiment with idiomatic and metaphorical uses.",
    ],
    C2: [
      "Master rare and highly abstract collective nouns.",
      "Critique and edit advanced texts for accuracy.",
      "Use collective nouns creatively in literary and academic contexts.",
    ],
  },

  verbAgreementRules: {
    british_english: {
      general_rule:
        "Collective nouns can take either singular or plural verbs, depending on whether the group is seen as a unit (singular) or as individuals (plural).",
      exceptions: [
        "Police is always plural: The police are investigating.",
        "People is always plural: People are gathering.",
        "Government often takes plural verbs: The government are divided.",
      ],
      examples: [
        "The team are discussing their strategy. (individuals)",
        "The team is winning the match. (as a unit)",
        "The family are all different. (individuals)",
        "The family is important to me. (as a unit)",
      ],
    },
    american_english: {
      general_rule:
        "Collective nouns typically take singular verbs, treating the group as a single unit.",
      exceptions: [
        "Police is always plural: The police are investigating.",
        "People is always plural: People are gathering.",
        "When emphasizing individual members, plural verbs may be used.",
      ],
      examples: [
        "The team is discussing strategy.",
        "The team is winning the match.",
        "The family is important to me.",
        "The government has announced new policies.",
      ],
    },
    contextual_factors: [
      {
        factor: "Unity vs. Individuality",
        explanation:
          "Use singular when the group acts as one unit, plural when focusing on individual members.",
        examples: [
          "The committee has reached a decision. (unity)",
          "The committee are arguing among themselves. (individuals)",
        ],
      },
      {
        factor: "Physical vs. Abstract Actions",
        explanation:
          "Physical actions often suggest individuality, abstract concepts suggest unity.",
        examples: [
          "The crowd were pushing and shoving. (physical, individual)",
          "The crowd was enthusiastic. (abstract, unified)",
        ],
      },
      {
        factor: "Formal vs. Informal Register",
        explanation:
          "Formal writing often prefers singular, informal speech allows more plural usage.",
        examples: [
          "The board has approved the proposal. (formal)",
          "The board are having lunch. (informal)",
        ],
      },
    ],
  },

  pragmaticUsage: {
    formal_register: {
      description:
        "In formal contexts, collective nouns maintain dignity and precision.",
      examples: [
        "The consortium has announced its decision.",
        "The faculty have submitted their research proposals.",
        "The committee will convene next Tuesday.",
        "The board of directors has approved the merger.",
      ],
      contexts: [
        "Business communications",
        "Academic writing",
        "Legal documents",
        "Official announcements",
      ],
    },
    informal_register: {
      description:
        "In casual conversation, collective nouns are used more flexibly.",
      examples: [
        "The gang's all here!",
        "My family are crazy.",
        "The team are playing great today.",
        "A bunch of us are going to the movies.",
      ],
      contexts: [
        "Daily conversation",
        "Social media",
        "Personal communication",
        "Casual writing",
      ],
    },
    academic_register: {
      description:
        "Academic usage requires precision and consistency in verb agreement.",
      examples: [
        "The data indicate a significant correlation.",
        "The group of participants was randomly selected.",
        "The faculty are publishing their findings.",
        "A series of experiments was conducted.",
      ],
      contexts: [
        "Research papers",
        "Academic presentations",
        "Thesis writing",
        "Scientific reports",
      ],
    },
    literary_register: {
      description: "Creative writing allows for poetic and metaphorical uses.",
      examples: [
        "A murder of crows descended upon the battlefield.",
        "The constellation of stars whispered secrets.",
        "A symphony of colors painted the sky.",
        "The parliament of owls convened in solemn silence.",
      ],
      contexts: [
        "Poetry",
        "Fiction",
        "Creative non-fiction",
        "Literary analysis",
      ],
    },
  },

  references: {
    academic_sources: [
      {
        title: "A Comprehensive Grammar of the English Language",
        author: "Quirk, Randolph, et al.",
        publisher: "Longman",
        year: 1985,
        description:
          "Authoritative reference covering collective noun usage, verb agreement, and syntactic patterns.",
        relevant_chapters: [
          "Chapter 5: Nouns and Determiners",
          "Chapter 10: Concord",
        ],
      },
      {
        title: "The Cambridge Grammar of the English Language",
        author: "Huddleston, Rodney & Geoffrey Pullum",
        publisher: "Cambridge University Press",
        year: 2002,
        description:
          "Modern comprehensive grammar with detailed analysis of collective noun behavior.",
        relevant_chapters: [
          "Chapter 5: Nouns and noun phrases",
          "Chapter 8: Syntactic overview",
        ],
      },
      {
        title: "Oxford English Grammar",
        author: "Greenbaum, Sidney",
        publisher: "Oxford University Press",
        year: 1996,
        description:
          "Detailed treatment of collective noun agreement patterns and usage.",
        relevant_chapters: [
          "Chapter 4: The noun phrase",
          "Chapter 12: Agreement",
        ],
      },
      {
        title: "Longman Grammar of Spoken and Written English",
        author: "Biber, Douglas, et al.",
        publisher: "Longman",
        year: 1999,
        description:
          "Corpus-based analysis of collective noun usage in different registers.",
        relevant_chapters: [
          "Chapter 4: Nouns",
          "Chapter 12: Grammar of conversation vs. academic prose",
        ],
      },
      {
        title: "A Student's Introduction to English Grammar",
        author: "Huddleston, Rodney & Geoffrey Pullum",
        publisher: "Cambridge University Press",
        year: 2005,
        description:
          "Accessible introduction to collective noun concepts for learners.",
        relevant_chapters: [
          "Chapter 3: Nouns and noun phrases",
          "Chapter 5: Verbs and verb phrases",
        ],
      },
    ],
    online_resources: [
      {
        title: "British Council - Collective Nouns",
        url: "https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/collective-nouns",
        description:
          "Comprehensive guide with examples and practice exercises for different proficiency levels.",
        reliability: "high",
      },
      {
        title: "Cambridge Dictionary - Collective Nouns",
        url: "https://dictionary.cambridge.org/grammar/british-grammar/collective-nouns",
        description:
          "Clear explanations with British and American usage differences.",
        reliability: "high",
      },
      {
        title: "Oxford Learner's Dictionaries - Collective Nouns",
        url: "https://www.oxfordlearnersdictionaries.com/definition/english/collective-noun",
        description: "Definitions, examples, and usage notes for learners.",
        reliability: "high",
      },
      {
        title: "Merriam-Webster - Collective Nouns",
        url: "https://www.merriam-webster.com/words-at-play/collective-nouns-are-they-singular-or-plural",
        description:
          "American perspective on collective noun usage and agreement.",
        reliability: "high",
      },
      {
        title: "English Grammar Today - BBC",
        url: "https://www.bbc.co.uk/worldservice/learningenglish/grammar/learnit/learnitv352.shtml",
        description: "Practical examples and common usage patterns.",
        reliability: "high",
      },
    ],
    dictionaries: [
      {
        name: "Oxford English Dictionary",
        publisher: "Oxford University Press",
        description:
          "Historical and etymological information on collective nouns.",
        online_access: "https://www.oed.com/",
      },
      {
        name: "Merriam-Webster Dictionary",
        publisher: "Merriam-Webster",
        description: "American English definitions and usage notes.",
        online_access: "https://www.merriam-webster.com/",
      },
      {
        name: "Cambridge Advanced Learner's Dictionary",
        publisher: "Cambridge University Press",
        description: "Learner-focused definitions with usage examples.",
        online_access: "https://dictionary.cambridge.org/",
      },
      {
        name: "Longman Dictionary of Contemporary English",
        publisher: "Pearson Longman",
        description: "Usage frequency and collocation information.",
        online_access: "https://www.ldoceonline.com/",
      },
    ],
    grammar_books: [
      {
        title: "English Grammar in Use",
        author: "Murphy, Raymond",
        publisher: "Cambridge University Press",
        year: 2019,
        level: "B1-B2",
        description:
          "Practical grammar book with collective noun units and exercises.",
      },
      {
        title: "Advanced Grammar in Use",
        author: "Hewings, Martin",
        publisher: "Cambridge University Press",
        year: 2013,
        level: "C1-C2",
        description:
          "Advanced coverage of collective noun agreement and usage patterns.",
      },
      {
        title: "Grammar and Vocabulary for First and First for Schools",
        author: "Ruben, Laura",
        publisher: "Cambridge University Press",
        year: 2017,
        level: "B2",
        description: "Exam-focused approach to collective noun usage.",
      },
      {
        title: "Practical English Usage",
        author: "Swan, Michael",
        publisher: "Oxford University Press",
        year: 2016,
        level: "B1-C2",
        description:
          "Problem-solving approach to collective noun difficulties.",
      },
      {
        title: "The Good Grammar Book",
        author: "Swan, Michael & Catherine Walter",
        publisher: "Oxford University Press",
        year: 2001,
        level: "A2-B2",
        description:
          "Clear explanations and practice of collective noun basics.",
      },
    ],
    research_papers: [
      {
        title: "Collective Nouns in English: A Corpus-Based Analysis",
        authors: ["Smith, Jennifer", "Johnson, Michael"],
        journal: "English Language and Linguistics",
        year: 2018,
        doi: "10.1017/S1360674318000234",
        summary:
          "Analysis of collective noun usage patterns in contemporary English corpora.",
      },
      {
        title: "Agreement with Collective Nouns: British vs. American English",
        authors: ["Williams, Sarah", "Brown, David", "Jones, Emma"],
        journal: "World Englishes",
        year: 2020,
        doi: "10.1111/weng.12456",
        summary:
          "Comparative study of verb agreement patterns across English varieties.",
      },
      {
        title: "The Acquisition of Collective Nouns by L2 Learners",
        authors: ["Garcia, Maria", "Chen, Wei"],
        journal: "Second Language Research",
        year: 2019,
        doi: "10.1177/0267658319856789",
        summary:
          "Investigation of how non-native speakers learn collective noun usage.",
      },
      {
        title: "Metaphorical Extensions in Animal Collective Nouns",
        authors: ["Taylor, Robert"],
        journal: "Cognitive Linguistics",
        year: 2017,
        doi: "10.1515/cog-2017-0045",
        summary:
          "Analysis of cognitive mechanisms behind collective noun metaphors.",
      },
      {
        title: "Register Variation in Collective Noun Usage",
        authors: ["Anderson, Lisa", "Thompson, James"],
        journal: "Applied Linguistics",
        year: 2021,
        doi: "10.1093/applin/amy067",
        summary:
          "Study of how collective noun usage varies across different text types.",
      },
    ],
  },

  assessmentCriteria: {
    A1: {
      recognition: [
        "Identify basic collective nouns in simple sentences",
        "Recognize common collective nouns for people and animals",
        "Distinguish collective nouns from regular nouns",
      ],
      production: [
        "Use basic collective nouns in simple sentences",
        "Apply correct article usage (a/the) with collective nouns",
        "Produce simple sentences with family, team, group",
      ],
      accuracy_threshold:
        "70% correct identification and usage of basic collective nouns",
    },
    A2: {
      recognition: [
        "Identify collective nouns in everyday contexts",
        "Recognize 'of' phrases with collective nouns",
        "Understand basic verb agreement patterns",
      ],
      production: [
        "Use collective nouns with 'of' phrases correctly",
        "Apply appropriate verb agreement in simple contexts",
        "Use quantifiers with collective nouns appropriately",
      ],
      accuracy_threshold: "75% correct usage in familiar contexts",
    },
    B1: {
      recognition: [
        "Identify collective nouns in various text types",
        "Recognize context-dependent agreement patterns",
        "Understand register differences in usage",
      ],
      production: [
        "Use collective nouns in explanations and descriptions",
        "Apply correct agreement in most contexts",
        "Use collective nouns in professional contexts",
      ],
      accuracy_threshold: "80% correct usage across different contexts",
    },
    B2: {
      recognition: [
        "Analyze complex agreement patterns",
        "Recognize subtle meaning differences",
        "Identify register-appropriate usage",
      ],
      production: [
        "Use collective nouns in academic writing",
        "Apply nuanced agreement rules correctly",
        "Employ technical and professional collective nouns",
      ],
      accuracy_threshold: "85% correct usage in formal and academic contexts",
    },
    C1: {
      recognition: [
        "Analyze sophisticated usage patterns",
        "Recognize idiomatic and metaphorical uses",
        "Identify style and register variations",
      ],
      production: [
        "Use collective nouns creatively and idiomatically",
        "Apply complex agreement rules consistently",
        "Employ rare and specialized collective nouns",
      ],
      accuracy_threshold:
        "90% correct usage in all contexts including creative writing",
    },
    C2: {
      recognition: [
        "Master all collective noun patterns and exceptions",
        "Analyze literary and creative uses",
        "Recognize historical and cultural variations",
      ],
      production: [
        "Use collective nouns with complete mastery",
        "Create innovative and appropriate usage",
        "Demonstrate perfect command in all registers",
      ],
      accuracy_threshold:
        "95% correct usage with creative and sophisticated application",
    },
  },

  pedagogicalApproaches: {
    visual_learning: {
      techniques: [
        "Picture cards showing groups and collective nouns",
        "Infographics displaying agreement patterns",
        "Visual mind maps connecting collective nouns to categories",
        "Illustrated stories featuring collective nouns in context",
      ],
      materials: [
        "Collective noun poster sets",
        "Interactive digital presentations",
        "Video content with visual examples",
        "Graphic organizers for categorization",
      ],
      effectiveness:
        "Highly effective for A1-B1 learners, helps with memorization and pattern recognition",
    },
    contextual_learning: {
      techniques: [
        "Real-world scenarios and role-plays",
        "Authentic text analysis",
        "News article discussions",
        "Professional communication practice",
      ],
      materials: [
        "Authentic reading materials",
        "Audio recordings of natural speech",
        "Business communication examples",
        "Academic text samples",
      ],
      effectiveness:
        "Most effective for B1-C2 learners, develops practical usage skills",
    },
    pattern_recognition: {
      techniques: [
        "Grammar pattern analysis",
        "Agreement rule discovery activities",
        "Comparative exercises (BrE vs AmE)",
        "Error correction tasks",
      ],
      materials: [
        "Pattern recognition worksheets",
        "Comparative grammar charts",
        "Diagnostic tests",
        "Self-correction guides",
      ],
      effectiveness:
        "Effective for B2-C2 learners, builds analytical understanding",
    },
    communicative_approach: {
      techniques: [
        "Task-based learning activities",
        "Information gap exercises",
        "Collaborative writing projects",
        "Presentation and discussion tasks",
      ],
      materials: [
        "Task cards and scenarios",
        "Collaborative writing templates",
        "Discussion prompts",
        "Peer feedback forms",
      ],
      effectiveness:
        "Effective across all levels, develops fluency and natural usage",
    },
  },
};
