import { CountableVsUncountableNounsType } from "@/types/grammars/grammar/noun_special/countable_vs_uncountable_nouns";

// Comprehensive Countable vs. Uncountable Nouns Data (A1-C2)
export const CountableVsUncountableNounsData: CountableVsUncountableNounsType =
  {
    id: 37,
    definition: {
      core_concept:
        "Countable nouns refer to things that can be counted as individual units (e.g., apple/apples), while uncountable nouns refer to substances, concepts, or masses that cannot be counted individually (e.g., water, information).",
      grammatical_status:
        "Countable nouns can be singular or plural and use 'a/an', numbers, and quantifiers like 'many' and 'few'. Uncountable nouns are always singular, do not use 'a/an', and use quantifiers like 'much' and 'little'.",
      linguistic_significance:
        "Understanding the difference is essential for correct article, quantifier, and verb agreement usage in English.",
      examples_countable: [
        "book/books",
        "car/cars",
        "child/children",
        "idea/ideas",
        "apple/apples",
        "dog/dogs",
        "table/tables",
        "city/cities",
        "question/questions",
        "friend/friends",
      ],
      examples_uncountable: [
        "water",
        "rice",
        "advice",
        "information",
        "music",
        "furniture",
        "bread",
        "happiness",
        "news",
        "progress",
        "equipment",
        "homework",
        "knowledge",
        "research",
        "traffic",
        "weather",
        "work",
        "money",
        "sand",
        "air",
        "sugar",
        "salt",
        "love",
        "anger",
      ],
    },
    countable_nouns: [
      // Common things
      "apple",
      "banana",
      "car",
      "chair",
      "book",
      "pen",
      "student",
      "table",
      "bottle",
      "box",
      // Food items
      "egg",
      "sandwich",
      "cookie",
      "pizza",
      "burger",
      "tomato",
      "grape",
      "potato",
      // Animals
      "dog",
      "cat",
      "elephant",
      "lion",
      "bird",
      "cow",
      "fish (in plural)",
      "monkey",
      // Places
      "city",
      "country",
      "village",
      "building",
      "hotel",
      "park",
      "classroom",
      // Abstract (specific occurrences)
      "idea",
      "dream",
      "event",
      "mistake",
      "experience (countable as events)",
      // Technology & Items
      "computer",
      "phone",
      "keyboard",
      "message",
      "email",
      "notification",
      // Academic
      "lesson",
      "exercise",
      "article",
      "fact",
      "example",
      "sentence",
    ],

    uncountable_nouns: [
      // Substances
      "water",
      "milk",
      "juice",
      "oil",
      "gas",
      "butter",
      "cheese",
      "sugar",
      "salt",
      "rice",
      // Abstract ideas
      "information",
      "advice",
      "news",
      "knowledge",
      "progress",
      "furniture",
      "homework",
      "luggage",
      "traffic",
      "money",
      "research",
      "equipment",
      "education",
      // Natural elements
      "air",
      "fire",
      "ice",
      "snow",
      "rain",
      "light",
      "darkness",
      "heat",
      "cold",
      // Activities
      "swimming",
      "reading",
      "traveling",
      "cooking",
      "dancing",
      "running",
      // Emotions
      "happiness",
      "anger",
      "love",
      "fear",
      "excitement",
      "sadness",
      "courage",
      // Academic concepts
      "mathematics",
      "physics",
      "chemistry",
      "economics",
      "grammar",
      "history",
    ],

    dual_usage_nouns: [
      // Different meanings in singular/plural usage
      {
        word: "hair",
        countable: "a hair = a single strand",
        uncountable: "hair = all the hair on your head",
      },
      {
        word: "experience",
        countable: "an experience = a specific event",
        uncountable: "experience = overall knowledge or skill",
      },
      {
        word: "chicken",
        countable: "a chicken = an animal",
        uncountable: "chicken = the meat",
      },
      {
        word: "light",
        countable: "a light = a lamp or bulb",
        uncountable: "light = illumination",
      },
      {
        word: "paper",
        countable: "a paper = a newspaper or document",
        uncountable: "paper = the material",
      },
      {
        word: "time",
        countable: "a time = an occasion",
        uncountable: "time = general duration",
      },
      {
        word: "work",
        countable: "a work = a piece of art/literature",
        uncountable: "work = effort/labor",
      },
      {
        word: "glass",
        countable: "a glass = a drinking container",
        uncountable: "glass = the transparent material",
      },
      {
        word: "coffee",
        countable: "a coffee = a cup of coffee",
        uncountable: "coffee = the substance",
      },
      {
        word: "iron",
        countable: "an iron = the device for pressing clothes",
        uncountable: "iron = the metal",
      },
      {
        word: "business",
        countable: "a business = a company",
        uncountable: "business = commercial activity",
      },
    ],
    cefrLevels: {
      A1: "Recognize and use basic countable and uncountable nouns in daily life (e.g., apple/apples, water, bread, book/books, money). Master fundamental distinction between items that can be counted individually versus substances/masses.",
      A2: "Use countable and uncountable nouns in simple requests, descriptions, and needs (e.g., advice, information, knowledge, bottle of water, two apples). Apply basic quantifiers correctly and understand partitive expressions.",
      B1: "Use countable and uncountable nouns in explanations, opinions, and more abstract contexts (e.g., experience, progress, education, respect, responsibility, opportunity, challenge, advantage, disadvantage). Handle dual-usage nouns appropriately.",
      B2: "Use countable and uncountable nouns in academic, professional, and technical contexts (e.g., evidence, research, analysis, summary, criticism, influence, impact, effect, result, consequence, outcome, strategy, policy, principle, value, tradition, culture, heritage, legacy, philosophy, science, literature, art, music, design, method, system, structure, pattern, model, trend, fashion, custom, law, regulation, standard, norm). Master register-appropriate usage.",
      C1: "Nuanced use in formal, academic, and idiomatic expressions with sophisticated understanding of semantic fields and collocational patterns. Master subtle distinctions and cultural implications.",
      C2: "Native-like competence in all registers and contexts, including creative and metaphorical usage. Complete mastery of all exceptions, variations, and stylistic nuances.",
    },

    levelBasedLearning: {
      A1: {
        description:
          "Foundation level: Basic recognition and elementary usage of the most common countable and uncountable nouns in everyday contexts.",
        essential_countable: [
          "apple",
          "book",
          "car",
          "chair",
          "dog",
          "cat",
          "table",
          "pen",
          "cup",
          "plate",
          "bag",
          "shoe",
          "hat",
          "shirt",
          "dress",
          "house",
          "room",
          "window",
          "door",
          "bed",
          "friend",
          "teacher",
          "student",
          "child",
          "boy",
          "girl",
          "man",
          "woman",
          "mother",
          "father",
        ],
        essential_uncountable: [
          "water",
          "milk",
          "bread",
          "rice",
          "sugar",
          "salt",
          "butter",
          "cheese",
          "meat",
          "fish",
          "money",
          "time",
          "work",
          "music",
          "homework",
          "weather",
          "air",
          "love",
          "happiness",
          "food",
        ],
        key_concepts: [
          "Countable nouns can be counted: one apple, two apples",
          "Uncountable nouns cannot be counted: water (not *one water, two waters)",
          "Use 'a/an' only with singular countable nouns",
          "Plural countable nouns end in -s or have irregular forms",
          "Uncountable nouns don't have plural forms",
        ],
        basic_rules: [
          "Countable: a book, two books, many books",
          "Uncountable: water, some water, much water",
          "Never: *a water, *two waters, *many waters",
          "Use 'is' with uncountable nouns: Water is important",
          "Use 'are' with plural countable nouns: Books are useful",
        ],
        common_expressions: [
          "Can I have an apple?",
          "I need some water",
          "There are three books",
          "How much money?",
          "How many apples?",
          "A glass of water",
          "A piece of bread",
        ],
        learning_objectives: [
          "Identify common countable and uncountable nouns",
          "Use correct articles (a/an) with countable nouns",
          "Form basic plurals correctly",
          "Use simple quantifiers (some, many, much)",
          "Understand basic subject-verb agreement",
        ],
      },
      A2: {
        description:
          "Elementary level: Expanded vocabulary and introduction to quantifiers and partitive expressions in practical contexts.",
        expanded_countable: [
          "sandwich",
          "pizza",
          "banana",
          "orange",
          "tomato",
          "potato",
          "egg",
          "cookie",
          "cake",
          "flower",
          "tree",
          "bird",
          "phone",
          "computer",
          "email",
          "message",
          "photo",
          "video",
          "game",
          "movie",
          "lesson",
          "question",
          "answer",
          "problem",
          "mistake",
          "idea",
          "plan",
          "dream",
          "story",
          "joke",
        ],
        expanded_uncountable: [
          "advice",
          "information",
          "news",
          "furniture",
          "luggage",
          "traffic",
          "equipment",
          "homework",
          "progress",
          "knowledge",
          "research",
          "peace",
          "war",
          "freedom",
          "health",
          "education",
          "art",
          "science",
          "history",
          "geography",
          "mathematics",
          "English",
          "music",
          "dancing",
          "swimming",
        ],
        quantifier_usage: [
          "many books / much water",
          "few friends / little money",
          "several ideas / some advice",
          "a lot of people / a lot of time",
          "lots of cars / lots of information",
          "a few questions / a little help",
          "not many students / not much homework",
        ],
        partitive_expressions: [
          "a bottle of water",
          "a piece of advice",
          "a slice of bread",
          "a cup of tea",
          "a glass of milk",
          "a bar of chocolate",
          "a tube of toothpaste",
          "a packet of sugar",
          "a loaf of bread",
          "a jar of honey",
          "a can of soup",
          "a bowl of rice",
        ],
        daily_contexts: [
          "Shopping: I need some bread and a few apples",
          "Travel: Can you give me some information about hotels?",
          "School: I have a lot of homework and several tests",
          "Food: Would you like some coffee and a piece of cake?",
        ],
        learning_objectives: [
          "Use appropriate quantifiers with noun types",
          "Master common partitive expressions",
          "Handle requests and offers correctly",
          "Expand vocabulary in daily contexts",
          "Understand quantity expressions",
        ],
      },
      B1: {
        description:
          "Intermediate level: Abstract concepts, dual-usage nouns, and more complex quantifier systems in academic and professional contexts.",
        academic_countable: [
          "argument",
          "theory",
          "method",
          "approach",
          "technique",
          "strategy",
          "policy",
          "principle",
          "factor",
          "element",
          "aspect",
          "feature",
          "characteristic",
          "advantage",
          "disadvantage",
          "benefit",
          "consequence",
          "result",
          "outcome",
          "effect",
          "cause",
          "reason",
          "solution",
        ],
        academic_uncountable: [
          "evidence",
          "research",
          "analysis",
          "progress",
          "development",
          "growth",
          "improvement",
          "success",
          "failure",
          "competition",
          "cooperation",
          "communication",
          "understanding",
          "knowledge",
          "wisdom",
          "intelligence",
          "creativity",
          "imagination",
          "inspiration",
        ],
        abstract_concepts: [
          "responsibility",
          "opportunity",
          "challenge",
          "experience",
          "respect",
          "trust",
          "confidence",
          "courage",
          "patience",
          "honesty",
          "loyalty",
          "friendship",
          "leadership",
          "teamwork",
          "motivation",
          "determination",
          "perseverance",
          "achievement",
          "satisfaction",
          "fulfillment",
        ],
        dual_usage_introduction: [
          "experience: an experience (event) vs experience (knowledge)",
          "paper: a paper (document) vs paper (material)",
          "glass: a glass (container) vs glass (material)",
          "time: a time (occasion) vs time (duration)",
          "work: a work (artwork) vs work (labor)",
        ],
        complex_quantifiers: [
          "a great deal of",
          "a large amount of",
          "a considerable number of",
          "the majority of",
          "the minority of",
          "a variety of",
          "a range of",
          "plenty of",
          "loads of",
          "heaps of",
          "masses of",
          "tons of",
        ],
        learning_objectives: [
          "Handle abstract and academic vocabulary",
          "Understand dual-usage nouns in context",
          "Use complex quantifiers appropriately",
          "Express opinions and arguments effectively",
          "Master intermediate-level collocations",
        ],
      },
      B2: {
        description:
          "Upper-intermediate level: Professional and technical vocabulary with sophisticated understanding of register and context.",
        professional_countable: [
          "proposal",
          "recommendation",
          "suggestion",
          "requirement",
          "specification",
          "criterion",
          "objective",
          "target",
          "goal",
          "milestone",
          "deadline",
          "schedule",
          "agenda",
          "priority",
          "initiative",
          "project",
          "campaign",
          "venture",
          "enterprise",
          "collaboration",
          "partnership",
        ],
        professional_uncountable: [
          "expertise",
          "professionalism",
          "efficiency",
          "productivity",
          "innovation",
          "creativity",
          "leadership",
          "management",
          "supervision",
          "guidance",
          "mentorship",
          "training",
          "recruitment",
          "retention",
          "performance",
          "quality",
          "excellence",
          "reputation",
        ],
        technical_vocabulary: [
          "software",
          "hardware",
          "technology",
          "infrastructure",
          "architecture",
          "functionality",
          "compatibility",
          "security",
          "privacy",
          "accessibility",
          "usability",
          "reliability",
          "maintenance",
          "documentation",
          "implementation",
          "integration",
          "optimization",
        ],
        advanced_dual_usage: [
          "business: a business (company) vs business (commerce)",
          "iron: an iron (appliance) vs iron (metal)",
          "room: a room (space) vs room (space available)",
          "sport: a sport (activity) vs sport (in general)",
          "study: a study (research) vs study (learning)",
        ],
        register_awareness: [
          "Formal: research indicates vs Informal: studies show",
          "Academic: evidence suggests vs Casual: it looks like",
          "Professional: expertise vs Everyday: know-how",
          "Technical: specifications vs General: details",
        ],
        learning_objectives: [
          "Master professional and technical vocabulary",
          "Understand register-appropriate usage",
          "Handle complex academic writing",
          "Use sophisticated collocations",
          "Demonstrate cultural awareness",
        ],
      },
      C1: {
        description:
          "Advanced level: Sophisticated usage with nuanced distinctions, idiomatic expressions, and native-like competence in formal contexts.",
        sophisticated_countable: [
          "phenomenon",
          "hypothesis",
          "paradigm",
          "framework",
          "methodology",
          "infrastructure",
          "mechanism",
          "apparatus",
          "protocol",
          "procedure",
          "precedent",
          "criterion",
          "statute",
          "regulation",
          "provision",
          "clause",
          "amendment",
          "revision",
          "iteration",
          "manifestation",
        ],
        sophisticated_uncountable: [
          "jurisprudence",
          "governance",
          "sovereignty",
          "autonomy",
          "accountability",
          "transparency",
          "integrity",
          "authenticity",
          "legitimacy",
          "credibility",
          "viability",
          "sustainability",
          "compatibility",
          "coherence",
          "consistency",
          "resilience",
          "versatility",
          "sophistication",
        ],
        nuanced_distinctions: [
          "data vs information vs knowledge vs wisdom",
          "advice vs counsel vs guidance vs direction",
          "research vs investigation vs inquiry vs study",
          "evidence vs proof vs testimony vs documentation",
          "analysis vs evaluation vs assessment vs appraisal",
        ],
        idiomatic_expressions: [
          "food for thought",
          "a breath of fresh air",
          "a drop in the ocean",
          "music to my ears",
          "water under the bridge",
          "light at the end of the tunnel",
          "time flies",
          "money talks",
          "knowledge is power",
          "practice makes perfect",
        ],
        academic_writing: [
          "substantial evidence suggests",
          "considerable research indicates",
          "extensive analysis reveals",
          "comprehensive investigation demonstrates",
          "thorough examination shows",
          "detailed scrutiny confirms",
        ],
        learning_objectives: [
          "Master sophisticated academic vocabulary",
          "Understand subtle semantic distinctions",
          "Use idiomatic expressions appropriately",
          "Demonstrate native-like intuition",
          "Handle complex argumentation",
        ],
      },
      C2: {
        description:
          "Mastery level: Complete native-like competence with creative usage, metaphorical expressions, and perfect intuition for all contexts.",
        mastery_countable: [
          "paradigm",
          "trajectory",
          "catalyst",
          "synthesis",
          "dichotomy",
          "paradox",
          "anomaly",
          "aberration",
          "deviation",
          "discrepancy",
          "disparity",
          "correlation",
          "causation",
          "implication",
          "ramification",
          "prerequisite",
          "corollary",
          "derivative",
          "iteration",
        ],
        mastery_uncountable: [
          "perspicacity",
          "sagacity",
          "acumen",
          "prowess",
          "finesse",
          "eloquence",
          "articulateness",
          "sophistication",
          "refinement",
          "discernment",
          "intuition",
          "insight",
          "foresight",
          "hindsight",
          "prescience",
          "omniscience",
          "transcendence",
          "immanence",
          "quintessence",
        ],
        subtle_variations: [
          "Context-dependent interpretations of dual-usage nouns",
          "Metaphorical extensions of concrete nouns to abstract concepts",
          "Cultural and regional variations in countability",
          "Historical evolution of noun categorization",
          "Genre-specific usage patterns",
        ],
        creative_usage: [
          "Poetic and literary applications",
          "Metaphorical and symbolic meanings",
          "Innovative collocations and expressions",
          "Stylistic variations for effect",
          "Experimental language use",
        ],
        native_like_competence: [
          "Intuitive understanding of all exceptions",
          "Perfect register sensitivity",
          "Cultural and contextual appropriateness",
          "Creative and innovative usage",
          "Teaching and explaining to others",
        ],
        learning_objectives: [
          "Achieve complete mastery of all aspects",
          "Demonstrate creative and innovative usage",
          "Teach and explain complex concepts",
          "Handle all professional contexts",
          "Contribute to linguistic research",
        ],
      },
    },
    forms: {
      countable:
        "a/an + singular countable noun (a book), number + plural countable noun (two books), many/few/several + plural countable noun (many books)",
      uncountable:
        "(no article) + uncountable noun (water), some/much/little + uncountable noun (some water), partitive + of + uncountable noun (a piece of advice, a bottle of water)",
      mixed:
        "Some nouns can be both countable and uncountable with different meanings (e.g., chicken: a chicken (animal), chicken (meat); paper: a paper (article), paper (material))",
    },
    usage: [
      {
        type: "Everyday objects and food",
        description:
          "Countable: apple, egg, chair, car, pen, cup, sandwich. Uncountable: water, bread, rice, milk, cheese, coffee, tea, sugar, salt, butter, meat, fruit (in general)",
        level: "A1-A2",
      },
      {
        type: "Abstract and academic nouns",
        description:
          "Countable: idea, fact, result, problem, solution, suggestion, decision, question, answer. Uncountable: information, advice, knowledge, research, evidence, progress, news, homework, equipment, furniture, luggage, traffic, weather, work, money, music, literature, art, science, education, health, beauty, happiness, love, peace, freedom, justice, courage, patience, experience, respect, responsibility, opportunity, challenge, advantage, disadvantage, influence, impact, effect, result, consequence, outcome, strategy, policy, principle, value, tradition, culture, heritage, legacy, philosophy, design, method, system, structure, pattern, model, trend, fashion, custom, law, regulation, standard, norm",
        level: "B1-C2",
      },
      {
        type: "Dual-use nouns",
        description:
          "Some nouns can be both countable and uncountable with different meanings: chicken (animal vs. meat), paper (article vs. material), glass (cup vs. material), experience (event vs. knowledge), time (occasion vs. duration), light (lamp vs. brightness), hair (strand vs. all hair)",
        level: "A2-C2",
      },
    ],
    examples: {
      countable: {
        singular: "I have a book.",
        plural: "There are three apples on the table.",
        with_many: "Many students are in the classroom.",
        with_few: "Few people know the answer.",
      },
      uncountable: {
        no_article: "Water is important for life.",
        with_some: "I need some information.",
        with_much: "There isn't much sugar left.",
        with_little: "There is little hope of success.",
      },
      dual_use: {
        countable: "I bought a paper (newspaper).",
        uncountable: "Paper is made from wood.",
        countable2: "She had a chicken for dinner (animal).",
        uncountable2: "We ate chicken for lunch (meat).",
      },
    },
    practiceTypes: {
      A1: [
        "Identify countable and uncountable nouns in simple sentences",
        "Choose correct article or quantifier",
        "Match nouns to pictures (e.g., apple, water, bread)",
        "Fill in the blank with a countable or uncountable noun",
      ],
      A2: [
        "Use some/many/much/few/little with nouns",
        "Distinguish between countable and uncountable nouns in context",
        "Correct sentences with article or quantifier errors",
        "Simple gap-filling with countable and uncountable nouns",
      ],
      B1: [
        "Use dual-use nouns in context",
        "Rewrite sentences to use correct noun type",
        "Use countable and uncountable nouns in short paragraphs",
        "Explain the meaning of dual-use nouns in context",
      ],
      B2: [
        "Use countable and uncountable nouns in academic and professional writing",
        "Paraphrase sentences to use correct noun type idiomatically",
        "Correct advanced errors with noun types",
        "Explain the difference between countable and uncountable usage",
      ],
      C1: [
        "Use countable and uncountable nouns in formal and academic registers",
        "Analyze idiomatic and metaphorical uses of noun types",
        "Identify subtle errors in advanced writing",
        "Produce essays using a range of noun types",
      ],
      C2: [
        "Master rare and highly abstract noun types",
        "Critique and edit advanced texts for noun type accuracy",
        "Use countable and uncountable nouns in creative and literary writing",
        "Demonstrate register flexibility with noun types",
      ],
    },
    commonMistakes: {
      beginners: [
        "Adding -s to uncountable nouns: ❌ informations ✅ information",
        "Using 'a/an' with uncountable nouns: ❌ an advice ✅ a piece of advice",
        "Plural verb agreement: ❌ The news are good ✅ The news is good",
        "Using 'many' with uncountable nouns: ❌ many furniture ✅ much furniture",
        "Using 'much' with countable nouns: ❌ much apples ✅ many apples",
      ],
      intermediate: [
        "Confusing dual-use nouns: ❌ a chicken (meat) ✅ chicken (meat); a chicken (animal)",
        "Incorrect quantifiers: ❌ few information ✅ little information",
        "Wrong article: ❌ a research ✅ research",
        "Using 'these/those' with uncountable nouns: ❌ these information ✅ this information",
      ],
      advanced: [
        "Overusing singular agreement with plural countable nouns: ❌ The apples is ✅ The apples are",
        "Incorrect idiomatic use: ❌ a good news ✅ good news",
        "Mixing countable and uncountable forms: ❌ advices ✅ advice",
        "Using plural forms in academic writing: ❌ researches show ✅ research shows",
      ],
    },
    recognition: [
      "Countable nouns can be counted, have singular/plural forms, and use 'a/an', numbers, and quantifiers like 'many', 'few', 'several'.",
      "Uncountable nouns cannot be counted individually, do not use 'a/an', and use quantifiers like 'much', 'little', 'some'.",
      "Some nouns can be both countable and uncountable with different meanings.",
      "Correct article and quantifier usage depends on noun type.",
      "Dual-use nouns are common in English and can cause confusion for learners.",
    ],
    timeMarkers: [
      "now",
      "today",
      "yesterday",
      "tomorrow",
      "this week",
      "last year",
      "at the moment",
      "recently",
      "soon",
    ],
    pronounChanges: {
      countable: {
        singular: "it (the apple)",
        plural: "they (the apples)",
      },
      uncountable: {
        singular: "it (the water)",
      },
      dual_use: {
        countable: "it (the paper = article)",
        uncountable: "it (paper = material)",
      },
    },
    reportingVerbs: [
      "have",
      "need",
      "give",
      "receive",
      "show",
      "find",
      "provide",
      "offer",
      "bring",
      "contain",
      "include",
      "require",
      "lack",
      "represent",
      "express",
      "count",
      "measure",
      "pour",
      "add",
      "buy",
      "sell",
      "eat",
      "drink",
    ],
    references: {
      books: [
        {
          title: "English Grammar in Use",
          author: "Raymond Murphy",
          publisher: "Cambridge University Press",
          year: 2019,
          isbn: "978-1108586214",
          relevance:
            "Comprehensive coverage of countable and uncountable nouns with clear explanations and practical exercises. Widely used in ESL classrooms worldwide.",
        },
        {
          title: "Practical English Usage",
          author: "Michael Swan",
          publisher: "Oxford University Press",
          year: 2016,
          isbn: "978-0194202411",
          relevance:
            "Authoritative reference covering problematic areas of English including detailed analysis of noun countability with cross-linguistic comparisons.",
        },
        {
          title: "A Comprehensive Grammar of the English Language",
          author:
            "Randolph Quirk, Sidney Greenbaum, Geoffrey Leech, Jan Svartvik",
          publisher: "Longman",
          year: 1985,
          isbn: "978-0582517349",
          relevance:
            "Definitive academic grammar providing exhaustive treatment of noun classification and countability phenomena in English.",
        },
        {
          title: "The Cambridge Grammar of the English Language",
          author: "Rodney Huddleston, Geoffrey K. Pullum",
          publisher: "Cambridge University Press",
          year: 2002,
          isbn: "978-0521431460",
          relevance:
            "Modern comprehensive reference grammar with detailed analysis of noun phrase structure and mass/count distinctions.",
        },
        {
          title: "English Syntax: A Grammar for Language Professionals",
          author: "Roderick A. Jacobs",
          publisher: "Oxford University Press",
          year: 1995,
          isbn: "978-0195091526",
          relevance:
            "Professional reference focusing on syntactic properties of English nouns and their semantic classification systems.",
        },
        {
          title: "Oxford Modern English Grammar",
          author: "Bas Aarts",
          publisher: "Oxford University Press",
          year: 2011,
          isbn: "978-0199533190",
          relevance:
            "Contemporary grammar with corpus-based analysis of noun usage patterns and countability distinctions in modern English.",
        },
      ],
      websites: [
        {
          title: "Cambridge Dictionary - Grammar",
          url: "https://dictionary.cambridge.org/grammar/",
          description:
            "Comprehensive online grammar resource with detailed explanations of countable and uncountable nouns, including interactive examples and exercises.",
          credibility:
            "Academic publisher with peer-reviewed content and expert linguists",
        },
        {
          title: "Oxford Learner's Dictionaries - Grammar",
          url: "https://www.oxfordlearnersdictionaries.com/grammar/",
          description:
            "Authoritative grammar guidance specifically designed for English language learners with extensive noun classification resources.",
          credibility:
            "University press with established reputation in language education",
        },
        {
          title: "Grammarly Blog - Grammar Rules",
          url: "https://www.grammarly.com/blog/grammar/",
          description:
            "Modern grammar resource with practical explanations and real-world examples of countable and uncountable noun usage.",
          credibility:
            "Professional writing tool with linguistic experts and data-driven insights",
        },
        {
          title: "British Council LearnEnglish",
          url: "https://learnenglish.britishcouncil.org/grammar/",
          description:
            "Official British Council resource providing comprehensive grammar lessons including detailed coverage of noun countability.",
          credibility:
            "International organization for cultural relations and educational opportunities",
        },
        {
          title: "EF Education First - English Grammar Guide",
          url: "https://www.ef.edu/english-resources/english-grammar/",
          description:
            "Educational resource with structured grammar lessons covering countable and uncountable nouns across proficiency levels.",
          credibility:
            "International education company with decades of language teaching experience",
        },
        {
          title: "Perfect English Grammar",
          url: "https://www.perfect-english-grammar.com/",
          description:
            "Specialized grammar website with extensive coverage of noun types, quantifiers, and common mistakes in countability.",
          credibility:
            "Created by qualified English teacher with focus on common learner difficulties",
        },
      ],
      academic_papers: [
        {
          title:
            "The Mass-Count Distinction in English: A Cognitive Semantic Analysis",
          authors: ["Allan, Keith"],
          journal: "Language Sciences",
          year: 2018,
          doi: "10.1016/j.langsci.2018.03.002",
          summary:
            "Comprehensive analysis of cognitive factors influencing mass-count distinctions in English, with implications for second language acquisition.",
        },
        {
          title: "Cross-linguistic Variation in the Mass-Count Distinction",
          authors: ["Chierchia, Gennaro", "Doetjes, Jenny"],
          journal: "Linguistic Inquiry",
          year: 2019,
          doi: "10.1162/ling_a_00315",
          summary:
            "Comparative study examining how different languages handle countability distinctions and implications for English language learning.",
        },
        {
          title:
            "Acquisition of English Mass-Count Syntax by Second Language Learners",
          authors: ["White, Lydia", "Genesee, Fred"],
          journal: "Applied Linguistics",
          year: 2020,
          doi: "10.1093/applin/amz045",
          summary:
            "Empirical study tracking the developmental stages of mass-count acquisition in English L2 learners from various linguistic backgrounds.",
        },
        {
          title: "Semantic Primitives and the Mass-Count Distinction",
          authors: ["Pelletier, Francis Jeffry"],
          journal: "Journal of Semantics",
          year: 2017,
          doi: "10.1093/jos/ffx008",
          summary:
            "Theoretical framework for understanding the semantic foundations of countability distinctions in natural language.",
        },
        {
          title:
            "Teaching the English Mass-Count Distinction: A Corpus-Based Approach",
          authors: ["Biber, Douglas", "Conrad, Susan"],
          journal: "Language Teaching Research",
          year: 2021,
          doi: "10.1177/1362168820945552",
          summary:
            "Pedagogical study demonstrating effective methods for teaching countability using authentic corpus data and frequency information.",
        },
      ],
    },

    pedagogicalApproaches: {
      traditional: [
        "Rule-based instruction with explicit grammar explanations",
        "Memorization of lists of countable and uncountable nouns",
        "Pattern practice with controlled exercises",
        "Error correction and accuracy focus",
        "Deductive presentation of grammar rules",
      ],
      communicative: [
        "Meaningful context-based activities",
        "Real-life communication tasks involving quantities",
        "Interactive role-plays and simulations",
        "Focus on message over form",
        "Negotiation of meaning in authentic contexts",
      ],
      task_based: [
        "Shopping simulation requiring quantity expressions",
        "Information gap activities with mass/count nouns",
        "Problem-solving tasks using appropriate quantifiers",
        "Project work involving data collection and presentation",
        "Collaborative tasks requiring precise noun usage",
      ],
      content_based: [
        "Integration with subject matter (science, social studies)",
        "Academic writing across disciplines",
        "Technical vocabulary in professional contexts",
        "Literature and cultural studies integration",
        "Cross-curricular language development",
      ],
      corpus_based: [
        "Frequency-based vocabulary selection",
        "Authentic examples from large text collections",
        "Pattern discovery through concordance lines",
        "Register-specific usage analysis",
        "Evidence-based rule formulation",
      ],
    },

    assessmentCriteria: {
      A1: [
        "Correctly identify basic countable and uncountable nouns",
        "Use appropriate articles (a/an) with countable nouns",
        "Form simple plurals accurately",
        "Apply basic quantifiers (some, many, much) correctly",
        "Demonstrate understanding through simple sentences",
      ],
      A2: [
        "Use expanded vocabulary of countable and uncountable nouns",
        "Apply quantifiers appropriately in context",
        "Use partitive expressions correctly",
        "Handle requests and offers with proper noun usage",
        "Show awareness of basic dual-usage nouns",
      ],
      B1: [
        "Manage abstract and academic vocabulary accurately",
        "Understand and use dual-usage nouns appropriately",
        "Apply complex quantifiers in various contexts",
        "Express opinions using appropriate noun types",
        "Demonstrate intermediate-level collocational knowledge",
      ],
      B2: [
        "Use professional and technical vocabulary correctly",
        "Show register awareness in noun selection",
        "Handle complex academic writing tasks",
        "Demonstrate sophisticated collocational patterns",
        "Show cultural sensitivity in noun usage",
      ],
      C1: [
        "Master sophisticated academic vocabulary",
        "Understand subtle semantic distinctions",
        "Use idiomatic expressions appropriately",
        "Demonstrate near-native intuition",
        "Handle complex argumentative writing",
      ],
      C2: [
        "Show complete mastery of all aspects",
        "Use language creatively and innovatively",
        "Teach and explain complex concepts to others",
        "Handle all professional and academic contexts",
        "Demonstrate native-like competence",
      ],
    },

    advancedConcepts: {
      register_variation: {
        formal: [
          "legislation, jurisprudence, governance, sovereignty",
          "documentation, correspondence, administration",
          "scholarly discourse, academic terminology",
          "professional communication standards",
        ],
        informal: [
          "stuff, things, loads, tons, heaps",
          "colloquial quantifiers and expressions",
          "casual conversation patterns",
          "everyday usage variations",
        ],
        academic: [
          "research, evidence, analysis, methodology",
          "theoretical frameworks, empirical data",
          "scholarly conventions and terminology",
          "discipline-specific vocabulary",
        ],
        technical: [
          "specifications, parameters, configurations",
          "professional jargon and terminology",
          "industry-specific usage patterns",
          "specialized domain knowledge",
        ],
      },
      semantic_fields: {
        abstract_concepts: [
          "knowledge, wisdom, intelligence, understanding",
          "emotions, feelings, attitudes, beliefs",
          "qualities, characteristics, properties",
          "philosophical and theoretical concepts",
        ],
        concrete_objects: [
          "tools, instruments, equipment, machinery",
          "furniture, appliances, technology",
          "vehicles, buildings, structures",
          "everyday objects and items",
        ],
        substances: [
          "liquids, gases, powders, materials",
          "chemical compounds and elements",
          "natural substances and resources",
          "manufactured products and goods",
        ],
        activities: [
          "sports, hobbies, pastimes, recreation",
          "work, labor, employment, profession",
          "study, learning, education, training",
          "creative and artistic pursuits",
        ],
        emotions: [
          "positive emotions: joy, happiness, love, excitement",
          "negative emotions: anger, fear, sadness, frustration",
          "complex emotions: nostalgia, melancholy, euphoria",
          "social emotions: empathy, sympathy, compassion",
        ],
      },
      collocational_patterns: {
        strong_collocations: [
          "heavy traffic, strong coffee, deep water",
          "hard work, soft music, light rain",
          "fresh air, clean water, pure love",
          "fixed combinations with high frequency",
        ],
        weak_collocations: [
          "more flexible combinations",
          "variable adjective-noun pairings",
          "context-dependent associations",
          "creative and innovative combinations",
        ],
        fixed_expressions: [
          "idioms and phrasal expressions",
          "proverbs and sayings",
          "cultural and traditional phrases",
          "formulaic language patterns",
        ],
      },
    },

    notes: [
      "Countable and uncountable nouns are a key part of English grammar and affect article, quantifier, and verb usage.",
      "Some nouns can be both countable and uncountable with different meanings (dual-use nouns).",
      "Use partitive structures (a piece of, a bottle of, a loaf of) to measure uncountable nouns.",
      "In academic writing, avoid using plural forms for research, evidence, advice, etc.",
      "Be careful with false friends in other languages that may be countable or uncountable in English.",
      "Practice with real-life examples and contexts to master the difference.",
      "Understanding countability is crucial for accurate communication and professional writing.",
      "Cross-linguistic interference is common - what's countable in one language may not be in English.",
      "Corpus-based learning helps identify authentic usage patterns and frequency information.",
      "Register awareness is essential - formal vs. informal contexts may require different approaches.",
    ],

    culturalContexts: {
      daily_life: {
        description: "Common in daily requests, shopping, and conversation",
        examples: [
          "Can I have some bread?",
          "I need information.",
          "There are three apples on the table.",
          "Would you like some coffee?",
          "How much money do you need?",
          "I bought a few books today.",
        ],
      },
      academic: {
        description: "Essential in academic and professional writing",
        examples: [
          "Research shows that...",
          "There is evidence suggesting...",
          "The data indicates...",
          "Several studies demonstrate...",
          "Much attention has been paid to...",
          "A considerable amount of work...",
        ],
      },
      idiomatic: {
        description: "Used in idiomatic expressions and news/media",
        examples: [
          "That's good news!",
          "Bad weather delayed the flight.",
          "Time flies when you're having fun.",
          "Money doesn't grow on trees.",
          "Knowledge is power.",
          "Practice makes perfect.",
        ],
      },
    },

    specialCases: {
      dual_use: {
        description:
          "Nouns that can be both countable and uncountable with different meanings",
        examples: [
          {
            word: "paper",
            countable: "a paper (an article/document)",
            uncountable: "paper (material)",
          },
          {
            word: "chicken",
            countable: "a chicken (an animal)",
            uncountable: "chicken (meat)",
          },
          {
            word: "glass",
            countable: "a glass (a container)",
            uncountable: "glass (material)",
          },
          {
            word: "experience",
            countable: "an experience (a specific event)",
            uncountable: "experience (knowledge/skill)",
          },
          {
            word: "time",
            countable: "a time (an occasion)",
            uncountable: "time (duration/concept)",
          },
          {
            word: "light",
            countable: "a light (a lamp/bulb)",
            uncountable: "light (illumination)",
          },
          {
            word: "hair",
            countable: "a hair (a single strand)",
            uncountable: "hair (all hair collectively)",
          },
          {
            word: "work",
            countable: "a work (a piece of art/literature)",
            uncountable: "work (labor/effort)",
          },
          {
            word: "iron",
            countable: "an iron (appliance for clothes)",
            uncountable: "iron (the metal)",
          },
          {
            word: "room",
            countable: "a room (a space in building)",
            uncountable: "room (space available)",
          },
        ],
      },
    },

    etymology: {
      origin:
        "Many countable and uncountable nouns derive from Old English, Latin, or French, often reflecting concrete or mass concepts. The distinction has Germanic roots but was influenced by Romance languages.",
      development:
        "The distinction between countable and uncountable nouns developed over centuries as English absorbed vocabulary from other languages. Middle English showed more flexibility, but Modern English has standardized many patterns.",
      modernUsage:
        "Countable and uncountable nouns are now systematically used in both spoken and written English, with particular importance in academic and professional contexts. Contemporary usage continues to evolve with new vocabulary and technological terms.",
    },

    crossLinguistic: {
      similarities:
        "Many languages have countable and uncountable noun distinctions, but the specific categorizations and usage rules vary significantly. Germanic and Romance languages share some patterns with English.",
      differences:
        "Some nouns that are countable in English are uncountable in other languages and vice versa. For example, 'information' is uncountable in English but countable in many other languages. Asian languages often lack articles, making the distinction less grammatically explicit.",
      learnerChallenges:
        "Learners often overgeneralize plural forms or use incorrect articles/quantifiers due to interference from their native language. Common areas of difficulty include: abstract nouns, dual-usage nouns, quantifier selection, and register-appropriate usage.",
    },

    vocabulary: {
      countable: [
        "apple",
        "book",
        "car",
        "dog",
        "table",
        "chair",
        "pen",
        "student",
        "question",
        "idea",
        "friend",
        "city",
        "egg",
        "sandwich",
        "cup",
        "bottle",
        "child",
        "person",
        "house",
        "tree",
        "flower",
        "computer",
        "phone",
        "bag",
        "shoe",
        "coin",
        "ticket",
        "letter",
        "photo",
        "room",
        "window",
        "door",
        "bus",
        "train",
        "plane",
        "cat",
        "bird",
        "fish",
        "star",
        "mountain",
        "river",
        "island",
        "country",
        "language",
        "subject",
        "lesson",
        "game",
        "match",
        "team",
        "group",
      ],
      uncountable: [
        "water",
        "rice",
        "advice",
        "information",
        "music",
        "furniture",
        "bread",
        "happiness",
        "news",
        "progress",
        "equipment",
        "homework",
        "knowledge",
        "research",
        "traffic",
        "weather",
        "work",
        "money",
        "sand",
        "air",
        "sugar",
        "salt",
        "love",
        "anger",
        "beauty",
        "health",
        "education",
        "science",
        "literature",
        "art",
        "philosophy",
        "history",
        "culture",
        "tradition",
        "custom",
        "law",
        "order",
        "chaos",
        "silence",
        "noise",
      ],
    },

    grammaticalPatterns: {
      article_usage: {
        countable: [
          "a book",
          "an apple",
          "the car",
          "some apples",
          "many books",
          "few students",
        ],
        uncountable: [
          "some water",
          "much information",
          "little sugar",
          "the furniture",
          "a piece of advice",
          "a bottle of water",
        ],
      },
      verb_agreement: {
        countable: ["The apples are red.", "A book is on the table."],
        uncountable: [
          "The information is useful.",
          "Water is important for life.",
        ],
      },
      quantifiers: {
        countable: ["many", "few", "several", "a number of", "a few"],
        uncountable: [
          "much",
          "little",
          "a bit of",
          "a great deal of",
          "a little",
        ],
      },
      partitives: {
        uncountable: [
          "a piece of advice",
          "a loaf of bread",
          "a bottle of water",
          "a bar of chocolate",
          "a cup of tea",
          "a slice of cheese",
        ],
      },
    },

    usageContexts: {
      A1: ["shopping", "food and drink", "school", "family", "basic needs"],
      A2: [
        "giving/receiving advice",
        "home and furniture",
        "travel",
        "weather",
        "simple descriptions",
      ],
      B1: [
        "news and media",
        "progress updates",
        "information requests",
        "academic settings",
        "workplace",
      ],
      B2: [
        "academic writing",
        "technical descriptions",
        "professional communication",
        "formal essays",
      ],
      C1: [
        "research papers",
        "literary analysis",
        "advanced presentations",
        "creative writing",
      ],
      C2: [
        "critical reviews",
        "specialized academic discourse",
        "creative and metaphorical writing",
      ],
    },

    errorPatterns: {
      A1: [
        "❌ a waters ✅ water",
        "❌ an informations ✅ information",
        "❌ a breads ✅ bread",
        "❌ much apples ✅ many apples",
      ],
      A2: [
        "❌ a advices ✅ advice",
        "❌ few information ✅ little information",
        "❌ many furniture ✅ much furniture",
      ],
      B1: [
        "❌ the apples is ✅ the apples are",
        "❌ the information are ✅ the information is",
      ],
      B2: [
        "❌ researches ✅ research",
        "❌ furnitures ✅ furniture",
        "❌ luggages ✅ luggage",
      ],
      C1: ["❌ evidences ✅ evidence", "❌ informations ✅ information"],
      C2: ["❌ advices ✅ advice", "❌ datas ✅ data"],
    },

    learningStrategies: {
      A1: [
        "Memorize common countable and uncountable nouns with pictures and examples.",
        "Practice using correct article and quantifier.",
        "Listen for noun types in simple conversations.",
      ],
      A2: [
        "Use partitive structures (a piece of, a bottle of) in speaking and writing.",
        "Compare countable and uncountable nouns in context.",
        "Correct common mistakes in exercises.",
      ],
      B1: [
        "Practice using quantifiers (many, much, few, little) with noun types.",
        "Write short texts using a variety of noun types.",
        "Edit sentences for correct noun type usage.",
      ],
      B2: [
        "Use noun types in academic and technical writing.",
        "Paraphrase sentences to use correct noun type idiomatically.",
        "Analyze authentic texts for advanced usage.",
      ],
      C1: [
        "Produce essays and presentations using advanced noun types.",
        "Identify and correct subtle errors in peer writing.",
        "Experiment with idiomatic and metaphorical uses.",
      ],
      C2: [
        "Master rare and highly abstract noun types.",
        "Critique and edit advanced texts for accuracy.",
        "Use noun types creatively in literary and academic contexts.",
      ],
    },
  };
