import { singulariaTantumType } from "@/types/grammars/grammar/noun_special/singularia_tantum";

// Comprehensive Singularia Tantum Data (A1-C2)
export const singulariaTantumData: singulariaTantumType = {
  id: 43,
  definition: {
    core_concept:
      "Singularia tantum are nouns that exist only in the singular form and do not have a standard plural counterpart in English. These nouns represent concepts, substances, or entities that are inherently indivisible, abstract, or treated as unified wholes in the English language system.",
    grammatical_status:
      "These nouns always take singular verb agreement and are treated as individual, unique, or uncountable entities. They function grammatically as singular nouns but semantically may represent mass, abstract, or collective concepts.",
    linguistic_significance:
      "They highlight the concept of uniqueness, indivisibility, or abstractness in language, reflecting how different cultures and languages categorize reality through grammatical structures.",
    etymology_background:
      "The term 'singularia tantum' comes from Latin, meaning 'singular only.' Many English singularia tantum derive from Latin mass nouns, Greek abstractions, or Germanic collective concepts that were borrowed into English while maintaining their singular-only nature.",
    cross_linguistic_perspective:
      "Different languages have varying sets of singularia tantum, reflecting cultural and conceptual differences in how societies categorize and grammaticalize experience. What is singular-only in English may be countable in other languages and vice versa.",
    academic_definition:
      "In linguistic terminology, singularia tantum (also called 'non-count nouns' or 'mass nouns' in some contexts) are lexical items that are morphologically constrained to appear only in singular form, lacking plural morphology and requiring singular agreement patterns in syntactic structures.",
    examples: [
      "information",
      "advice",
      "furniture",
      "luggage",
      "bread",
      "happiness",
      "music",
      "news",
      "progress",
      "equipment",
      "homework",
      "knowledge",
      "research",
      "traffic",
      "weather",
      "work",
      "money",
      "sand",
      "air",
      "sugar",
      "salt",
      "love",
      "anger",
      "literature",
      "poetry",
      "evidence",
      "scenery",
      "software",
      "hardware",
      "data",
      "content",
      "imagery",
      "syntax",
      "semantics",
      "lexicon",
      "foliage",
      "prose",
      "wisdom",
      "courage",
      "freedom",
      "justice",
      "peace",
      "energy",
      "matter",
    ],
  },

  detailed_references: {
    academic_sources: [
      {
        title: "The Grammar of English Grammars",
        author: "Goold Brown",
        year: 1851,
        publisher: "Samuel S. Wood & Sons",
        description:
          "Historical analysis of English grammar including early documentation of singular-only nouns and their usage patterns in formal English.",
      },
      {
        title: "A Comprehensive Grammar of the English Language",
        author:
          "Randolph Quirk, Sidney Greenbaum, Geoffrey Leech, Jan Svartvik",
        year: 1985,
        publisher: "Longman",
        description:
          "Authoritative reference covering the complete grammatical structure of English, with detailed sections on mass nouns and countability.",
      },
      {
        title: "The Cambridge Grammar of the English Language",
        author: "Rodney Huddleston and Geoffrey K. Pullum",
        year: 2002,
        publisher: "Cambridge University Press",
        url: "https://www.cambridge.org/core/books/cambridge-grammar-of-the-english-language",
        description:
          "Modern comprehensive analysis of English grammar with extensive coverage of noun categorization and singularia tantum phenomena.",
      },
      {
        title: "English Grammar: An Introduction",
        author: "John Eastwood",
        year: 2019,
        publisher: "Oxford University Press",
        url: "https://global.oup.com/academic/product/english-grammar-9780194329996",
        description:
          "Contemporary pedagogical grammar with practical explanations of singularia tantum usage for language learners.",
      },
      {
        title: "Cognitive English Grammar",
        author: "Günter Radden and René Dirven",
        year: 2007,
        publisher: "John Benjamins Publishing",
        description:
          "Cognitive linguistic approach to English grammar explaining the conceptual basis for singularia tantum categorization.",
      },
    ],
    linguistic_studies: [
      {
        researcher: "Anna Wierzbicka",
        study_title: "Countability and the mass-count distinction",
        year: 1988,
        key_findings:
          "Cross-linguistic research showing that mass-count distinctions vary significantly across languages, with English singularia tantum representing specific cultural categorizations of reality.",
      },
      {
        researcher: "Helen de Hoop",
        study_title: "Case Configuration and Noun Phrase Interpretation",
        year: 1996,
        key_findings:
          "Demonstrated that singularia tantum behavior is linked to semantic and syntactic features that determine how nouns are interpreted in different grammatical contexts.",
      },
      {
        researcher: "Peter Allan David",
        study_title:
          "Mass and Count in Linguistics, Philosophy, and Cognitive Science",
        year: 2011,
        key_findings:
          "Comprehensive analysis showing that singularia tantum represent a fundamental cognitive category for organizing experience into discrete vs. continuous entities.",
      },
    ],
    grammar_books: [
      {
        title: "Practical English Usage",
        author: "Michael Swan",
        edition: "4th Edition",
        publisher: "Oxford University Press",
        isbn: "978-0194202411",
        relevant_chapters: [
          "Chapter 54: Countable and uncountable nouns",
          "Chapter 89: Articles",
        ],
      },
      {
        title: "English Grammar in Use",
        author: "Raymond Murphy",
        edition: "5th Edition",
        publisher: "Cambridge University Press",
        isbn: "978-1316631737",
        relevant_chapters: [
          "Unit 68: Countable and uncountable 1",
          "Unit 69: Countable and uncountable 2",
        ],
      },
      {
        title: "Advanced Grammar in Use",
        author: "Martin Hewings",
        edition: "3rd Edition",
        publisher: "Cambridge University Press",
        isbn: "978-1107539303",
        relevant_chapters: [
          "Unit 44: Countable and uncountable nouns",
          "Unit 45: Agreement",
        ],
      },
      {
        title: "The Teacher's Grammar of English",
        author: "Ron Cowan",
        publisher: "Cambridge University Press",
        isbn: "978-0521804448",
        relevant_chapters: [
          "Chapter 3: Nouns and Determiners",
          "Chapter 15: Mass and Count Nouns",
        ],
      },
      {
        title: "Understanding and Using English Grammar",
        author: "Betty Azar and Stacy Hagen",
        edition: "5th Edition",
        publisher: "Pearson",
        isbn: "978-0134275239",
        relevant_chapters: [
          "Chapter 7: Count and Noncount Nouns",
          "Chapter 11: Subject-Verb Agreement",
        ],
      },
    ],
  },

  comprehensive_learning_levels: {
    A1: {
      learning_objectives: [
        "Recognize 20-30 most common singularia tantum nouns in daily contexts",
        "Use basic singularia tantum with correct singular verb forms (is/was)",
        "Understand that some nouns cannot be counted directly",
        "Differentiate between 'a/an' (countable) and no article usage patterns",
        "Use simple quantifiers like 'some' and 'much' with basic singularia tantum",
      ],
      core_vocabulary: [
        "water",
        "milk",
        "bread",
        "money",
        "music",
        "weather",
        "information",
        "homework",
        "food",
        "love",
        "time",
        "work",
        "air",
        "light",
        "news",
      ],
      basic_rules: [
        "These nouns are always singular: 'water is', not 'water are'",
        "Cannot use 'a/an' directly: 'some bread', not 'a bread'",
        "Use 'is/was' for present and past tense",
        "Common with 'some', 'much', 'a little'",
        "No -s ending for plural",
      ],
      common_contexts: [
        "Talking about food and drink",
        "Describing weather",
        "Daily activities and school",
        "Basic emotions and feelings",
        "Simple information exchange",
      ],
      fundamental_patterns: [
        "Subject + is/was + adjective (The weather is nice)",
        "I need some + noun (I need some water)",
        "There is + noun (There is music)",
        "Do you have + noun? (Do you have homework?)",
        "I like + noun (I like music)",
      ],
      error_prevention: [
        "Never add -s to these nouns",
        "Always use singular verbs",
        "Don't use 'a/an' directly",
        "Remember: 'information', not 'informations'",
        "Use 'How much' not 'How many' for questions",
      ],
    },
    A2: {
      learning_objectives: [
        "Expand vocabulary to 50-60 singularia tantum nouns",
        "Use basic quantifiers and containers correctly",
        "Form simple questions and negative sentences",
        "Understand the concept of 'pieces' and 'items' for counting",
        "Recognize singularia tantum in simple reading texts",
      ],
      expanded_vocabulary: [
        "advice",
        "furniture",
        "luggage",
        "equipment",
        "traffic",
        "progress",
        "knowledge",
        "happiness",
        "sadness",
        "anger",
        "peace",
        "freedom",
        "health",
        "beauty",
        "strength",
        "courage",
        "luck",
        "help",
        "fun",
        "sleep",
      ],
      sentence_patterns: [
        "Comparative structures: 'This furniture is more expensive'",
        "Question formation: 'How much information do you need?'",
        "Negative forms: 'There isn't much traffic today'",
        "Present perfect: 'I have learned new information'",
        "Modal verbs: 'You should take advice'",
      ],
      practical_usage: [
        "Giving and asking for advice",
        "Describing furniture and belongings",
        "Talking about travel and luggage",
        "Discussing emotions and feelings",
        "Simple academic contexts",
      ],
      quantifier_introduction: [
        "a piece of (advice, information, furniture)",
        "a bit of (help, luck, fun)",
        "a lot of (traffic, homework, work)",
        "containers: a glass of water, a cup of coffee",
        "portions: a slice of bread, a drop of milk",
      ],
      common_mistakes_awareness: [
        "Avoiding 'advices', 'furnitures', 'informations'",
        "Correct quantifier selection",
        "Proper article usage",
        "Verb agreement in questions",
        "Understanding when to use containers vs. direct quantifiers",
      ],
    },
    B1: {
      learning_objectives: [
        "Master 80-100 singularia tantum nouns including abstract concepts",
        "Use complex quantifiers and expressions fluently",
        "Understand register differences in formal vs. informal contexts",
        "Recognize and correct common errors in speech and writing",
        "Apply singularia tantum rules in narrative and descriptive texts",
      ],
      intermediate_vocabulary: [
        "research",
        "evidence",
        "literature",
        "poetry",
        "music",
        "art",
        "education",
        "experience",
        "independence",
        "responsibility",
        "honesty",
        "patience",
        "wisdom",
        "intelligence",
        "creativity",
        "ambition",
        "enthusiasm",
        "confidence",
        "respect",
        "trust",
        "faith",
      ],
      contextual_usage: [
        "Academic discussions and presentations",
        "Formal email and letter writing",
        "Narrative storytelling",
        "Opinion expression and argumentation",
        "Cultural and social commentary",
      ],
      comparison_with_countables: [
        "Understanding when nouns can be both countable and uncountable",
        "Recognizing context-dependent usage",
        "Differentiating specific vs. general references",
        "Mastering double-category nouns (paper/papers, work/works)",
        "Understanding semantic shifts in meaning",
      ],
      idiomatic_expressions: [
        "Time is money",
        "Knowledge is power",
        "Practice makes perfect",
        "Experience is the best teacher",
        "Honesty is the best policy",
        "Patience is a virtue",
        "Beauty is in the eye of the beholder",
      ],
      discourse_markers: [
        "Furthermore, this research shows...",
        "Based on the evidence...",
        "From my experience...",
        "According to the information...",
        "In terms of education...",
      ],
    },
    B2: {
      learning_objectives: [
        "Command 120-150 singularia tantum including technical and academic terms",
        "Use sophisticated quantification and modification patterns",
        "Understand nuanced differences in meaning and register",
        "Apply singularia tantum appropriately in formal writing",
        "Analyze usage patterns in authentic academic and professional texts",
      ],
      advanced_vocabulary: [
        "legislation",
        "jurisprudence",
        "bureaucracy",
        "surveillance",
        "infrastructure",
        "maintenance",
        "surveillance",
        "propaganda",
        "rhetoric",
        "eloquence",
        "charisma",
        "intuition",
        "consciousness",
        "subconscious",
        "metabolism",
        "photosynthesis",
        "entropy",
        "momentum",
      ],
      academic_contexts: [
        "Research methodology discussions",
        "Scientific report writing",
        "Literature and cultural analysis",
        "Business and economics texts",
        "Legal and political discourse",
      ],
      technical_usage: [
        "Scientific and technical writing",
        "Professional communications",
        "Academic essay structure",
        "Formal presentation delivery",
        "Critical analysis and evaluation",
      ],
      formal_writing_applications: [
        "Thesis and dissertation writing",
        "Academic journal articles",
        "Professional reports and proposals",
        "Legal and policy documents",
        "Literary and cultural criticism",
      ],
      nuanced_distinctions: [
        "Register-appropriate vocabulary selection",
        "Connotative vs. denotative meanings",
        "Formal vs. informal variants",
        "Discipline-specific usage patterns",
        "Cultural and contextual sensitivity",
      ],
    },
    C1: {
      learning_objectives: [
        "Master 180-200 singularia tantum including specialized terminology",
        "Demonstrate sophisticated control of style and register",
        "Understand etymological and cross-linguistic perspectives",
        "Use singularia tantum effectively in persuasive and analytical writing",
        "Recognize and analyze patterns in professional and literary texts",
      ],
      sophisticated_vocabulary: [
        "phenomenology",
        "epistemology",
        "hermeneutics",
        "semiotics",
        "pragmatics",
        "semantics",
        "syntax",
        "morphology",
        "phonetics",
        "acoustics",
        "aerodynamics",
        "thermodynamics",
        "quantum",
        "relativity",
        "existentialism",
        "nihilism",
        "hedonism",
        "altruism",
        "stoicism",
      ],
      professional_contexts: [
        "Academic conference presentations",
        "Professional consultation and advisory roles",
        "Policy development and analysis",
        "International business communications",
        "Cross-cultural professional interactions",
      ],
      literary_usage: [
        "Poetry and creative writing",
        "Literary criticism and analysis",
        "Philosophical and theoretical discourse",
        "Artistic and aesthetic commentary",
        "Cultural and social critique",
      ],
      specialized_fields: [
        "Medical and healthcare terminology",
        "Legal and judicial language",
        "Scientific and technical discourse",
        "Economic and financial analysis",
        "Educational and pedagogical contexts",
      ],
      stylistic_considerations: [
        "Tone and mood manipulation",
        "Rhythm and flow in academic prose",
        "Sophisticated argumentation techniques",
        "Subtle persuasion and influence",
        "Advanced coherence and cohesion strategies",
      ],
    },
    C2: {
      learning_objectives: [
        "Achieve native-like competence with 200+ singularia tantum",
        "Demonstrate mastery across all registers and contexts",
        "Understand historical development and etymology",
        "Use singularia tantum creatively and innovatively",
        "Analyze and critique usage in complex academic and literary texts",
      ],
      mastery_vocabulary: [
        "lexicography",
        "philology",
        "etymology",
        "dialectology",
        "sociolinguistics",
        "psycholinguistics",
        "neurolinguistics",
        "computational linguistics",
        "corpus linguistics",
        "forensic linguistics",
        "clinical linguistics",
        "anthropological linguistics",
        "historical linguistics",
        "comparative linguistics",
      ],
      expert_usage: [
        "Original research and scholarship",
        "Advanced literary and artistic creation",
        "Professional editing and proofreading",
        "Cross-linguistic translation and interpretation",
        "Meta-linguistic analysis and commentary",
      ],
      research_contexts: [
        "Doctoral dissertation research",
        "Professional academic publication",
        "Grant proposal writing",
        "International scholarly collaboration",
        "Advanced theoretical investigation",
      ],
      cross_disciplinary_applications: [
        "Interdisciplinary research methodology",
        "Theoretical framework development",
        "Comparative cultural analysis",
        "Advanced statistical and empirical analysis",
        "Meta-analytical and systematic review",
      ],
      linguistic_analysis: [
        "Morphosyntactic pattern recognition",
        "Semantic field analysis",
        "Pragmatic and discourse analysis",
        "Historical and diachronic investigation",
        "Typological and comparative analysis",
      ],
    },
  },
  singularia_tantum_vocab: {
    abstract_concepts: [
      "information",
      "advice",
      "knowledge",
      "love",
      "anger",
      "happiness",
      "sadness",
      "hope",
      "fear",
      "courage",
      "honesty",
      "truth",
      "justice",
      "loyalty",
      "wisdom",
      "freedom",
      "peace",
      "education",
      "music",
      "art",
      "patience",
      "faith",
      "trust",
      "beauty",
      "strength",
      "confidence",
      "respect",
      "responsibility",
      "independence",
      "creativity",
      "intelligence",
      "consciousness",
      "awareness",
      "intuition",
      "imagination",
      "inspiration",
      "motivation",
      "ambition",
      "determination",
      "perseverance",
      "resilience",
    ],

    academic_fields: [
      "mathematics",
      "physics",
      "chemistry",
      "biology",
      "history",
      "geography",
      "philosophy",
      "economics",
      "linguistics",
      "ethics",
      "sociology",
      "psychology",
      "anthropology",
      "archaeology",
      "literature",
      "grammar",
      "logic",
      "aesthetics",
      "epistemology",
      "ontology",
      "phenomenology",
      "hermeneutics",
      "semiotics",
      "pragmatics",
      "semantics",
      "syntax",
      "morphology",
      "phonetics",
      "phonology",
      "sociolinguistics",
      "psycholinguistics",
      "neurolinguistics",
      "computational linguistics",
    ],

    material_substances: [
      "water",
      "milk",
      "oil",
      "gas",
      "electricity",
      "air",
      "wood",
      "metal",
      "plastic",
      "gold",
      "silver",
      "copper",
      "glass",
      "sand",
      "dust",
      "iron",
      "lead",
      "aluminum",
      "steel",
      "concrete",
      "cement",
      "clay",
      "mud",
      "soil",
      "coal",
      "charcoal",
      "fabric",
      "leather",
      "rubber",
      "cotton",
      "wool",
      "silk",
      "nylon",
      "polyester",
      "vinyl",
      "ceramic",
      "porcelain",
    ],

    phenomena_and_nature: [
      "rain",
      "snow",
      "fog",
      "sunshine",
      "lightning",
      "thunder",
      "heat",
      "cold",
      "gravity",
      "time",
      "space",
      "weather",
      "wind",
      "darkness",
      "light",
      "dew",
      "frost",
      "mist",
      "humidity",
      "pressure",
      "radiation",
      "magnetism",
      "electricity",
      "energy",
      "motion",
      "acceleration",
      "velocity",
      "momentum",
      "inertia",
      "friction",
      "turbulence",
      "erosion",
    ],

    mass_and_measurement: [
      "furniture",
      "luggage",
      "equipment",
      "baggage",
      "clothing",
      "traffic",
      "homework",
      "work",
      "money",
      "bread",
      "meat",
      "rice",
      "flour",
      "butter",
      "salt",
      "sugar",
      "machinery",
      "jewelry",
      "cutlery",
      "crockery",
      "stationery",
      "software",
      "hardware",
      "ammunition",
      "artillery",
      "infantry",
      "cavalry",
      "personnel",
      "staff",
      "crew",
      "livestock",
    ],

    disciplines_and_theories: [
      "realism",
      "idealism",
      "symbolism",
      "existentialism",
      "capitalism",
      "socialism",
      "communism",
      "modernism",
      "postmodernism",
      "feminism",
      "humanism",
      "nationalism",
      "liberalism",
      "conservatism",
      "fascism",
      "anarchism",
      "structuralism",
      "poststructuralism",
      "deconstructionism",
      "minimalism",
      "impressionism",
      "expressionism",
      "surrealism",
      "cubism",
    ],

    activities_and_events: [
      "travel",
      "shopping",
      "cooking",
      "reading",
      "writing",
      "dancing",
      "running",
      "swimming",
      "sleep",
      "fun",
      "entertainment",
      "recreation",
      "leisure",
      "research",
      "training",
      "exercise",
      "practice",
      "rehearsal",
      "performance",
      "competition",
      "gaming",
      "fishing",
      "hunting",
      "hiking",
      "camping",
      "sailing",
      "skiing",
      "surfing",
      "climbing",
      "cycling",
    ],

    states_and_conditions: [
      "health",
      "illness",
      "poverty",
      "wealth",
      "chaos",
      "order",
      "silence",
      "noise",
      "strength",
      "weakness",
      "beauty",
      "ugliness",
      "madness",
      "calm",
      "violence",
      "peace",
      "war",
      "conflict",
      "harmony",
      "discord",
      "unity",
      "division",
      "stability",
      "instability",
      "security",
      "insecurity",
      "certainty",
      "uncertainty",
      "clarity",
      "confusion",
      "simplicity",
      "complexity",
    ],

    emotions_and_feelings: [
      "joy",
      "grief",
      "sorrow",
      "envy",
      "jealousy",
      "sympathy",
      "compassion",
      "hatred",
      "shock",
      "pleasure",
      "delight",
      "boredom",
      "stress",
      "relief",
      "nostalgia",
      "melancholy",
      "euphoria",
      "anxiety",
      "depression",
      "panic",
      "excitement",
      "enthusiasm",
      "disappointment",
      "frustration",
      "irritation",
      "contentment",
      "satisfaction",
      "pride",
      "shame",
      "guilt",
      "regret",
    ],

    legal_and_philosophical: [
      "evidence",
      "legislation",
      "jurisprudence",
      "morality",
      "ethics",
      "logic",
      "reason",
      "consciousness",
      "identity",
      "responsibility",
      "autonomy",
      "duty",
      "liberty",
      "equality",
      "justice",
      "injustice",
      "fairness",
      "unfairness",
      "legitimacy",
      "authority",
      "sovereignty",
      "citizenship",
      "democracy",
      "autocracy",
      "bureaucracy",
      "meritocracy",
      "transparency",
      "accountability",
    ],

    scientific_and_technical: [
      "energy",
      "matter",
      "radiation",
      "quantum",
      "data",
      "entropy",
      "evolution",
      "relativity",
      "thermodynamics",
      "momentum",
      "mass",
      "velocity",
      "inertia",
      "fusion",
      "fission",
      "photosynthesis",
      "metabolism",
      "genetics",
      "genomics",
      "biotechnology",
      "nanotechnology",
      "cybernetics",
      "robotics",
      "automation",
      "digitization",
      "computerization",
      "virtualization",
      "simulation",
      "modeling",
    ],

    business_and_finance: [
      "capital",
      "finance",
      "income",
      "revenue",
      "investment",
      "wealth",
      "inflation",
      "unemployment",
      "commerce",
      "trade",
      "debt",
      "credit",
      "taxation",
      "banking",
      "insurance",
      "accounting",
      "auditing",
      "marketing",
      "advertising",
      "branding",
      "merchandising",
      "logistics",
      "procurement",
      "manufacturing",
      "production",
      "distribution",
      "retail",
      "wholesale",
    ],

    food_and_drink: [
      "water",
      "coffee",
      "tea",
      "milk",
      "wine",
      "juice",
      "bread",
      "butter",
      "salt",
      "pepper",
      "flour",
      "cheese",
      "meat",
      "honey",
      "rice",
      "pasta",
      "soup",
      "sauce",
      "gravy",
      "jam",
      "jelly",
      "cream",
      "yogurt",
      "chocolate",
      "candy",
      "sugar",
      "vinegar",
      "mustard",
      "ketchup",
      "mayonnaise",
    ],

    culture_and_language: [
      "language",
      "poetry",
      "music",
      "art",
      "literature",
      "cinema",
      "drama",
      "humour",
      "mythology",
      "folklore",
      "rhetoric",
      "irony",
      "satire",
      "symbolism",
      "allegory",
      "metaphor",
      "imagery",
      "narrative",
      "discourse",
      "dialogue",
      "monologue",
      "eloquence",
      "oratory",
      "calligraphy",
      "typography",
    ],

    other_concepts: [
      "nature",
      "society",
      "technology",
      "humanity",
      "reality",
      "existence",
      "truthfulness",
      "perception",
      "emotion",
      "concentration",
      "ambition",
      "despair",
      "creativity",
      "innovation",
      "leadership",
      "teamwork",
      "cooperation",
      "collaboration",
      "communication",
      "networking",
      "globalization",
      "localization",
      "urbanization",
      "modernization",
      "industrialization",
      "digitalization",
    ],
  },

  detailed_categorization: {
    by_semantic_field: {
      cognitive_processes: {
        description: "Mental activities and intellectual functions",
        examples: [
          "thinking",
          "reasoning",
          "understanding",
          "comprehension",
          "analysis",
        ],
        level_distribution: {
          A1: ["thinking"],
          A2: ["understanding"],
          B1: ["reasoning", "comprehension"],
          B2: ["analysis", "synthesis"],
          C1: ["cognition", "metacognition"],
          C2: ["epistemology", "hermeneutics"],
        },
      },
      physical_phenomena: {
        description: "Natural and physical processes and states",
        examples: [
          "weather",
          "gravity",
          "electricity",
          "magnetism",
          "radiation",
        ],
        level_distribution: {
          A1: ["weather", "light", "heat"],
          A2: ["electricity", "wind"],
          B1: ["gravity", "pressure"],
          B2: ["magnetism", "radiation"],
          C1: ["thermodynamics", "quantum"],
          C2: ["electromagnetism", "relativity"],
        },
      },
      social_constructs: {
        description: "Concepts created and maintained by human society",
        examples: [
          "democracy",
          "capitalism",
          "culture",
          "tradition",
          "progress",
        ],
        level_distribution: {
          A1: ["culture"],
          A2: ["tradition", "progress"],
          B1: ["democracy", "freedom"],
          B2: ["capitalism", "socialism"],
          C1: ["bureaucracy", "meritocracy"],
          C2: ["jurisprudence", "sovereignty"],
        },
      },
      abstract_qualities: {
        description: "Non-physical characteristics and properties",
        examples: ["beauty", "wisdom", "courage", "honesty", "intelligence"],
        level_distribution: {
          A1: ["beauty", "love"],
          A2: ["courage", "honesty"],
          B1: ["wisdom", "patience"],
          B2: ["intelligence", "creativity"],
          C1: ["eloquence", "charisma"],
          C2: ["perspicacity", "sagacity"],
        },
      },
    },
    by_frequency: {
      high_frequency: [
        "information",
        "advice",
        "money",
        "work",
        "time",
        "water",
        "food",
        "music",
        "news",
        "weather",
        "love",
        "help",
        "fun",
        "health",
        "peace",
      ],
      medium_frequency: [
        "furniture",
        "equipment",
        "research",
        "knowledge",
        "education",
        "experience",
        "progress",
        "traffic",
        "luggage",
        "homework",
      ],
      low_frequency: [
        "literature",
        "poetry",
        "evidence",
        "legislation",
        "jurisprudence",
        "rhetoric",
        "eloquence",
        "consciousness",
        "phenomenology",
      ],
      academic_specialized: [
        "epistemology",
        "hermeneutics",
        "semiotics",
        "pragmatics",
        "syntax",
        "morphology",
        "phonetics",
        "sociolinguistics",
        "psycholinguistics",
      ],
    },
    by_origin: {
      latin_origin: [
        "information",
        "education",
        "evidence",
        "jurisprudence",
        "legislation",
        "administration",
        "transportation",
        "communication",
        "cooperation",
      ],
      greek_origin: [
        "philosophy",
        "psychology",
        "physics",
        "mathematics",
        "grammar",
        "rhetoric",
        "logic",
        "ethics",
        "aesthetics",
        "epistemology",
      ],
      germanic_origin: [
        "work",
        "bread",
        "water",
        "weather",
        "strength",
        "wisdom",
        "freedom",
        "happiness",
        "sadness",
        "anger",
        "fear",
        "hope",
      ],
      french_origin: [
        "beauty",
        "courage",
        "honor",
        "justice",
        "literature",
        "poetry",
        "art",
        "music",
        "dance",
        "culture",
      ],
      modern_formations: [
        "software",
        "hardware",
        "internet",
        "cybersecurity",
        "biotechnology",
        "nanotechnology",
        "telecommunications",
        "digitalization",
      ],
    },
  },

  grammatical_properties: {
    verb_agreement: {
      present_tense: [
        "Information is valuable",
        "Advice helps people",
        "Music sounds beautiful",
        "Weather affects mood",
        "Knowledge empowers individuals",
      ],
      past_tense: [
        "The information was accurate",
        "His advice was helpful",
        "The music was loud",
        "The weather was terrible",
      ],
      perfect_aspects: [
        "The information has been verified",
        "Advice has been given",
        "Music has always been important",
        "Weather has improved",
      ],
      modal_constructions: [
        "Information should be accurate",
        "Advice can be helpful",
        "Music might be loud",
        "Weather could change",
      ],
    },
    determiner_usage: {
      articles: [
        "The information (specific)",
        "Some advice (indefinite quantity)",
        "Much knowledge (large quantity)",
        "Little progress (small quantity)",
      ],
      quantifiers: [
        "much/little",
        "some/any",
        "a lot of/lots of",
        "a great deal of",
        "a piece of",
        "an item of",
        "a bit of",
      ],
      possessives: [
        "my advice",
        "your information",
        "his knowledge",
        "her wisdom",
        "our research",
        "their equipment",
      ],
      demonstratives: [
        "this information",
        "that advice",
        "these data (pl. in academic)",
        "such knowledge",
        "this kind of research",
      ],
    },
    modification_patterns: {
      adjective_placement: [
        "valuable information",
        "useful advice",
        "beautiful music",
        "accurate data",
        "reliable equipment",
      ],
      prepositional_phrases: [
        "information about the project",
        "advice on relationships",
        "research into climate change",
        "knowledge of linguistics",
      ],
      relative_clauses: [
        "information that is accurate",
        "advice which helps people",
        "research that has been conducted",
        "knowledge that empowers",
      ],
      participial_constructions: [
        "information gathered from surveys",
        "advice given by experts",
        "research conducted by scientists",
        "knowledge acquired through study",
      ],
    },
  },
  cefrLevels: {
    A1: "Recognize and use common singularia tantum nouns in basic contexts (e.g., information, advice, bread)",
    A2: "Use singularia tantum nouns in simple sentences and understand their singular verb agreement",
    B1: "Distinguish singularia tantum from countable nouns and use them in everyday conversation",
    B2: "Use less common singularia tantum nouns and understand academic/technical contexts",
    C1: "Employ singularia tantum in academic, technical, and formal writing",
    C2: "Mastery of all singularia tantum forms, including rare and specialized terms",
  },
  forms: {
    basic:
      "Singularia tantum nouns always appear in the singular form (e.g., information is, advice is)",
    with_quantifier: "A piece of advice, a bit of information, a loaf of bread",
    with_article: "The furniture is new",
    no_plural:
      "No standard plural form exists (not 'informations', but 'pieces of information')",
  },
  usage: [
    "Abstract concepts (advice, knowledge, happiness)",
    "Substances and materials (bread, water, sand, air)",
    "Collective or mass nouns (furniture, equipment, luggage)",
    "Academic and technical terms (data, evidence, research)",
  ],
  examples: {
    basic: [
      "The information is accurate.",
      "She gave me good advice.",
      "This furniture is expensive.",
      "I need some bread.",
      "The news is interesting.",
    ],
    with_quantifier: [
      "Can I have a piece of cake?",
      "He offered a bit of advice.",
      "There is a loaf of bread on the table.",
    ],
    idiomatic: ["Knowledge is power.", "Time is money."],
    academic: ["The research is ongoing.", "The evidence is inconclusive."],
  },
  practiceTypes: {
    A1: "Recognition and matching exercises with common singularia tantum nouns",
    A2: "Fill-in-the-blank and sentence completion with correct verb agreement",
    B1: "Error correction and production tasks in context",
    B2: "Academic and technical usage in writing",
    C1: "Formal and specialized writing with singularia tantum",
    C2: "Advanced editing and nuanced usage in academic texts",
  },
  commonMistakes: {
    beginners: [
      "Using plural verbs (e.g., 'information are')",
      "Trying to use a plural form (e.g., 'informations')",
    ],
    intermediate: [
      "Incorrect quantifier usage (e.g., 'two advices' instead of 'two pieces of advice')",
      "Confusing singularia tantum with countable nouns",
    ],
    advanced: [
      "Misusing rare or technical singularia tantum nouns",
      "Incorrect verb agreement in complex sentences",
    ],
  },
  recognition: [
    "Look for nouns that refer to abstract concepts, substances, or mass/collective items",
    "Check for nouns that only appear in the singular in dictionaries",
    "Practice with context clues and collocations",
  ],
  timeMarkers: ["Always", "In all tenses and contexts"],
  pronounVerbAgreement: {
    basic: "Always use singular verbs and pronouns (e.g., 'this is', 'it is')",
    advanced: "Maintain agreement in complex and embedded clauses",
  },
  exercises: {
    recognition: "Identify singularia tantum nouns in sentences",
    correction: "Correct verb agreement and quantifier errors",
    production: "Use singularia tantum nouns accurately in context",
  },
  notes: [
    "Some singularia tantum nouns can be made countable with 'a piece of...', 'an item of...', etc.",
    "Not all uncountable nouns are singularia tantum (e.g., 'news' is singular in form but plural in meaning in some languages)",
    "Some words are singularia tantum in English but not in other languages",
  ],
  culturalContexts: {
    daily_life: "Common in food, advice, and information contexts",
    academic: "Used in research, technical, and scientific writing",
    idiomatic: "Appear in idioms and set phrases",
  },
  specialCases: {
    false_plural:
      "Words that look plural but are singular in meaning (e.g., 'news', 'mathematics')",
    regional:
      "Regional differences in usage (e.g., 'data' as plural in British English)",
    archaic: "Archaic or rare singularia tantum forms",
  },
  etymology: {
    origin:
      "Many singularia tantum nouns derive from Latin or Greek mass nouns or abstract concepts",
    development: "Evolved to reflect abstractness or indivisibility",
    modernUsage:
      "Some have developed plural forms in informal speech, but standard English maintains the singular",
  },
  crossLinguistic: {
    similarities:
      "Other languages also have singularia tantum nouns, often for similar concepts",
    differences: "The specific nouns and rules vary across languages",
    learnerChallenges:
      "Learners may overgeneralize or misapply singularia tantum rules",
  },
  vocabulary: {
    A1: ["information", "advice", "bread", "music"],
    A2: ["furniture", "luggage", "happiness", "news"],
    B1: ["equipment", "homework", "knowledge", "research"],
    B2: ["traffic", "weather", "work", "money"],
    C1: ["literature", "poetry", "evidence", "scenery"],
    C2: ["syntax", "semantics", "lexicon", "foliage"],
  },
  grammaticalPatterns: {
    article_usage: "Use 'a piece of', 'an item of' for countable reference",
    verb_agreement: "Always use singular verbs",
    quantifiers: "Use 'some', 'much', 'a little', etc.",
  },
  usageContexts: {
    A1: "Basic daily life contexts (food, advice, information)",
    A2: "Simple descriptions and instructions",
    B1: "Narrative and conversation",
    B2: "Academic and technical writing",
    C1: "Formal and specialized contexts",
    C2: "Advanced academic, legal, and literary contexts",
  },
  errorPatterns: {
    A1: "Using plural verbs",
    A2: "Omitting quantifiers when needed",
    B1: "Confusing with countable nouns",
    B2: "Incorrect use in idiomatic expressions",
    C1: "Misuse in formal writing",
    C2: "Rare or archaic errors",
  },
  learningStrategies: {
    A1: "Memorize common singularia tantum nouns through repetition and visual association",
    A2: "Practice with matching and fill-in-the-blank exercises using basic quantifiers",
    B1: "Use in context and conversation, focusing on natural speech patterns",
    B2: "Study idioms and technical usage through authentic texts and materials",
    C1: "Analyze academic and formal texts to understand sophisticated usage patterns",
    C2: "Mastery through editing and advanced writing, including creative applications",
  },

  advanced_applications: {
    discourse_analysis: [
      "Tracking thematic development through singularia tantum usage",
      "Analyzing register shifts via vocabulary selection",
      "Identifying authorial stance through abstract noun choices",
      "Examining cohesion patterns in academic writing",
      "Understanding information packaging in complex texts",
    ],
    stylistic_variation: [
      "Formal vs. informal register distinctions",
      "Academic vs. popular writing styles",
      "Technical vs. general audience adaptations",
      "Creative vs. expository writing applications",
      "Cross-cultural communication adaptations",
    ],
    register_awareness: [
      "Professional communication protocols",
      "Academic writing conventions",
      "Legal and policy document requirements",
      "Scientific and technical reporting standards",
      "Literary and creative writing techniques",
    ],
    pragmatic_considerations: [
      "Context-appropriate vocabulary selection",
      "Audience-sensitive language choices",
      "Cultural and social sensitivity factors",
      "Persuasive and rhetorical applications",
      "Cross-linguistic translation challenges",
    ],
  },

  assessment_criteria: {
    A1: [
      "Recognizes 15-20 high-frequency singularia tantum in context",
      "Uses correct singular verb agreement with basic nouns",
      "Understands that some nouns cannot take 'a/an'",
      "Can form simple affirmative sentences with singularia tantum",
      "Demonstrates basic quantifier usage with 'some' and 'much'",
    ],
    A2: [
      "Recognizes 35-45 common singularia tantum across various contexts",
      "Uses basic quantifiers and containers appropriately",
      "Forms questions and negatives with correct agreement",
      "Understands 'piece of/bit of' constructions",
      "Avoids common errors like adding -s endings",
    ],
    B1: [
      "Commands 60-80 singularia tantum including abstract concepts",
      "Uses complex quantifiers and expressions fluently",
      "Demonstrates register awareness in different contexts",
      "Can correct errors in others' usage",
      "Applies rules consistently in extended discourse",
    ],
    B2: [
      "Masters 100-120 singularia tantum including technical terms",
      "Shows sophisticated quantification patterns",
      "Understands nuanced meaning differences",
      "Uses appropriately in formal writing contexts",
      "Demonstrates cross-linguistic awareness",
    ],
    C1: [
      "Commands 150-180 singularia tantum including specialized terminology",
      "Shows sophisticated style and register control",
      "Understands etymological relationships",
      "Uses effectively in persuasive and analytical writing",
      "Recognizes patterns in professional texts",
    ],
    C2: [
      "Achieves native-like competence with 200+ singularia tantum",
      "Demonstrates mastery across all registers and contexts",
      "Shows creative and innovative usage",
      "Can analyze and critique complex usage patterns",
      "Understands historical and cross-linguistic perspectives",
    ],
  },
};
