import { uncountableNounsType } from "@/types/grammars/grammar/noun_special/uncountable_nouns";

// Comprehensive Uncountable Nouns Data (A1-C2)
export const uncountableNounsData: uncountableNounsType = {
  id: 44,
  definition: {
    core_concept:
      "Uncountable nouns (also known as mass nouns or non-count nouns) are nouns that refer to substances, concepts, activities, or entities that cannot be counted as separate, discrete units. They represent continuous quantities, abstract ideas, or collective categories that exist as undifferentiated masses or wholes rather than countable individuals.",
    grammatical_status:
      "Uncountable nouns are grammatically singular, always taking singular verb forms and determiners. They cannot be directly preceded by indefinite articles (a/an) or numbers, and they do not have plural forms. When quantification is needed, they require partitive constructions or quantifiers.",
    linguistic_significance:
      "Uncountable nouns represent a fundamental grammatical distinction in English that reflects how speakers conceptualize and categorize reality. They encode cultural and cognitive patterns of how mass, continuity, and abstractness are linguistically represented, serving crucial functions in academic, professional, and everyday discourse.",
    historical_development:
      "The count/mass distinction in English evolved from Old English and was influenced by Latin and French. Historical linguistics shows that the categorization of nouns as countable or uncountable has shifted over time, with some nouns changing categories due to semantic bleaching, grammaticalization, and contact with other languages.",
    cross_linguistic_perspective:
      "While most languages have some form of count/mass distinction, the specific categorizations vary significantly. What is uncountable in English may be countable in other languages (e.g., 'advice' vs. French 'conseil'), creating learning challenges for L2 speakers and revealing deep structural differences between language systems.",
    semantic_classification:
      "Uncountable nouns typically fall into semantic categories: (1) Substances and materials, (2) Abstract concepts and qualities, (3) Collective masses, (4) Activities and processes, (5) Academic disciplines and fields of knowledge, (6) Natural phenomena, and (7) States and conditions.",
    examples: [
      "water",
      "rice",
      "advice",
      "information",
      "music",
      "furniture",
      "bread",
      "happiness",
      "news",
      "progress",
      "equipment",
      "homework",
      "knowledge",
      "research",
      "traffic",
      "weather",
      "work",
      "money",
      "sand",
      "air",
      "sugar",
      "salt",
      "love",
      "anger",
      "luggage",
      "machinery",
      "literature",
      "poetry",
      "evidence",
      "scenery",
      "software",
      "hardware",
      "data",
      "content",
      "criteria",
      "imagery",
      "syntax",
      "semantics",
      "lexicon",
      "foliage",
      "prose",
      "phonetics",
      "morphology",
      "pragmatics",
    ],
  },

  references: {
    academic_sources: [
      {
        title: "The Grammar of English Nouns and Noun Phrases",
        author: "Huddleston, R. & Pullum, G.",
        year: 2002,
        publisher: "Cambridge University Press",
        isbn: "978-0521431460",
        pages: "334-398",
        description:
          "Comprehensive analysis of count/mass distinction with detailed grammatical rules and cross-linguistic comparisons",
      },
      {
        title:
          "Mass and Count in Linguistics, Philosophy, and Cognitive Science",
        author: "Pelletier, F. J. & Schubert, L. K.",
        year: 2003,
        publisher: "John Benjamins",
        isbn: "978-1588113191",
        description:
          "Interdisciplinary approach to understanding mass/count distinctions from linguistic, philosophical, and cognitive perspectives",
      },
      {
        title: "Countability and Number in English Nouns",
        author: "Wickens, P.",
        year: 1992,
        publisher: "Whurr Publishers",
        isbn: "978-1870332453",
        description:
          "Detailed study of countability phenomena with pedagogical implications for ESL teaching",
      },
      {
        title: "The Semantics of Mass and Count",
        author: "Borer, H.",
        year: 2005,
        publisher: "Oxford University Press",
        isbn: "978-0199263936",
        description:
          "Theoretical analysis of mass/count distinction from a generative grammar perspective",
      },
      {
        title: "English Grammar: A University Course",
        author: "Downing, A. & Locke, P.",
        year: 2006,
        publisher: "Routledge",
        isbn: "978-0415288965",
        pages: "156-189",
        description:
          "University-level treatment of uncountable nouns with comprehensive examples and usage patterns",
      },
    ],
    grammar_books: [
      {
        title: "A Comprehensive Grammar of the English Language",
        author: "Quirk, R., Greenbaum, S., Leech, G., & Svartvik, J.",
        level: "Advanced/Reference",
        publisher: "Longman",
        edition: "1st Edition",
        isbn: "978-0582517349",
        relevance:
          "The definitive reference work on English grammar with extensive coverage of uncountable nouns",
      },
      {
        title: "English Grammar in Use",
        author: "Murphy, R.",
        level: "Intermediate (B1-B2)",
        publisher: "Cambridge University Press",
        edition: "5th Edition",
        isbn: "978-1108457651",
        relevance:
          "Practical grammar book with clear explanations and exercises for uncountable nouns",
      },
      {
        title: "Advanced Grammar in Use",
        author: "Hewings, M.",
        level: "Advanced (C1-C2)",
        publisher: "Cambridge University Press",
        edition: "4th Edition",
        isbn: "978-1108274203",
        relevance:
          "Advanced treatment of complex grammatical issues including sophisticated uncountable noun usage",
      },
      {
        title: "Practical English Usage",
        author: "Swan, M.",
        level: "All levels (Reference)",
        publisher: "Oxford University Press",
        edition: "4th Edition",
        isbn: "978-0194202435",
        relevance:
          "Comprehensive reference covering common problems and usage issues with uncountable nouns",
      },
      {
        title: "The Grammar Book: An ESL/EFL Teacher's Course",
        author: "Celce-Murcia, M. & Larsen-Freeman, D.",
        level: "Teacher Reference",
        publisher: "Heinle ELT",
        edition: "3rd Edition",
        isbn: "978-1413017823",
        relevance:
          "Pedagogical approach to teaching uncountable nouns with learning strategies and common errors",
      },
    ],
    online_resources: [
      {
        title: "Cambridge Dictionary Grammar Guide: Uncountable Nouns",
        url: "https://dictionary.cambridge.org/grammar/british-grammar/nouns-countable-and-uncountable",
        institution: "Cambridge University Press",
        description:
          "Comprehensive online guide with interactive exercises and audio examples",
        access_date: "2024-01-15",
      },
      {
        title: "British Council LearnEnglish: Countable and Uncountable Nouns",
        url: "https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/countable-and-uncountable-nouns",
        institution: "British Council",
        description:
          "Interactive lessons and practice activities for different proficiency levels",
        access_date: "2024-01-15",
      },
      {
        title: "Oxford Learner's Dictionaries: Grammar Guide",
        url: "https://www.oxfordlearnersdictionaries.com/grammar/uncountable-nouns",
        institution: "Oxford University Press",
        description:
          "Clear explanations with extensive examples and usage notes",
        access_date: "2024-01-15",
      },
      {
        title: "Grammarly Blog: Count and Mass Nouns",
        url: "https://www.grammarly.com/blog/count-and-mass-nouns/",
        institution: "Grammarly Inc.",
        description:
          "Practical guide with writing tips and common mistake prevention",
        access_date: "2024-01-15",
      },
      {
        title: "BBC Learning English: Countable and Uncountable",
        url: "https://www.bbc.co.uk/learningenglish/english/course/intermediate/unit-7/session-1",
        institution: "BBC",
        description:
          "Video lessons and audio materials for intermediate learners",
        access_date: "2024-01-15",
      },
    ],
    linguistic_journals: [
      {
        title: "The Count-Mass Distinction in Natural Language",
        journal: "Language and Linguistics Compass",
        volume: "12",
        issue: "4",
        year: 2018,
        pages: "e12269",
        doi: "10.1111/lnc3.12269",
      },
      {
        title: "Cross-linguistic Variation in Countability",
        journal: "Studies in Language",
        volume: "41",
        issue: "2",
        year: 2017,
        pages: "275-312",
      },
      {
        title: "Acquisition of Count-Mass Distinction in L2 English",
        journal: "Second Language Research",
        volume: "33",
        issue: "3",
        year: 2017,
        pages: "379-402",
      },
    ],
    dictionaries: [
      {
        title: "Oxford English Dictionary Online",
        publisher: "Oxford University Press",
        edition: "3rd Edition",
        url: "https://www.oed.com/",
        isbn: "N/A",
      },
      {
        title: "Merriam-Webster Dictionary",
        publisher: "Merriam-Webster Inc.",
        edition: "Online Edition",
        url: "https://www.merriam-webster.com/",
      },
      {
        title: "Longman Dictionary of Contemporary English",
        publisher: "Pearson Education",
        edition: "6th Edition",
        isbn: "978-1447954200",
      },
    ],
  },

  levelBasedLearning: {
    A1: {
      learning_objectives: [
        "Recognize common uncountable nouns in daily contexts",
        "Use uncountable nouns with correct singular verb forms",
        "Understand that uncountable nouns don't take 'a/an'",
        "Use basic quantifiers like 'some' with uncountable nouns",
        "Identify uncountable nouns for food, drinks, and materials",
      ],
      essential_vocabulary: [
        "water",
        "bread",
        "milk",
        "rice",
        "money",
        "music",
        "air",
        "sugar",
        "salt",
        "tea",
        "coffee",
        "juice",
        "meat",
        "fish",
        "butter",
        "cheese",
      ],
      key_concepts: [
        "No plural forms (no -s ending)",
        "Always singular verbs (water IS, not water ARE)",
        "Cannot use 'a' or 'an' directly",
        "Use 'some' for positive statements",
        "Basic partitive: a glass of water, a piece of bread",
      ],
      practical_applications: [
        "Ordering food and drinks",
        "Shopping for groceries",
        "Describing basic needs",
        "Simple cooking instructions",
        "Talking about weather",
      ],
      common_contexts: [
        "Restaurant and café conversations",
        "Grocery shopping",
        "Home and kitchen",
        "Basic weather descriptions",
        "Simple daily activities",
      ],
      basic_rules: [
        "Use 'some' in positive sentences: I want some water",
        "Use 'any' in questions and negatives: Do you have any milk?",
        "No articles: Water is important (not 'The water is important')",
        "Singular verbs only: Bread is fresh",
        "Basic partitives: a cup of tea, a bottle of water",
      ],
    },
    A2: {
      learning_objectives: [
        "Use partitive expressions (a piece of, a bit of, a lot of)",
        "Make polite requests using uncountable nouns",
        "Express quantities without counting",
        "Use uncountable nouns in simple descriptions",
        "Understand the difference between countable and uncountable",
      ],
      essential_vocabulary: [
        "advice",
        "homework",
        "furniture",
        "luggage",
        "weather",
        "news",
        "traffic",
        "work",
        "help",
        "time",
        "space",
        "equipment",
      ],
      key_concepts: [
        "Partitive constructions: a piece of advice",
        "Quantifiers: much, little, a lot of",
        "How much vs. How many",
        "Some vs. any usage patterns",
        "Basic abstract concepts",
      ],
      practical_applications: [
        "Asking for and giving advice",
        "Describing home and possessions",
        "Talking about school and work",
        "Travel situations with luggage",
        "Discussing weather and conditions",
      ],
      common_contexts: [
        "School and homework discussions",
        "Home decoration and furniture",
        "Travel and transportation",
        "Weather reports and descriptions",
        "Simple advice-giving situations",
      ],
      basic_rules: [
        "Partitives: a piece of furniture, a bit of advice",
        "Questions: How much money? (not How many money?)",
        "Quantifiers: much traffic, little time, a lot of work",
        "No indefinite articles: I need advice (not 'an advice')",
        "Demonstratives: this information, that equipment",
      ],
    },
    B1: {
      learning_objectives: [
        "Use uncountable nouns in explanations and opinions",
        "Handle abstract concepts with confidence",
        "Use appropriate quantifiers in various contexts",
        "Understand when to use 'the' with uncountable nouns",
        "Express progress, development, and change",
      ],
      essential_vocabulary: [
        "information",
        "knowledge",
        "research",
        "progress",
        "experience",
        "evidence",
        "freedom",
        "independence",
        "responsibility",
        "development",
      ],
      key_concepts: [
        "Abstract uncountable nouns",
        "Generic vs. specific reference with 'the'",
        "Progress and development vocabulary",
        "Information and knowledge concepts",
        "Experience as uncountable vs. countable",
      ],
      practical_applications: [
        "Giving presentations and explanations",
        "Discussing education and learning",
        "Talking about personal development",
        "Academic and work contexts",
        "News and current events",
      ],
      common_contexts: [
        "Educational settings and discussions",
        "Professional development",
        "News and media consumption",
        "Personal growth conversations",
        "Academic writing basics",
      ],
      intermediate_rules: [
        "Generic reference: Knowledge is power",
        "Specific reference: The information you gave me",
        "Zero article with abstract concepts: Freedom is important",
        "Progress expressions: make progress, show improvement",
        "Information patterns: give information, provide evidence",
      ],
    },
    B2: {
      learning_objectives: [
        "Use uncountable nouns in academic and professional writing",
        "Handle technical and specialized vocabulary",
        "Understand register differences in usage",
        "Use complex quantification patterns",
        "Navigate countable/uncountable variations",
      ],
      essential_vocabulary: [
        "terminology",
        "methodology",
        "analysis",
        "synthesis",
        "criteria",
        "phenomena",
        "data",
        "software",
        "hardware",
        "infrastructure",
      ],
      key_concepts: [
        "Academic and technical uncountables",
        "Register-appropriate usage",
        "Complex quantification",
        "Formal vs. informal contexts",
        "Disciplinary-specific vocabulary",
      ],
      practical_applications: [
        "Academic essay writing",
        "Professional presentations",
        "Technical documentation",
        "Research reports",
        "Business communication",
      ],
      common_contexts: [
        "University and academic settings",
        "Professional workplace",
        "Technical and scientific contexts",
        "Business and corporate environments",
        "Research and development",
      ],
      advanced_rules: [
        "Academic register: Research indicates...",
        "Technical contexts: Software requires...",
        "Formal quantification: a substantial amount of data",
        "Professional discourse: valuable expertise",
        "Scientific writing: evidence suggests...",
      ],
    },
    C1: {
      learning_objectives: [
        "Master sophisticated academic discourse",
        "Use uncountable nouns in formal presentations",
        "Handle nuanced semantic distinctions",
        "Employ stylistic variations appropriately",
        "Understand etymological and cultural aspects",
      ],
      essential_vocabulary: [
        "discourse",
        "rhetoric",
        "semantics",
        "pragmatics",
        "ideology",
        "consciousness",
        "aesthetics",
        "jurisprudence",
        "epistemology",
      ],
      key_concepts: [
        "Sophisticated academic vocabulary",
        "Stylistic and register variation",
        "Nuanced semantic differences",
        "Cultural and contextual appropriateness",
        "Interdisciplinary terminology",
      ],
      practical_applications: [
        "Academic conference presentations",
        "Research publication writing",
        "Professional consultation",
        "Policy document creation",
        "Cross-cultural communication",
      ],
      common_contexts: [
        "Academic conferences and symposiums",
        "Professional consultation",
        "Policy and governmental discourse",
        "International business",
        "Cultural and artistic discussions",
      ],
      sophisticated_rules: [
        "Formal academic discourse patterns",
        "Disciplinary-specific conventions",
        "Cultural sensitivity in usage",
        "Stylistic appropriateness",
        "Historical and etymological awareness",
      ],
    },
    C2: {
      learning_objectives: [
        "Achieve native-like mastery of all uncountable nouns",
        "Use rare and highly specialized vocabulary",
        "Employ creative and literary applications",
        "Understand all dialectal and register variations",
        "Master idiomatic and metaphorical uses",
      ],
      essential_vocabulary: [
        "verisimilitude",
        "quintessence",
        "ephemera",
        "minutiae",
        "paraphernalia",
        "iconography",
        "lexicography",
        "historiography",
        "phenomenology",
      ],
      key_concepts: [
        "Rare and archaic uncountable nouns",
        "Literary and creative applications",
        "Dialectal and historical variations",
        "Metaphorical and figurative uses",
        "Complete mastery of all exceptions",
      ],
      practical_applications: [
        "Literary and creative writing",
        "Academic research and publication",
        "Professional expertise demonstration",
        "Cultural and artistic criticism",
        "Historical and philosophical discourse",
      ],
      common_contexts: [
        "Literary and artistic creation",
        "High-level academic research",
        "Cultural criticism and analysis",
        "Professional expertise fields",
        "Historical and philosophical inquiry",
      ],
      mastery_rules: [
        "Complete intuitive understanding",
        "Creative and innovative usage",
        "Historical and dialectal awareness",
        "Literary and metaphorical applications",
        "Native-like intuition for all contexts",
      ],
    },
  },

  semanticCategories: {
    substances_materials: {
      definition:
        "Physical matter that exists as continuous mass without distinct individual boundaries",
      subcategories: {
        liquids: {
          description:
            "Fluid substances that flow and take the shape of their container",
          examples: [
            "water",
            "milk",
            "juice",
            "oil",
            "wine",
            "beer",
            "soup",
            "sauce",
          ],
          level: "A1-A2",
        },
        solids: {
          description:
            "Solid materials that exist as mass rather than discrete objects",
          examples: [
            "bread",
            "rice",
            "sugar",
            "salt",
            "flour",
            "sand",
            "mud",
            "clay",
          ],
          level: "A1-A2",
        },
        gases: {
          description: "Gaseous substances that fill space uniformly",
          examples: ["air", "oxygen", "hydrogen", "smoke", "steam", "fog"],
          level: "A2-B1",
        },
        metals_minerals: {
          description:
            "Metallic and mineral substances considered as materials",
          examples: [
            "gold",
            "silver",
            "iron",
            "copper",
            "steel",
            "aluminum",
            "concrete",
          ],
          level: "B1-B2",
        },
        organic_materials: {
          description: "Natural materials from living organisms",
          examples: ["wood", "cotton", "wool", "leather", "silk", "rubber"],
          level: "A2-B1",
        },
        synthetic_materials: {
          description: "Artificially created materials and substances",
          examples: [
            "plastic",
            "nylon",
            "polyester",
            "fiberglass",
            "carbon fiber",
          ],
          level: "B1-B2",
        },
      },
    },
    abstract_concepts: {
      definition:
        "Intangible ideas, qualities, states, and mental constructs that cannot be physically counted",
      subcategories: {
        emotions_feelings: {
          description: "Psychological states and emotional experiences",
          examples: [
            "happiness",
            "sadness",
            "anger",
            "love",
            "fear",
            "joy",
            "excitement",
            "anxiety",
          ],
          level: "A1-B1",
        },
        intellectual_concepts: {
          description: "Mental processes and cognitive abilities",
          examples: [
            "knowledge",
            "wisdom",
            "intelligence",
            "understanding",
            "awareness",
            "consciousness",
          ],
          level: "B1-C1",
        },
        moral_ethical: {
          description: "Values, principles, and ethical concepts",
          examples: [
            "honesty",
            "integrity",
            "justice",
            "freedom",
            "responsibility",
            "loyalty",
          ],
          level: "B2-C1",
        },
        social_concepts: {
          description: "Societal and interpersonal abstractions",
          examples: [
            "culture",
            "society",
            "community",
            "relationship",
            "friendship",
            "leadership",
          ],
          level: "B1-C1",
        },
        philosophical: {
          description: "Deep philosophical and metaphysical concepts",
          examples: [
            "existence",
            "reality",
            "truth",
            "beauty",
            "consciousness",
            "being",
          ],
          level: "C1-C2",
        },
      },
    },
    collective_mass: {
      definition:
        "Groups or collections of items viewed as unified wholes rather than individual components",
      subcategories: {
        household_items: {
          description:
            "Collections of domestic objects treated as mass categories",
          examples: [
            "furniture",
            "luggage",
            "baggage",
            "cutlery",
            "crockery",
            "jewelry",
          ],
          level: "A2-B1",
        },
        equipment_machinery: {
          description:
            "Collections of tools, devices, and mechanical apparatus",
          examples: [
            "equipment",
            "machinery",
            "apparatus",
            "gear",
            "hardware",
            "software",
          ],
          level: "B1-B2",
        },
        clothing_textiles: {
          description: "Garments and fabric items as collective categories",
          examples: ["clothing", "underwear", "footwear", "bedding", "linen"],
          level: "A2-B1",
        },
        vegetation: {
          description: "Plant life and botanical masses",
          examples: [
            "vegetation",
            "foliage",
            "greenery",
            "undergrowth",
            "shrubbery",
          ],
          level: "B2-C1",
        },
        information_data: {
          description: "Collective information and data sets",
          examples: [
            "information",
            "data",
            "evidence",
            "documentation",
            "paperwork",
          ],
          level: "B1-C1",
        },
      },
    },
    activities_processes: {
      definition:
        "Ongoing actions, processes, and activities viewed as continuous rather than discrete events",
      subcategories: {
        work_labor: {
          description: "Employment, tasks, and productive activities",
          examples: [
            "work",
            "labor",
            "employment",
            "business",
            "commerce",
            "trade",
          ],
          level: "A2-B2",
        },
        education_learning: {
          description: "Educational processes and learning activities",
          examples: [
            "education",
            "training",
            "learning",
            "teaching",
            "studying",
            "homework",
          ],
          level: "A1-B2",
        },
        research_investigation: {
          description: "Investigative and analytical processes",
          examples: [
            "research",
            "investigation",
            "analysis",
            "exploration",
            "experimentation",
          ],
          level: "B2-C2",
        },
        communication: {
          description: "Communicative processes and interactions",
          examples: [
            "communication",
            "conversation",
            "dialogue",
            "correspondence",
            "networking",
          ],
          level: "B1-C1",
        },
        recreation_entertainment: {
          description: "Leisure activities and entertainment",
          examples: [
            "recreation",
            "entertainment",
            "fun",
            "relaxation",
            "leisure",
          ],
          level: "A2-B1",
        },
      },
    },
    fields_disciplines: {
      definition:
        "Academic subjects, professional fields, and areas of specialized knowledge",
      subcategories: {
        sciences: {
          description: "Scientific disciplines and branches of natural science",
          examples: [
            "physics",
            "chemistry",
            "biology",
            "mathematics",
            "astronomy",
            "geology",
          ],
          level: "B1-C1",
        },
        humanities: {
          description: "Humanistic studies and cultural disciplines",
          examples: [
            "literature",
            "history",
            "philosophy",
            "linguistics",
            "archaeology",
          ],
          level: "B2-C2",
        },
        social_sciences: {
          description: "Studies of human society and behavior",
          examples: [
            "psychology",
            "sociology",
            "anthropology",
            "economics",
            "politics",
          ],
          level: "B2-C1",
        },
        arts: {
          description: "Creative and aesthetic disciplines",
          examples: ["art", "music", "poetry", "drama", "dance", "sculpture"],
          level: "A1-C1",
        },
        applied_fields: {
          description: "Professional and technical applications",
          examples: [
            "engineering",
            "medicine",
            "law",
            "architecture",
            "technology",
          ],
          level: "B2-C1",
        },
      },
    },
  },
  uncountable_nouns_vocabs: {
    // A1 Level - Basic Daily Life
    "Food & Drink (A1)": [
      "water",
      "milk",
      "juice",
      "tea",
      "coffee",
      "sugar",
      "salt",
      "flour",
      "butter",
      "cheese",
      "bread",
      "rice",
      "meat",
      "fish",
      "fruit",
      "vegetables",
      "soup",
      "cake",
    ],

    "Basic Materials (A1)": [
      "wood",
      "metal",
      "plastic",
      "glass",
      "paper",
      "ice",
      "sand",
      "mud",
      "air",
      "fire",
    ],

    "Money & Basic Concepts (A1)": [
      "money",
      "time",
      "music",
      "work",
      "help",
      "love",
      "fun",
    ],

    // A2 Level - Expanding Contexts
    "Household & Travel (A2)": [
      "furniture",
      "luggage",
      "baggage",
      "equipment",
      "clothing",
      "jewelry",
      "mail",
      "garbage",
      "rubbish",
      "laundry",
      "homework",
    ],

    "Weather & Environment (A2)": [
      "weather",
      "rain",
      "snow",
      "ice",
      "fog",
      "sunshine",
      "wind",
      "thunder",
      "lightning",
      "pollution",
      "climate",
    ],

    "Health & Feelings (A2)": [
      "health",
      "pain",
      "stress",
      "happiness",
      "sadness",
      "anger",
      "fear",
      "joy",
      "advice",
      "news",
      "traffic",
    ],

    // B1 Level - Abstract and Academic Introduction
    "Information & Knowledge (B1)": [
      "information",
      "knowledge",
      "research",
      "education",
      "progress",
      "experience",
      "evidence",
      "data",
      "communication",
      "technology",
    ],

    "Professional & Business (B1)": [
      "business",
      "marketing",
      "advertising",
      "management",
      "leadership",
      "teamwork",
      "development",
      "training",
      "employment",
      "unemployment",
    ],

    "Social & Cultural (B1)": [
      "culture",
      "society",
      "freedom",
      "justice",
      "democracy",
      "equality",
      "diversity",
      "tradition",
      "heritage",
      "identity",
    ],

    // B2 Level - Academic and Technical
    "Academic Subjects (B2)": [
      "mathematics",
      "physics",
      "chemistry",
      "biology",
      "history",
      "economics",
      "politics",
      "psychology",
      "sociology",
      "philosophy",
      "linguistics",
      "literature",
      "geography",
    ],

    "Technology & Science (B2)": [
      "software",
      "hardware",
      "machinery",
      "engineering",
      "robotics",
      "genetics",
      "nanotechnology",
      "biotechnology",
      "telecommunications",
      "cybersecurity",
    ],

    "Advanced Materials & Energy (B2)": [
      "electricity",
      "energy",
      "petroleum",
      "aluminum",
      "titanium",
      "uranium",
      "renewable energy",
      "nuclear power",
      "solar power",
      "hydropower",
    ],

    "Finance & Economics (B2)": [
      "wealth",
      "poverty",
      "revenue",
      "expenditure",
      "taxation",
      "inflation",
      "investment",
      "capital",
      "debt",
      "credit",
      "insurance",
      "accounting",
    ],

    // C1 Level - Sophisticated Academic
    "Advanced Academic Disciplines (C1)": [
      "anthropology",
      "archaeology",
      "criminology",
      "jurisprudence",
      "theology",
      "epistemology",
      "ontology",
      "phenomenology",
      "hermeneutics",
      "dialectics",
    ],

    "Arts & Humanities (C1)": [
      "aesthetics",
      "rhetoric",
      "discourse",
      "narrative",
      "imagery",
      "symbolism",
      "allegory",
      "metaphor",
      "irony",
      "satire",
      "pastiche",
      "parody",
    ],

    "Professional Expertise (C1)": [
      "expertise",
      "proficiency",
      "competence",
      "methodology",
      "analysis",
      "synthesis",
      "evaluation",
      "assessment",
      "validation",
      "verification",
      "optimization",
    ],

    "Social Sciences Advanced (C1)": [
      "bureaucracy",
      "governance",
      "legislation",
      "jurisprudence",
      "diplomacy",
      "geopolitics",
      "demographics",
      "ethnography",
      "historiography",
    ],

    // C2 Level - Rare and Specialized
    "Highly Specialized Academic (C2)": [
      "lexicography",
      "phonetics",
      "morphology",
      "syntax",
      "semantics",
      "pragmatics",
      "sociolinguistics",
      "psycholinguistics",
      "neurolinguistics",
      "computational linguistics",
    ],

    "Philosophy & Metaphysics (C2)": [
      "consciousness",
      "existence",
      "being",
      "nothingness",
      "transcendence",
      "immanence",
      "verisimilitude",
      "quintessence",
      "zeitgeist",
      "weltanschauung",
    ],

    "Literary & Artistic (C2)": [
      "iconography",
      "calligraphy",
      "typography",
      "prosody",
      "scansion",
      "versification",
      "poetics",
      "dramaturgy",
      "cinematography",
      "choreography",
    ],

    "Rare & Archaic (C2)": [
      "ephemera",
      "minutiae",
      "paraphernalia",
      "regalia",
      "memorabilia",
      "trivia",
      "marginalia",
      "minutiae",
      "detritus",
      "flotsam",
      "jetsam",
    ],

    "Scientific & Technical Advanced (C2)": [
      "nanotechnology",
      "biotechnology",
      "pharmacology",
      "toxicology",
      "epidemiology",
      "crystallography",
      "spectroscopy",
      "chromatography",
      "electromagnetism",
    ],
  },
  cefrLevels: {
    A1: "Recognize and use basic uncountable nouns for daily survival needs: water, bread, milk, money, music, time. Understand they don't take 'a/an' and use singular verbs. Use 'some' in positive statements and 'any' in questions/negatives. Master essential food, drink, and material vocabulary for shopping and basic communication.",

    A2: "Expand to abstract concepts and partitive expressions: advice, homework, furniture, weather, traffic. Use quantifiers (much, little, a lot of) and partitive constructions (a piece of advice, a bit of help). Handle uncountable nouns in travel contexts (luggage), school settings (homework), and home descriptions (furniture). Distinguish clearly between countable and uncountable usage.",

    B1: "Navigate complex abstract concepts and academic introduction: information, knowledge, research, progress, experience, evidence. Use uncountable nouns in explanations, opinions, and discussions about education, work, and social issues. Understand generic vs. specific reference with articles. Express development, change, and personal growth using appropriate uncountable vocabulary.",

    B2: "Master academic, professional, and technical contexts: methodology, analysis, data, software, infrastructure, expertise. Use uncountable nouns appropriately in formal writing, presentations, and professional communication. Handle discipline-specific vocabulary in science, business, and technology. Demonstrate register awareness and stylistic appropriateness in formal contexts.",

    C1: "Achieve sophisticated academic discourse and cultural fluency: rhetoric, discourse, ideology, consciousness, jurisprudence, epistemology. Use uncountable nouns in conference presentations, research publications, and policy documents. Navigate nuanced semantic distinctions and employ culturally appropriate usage. Master interdisciplinary terminology and formal academic conventions.",

    C2: "Demonstrate native-like mastery including rare, archaic, and highly specialized vocabulary: lexicography, phenomenology, verisimilitude, iconography, paraphernalia. Use uncountable nouns creatively in literary and artistic contexts. Understand all dialectal variations, historical usage, and metaphorical applications. Employ intuitive understanding equivalent to educated native speakers.",
  },
  forms: {
    basic:
      "S + uncountable noun + singular verb • e.g., The information is useful.",
    with_article:
      "S + a piece of/some + uncountable noun • e.g., I need a piece of advice.",
    with_quantifier:
      "S + much/little/a lot of + uncountable noun • e.g., There is much traffic.",
    with_no_article:
      "S + uncountable noun (no article) • e.g., Music helps me relax.",
    partitive:
      "S + a glass of/slice of/loaf of + uncountable noun • e.g., a glass of water, a loaf of bread",
  },
  usage: [
    {
      type: "Substances and materials",
      description:
        "Nouns that refer to substances or materials that cannot be counted individually.",
      examples: [
        "water",
        "bread",
        "rice",
        "sand",
        "air",
        "gold",
        "milk",
        "sugar",
        "salt",
      ],
      level: "A1-A2",
    },
    {
      type: "Abstract concepts",
      description:
        "Nouns that refer to ideas, qualities, or states that are not concrete objects.",
      examples: [
        "happiness",
        "advice",
        "progress",
        "knowledge",
        "love",
        "anger",
        "information",
        "research",
        "evidence",
      ],
      level: "A2-B1",
    },
    {
      type: "Collective/General categories",
      description:
        "Nouns that refer to a category or group as a whole, not individual items.",
      examples: [
        "furniture",
        "luggage",
        "equipment",
        "machinery",
        "clothing",
        "software",
        "hardware",
        "literature",
        "poetry",
      ],
      level: "B1-B2",
    },
    {
      type: "Academic/Professional/Technical",
      description:
        "Nouns used in academic, scientific, or professional contexts.",
      examples: [
        "research",
        "evidence",
        "terminology",
        "criteria",
        "data",
        "content",
        "progress",
      ],
      level: "B2-C2",
    },
    {
      type: "News and media",
      description:
        "Nouns that refer to information or communication as a whole.",
      examples: ["news", "media", "information", "content"],
      level: "B1-C1",
    },
  ],
  examples: {
    basic: {
      direct: "I need information.",
      correct: "I need some information.",
      incorrect: "I need informations.",
      context: "Requesting help (A1)",
    },
    with_article: {
      direct: "Can you give me advice?",
      correct: "Can you give me a piece of advice?",
      incorrect: "Can you give me an advice?",
      context: "Seeking suggestions (A2)",
    },
    with_quantifier: {
      direct: "There is much traffic today.",
      correct: "There is a lot of traffic today.",
      incorrect: "There are many traffics today.",
      context: "Describing conditions (B1)",
    },
    partitive: {
      direct: "I want bread.",
      correct: "I want a slice of bread.",
      incorrect: "I want a bread.",
      context: "Ordering food (A1)",
    },
    academic: {
      direct: "The research shows new results.",
      correct: "Research shows new results.",
      incorrect: "The researches show new results.",
      context: "Academic writing (B2)",
    },
    idiomatic: {
      direct: "The news is good.",
      correct: "This is good news.",
      incorrect: "These are good news.",
      context: "Reacting to information (B1)",
    },
  },
  practiceTypes: {
    A1: [
      "Identify uncountable nouns in simple sentences",
      "Choose correct verb agreement with uncountable nouns",
      "Match nouns to pictures (e.g., bread, water, music)",
      "Fill in the blank with an uncountable noun",
    ],
    A2: [
      "Use a piece of/some with uncountable nouns",
      "Distinguish between countable and uncountable nouns",
      "Correct sentences with article errors",
      "Simple gap-filling with uncountable nouns",
    ],
    B1: [
      "Use quantifiers (much/little/a lot of) with uncountable nouns",
      "Rewrite incorrect plural forms to correct uncountable forms",
      "Use uncountable nouns in short paragraphs",
      "Identify abstract uncountable nouns in context",
    ],
    B2: [
      "Use uncountable nouns in academic and professional writing",
      "Paraphrase sentences to use uncountable nouns idiomatically",
      "Correct advanced errors with uncountable nouns",
      "Explain the meaning of abstract uncountable nouns",
    ],
    C1: [
      "Use uncountable nouns in formal and academic registers",
      "Analyze idiomatic and metaphorical uses of uncountable nouns",
      "Identify subtle errors in advanced writing",
      "Produce essays using a range of uncountable nouns",
    ],
    C2: [
      "Master rare and highly abstract uncountable nouns",
      "Critique and edit advanced texts for uncountable noun accuracy",
      "Use uncountable nouns in creative and literary writing",
      "Demonstrate register flexibility with uncountable nouns",
    ],
  },
  commonMistakes: {
    beginners: [
      "Adding -s to uncountable nouns: ❌ informations ✅ information",
      "Using 'a/an' with uncountable nouns: ❌ an advice ✅ a piece of advice",
      "Plural verb agreement: ❌ The news are good ✅ The news is good",
      "Using 'many' with uncountable nouns: ❌ many furniture ✅ much furniture",
    ],
    intermediate: [
      "Confusing countable and uncountable nouns: ❌ a bread ✅ a loaf of bread",
      "Incorrect quantifiers: ❌ few equipment ✅ little equipment",
      "Wrong article: ❌ a research ✅ research",
      "Using 'these/those' with uncountable nouns: ❌ these information ✅ this information",
    ],
    advanced: [
      "Overusing 'the' with abstract nouns: ❌ the happiness is important ✅ happiness is important",
      "Incorrect idiomatic use: ❌ a good news ✅ good news",
      "Mixing countable and uncountable forms: ❌ advices ✅ advice",
      "Using plural forms in academic writing: ❌ researches show ✅ research shows",
    ],
  },
  recognition: [
    "Uncountable nouns never take -s for plural",
    "They always use singular verb agreement",
    "Often refer to substances, materials, abstract ideas, or collective categories",
    "Require quantifiers or partitive expressions for measurement (e.g., a piece of, a bit of, some)",
    "Cannot be used with 'many', 'few', 'these', 'those'",
    "Often used without an article, or with 'the' for specificity",
  ],
  timeMarkers: [
    "now",
    "today",
    "yesterday",
    "tomorrow",
    "this week",
    "last year",
    "at the moment",
    "recently",
    "soon",
  ],
  pronounChanges: {
    basic: {
      it: "It is important.",
      this: "This is useful information.",
      that: "That is good advice.",
    },
    advanced: {
      what: "What I need is evidence.",
      all: "All that matters is progress.",
    },
  },
  reportingVerbs: [
    "have",
    "need",
    "give",
    "receive",
    "show",
    "find",
    "provide",
    "offer",
    "bring",
    "contain",
    "include",
    "require",
    "lack",
    "represent",
    "express",
  ],
  exercises: {
    recognition: {
      description: "Identify uncountable nouns in context",
      difficulty: "A1-B1",
      examples: [
        "Find the uncountable noun: I need some information.",
        "Choose the correct form: There is much (traffic/traffics).",
      ],
    },
    correction: {
      description: "Correct common mistakes with uncountable nouns",
      difficulty: "A2-B2",
      examples: [
        "❌ I have many luggages. ✅ I have a lot of luggage.",
        "❌ These are good advices. ✅ This is good advice.",
      ],
    },
    production: {
      description: "Use uncountable nouns in your own sentences",
      difficulty: "B1-C2",
      examples: [
        "Write a paragraph about your homework using uncountable nouns.",
        "Describe a problem and use 'information', 'advice', and 'progress' correctly.",
      ],
    },
  },
  notes: [
    "Uncountable nouns are often mass nouns, but not all mass nouns are uncountable in every context.",
    "Some nouns can be both countable and uncountable with different meanings (e.g., 'paper' as material vs. 'a paper' as an article).",
    "Use partitive structures (a piece of, a bit of, an item of) to measure uncountable nouns.",
    "In academic writing, avoid using plural forms for research, evidence, advice, etc.",
    "Some uncountable nouns are used idiomatically (e.g., 'good news', 'bad weather').",
    "Be careful with false friends in other languages that may be countable.",
    "Uncountable nouns are common in both spoken and written English, especially in academic and professional contexts.",
  ],
  culturalContexts: {
    daily_life: {
      description: "Common in daily requests, shopping, and conversation",
      examples: [
        "Can I have some bread?",
        "I need information.",
        "The weather is nice today.",
      ],
    },
    academic: {
      description: "Essential in academic and professional writing",
      examples: ["Research shows...", "There is evidence that..."],
    },
    idiomatic: {
      description: "Used in idiomatic expressions and news/media",
      examples: ["That's good news!", "Bad weather delayed the flight."],
    },
  },
  specialCases: {
    idiomatic: {
      description: "Fixed expressions and idioms with uncountable nouns",
      examples: [
        "a piece of cake",
        "bread and butter",
        "make progress",
        "give advice",
        "do homework",
        "make an effort",
      ],
    },
    academic: {
      description: "Academic and technical terms that are always uncountable",
      examples: [
        "evidence",
        "research",
        "literature",
        "terminology",
        "machinery",
      ],
    },
    false_friends: {
      description:
        "Words that are countable in other languages but uncountable in English",
      examples: ["advice", "information", "furniture", "luggage", "news"],
    },
    dual_use: {
      description:
        "Nouns that can be both countable and uncountable with different meanings",
      examples: [
        {
          word: "paper",
          countable: "a paper (an article)",
          uncountable: "paper (material)",
        },
        {
          word: "chicken",
          countable: "a chicken (an animal)",
          uncountable: "chicken (meat)",
        },
        {
          word: "glass",
          countable: "a glass (a cup)",
          uncountable: "glass (material)",
        },
        {
          word: "experience",
          countable: "an experience (an event)",
          uncountable: "experience (knowledge)",
        },
      ],
    },
  },
  etymology: {
    origin:
      "Many uncountable nouns derive from Old English, Latin, or French, often reflecting abstract or mass concepts.",
    development:
      "The distinction between countable and uncountable nouns developed over centuries as English absorbed vocabulary from other languages.",
    modernUsage:
      "Uncountable nouns are now common in both spoken and written English, especially in academic and professional contexts.",
  },
  crossLinguistic: {
    similarities:
      "Many languages have uncountable or mass nouns, but the specific list and usage rules vary.",
    differences:
      "Some nouns that are uncountable in English are countable in other languages (e.g., 'advice' in French: 'un conseil').",
    learnerChallenges:
      "Learners often overgeneralize plural forms or use incorrect articles due to interference from their native language.",
  },
  vocabulary: {
    A1: [
      "bread",
      "water",
      "music",
      "air",
      "rice",
      "milk",
      "sand",
      "sugar",
      "salt",
      "money",
    ],
    A2: [
      "advice",
      "homework",
      "furniture",
      "luggage",
      "traffic",
      "weather",
      "news",
      "progress",
      "equipment",
    ],
    B1: [
      "information",
      "knowledge",
      "research",
      "evidence",
      "machinery",
      "clothing",
      "literature",
      "media",
    ],
    B2: [
      "terminology",
      "poetry",
      "scenery",
      "software",
      "hardware",
      "data",
      "content",
      "work",
    ],
    C1: [
      "criteria",
      "evidence",
      "machinery",
      "literature",
      "poetry",
      "terminology",
      "progress",
    ],
    C2: [
      "iconography",
      "imagery",
      "syntax",
      "semantics",
      "lexicon",
      "paraphernalia",
      "foliage",
      "prose",
    ],
  },
  grammaticalPatterns: {
    article_usage: {
      correct: ["some information", "a piece of advice", "the furniture"],
      incorrect: ["an information", "an advice", "the advices"],
    },
    verb_agreement: {
      correct: ["The news is good.", "The equipment works well."],
      incorrect: ["The news are good.", "The equipment work well."],
    },
    quantifiers: {
      correct: ["much information", "little progress", "a lot of bread"],
      incorrect: ["many informations", "few progresses", "many breads"],
    },
  },
  usageContexts: {
    A1: ["shopping", "food and drink", "music", "weather", "basic needs"],
    A2: [
      "schoolwork",
      "giving/receiving advice",
      "home and furniture",
      "travel (luggage)",
    ],
    B1: [
      "news and media",
      "traffic reports",
      "progress updates",
      "information requests",
    ],
    B2: [
      "academic writing",
      "technical descriptions",
      "professional communication",
    ],
    C1: [
      "formal essays",
      "research papers",
      "literary analysis",
      "advanced presentations",
    ],
    C2: [
      "creative writing",
      "critical reviews",
      "specialized academic discourse",
    ],
  },
  errorPatterns: {
    A1: ["❌ musics ✅ music", "❌ a bread ✅ bread", "❌ a water ✅ water"],
    A2: ["❌ an advice ✅ a piece of advice", "❌ homeworks ✅ homework"],
    B1: ["❌ informations ✅ information", "❌ traffics ✅ traffic"],
    B2: ["❌ researches ✅ research", "❌ softwares ✅ software"],
    C1: ["❌ evidences ✅ evidence", "❌ terminologies ✅ terminology"],
    C2: ["❌ iconographies ✅ iconography", "❌ foliages ✅ foliage"],
  },
  learningStrategies: {
    A1: [
      "Memorize common uncountable nouns with pictures and examples.",
      "Practice using correct verb agreement.",
      "Listen for uncountable nouns in simple conversations.",
    ],
    A2: [
      "Use partitive structures (a piece of, some) in speaking and writing.",
      "Compare countable and uncountable nouns in context.",
      "Correct common mistakes in exercises.",
    ],
    B1: [
      "Practice using quantifiers (much, little, a lot of) with uncountable nouns.",
      "Write short texts using a variety of uncountable nouns.",
      "Edit sentences for correct uncountable noun usage.",
    ],
    B2: [
      "Use uncountable nouns in academic and technical writing.",
      "Paraphrase sentences to use uncountable nouns idiomatically.",
      "Analyze authentic texts for advanced usage.",
    ],
    C1: [
      "Produce essays and presentations using advanced uncountable nouns.",
      "Identify and correct subtle errors in peer writing.",
      "Experiment with idiomatic and metaphorical uses.",
    ],
    C2: [
      "Master rare and highly abstract uncountable nouns.",
      "Critique and edit advanced texts for accuracy.",
      "Use uncountable nouns creatively in literary and academic contexts.",
    ],
  },

  advancedConcepts: {
    countable_uncountable_pairs: [
      {
        word: "paper",
        countable_meaning: "A newspaper, academic article, or document",
        uncountable_meaning: "Material made from wood pulp for writing",
        examples: {
          countable: [
            "I read three papers this morning",
            "She wrote a paper on linguistics",
          ],
          uncountable: [
            "I need some paper to write on",
            "Paper is made from trees",
          ],
        },
        level: "B1-B2",
      },
      {
        word: "experience",
        countable_meaning: "A particular event or situation that happened",
        uncountable_meaning: "Knowledge or skill gained over time",
        examples: {
          countable: [
            "That was an amazing experience",
            "He had many experiences abroad",
          ],
          uncountable: [
            "She has a lot of experience in teaching",
            "Experience is the best teacher",
          ],
        },
        level: "B1-B2",
      },
      {
        word: "glass",
        countable_meaning: "A drinking vessel or eyewear",
        uncountable_meaning: "The transparent material",
        examples: {
          countable: ["Please bring me a glass", "He wears glasses"],
          uncountable: ["The window is made of glass", "Glass is fragile"],
        },
        level: "A2-B1",
      },
      {
        word: "chicken",
        countable_meaning: "The live bird",
        uncountable_meaning: "The meat as food",
        examples: {
          countable: [
            "There are three chickens in the yard",
            "A chicken crossed the road",
          ],
          uncountable: [
            "I like chicken for dinner",
            "Chicken is a good source of protein",
          ],
        },
        level: "A2-B1",
      },
      {
        word: "light",
        countable_meaning: "A source of illumination or lamp",
        uncountable_meaning:
          "Electromagnetic radiation that makes vision possible",
        examples: {
          countable: [
            "Turn on the lights",
            "There are three lights in this room",
          ],
          uncountable: [
            "Light travels at 299,792,458 meters per second",
            "Plants need light to grow",
          ],
        },
        level: "B1-B2",
      },
      {
        word: "work",
        countable_meaning: "A piece of art, literature, or creative output",
        uncountable_meaning: "Activity involving mental or physical effort",
        examples: {
          countable: [
            "Shakespeare's works are famous",
            "This is one of his best works",
          ],
          uncountable: [
            "I have a lot of work to do",
            "Work is important for personal fulfillment",
          ],
        },
        level: "A2-B2",
      },
    ],
    register_variation: {
      formal: [
        "research",
        "evidence",
        "legislation",
        "documentation",
        "correspondence",
        "consultation",
      ],
      informal: ["stuff", "food", "music", "fun", "help", "work"],
      academic: [
        "literature",
        "methodology",
        "analysis",
        "discourse",
        "terminology",
        "phenomena",
      ],
      technical: [
        "software",
        "hardware",
        "data",
        "infrastructure",
        "bandwidth",
        "connectivity",
      ],
    },
    collocations: [
      {
        noun: "advice",
        common_collocations: [
          "give advice",
          "take advice",
          "seek advice",
          "follow advice",
          "sound advice",
          "practical advice",
        ],
        level: "A2-B1",
      },
      {
        noun: "information",
        common_collocations: [
          "provide information",
          "gather information",
          "reliable information",
          "confidential information",
          "detailed information",
        ],
        level: "A2-B2",
      },
      {
        noun: "research",
        common_collocations: [
          "conduct research",
          "carry out research",
          "extensive research",
          "groundbreaking research",
          "empirical research",
        ],
        level: "B2-C1",
      },
      {
        noun: "progress",
        common_collocations: [
          "make progress",
          "show progress",
          "steady progress",
          "significant progress",
          "monitor progress",
        ],
        level: "B1-B2",
      },
      {
        noun: "knowledge",
        common_collocations: [
          "acquire knowledge",
          "share knowledge",
          "extensive knowledge",
          "in-depth knowledge",
          "prior knowledge",
        ],
        level: "B1-C1",
      },
    ],
    idiomatic_expressions: [
      {
        expression: "a piece of cake",
        meaning: "something very easy to do",
        example: "The exam was a piece of cake",
        level: "B1",
      },
      {
        expression: "break the ice",
        meaning: "to make people feel more comfortable in a social situation",
        example: "He told a joke to break the ice",
        level: "B2",
      },
      {
        expression: "spill the beans",
        meaning: "to reveal a secret",
        example: "Don't spill the beans about the surprise party",
        level: "B2",
      },
      {
        expression: "food for thought",
        meaning: "something worth thinking about",
        example: "Your presentation gave us a lot of food for thought",
        level: "C1",
      },
      {
        expression: "music to my ears",
        meaning: "very pleasant news",
        example: "When she said yes, it was music to my ears",
        level: "B2",
      },
    ],
  },

  pedagogicalSequencing: {
    teaching_order: [
      "Basic concrete substances (water, bread, milk) - A1",
      "Common daily uncountables (money, music, weather) - A1-A2",
      "Abstract concepts (advice, homework, information) - A2-B1",
      "Academic and professional terms (research, evidence, progress) - B1-B2",
      "Sophisticated and specialized vocabulary (terminology, phenomena, discourse) - B2-C1",
      "Rare and highly academic terms (iconography, epistemology, jurisprudence) - C1-C2",
    ],
    prerequisite_knowledge: [
      "Understanding of singular/plural distinction in countable nouns",
      "Basic knowledge of articles (a, an, the)",
      "Familiarity with quantifiers (some, any, much, many)",
      "Understanding of verb agreement with singular subjects",
      "Basic vocabulary for everyday concrete objects",
    ],
    assessment_criteria: {
      A1: [
        "Can identify common uncountable nouns in simple contexts",
        "Uses correct singular verb forms with uncountable nouns",
        "Avoids using 'a/an' with basic uncountable nouns",
        "Can use 'some' appropriately with uncountable nouns",
      ],
      A2: [
        "Uses partitive expressions correctly (a piece of, a bit of)",
        "Distinguishes between countable and uncountable nouns",
        "Uses basic quantifiers appropriately (much, little, a lot of)",
        "Can make simple requests using uncountable nouns",
      ],
      B1: [
        "Uses abstract uncountable nouns in explanations and opinions",
        "Applies correct article usage with uncountable nouns",
        "Uses uncountable nouns in academic contexts appropriately",
        "Can express quantities and measurements accurately",
      ],
      B2: [
        "Uses technical and professional uncountable nouns correctly",
        "Demonstrates register awareness in formal contexts",
        "Handles complex quantification patterns",
        "Can navigate countable/uncountable variations effectively",
      ],
      C1: [
        "Uses sophisticated academic vocabulary appropriately",
        "Demonstrates cultural and contextual sensitivity",
        "Employs stylistic variations in formal discourse",
        "Can handle nuanced semantic distinctions",
      ],
      C2: [
        "Shows native-like intuition for all uncountable nouns",
        "Uses rare and specialized vocabulary accurately",
        "Employs creative and literary applications",
        "Demonstrates complete mastery of all exceptions and variations",
      ],
    },
  },
};
