export const RelativeClausesData = {
  level: "A2-C2",
  difficulty: {
    A2: "Basic defining relative clauses with who, which, that",
    B1: "Non-defining relative clauses, whose, where, when",
    B2: "Reduced relative clauses, omission of relative pronouns",
    C1: "Complex relative structures, preposition + relative pronoun",
    C2: "Advanced forms, quantifiers with relative clauses, double relatives",
  },
  forms: {
    defining:
      "S + V + noun + relative pronoun + clause • e.g., The man **who** called you is my brother.",
    nonDefining:
      "S + V + noun, relative pronoun + clause, • e.g., My father, **who** is a teacher, loves reading.",
    reduced:
      "Reduced form: relative pronoun + be → omitted or replaced with V-ing/V3 • e.g., The book **which is** on the table → The book **on the table**",
    prepositionRelative:
      "Preposition + relative pronoun (formal) • e.g., The house **in which** I live vs The house **which** I live **in**",
    quantifierRelative:
      "Quantifier + of + relative pronoun • e.g., I met several people, **most of whom** were teachers.",
    doubleRelative:
      "Relative clause within relative clause • e.g., The person **who told me the story that** you heard was lying.",
    contactClause:
      "Relative clause without relative pronoun (zero relative) • e.g., The book **Ø** I read was interesting.",
    cleftSentence:
      "It + be + noun/pronoun + relative clause (emphasis) • e.g., It was **John who** called you.",
    pseudoCleft:
      "What/Where/When + clause + be + focus • e.g., **What I need** is more time.",
    conditionalRelative:
      "Relative clause with conditional meaning • e.g., Anyone **who wants** to come should register.",
    nominalRelative:
      "Relative clause functioning as noun • e.g., **Whoever did this** will be punished.",
  },
  usage: [
    {
      type: "Defining Relative Clause",
      level: "A2-B1",
      description:
        "Cung cấp thông tin cần thiết để nhận biết người/vật đang nói đến",
      example: "The student **who studies hard** will succeed.",
      function:
        "Essential information - cannot be removed without changing meaning",
      subcategories: {
        restrictive: "Limits the meaning of the antecedent",
        identifying: "Helps identify which specific person/thing is meant",
        distinguishing: "Distinguishes from other similar items",
      },
    },
    {
      type: "Non-defining Relative Clause",
      level: "B1-B2",
      description:
        "Bổ sung thông tin không bắt buộc (có dấu phẩy), không thể bỏ đại từ quan hệ",
      example: "London, **which is the capital of England**, is very old.",
      function:
        "Additional information - can be removed without changing core meaning",
      subcategories: {
        descriptive: "Adds extra description about the antecedent",
        explanatory: "Provides additional explanation or context",
        parenthetical: "Acts like information in parentheses",
      },
    },
    {
      type: "Reduced Relative Clause",
      level: "B2-C1",
      description: "Rút gọn mệnh đề quan hệ để câu ngắn gọn hơn",
      example:
        "The man **waiting outside** is my uncle. (who is waiting → waiting)",
      function: "Concise expression, common in written English",
      reductionRules: {
        activeReduction: "who/which + be + V-ing → V-ing",
        passiveReduction: "who/which + be + V3 → V3",
        adjectiveReduction: "who/which + be + adjective → adjective",
        infinitiveReduction: "who/which + be + to-infinitive → to-infinitive",
      },
    },
    {
      type: "Sentential Relative Clause",
      level: "C1-C2",
      description: "Mệnh đề quan hệ bổ sung cho cả câu trước đó",
      example: "He was late again, **which** annoyed his boss.",
      function: "Comments on the entire previous statement",
      variations: {
        consequence: "Shows result of previous statement",
        evaluation: "Gives opinion about previous statement",
        elaboration: "Adds more details about the situation",
      },
    },
    {
      type: "Free Relative Clause",
      level: "C1-C2",
      description: "Mệnh đề quan hệ tự do không có từ đứng trước",
      example: "**What** you said is true. / **Whoever** comes first wins.",
      function: "Acts as noun phrase, no antecedent needed",
      types: {
        nominal: "Functions as subject or object",
        adverbial: "Functions as adverbial phrase",
        universal: "Expresses universal quantification",
      },
    },
    {
      type: "Contact Relative Clause",
      level: "B1-B2",
      description: "Mệnh đề quan hệ không có đại từ quan hệ (zero relative)",
      example: "The book **Ø** I read was fantastic.",
      function: "Very common in spoken English, informal style",
      conditions: "Only when relative pronoun is object of the clause",
    },
    {
      type: "Cleft Sentence",
      level: "B2-C1",
      description: "Câu chẻ để nhấn mạnh thông tin",
      example: "It was **Mary who** won the prize.",
      function: "Emphasizes specific information using relative structure",
      patterns: {
        itCleft: "It + be + focus + who/that/which + clause",
        whatCleft: "What + clause + be + focus",
        pseudoCleft: "The one who/The thing that + clause + be + focus",
      },
    },
  ],
  relativePronouns: {
    who: {
      usage: "Dùng cho người (chủ ngữ)",
      level: "A2",
      examples: [
        "The girl **who** lives next door is friendly.",
        "People **who** exercise regularly stay healthy.",
        "The teacher **who** taught me math retired.",
        "Students **who** study abroad gain experience.",
        "Anyone **who** wants to join can register.",
      ],
      notes: "Cannot be omitted when subject of the clause",
      formality: "Neutral - used in all contexts",
      alternatives: "Can be replaced by 'that' in defining clauses",
    },
    whom: {
      usage: "Dùng cho người (tân ngữ – trang trọng)",
      level: "B2-C1",
      examples: [
        "The man **whom** I met was a doctor.",
        "The student **whom** the teacher praised felt proud.",
        "To **whom** should I address this letter? (formal)",
        "The people **whom** we invited didn't come.",
        "The author **whom** critics admire writes beautifully.",
      ],
      notes: "Often replaced by 'who' in informal speech, can be omitted",
      formality: "Formal - mainly used in written English",
      alternatives: "Can be replaced by 'who' or omitted in informal speech",
    },
    whose: {
      usage: "Chỉ sở hữu (cho người và vật)",
      level: "B1-B2",
      examples: [
        "The boy **whose** bike was stolen is crying.",
        "The company **whose** profits increased hired more staff.",
        "I know a writer **whose** books are bestsellers.",
        "The house **whose** roof was damaged needs repair.",
        "Students **whose** parents support them succeed more.",
      ],
      notes: "Cannot be omitted, used for both people and things",
      formality: "Neutral - used in all contexts",
      structure: "whose + noun (never use 'of which' for people)",
    },
    which: {
      usage: "Dùng cho vật/con vật",
      level: "A2-B1",
      examples: [
        "The book **which** is on the table is mine.",
        "The movie **which** we watched was boring.",
        "The car **which** he bought is electric.",
        "The method **which** works best is simple.",
        "The place **which** I visited was beautiful.",
      ],
      notes: "Can be omitted when object, not used for people",
      formality: "Neutral - used in all contexts",
      alternatives: "Can be replaced by 'that' in defining clauses",
    },
    that: {
      usage: "Dùng thay cho who/which trong mệnh đề xác định",
      level: "A2-B1",
      examples: [
        "The car **that** he bought is fast.",
        "The person **that** called didn't leave a message.",
        "Everything **that** happened was recorded.",
        "The only thing **that** matters is love.",
        "All students **that** passed celebrated.",
      ],
      notes: "Only in defining clauses, can be omitted when object",
      formality: "Informal - very common in spoken English",
      restrictions: "Never used in non-defining clauses or after prepositions",
    },
    where: {
      usage: "Chỉ nơi chốn",
      level: "B1",
      examples: [
        "This is the house **where** I was born.",
        "The restaurant **where** we ate was expensive.",
        "I'd like to visit places **where** few tourists go.",
        "The office **where** she works is downtown.",
        "Countries **where** English is spoken attract students.",
      ],
      notes: "Can sometimes be replaced by 'in/at which'",
      formality: "Neutral - used in all contexts",
      metaphorical: "Can be used for abstract 'places': situations where...",
    },
    when: {
      usage: "Chỉ thời gian",
      level: "B1",
      examples: [
        "I remember the day **when** we first met.",
        "Summer is the season **when** people travel most.",
        "There was a time **when** life was simpler.",
        "The moment **when** everything changed was crucial.",
        "Years **when** technology advanced rapidly were exciting.",
      ],
      notes: "Can sometimes be replaced by 'in/on which'",
      formality: "Neutral - used in all contexts",
      omission: "Often omitted in informal speech: 'The day (when) I met her'",
    },
    why: {
      usage: "Chỉ lý do",
      level: "B1-B2",
      examples: [
        "I don't know the reason **why** she left.",
        "That's **why** I called you.",
        "The reason **why** he failed was obvious.",
        "Explain **why** this happened.",
        "There's no reason **why** we can't succeed.",
      ],
      notes: "Often used with 'reason', can be replaced by 'for which'",
      formality: "Neutral - used in all contexts",
      alternatives: "Can be omitted: 'The reason (why) she left'",
    },
    what: {
      usage: "Mệnh đề quan hệ tự do (= the thing that)",
      level: "B2-C1",
      examples: [
        "**What** you said surprised me.",
        "I don't understand **what** happened.",
        "**What** we need is more time.",
        "**What** matters most is family.",
        "Show me **what** you've learned.",
      ],
      notes: "No antecedent needed, acts as both pronoun and noun",
      formality: "Neutral - used in all contexts",
      emphasis: "Often used for emphasis in cleft sentences",
    },
    whoever: {
      usage: "Bất kỳ ai (= anyone who)",
      level: "C1",
      examples: [
        "**Whoever** arrives first gets the best seat.",
        "**Whoever** told you that was wrong.",
        "The prize goes to **whoever** wins the race.",
        "**Whoever** wants to help is welcome.",
        "I'll support **whoever** you choose.",
      ],
      notes: "Universal quantifier, emphasizes 'any person'",
      formality: "Formal to neutral",
      function: "Subject or object in main clause",
    },
    whatever: {
      usage: "Bất cứ gì (= anything that)",
      level: "C1",
      examples: [
        "**Whatever** happens, stay calm.",
        "You can choose **whatever** you like.",
        "**Whatever** he says, don't believe him.",
        "**Whatever** the cost, we must try.",
        "I'll accept **whatever** decision you make.",
      ],
      notes: "Universal quantifier, emphasizes 'any thing'",
      formality: "Neutral - used in all contexts",
      attitude: "Can express indifference or dismissal",
    },
    whichever: {
      usage: "Bất kỳ cái nào (= any one that)",
      level: "C1",
      examples: [
        "**Whichever** route you take will be fine.",
        "Choose **whichever** color you prefer.",
        "**Whichever** team wins deserves the trophy.",
        "Take **whichever** book interests you.",
        "**Whichever** method works is acceptable.",
      ],
      notes: "Choice from limited options",
      formality: "Formal to neutral",
      limitation: "Implies selection from known alternatives",
    },
    however: {
      usage: "Bằng cách nào (= in whatever way)",
      level: "C1",
      examples: [
        "**However** you do it, be careful.",
        "**However** difficult it is, don't give up.",
        "**However** much it costs, I'll pay.",
        "**However** long it takes, I'll wait.",
        "**However** you explain it, I don't understand.",
      ],
      notes: "Means 'in whatever way' or 'to whatever degree'",
      formality: "Formal",
      structure: "however + adjective/adverb",
    },
    whenever: {
      usage: "Bất cứ khi nào (= at any time that)",
      level: "B2-C1",
      examples: [
        "**Whenever** you're ready, we can start.",
        "**Whenever** it rains, I stay inside.",
        "Call me **whenever** you need help.",
        "**Whenever** possible, I walk to work.",
        "**Whenever** I see her, she's smiling.",
      ],
      notes: "Expresses time without specific limitation",
      formality: "Neutral - used in all contexts",
      frequency: "Often implies repeated action",
    },
    wherever: {
      usage: "Bất cứ nơi nào (= in any place that)",
      level: "B2-C1",
      examples: [
        "**Wherever** you go, I'll follow.",
        "**Wherever** you are, call me.",
        "You can sit **wherever** you like.",
        "**Wherever** possible, use recycled materials.",
        "**Wherever** I travel, I take photos.",
      ],
      notes: "Expresses place without specific limitation",
      formality: "Neutral - used in all contexts",
      metaphorical: "Can be used for abstract locations or situations",
    },
  },
  advancedStructures: {
    prepositionRelative: {
      formal: "The house **in which** I live is old.",
      informal: "The house **which** I live **in** is old.",
      level: "C1-C2",
      notes: "Formal style moves preposition before relative pronoun",
      commonPrepositions: {
        "in which": "The room **in which** we met was small.",
        "on which": "The table **on which** it sits is antique.",
        "at which": "The speed **at which** he works is impressive.",
        "by which": "The method **by which** this works is complex.",
        "for which": "The reason **for which** he left is unknown.",
        "with which": "The tool **with which** he fixed it was simple.",
        "from which": "The source **from which** this comes is reliable.",
        "to which": "The extent **to which** this matters is unclear.",
      },
      avoidance: "Preposition stranding is more common in informal English",
    },
    quantifierRelative: {
      examples: [
        "I have three sisters, **all of whom** are married.",
        "He wrote many books, **most of which** became bestsellers.",
        "There were 20 students, **none of whom** passed the exam.",
        "She has several friends, **some of whom** live abroad.",
        "We interviewed ten candidates, **few of whom** were suitable.",
        "They have many problems, **many of which** are serious.",
      ],
      level: "C1-C2",
      structure: "quantifier + of + whom/which",
      quantifiers: {
        all: "100% - complete quantity",
        most: "majority - more than half",
        many: "large number but not all",
        some: "partial quantity - indefinite",
        few: "small number",
        none: "zero quantity",
        several: "more than two but not many",
        both: "two items - complete",
        either: "one of two options",
        neither: "not one or the other",
        half: "50% of the total",
        one: "single item from group",
        two: "specific number from group",
      },
    },
    sententialRelative: {
      examples: [
        "It rained all day, **which** ruined our picnic.",
        "He passed the exam, **which** surprised everyone.",
        "She forgot her keys, **which** meant she couldn't get in.",
        "The meeting was cancelled, **which** disappointed many people.",
        "They arrived late, **which** caused problems.",
        "The project succeeded, **which** nobody expected.",
      ],
      level: "C1-C2",
      notes: "Refers to the entire previous clause, not just a noun",
      functions: {
        consequence: "Shows result of previous action",
        evaluation: "Expresses opinion about situation",
        elaboration: "Provides additional comment",
        contrast: "Shows unexpected result",
        explanation: "Clarifies the previous statement",
      },
    },
    embeddedRelative: {
      examples: [
        "The person **who told me the story that** you heard was lying.",
        "I met the woman **whose daughter who** studies medicine is your friend.",
        "The book **which describes the method that** we use is expensive.",
        "Students **who choose subjects that** interest them do better.",
        "The house **where the family who** owns it lives is beautiful.",
      ],
      level: "C2",
      notes: "Relative clause within another relative clause",
      complexity:
        "Should be avoided in most writing - rewrite as separate sentences",
      alternatives: "Break into multiple sentences for clarity",
    },
    nominalRelative: {
      examples: [
        "**What he said** was true.",
        "**Where she lives** is a secret.",
        "**When this happened** is unclear.",
        "**How they did it** remains a mystery.",
        "**Why she left** nobody knows.",
      ],
      level: "C1-C2",
      notes: "Entire relative clause functions as noun phrase",
      positions: "Can be subject, object, or complement of main clause",
    },
    conditionalRelative: {
      examples: [
        "Anyone **who comes late** will miss the start.",
        "Students **who don't study** will fail.",
        "People **who exercise regularly** stay healthy.",
        "Those **who work hard** deserve success.",
        "Anyone **who wants to join** should register.",
      ],
      level: "B2-C1",
      notes: "Relative clause expresses conditional meaning",
      meaning: "Similar to 'if' clauses but more concise",
    },
    temporalRelative: {
      examples: [
        "The moment **when** everything changed.",
        "The day **when** we first met.",
        "Times **when** life was different.",
        "The year **when** I graduated.",
        "Periods **when** growth was rapid.",
      ],
      level: "B1-B2",
      notes: "Emphasizes specific time periods",
      alternatives: "Can often omit 'when' in informal speech",
    },
  },
  recognition: [
    "Có thể nhận biết qua đại từ quan hệ: who, which, that, whose, where, when, why",
    "Mệnh đề xác định **không có dấu phẩy**; mệnh đề không xác định **có dấu phẩy**",
    "Có thể **rút gọn** khi đại từ quan hệ làm chủ ngữ + to be",
    "Có thể lược bỏ đại từ quan hệ khi nó làm tân ngữ (e.g., The book (that) I bought...)",
    "**Formal style**: preposition + relative pronoun (in which, to whom)",
    "**Quantifier patterns**: some/most/all/none + of + whom/which",
    "**Free relatives**: what, whoever, whatever, whichever (no antecedent)",
    "**Sentential relatives**: which referring to entire clause",
    "**Contact clauses**: relative pronoun omitted when object",
    "**Cleft sentences**: It + be + focus + relative clause",
    "**Pseudo-clefts**: What-clause + be + focus element",
    "**Embedded relatives**: relative clause within relative clause",
    "**Nominal relatives**: entire clause functions as noun phrase",
  ],
  examples: {
    defining: [
      "The man **who fixed the car** is my uncle.",
      "The movie **that we watched** was amazing.",
      "I know a place **where we can go hiking.**",
      "Students **whose grades are low** need extra help.",
      "The reason **why she quit** was personal.",
      "The moment **when everything changed** was unforgettable.",
      "People **who exercise daily** live longer.",
      "Books **that inspire readers** become classics.",
      "The method **which works best** is simplest.",
    ],
    nonDefining: [
      "My sister, **who lives in London**, is visiting us.",
      "The Eiffel Tower, **which was built in 1889**, is a famous landmark.",
      "Our teacher, **whose class is always fun**, is very kind.",
      "Paris, **where I spent my honeymoon**, is beautiful.",
      "1969, **when man first walked on the moon**, was historic.",
      "My birthday, **which is in December**, often gets forgotten.",
      "Shakespeare, **who wrote many plays**, lived in England.",
      "My car, **which I bought last year**, needs repair.",
      "Christmas, **when families gather**, is special.",
    ],
    reduced: [
      "The girl **sitting next to me** is my friend.",
      "The book **written by Orwell** is a classic.",
      "The man **invited to the party** didn't show up.",
      "People **living in cities** face more pollution.",
      "The email **sent yesterday** contained errors.",
      "Anyone **interested in joining** should contact us.",
      "Students **preparing for exams** study hard.",
      "The document **signed today** is important.",
      "Customers **waiting in line** were patient.",
    ],
    advanced: [
      "The house **in which** Shakespeare was born attracts tourists. (formal)",
      "I have two brothers, **both of whom** are doctors. (quantifier)",
      "**What** you need is confidence. (free relative)",
      "**Whoever** wins the lottery will be rich. (free relative)",
      "He arrived late, **which** annoyed his boss. (sentential)",
      "The method **by which** this was achieved remains secret. (formal preposition)",
      "**Whatever** happens, stay calm. (universal quantifier)",
      "The people **to whom** we spoke were helpful. (formal)",
      "**Whichever** option you choose will be fine. (choice)",
    ],
    contact: [
      "The book **Ø** I read was excellent.",
      "The person **Ø** you met is my cousin.",
      "The movie **Ø** we watched was boring.",
      "The food **Ø** they served was delicious.",
      "The car **Ø** he drives is expensive.",
    ],
    cleft: [
      "It was **John who** called you.",
      "It's **money that** we need most.",
      "It was **yesterday when** I saw her.",
      "It's **here where** the accident happened.",
      "It was **because of rain that** we stayed home.",
    ],
    pseudoCleft: [
      "**What I need** is more time.",
      "**Where we're going** is a surprise.",
      "**What happened** was unexpected.",
      "**What matters** is your effort.",
      "**Where she lives** is unknown.",
    ],
  },
  commonMistakes: [
    {
      mistake: "Using 'that' in non-defining clauses",
      wrong: "My father, that is a teacher, is kind.",
      correct: "My father, **who** is a teacher, is kind.",
      level: "B1",
      explanation: "'That' is never used in non-defining clauses with commas",
    },
    {
      mistake: "Omitting relative pronoun when it's the subject",
      wrong: "The man lives next door is friendly.",
      correct: "The man **who** lives next door is friendly.",
      level: "A2",
      explanation: "Relative pronoun cannot be omitted when it's the subject",
    },
    {
      mistake: "Double relative pronouns",
      wrong: "The book which I read it was good.",
      correct: "The book **which** I read was good.",
      level: "B1",
      explanation: "Don't use both relative pronoun and personal pronoun",
    },
    {
      mistake: "Wrong pronoun for people vs things",
      wrong: "The person which called didn't leave a message.",
      correct: "The person **who** called didn't leave a message.",
      level: "A2",
      explanation: "Use 'who' for people, 'which' for things",
    },
    {
      mistake: "Missing comma in non-defining clauses",
      wrong: "London which is the capital is expensive.",
      correct: "London**,** which is the capital**,** is expensive.",
      level: "B1",
      explanation: "Non-defining clauses must have commas",
    },
    {
      mistake: "Using 'whose' incorrectly",
      wrong: "The book whose cover is red belongs to me.",
      correct: "The book **whose cover** is red belongs to me.",
      level: "B1",
      explanation: "'Whose' must be followed by a noun",
    },
    {
      mistake: "Incorrect preposition placement",
      wrong: "The house in that I live is old.",
      correct: "The house **in which** I live is old.",
      level: "C1",
      explanation: "Use 'which' not 'that' after prepositions",
    },
    {
      mistake: "Wrong quantifier structure",
      wrong: "I met many people, most of them were teachers.",
      correct: "I met many people, **most of whom** were teachers.",
      level: "C1",
      explanation: "Use 'whom/which' not personal pronouns after quantifiers",
    },
    {
      mistake: "Confusing 'what' and 'that'",
      wrong: "I don't understand that happened.",
      correct: "I don't understand **what** happened.",
      level: "B2",
      explanation: "'What' means 'the thing that' - no antecedent needed",
    },
    {
      mistake: "Incorrect reduction",
      wrong: "The man is waiting outside is my uncle.",
      correct: "The man **waiting** outside is my uncle.",
      level: "B2",
      explanation: "Remove both relative pronoun and 'be' verb when reducing",
    },
  ],
  practiceTypes: {
    A2: [
      "Fill in: who, which, that",
      "Identify defining vs non-defining",
      "Simple sentence combination",
      "Choose correct relative pronoun",
      "Basic transformation exercises",
    ],
    B1: [
      "Add commas where needed",
      "Choose correct relative pronoun",
      "Whose, where, when exercises",
      "Formal vs informal choices",
      "Error correction activities",
    ],
    B2: [
      "Reduce relative clauses",
      "Omit relative pronouns where possible",
      "Formal vs informal style",
      "Contact clause practice",
      "Advanced pronoun usage",
    ],
    C1: [
      "Preposition + relative pronoun",
      "Quantifier + of + relative pronoun",
      "Complex sentence transformation",
      "Cleft sentence formation",
      "Register-appropriate choices",
    ],
    C2: [
      "Advanced relative structures",
      "Style and register awareness",
      "Creative writing with complex relatives",
      "Embedded relative clauses",
      "Academic writing applications",
    ],
  },
  stylistics: {
    register: {
      formal: {
        characteristics: "Preposition + relative pronoun, 'whom' usage",
        examples: [
          "The manner **in which** this was handled was professional.",
          "The person **to whom** you spoke is the manager.",
          "Students **from whom** we expect excellence must work hard.",
        ],
      },
      informal: {
        characteristics: "Contact clauses, 'who' instead of 'whom'",
        examples: [
          "The way **Ø** you handled this was great.",
          "The person **who** you spoke to is the manager.",
          "Students **who** we expect to do well must work hard.",
        ],
      },
      academic: {
        characteristics: "Complex structures, formal pronouns",
        examples: [
          "The methodology **by which** these results were obtained is sound.",
          "Participants **whose responses** indicated confusion were excluded.",
          "The extent **to which** this theory applies remains debatable.",
        ],
      },
    },
    emphasis: {
      cleftSentences: "Use to emphasize specific information",
      pseudoClefts: "Emphasize actions or abstract concepts",
      fronting: "Move relative clause to beginning for emphasis",
    },
    cohesion: {
      textBinding: "Relative clauses create complex, connected text",
      informationFlow:
        "New information in relative clause builds on known information",
      topicContinuity: "Maintains topic while adding details",
    },
  },
  notes: [
    "Không dùng **that** trong mệnh đề không xác định (non-defining).",
    "Đại từ quan hệ có thể làm **chủ ngữ**, **tân ngữ**, **bổ ngữ sở hữu**, hoặc chỉ **nơi chốn/thời gian/lý do**.",
    "Mệnh đề rút gọn dùng **V-ing** (chủ động) hoặc **V3** (bị động).",
    "Lược bỏ đại từ quan hệ **chỉ khi làm tân ngữ**, không được khi là **chủ ngữ**.",
    "Mệnh đề không xác định luôn **có dấu phẩy** và có thể bỏ đi mà không làm thay đổi nghĩa chính của câu.",
    "**Formal English** prefers preposition + relative pronoun (to whom, in which, by which).",
    "**Quantifiers** (some, most, all, none, many, few) + of + whom/which for advanced structures.",
    "**Free relatives** (what, whoever, whatever) don't need antecedents and act as noun phrases.",
    "**Sentential relatives** with 'which' refer to entire clauses, not specific nouns.",
    "**Reduced relatives** are more common in written English and formal contexts.",
    "**Contact clauses** (without relative pronoun) are very common in spoken English.",
    "**Double relatives** should be avoided in most contexts - rewrite as separate sentences.",
    "**Register awareness**: formal contexts prefer 'whom' and preposition + relative pronoun.",
    "**Cleft sentences** (It was John who...) emphasize specific information using relative structure.",
    "**Pseudo-clefts** (What I need is...) use 'what' clauses for emphasis and focus.",
    "**Nominal relatives** function as complete noun phrases without antecedents.",
    "**Temporal sequences**: when clauses often show chronological relationships.",
    "**Conditional meaning**: relative clauses can express conditional relationships.",
    "**Text cohesion**: relative clauses create sophisticated, connected discourse.",
    "**Information structure**: new information in relative clauses builds on given information.",
    "**Stylistic variation**: different structures serve different communicative purposes.",
    "**Cross-linguistic influence**: learners' L1 may affect relative clause production and comprehension.",
  ],
  communicativeFunctions: {
    description: "Provide detailed information about nouns",
    identification: "Help identify specific referents",
    classification: "Categorize or group items",
    evaluation: "Express opinions or judgments",
    elaboration: "Add supporting details",
    emphasis: "Highlight important information",
    cohesion: "Connect ideas across sentences",
    precision: "Specify exact meaning intended",
  },
  pedagogicalProgression: {
    A2: "Simple defining clauses with who/which/that",
    B1: "Non-defining clauses, whose/where/when",
    B2: "Reduction, omission, contact clauses",
    C1: "Formal structures, complex patterns",
    C2: "Stylistic awareness, advanced functions",
  },
};
